### ISSUE TITLE
Q: File System Shape?

### ISSUE THREAD

**Issue by crgardner** [plantuml-stdlib/C4-PlantUML#104]
Any plans to create a File System shape?

I believe it's one of the shapes that Simon Brown shows in his presentation linked 
https://c4model.com/

**Comment by adrianvlupu** [comment]
Hi, I couldn't find the shape you are mentioning. I tried using a folder or a file instead of the default rectangle but it doesn't look that great.

![image](https://user-images.githubusercontent.com/4486850/103155169-bb26f300-47a5-11eb-87d0-21f22b29c67d.png)

**Comment by Potherca** [comment]
Re-opening this as it is under consideration in #145

**Comment by kirchsth** [comment]
@Potherca: I would remove it from v2.3.0 because I think we should not add it (and all other points are basically implemented)

**Comment by Potherca** [comment]
Based on the discussion in #145, the current mindset is to **not** implement a folder shape.

To summarize:

> We should not add (too many) shapes, otherwise we would have to make a very generic implementation and we lose the C4 relation and create a new "Meta" notation.
>
> As Simon Brown stated in #97
>
> >    there is no "C4 model notation" [..] feel free to use whatever shapes/icons you like
>
> Adding the shape is only half of the solution. To my mind, we should not be adding _shapes_ but Container, Components, etc.

So, unless some _very_ convincing arguments are posted, this issue will not be re-opened.
