### ISSUE TITLE
support local imports without changes

### ISSUE THREAD

**Issue by dstockhammer** [plantuml-stdlib/C4-PlantUML#114]
It would be great if local imports could be supported/enabled out of the box without having to make changes to any code. That would make it possible to include this repo as submodule. For certain use cases it may not be acceptable to pull files from github on build and having a local copy is required.

I've made that scenario work with a fork, see https://github.com/dstockhammer/C4-PlantUML/commit/d444d99c5e8c0b9d948ae4818d64c8cdd0a3495d

But assuming that there will be breaking changes with v2 anyway (?), now might be a good time to consider supporting this use case natively.

A possible solution would be to not include dependencies in the individual files, but instead have two entrypoints, say `C4_all.puml` and `C4_all_local.puml` that include all dependencies in the right order: One uses github imports and the other uses local imports. That way the user can choose which way to import. The downside of this approach is of course that all components would always be included, but I think that's an acceptable tradeoff. The user would always be able to customize which components to import by not relying on `C4_all` and importing the required files manually.

**Comment by Potherca** [comment]
@dstockhammer You are not alone in wanting to use local import... @kirchsth has implemented a `RELATIVE_INCLUDE` variable in #107 which makes it possible to use local version with an additional command line argument:

```
java -jar plantuml.jar -DRELATIVE_INCLUDE="/path/to/files"  ...
```

**Comment by dstockhammer** [comment]
Awesome! That's great to hear; I was not aware of that development. Looking forward to the merge so I can get rid of my fork :)

**Comment by romkavt** [comment]
I add my vote for this issue and have to mention
https://github.com/plantuml/plantuml-stdlib/issues/32

Includes with network URL's in C4 library files makes them unusable as part of Plantuml-stdlib on servers.
