### ISSUE TITLE
Build broken by the new RELATIVE_INCLUDE variable

### ISSUE THREAD

**Issue by leio10** [plantuml-stdlib/C4-PlantUML#118]
Hi! I'm working in the [decidim](https://github.com/decidim/decidim) project, and after one of the [last commited changes](https://github.com/plantuml-stdlib/C4-PlantUML/commit/6cc10231fe5e168dbcbfb60fac1d3fec2ca3d1c0) the [project documentation](https://github.com/decidim/documentation) building process is failing with the following error:

```
Skipping plantuml block. Preprocessing of PlantUML include failed, because reading the referenced local file '%get_variable_value("RELATIVE_INCLUDE")/C4.puml' caused an error:
Error: ENOENT: no such file or directory, open '%get_variable_value("RELATIVE_INCLUDE")/C4.puml'
```

AFAIK, we are not defining a value for that variable, so it seems to be that the [if condition](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/C4_Component.puml#L2) is not working properly.

Should we modify anything on our project because of the last commit or it's a bug on this repo?

Thanks!

**Comment by adrianvlupu** [comment]
Hi! Interesting project 👍 

I suspect it's the version of plantuml that antora or asciidoc is using.
The `%get_variable_value` builtin preprocessor function doesn't seem to work.

I tested it locally with the latest jar file and with the online plantuml server and it seems to work fine, but with older versions it breaks.

Try to include `!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.0.1/C4.puml`. This should work as before.

The master branch will most likely keep breaking with all the changes form PR requests, and it's only tested on the latest PlantUml version. We need a better way to keep track of what works with what version of PlantUML and keep things clearer.
