### ISSUE TITLE
Microservice container

### ISSUE THREAD

**Issue by sudsk** [plantuml-stdlib/C4-PlantUML#12]
Thanks for the great work. I would like to use hexagon for microservice container instead of rectangle. Where should I add this additional container type?

**Comment by adrianvlupu** [comment]
Hi,

You can define new container types right after you include the C4_Container.puml, similar to how the ContainerDb type was created. 

```
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

skinparam database<<container>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor CONTAINER_BG_COLOR
    BorderColor #3C7FC0
}
!define ContainerDb(e_alias, e_label, e_techn) database "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<container>> as e_alias
!define ContainerDb(e_alias, e_label, e_techn, e_descr) database "==e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//\n\n e_descr" <<container>> as e_alias

ContainerDb(db1,"DB1", "SQL")

@enduml
```

But from what I know about plantUML you can't use the hexagon shape like you use the rectangle
```
rectangle Something
hexagon Other
```
This won't work.

**Comment by Potherca** [comment]
There is a feature request to add a hexagon shape: https://forum.plantuml.net/10418/please-provide-a-hexagon-shape

I would suggest upvoting that.

**Comment by aheil** [comment]
Adding such a shape will add in excess try complexity to the diagrams. In my opinion, I does not fully fit as a container neither as a component in terms of the C4 model. It probably makes more sense to create dedicated microservice diagrams in addition to your C4 diagrams.

**Comment by Potherca** [comment]
The hexagon shape has been implemented: ![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuSf8hKXCpyzJ0D66A3mZBZ3NK45Nrmugu92QbmBK1000)

**Comment by Potherca** [comment]
Reopening as this is under consideration in #145 .

**Comment by Potherca** [comment]
FYI: #146 also adds a eight-sided shape that can be used to represent a microservice.
