### ISSUE TITLE
Question: How to add diagram title and description

### ISSUE THREAD

**Issue by pdanysz** [plantuml-stdlib/C4-PlantUML#122]
Hello :)

I'm thinking about how to add Diagram title and description as is on C4 Models diagrams?

I know the ```title``` syntax but how to add this title and description to bottom-left corner?

![image](https://user-images.githubusercontent.com/385259/108347750-2eb31280-71e1-11eb-808b-2b865859f763.png)

Thanks in advance!
Przemek

**Comment by kirchsth** [comment]
Hi Przemek,

I found a docu in plantuml: 
https://plantuml.com/commons, section "Footer and header"

I think you could use it like 
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

right header
= Header sample with legend (using creol)
<font color=green>combination with legend is working too</font>
Details see https://plantuml.com/commons
endheader

left footer
= Footer sample with legend (using creol)
<font color=green>combination with legend is working too</font>
endfooter

caption
= Footer sample with legend (using creol)
<font color=green>combination with legend is working too</font>
Different default color but it supports no alignment
endcaption

Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")

SHOW_DYNAMIC_LEGEND()
@enduml
```
![header, caption, footer](http://www.plantuml.com/plantuml/png/lLBTRXfD3BsVf_2NxoABH5YbwbMLHA50GwL0KI6DUeLcTxtBgFCp6dk5eghlNW-5qBv0a91dRP_ZSopV4-l4lRFgF-DhspS8E-P87yeowVseCxphgvumrS4pUXxLmPNHQfynLyIDDLKvUN-rogcdnMFfD34cIMqdWj36Onh5pA-IwNOCEzGD9dKByyC3IBje4VOo22nsw1ieUZA-WpfXi0DrqmeFrC66TDibH7yd4YhZDPlW_y4PWdr8FpAMGxWfC_1EJL5KM0B2ixMJWOCR-RlWIGd5KPoos3Aq8V11wITvl8LIgHndgbh737h3uLFJjfXGE1fiTM-FN53r38Q1-XX3OW8VG5lJUIUjMV59gLfXek0BtJZZXt0npj4G9yqXNGpK-eKOtVPZw7sZqqjHNm_XSdrmTJc0dmhaztennHwhhOvHU9wnWd6CrjG79nUIclm_XF5wDLhEDW992Ez6rx3uDicriRLXJv0lbiIUc71HIuiJHoPlS2Eho0jbuz3AB19jluxg2lvJ59vZcnJLLxGdLsTPJoH8YVFDPhMMhjpqMZtJF22JV68ERGhkRuXQpxyyRwVVb-F5vydsSVOmMqwBWRgNfSff_WO0)

**Comment by kirchsth** [comment]
@pdanysz: Was my answer useful? Can we close this issue?

**Comment by pdanysz** [comment]
Yes it is !:) It was exactly what I was looking for :)
Thanks!
