### ISSUE TITLE
Old release (v1.0.0) is tagged with "Latest"

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#123]
Hi, 
I think the current latest release is "v2.0.1" (o at least v2.0.0) and should be tagged with "Latest". 
BR
Helmut

**Comment by Potherca** [comment]
Yeah, looks like something weird is going on with the GitHub Releases :raised_eyebrow: 

I think the mixup stems from v2 being tagged earlier than v1. There is also a difference between a git tag and a GitHub release.

It can probably be solved by deleting and re-applying the releases in order of their version or something. I'll play around with the official docs and a dummy repo and see what I can come up with to rectify the incorrect order.

For now, I've created a release for v2.0.1 (from the tag of the same name), so https://github.com/plantuml-stdlib/C4-PlantUML/releases/latest at least no longer points to v1.

**Comment by kirchsth** [comment]
Thank you, 
BR Helmut
