### ISSUE TITLE
Tag support for relationships

### ISSUE THREAD

**Issue by didierpirottin** [plantuml-stdlib/C4-PlantUML#137]
Hello,

Thank you of this great plantuml lib.
Would it be possible to add tag support for relationships ?
This is to be able to use color, or dashed style for certain types of relationships

Thanks !

**Comment by kirchsth** [comment]
Hello,
there is an open PR #130. It supports relationships with tags (changes colors)
Dashed styles are not possible atm (cannot be changed via skinparams).
BR Helmut
(PS.: you could check it on my [extended branch](https://github.com/kirchsth/C4-PlantUML) in the meantime)

**Comment by didierpirottin** [comment]
Hello,

Thanks a lot, I've checked your extended branch and found several useful improvements.
Do you know when your PRs will be included in the standard Lib ?

Didier

**Comment by kirchsth** [comment]
@Potherca I think this can be closed too

**Comment by Potherca** [comment]
@kirchsth You are correct. Will close.

@didierpirottin Before changes from here show up in PlantUML, we need to add an MR to https://github.com/plantuml/plantuml-stdlib/
