### ISSUE TITLE
Unknown variable $tagStereo

### ISSUE THREAD

**Issue by aheil** [plantuml-stdlib/C4-PlantUML#138]
Currently, our examples from the README don't work with the current master C4.puml and the latest VS Code plugin from jebbs (v2.14.4)

The following example from the README will result in the error below:

'''
@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml
'''

The same happens to a whole set of C4 models being a few weeks old. So we have introduced some bug or breaking change here? 

![c4](https://user-images.githubusercontent.com/509229/112132523-0301be80-8bcb-11eb-84fd-0469975296a5.png)

**Comment by PaddyS** [comment]
Got the same issue currently. However using an older version somehow doesn't seem to fix it. Weird.

**Comment by aheil** [comment]
@PaddyS does this happen to you with the VS Code extension or with plain PlantUML? I try to figure out if this is only related to the VS Code extension as this might be outdated.

**Comment by aheil** [comment]
I just replaced the plantuml.jar in the VS Code extension, which is the same as the latest from the PlantUML Website.

![Snag_a688e86](https://user-images.githubusercontent.com/509229/112149209-0606aa00-8bdf-11eb-9782-f78743460e1c.png)

**Comment by aheil** [comment]
I am going to close this issue, as it can now be reproduced on different machines. 
It is related to an outdated version of the plantuml.jar file as described below:

@PaddyS check, what PLantUML version you are using by generating 

```
@stastuml
version
@enduml
```

The one causing the error at my installation was 1.2019.06.

![Snag_a73f912](https://user-images.githubusercontent.com/509229/112150773-c476fe80-8be0-11eb-9df5-af85739acb3a.png)

After I replaced it with the latest version (1.2021.3) everything renders perfectly and nice. 

![Snag_a74e48b](https://user-images.githubusercontent.com/509229/112150902-e7a1ae00-8be0-11eb-83d6-f113e00f414c.png)

If you are using Visual Studio code, and the proposed PlantUML Extension, check if the JAR-location has been modified as it was with my instance. 

![Snag_a76f4ce](https://user-images.githubusercontent.com/509229/112151171-38b1a200-8be1-11eb-89e4-95837777e8cf.png)

Let us know if this fixed your issue as well.

**Comment by aheil** [comment]
As described before, I going to close this issue as it is related to an outdated version of plantuml.jar.

**Comment by PaddyS** [comment]
@aheil Thank you very much, appreciate your help and explanation here! :-)
It worked for me as well!
