### ISSUE TITLE
Ready to be deployed ?

### ISSUE THREAD

**Issue by arnaudroques** [plantuml-stdlib/C4-PlantUML#144]
[Some user has asked](https://github.com/plantuml/plantuml/issues/542) if we can merge this version to the official library.

Is it okay on your side ?
Thanks !

**Comment by Potherca** [comment]
We've started tagging versions, so although the `master` branch _might_ contain breaking changes, the latest version (at the time of this writing [v2.2.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.2.0)) _should_ always be stable and ready to deploy.

**Comment by Potherca** [comment]
Please also see my comment over at https://github.com/plantuml/plantuml/issues/542

**Comment by Potherca** [comment]
Closed as the current release (v2.2.0) has been [merged into the official repo](https://github.com/plantuml/plantuml-stdlib/pull/36).

> We will publish a new official release (V1.2021.6) in the incoming days with this updated library.
_Originally posted by @arnaudroques in https://github.com/plantuml/plantuml-stdlib/issues/36#issuecomment-841048991_
