### ISSUE TITLE
Improve layout of components

### ISSUE THREAD

**Issue by pete-puma** [plantuml-stdlib/C4-PlantUML#151]
The component layout appears to be disjointed at times and this may be due to order of execution of the UML. 

For example, my first class citizen component is far right and its integration flow is wonky and wonder if there is a way to improve this, like centering components, or alignment, as well as best practice for navigation within the design, to improve L&F.

**Comment by Potherca** [comment]
Hi! Without any example diagram it is hard to judge what the problem might be or what solutions to suggest.

Could you post or link to the diagram that is giving you trouble?

**Comment by Potherca** [comment]
Is it possible to also post the (redacted) PlantUML diagram text?

**Comment by kirchsth** [comment]
You could make it like 
```
@startuml
!include <awslib/AWSCommon>
!include <awslib/AWSSimplified.puml>
!include <awslib/Compute/all.puml>
!include <awslib/mobile/all.puml>
!include <awslib/General/Users>

' !include ./C4_Context.puml
' !include ./C4_Container.puml

!include <awslib/general/all.puml>
!include <awslib/GroupIcons/all.puml>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()
' LAYOUT_LEFT_RIGHT()

title Container diagram for: Simple chat flow

Mobile(customer, App, "A customer of the bank, with personal bank accounts")

System_Boundary(c1, "Platform") {
Container(web_app, "Chat Engine", "server", "Interface for Chat client")
Container(chat_agent, "Chat Agent", "Web interface", "Handles customer chat session")
ContainerDb(database, "Database", "SQL Database", "Stores chat transcript for customer session")
Container(backend_api, "Chat services", "server", "Internal service layer for chat transactions")
}

System_Ext(email_system, "E-Mail System", "Send chat transcript on request")

Rel_R(customer, web_app, "Chats with agent, based on region", "SSL")

Rel(chat_agent, backend_api, "Uses", "async, JSON/HTTPS")

Rel_U(email_system, customer, "Sends e-mails to customer email")
Rel(web_app, chat_agent, "Forwards message to")
Rel_R(backend_api, database, "Reads from and writes to", "JDBC")
Rel_L(backend_api, email_system, "Sends e-mails using", "SMTP")
@enduml
```
![](http://www.plantuml.com/plantuml/png/VLHThzf647tdLqplIuW4M9No55LH290BALmeDa9zijRhmQoo7-xkkWHL_U-TjS75kivzyvwPEUVCsPK_Ey-ihvGS_28qbrMEy1kxE2coQ7gCPqOfep_rrcAXIYbE0lD9IVCzJJHTLXuZ9kNFMfJ9X7opunarMYQZWqFhFWq6xw1jcKIp3-dCQ8y_V3tUMsI229hoQ_QYON_JW3LLkU96kxwki_Ub-nX5bbqcXV3dAgl8A0-cj9zmew9ICXq27ZkVrwby6Ey2TDYi8yMSHzldz1rKcgOLiO0_8voCbEOYT06Ike3f73fbOHrz6I1ra8QJq-jZ6ZqAw-cVsqEI9jjTEjyUNuRlgV-6JUCq_dsHp9O4tg3ZAbccwyNpucN-q4d8roJThvwN2Q43Bxn4Q8KW5womJ95v-n7gzuB0pyp3YNOP33RrvGzvvRnHQ4SmBSiHF4tXZe0vrTjbJ7yVmONYXHAjCvh96WF6kQcqTqya7byfIvL-8I1dzZhaln8N9Ur9NJszXty6hR7X1REKrMApO6UX2uAVwEZG_eqsVAsqHtjY78DxgDku59GtQVrF5BP9MK7mdMiQ3e7WY1c8Eqa0bdHf4bsxNHE5G-U4qO-iysoOCyyovf36virdJH7_iOREsHkBhY7obcd7hIXzSDogz0aCCyQ_eyuf0t7t7JON75rF2XJtlGoINT4s0gqeuvu4mYNysrx3ueSVec92fgu6Y6intj0PceRQFLbuvTreiFXNXSw7IzsZJFSFBwHxSQvv4xVyGoXvCr-GdreXNjzOEZVLNV_WcgsPkse-Wc_nzYLQ9iaklXiuT3Tfexsju037eUx0cxO6zGWn1EtMTUUvV3NsmYoDAtIEG1gd_cRZZiE7nx17HWCdQrJz2xXOuJ7e1l_VvbzcDu9rb-3H_YlJbHEwgCFQ93kQ_qpLIid_0000)

**Comment by pete-puma** [comment]
I see - using direct placement with Rel_L, Rel_R and the fixed starting position, you have a little more control versus the seemingly random ordering.  That worked, thanks !

**Comment by Potherca** [comment]
@pete-puma Are the suggestions by kirchsth a sufficient solution for your problem? If so, can we close this issue?
