### ISSUE TITLE
Change the fontcolor of Legend Title

### ISSUE THREAD

**Issue by christo-ph** [plantuml-stdlib/C4-PlantUML#152]
I am unable to get the setting which controls the default black legend title. I tried

`skinparam LegendFontColor #DDDDDD`

but this changes the color of the fine borders between the components only. Not the font color.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/16965068/120215567-2cc40b00-c236-11eb-8f8d-82b5c61f4142.png">

**Comment by kirchsth** [comment]
you can change it via !global $LEGEND_TITLE_COLOR = "#DDDDDD"

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


!global $LEGEND_TITLE_COLOR = "red"

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")

SHOW_LEGEND()
@enduml
```

![](http://www.plantuml.com/plantuml/png/ZP1FIyD04CNl-odIu245crmy2K8b3If4Kzg8nx3P3Cd2P7VPcI3zzcuY5aMKdkOFlDzxl2snz3oDA5RQA9mwY0PcHxTPvkLxsciUfdOYyCeQ1iEficFcK9fPio7kKBTPVhFPpw_Nvp8R9J7uy6hoe93QW4_Tp1TYrQDj9KPNPV5GlEoQ-gakYoQlokeGtKMnXouMOW-Uh4dSCkvHIxgEubAsW75OAiVQci3O0IclbojUYxDLehwsNz8Qr60islxq3-Xu8eOneMLSwYuEW3y3drFyZVWM9n2EZzLRyrbBiXPRC5sex0C0)

BR Helmut

**Comment by christo-ph** [comment]
Great, thanks Helmut. Did you find this in the documentation? Or code?

**Comment by kirchsth** [comment]
I wrote it ;-)

**Comment by christo-ph** [comment]
Nice life hack ;-) Thanks anyway
