### ISSUE TITLE
Add length parameter to Rel and Lay procedures

### ISSUE THREAD

**Issue by dannief** [plantuml-stdlib/C4-PlantUML#153]
For diagrams with a lot of elements, it would be helpful to have more control of the layout, by manipulating arrow lengths. See below

```plantuml
@startuml
!include <C4/C4_Context>

System(a, A)
System_Ext(b, B)
System_Ext(c, C)
System_Ext(d, D)
System_Ext(e, E)
System_Ext(f, F)
System_Ext(g, G)
System_Ext(h, H)
System_Ext(i, I)


Rel(a, b, " ")
Rel(a, c, " ")
Rel(a, d, " ")
Rel(a, e, " ")
Rel(a, f, " ")
Rel(a, g, " ")
Rel(a, h, " ")
Rel(a, i, " ")
@enduml
```

![Diagram 1](http://www.plantuml.com/plantuml/png/LSwxgeD058NXVfvY7Ik53QUn3C5aOYvjyW2YplO2eu4u0-RjGy0Kg_p-wY-MKBz2dBpv6-VMHwVOsVpVvfLzpa7Ni3VcyLw2JcajE6GRgd8DQICuKcW5be8Jd2YeeAJG2SuKUi65mY2uKXW5jymOSrV_VMe42PBinvRfcChic3rpO8uR2vrTdFm7)

After increasing the arrow length for some relations, the following diagram can  be achieved.
```plantuml
@startuml
!include <C4/C4_Context>

System(a, A)
System_Ext(b, B)
System_Ext(c, C)
System_Ext(d, D)
System_Ext(e, E)
System_Ext(f, F)
System_Ext(g, G)
System_Ext(h, H)
System_Ext(i, I)


a --> b
a ---> c
a --> d
a ---> e
a --> f
a ---> g
a --> h
a ---> i
@enduml
```

![Diagram 2](http://www.plantuml.com/plantuml/png/LSYxgeDG48NXVfvYdKvXv3IMGKnspANE0uYwnmkeWJY2UViWR8kfrlg_VD7ge-iqqjymD-Fg1IUN_hkqTEzPPTECwFLTLAQeOfpZ46MnQLGpBWOQXZFW6LS3mYWCj8oRWOvnDz0p7WO6nZCceWf9ag7UTpzD07-016WFw0Bq1moKo-pNQVm1)

Using the `nodesep` skinparam,  and longer arrows, the diagram can be further condensed.

```plantuml
@startuml
!include <C4/C4_Context>

skinparam nodesep 10

System(a, A)
System_Ext(b, B)
System_Ext(c, C)
System_Ext(d, D)
System_Ext(e, E)
System_Ext(f, F)
System_Ext(g, G)
System_Ext(h, H)
System_Ext(i, I)


a --> b
a ---> c
a ----> d
a --> e
a ---> f
a ----> g
a --> h
a ---> i
@enduml
``` 

![Diagram 3](http://www.plantuml.com/plantuml/png/LSdFYeCm4CVn-pp5x4rXP7V1On7RrFuvzm4acb53JHGJmRvziMWXf_dDvvixBoS_cnv-jAtxMJ4UHFehqb8CrlFYCm3tr7QKapHe1yMEH_p_0tYyd6SJIS9Zl3rbiVYe8Zm5K1EA01JXEG0cB09e22y1j8JN03h2Mm2Qy1u3WCGaoR1QxphgTNoMsXBlgVccTalTdZJaRDLi-ZS0)

**Comment by kirchsth** [comment]
Lay_Distance() support is part of #143. PlantUML has a limitation and "distance" only work in layout direction (details see #134) and therefore I cannot make a solution which works in all directions. 

In the meantime you can use my [branch](https://github.com/kirchsth/C4-PlantUML) like below
BR Helmut

```
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Context.puml
' !include <C4/C4_Context>

skinparam nodesep 10

System(a, A)
System_Ext(b, B)
System_Ext(c, C)
System_Ext(d, D)
System_Ext(e, E)
System_Ext(f, F)
System_Ext(g, G)
System_Ext(h, H)
System_Ext(i, I)

Rel(a, b, " ")
Rel(a, c, " ")
Rel(a, d, " ")
Rel(a, e, " ")
Rel(a, f, " ")
Rel(a, g, " ")
Rel(a, h, " ")
Rel(a, i, " ")

' Lay_Distance(a,b,0)
Lay_Distance(a,c,1)
Lay_Distance(a,d,2)
' Lay_Distance(a,e,0)
Lay_Distance(a,f,1)
Lay_Distance(a,g,2)
' Lay_Distance(a,h,0)
Lay_Distance(a,i,1)
@enduml
```
![](http://www.plantuml.com/plantuml/png/RP5FIyD044Vl-od6Njh0sBJIauXKq_e7AeZYkMnsfzcboJPa9zX-UnEeuj0St_lb3O5THjODjrMfhdmmPMi977CTRzEqqT_JmhDhypPIOmw1AV3K7AfqxnlZ8hiqMro_bphmrzicfMEtMxATt6RTnnrFw_xm6FvEtsMBV_EzKd7lGwqRNK4uM8fKmtocrESfCbKJZV2Gd66xFl8aHtWKmY1aGbY4bH24i1PYX_0aH87mB8H3U1728xmcIgaFAlj_oX56C4f-qKYq4adYJc8XqKdqPrHZsEZJTkKZws2ectAS9KewD3Y_S1PlaikQ1khTG5qCrcwWzdszf62xz_u1)

**Comment by kirchsth** [comment]
@Potherca: I wouldn't mark it with "wontfix" we have a working solution (workaround) for that

**Comment by dannief** [comment]
Reopening issue because the Lay_Distance only works in the DOWN direction. But I have upon situations where I need to customize arrow length in the UP direction as well. See diagram below where I made the arrow lengths for **I** and **G** longer in the UP direction

```
@startuml
!include <C4/C4_Context>

skinparam nodesep 10

System(a, A)
System_Ext(b, B)
System_Ext(c, C)
System_Ext(d, D)
System_Ext(e, E)
System_Ext(f, F)
System_Ext(g, G)
System_Ext(h, H)
System_Ext(i, I)


a --> b
a ---> c
a -up-> d
a --> e
a ---> f
a -up---> g
a --> h
a -up--> i
@enduml
```

![image](https://user-images.githubusercontent.com/6110488/144518317-e8d1acd5-ea84-42b8-9b30-48eb050de1a9.png)
