### ISSUE TITLE
Use default bgColor and fontColor for new element tags

### ISSUE THREAD

**Issue by dannief** [plantuml-stdlib/C4-PlantUML#154]
In the diagram below, when new elements or rel tags are defined, if `$fontColor` or `$bgColor` are not specified (for element tags for example), then the generated legend shows texts: `(no text)` and `(no back color)`. But since the element or relation uses the default colors, if not defined in the procedure, I think we should use the same colors in the legend. I find I keep setting the colors back to default colors, just so that `(no text)` and `(no back color)`  are not displayed in the legend.

```plantuml

'  code removed for brevity ...

AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#d73027")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange")

'  code removed for brevity ...

```

![Example C4 Model](https://camo.githubusercontent.com/79943c767365b3f510aa224637b08c316e18fd44d9e7fcbbdf2d945ce520b4be/68747470733a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f706e672f624c4a544a6a6a43344274644156527072756b574757427a344c38623941413049674e4766574a34394866783979777377727268506e70516a2d2d434f733838344c4d6c545a4c7050697753734d4556344b4659666c39785f7862472d4351594d4a424e7a366171496c306d4231716c63786d584a344b435a38363748516e366a4f5557444f563472686a794446626d4544464778544c714c30346e395764544a7747324e43307168424e5f746a5a513275794c316877315366326a5a655437734f357661795461434b73595a2d61712d7a2d556c337a775476426a78713056417465584a562d3670513775735448527739575762325857484c2d5a7471386f5f6a6632496a327857325f41507657655865376b7643316161754f754c6657346469716d7258754442753544474249634a6a34733150454b544c4c57416e5334456a524a344956572d41384d2d5949495837334a6f416d536a3836303371504e4f6b47767758583445524b6765414a4a546254326b54645f57366547596c626968346f59655f3747616a7638667165576e574e366a383259367130505961784f455754415f5931635132566564677764457a676336705f4c514e4f706d7a43545f454338636d4d7965586667666e46436c595a5833725931646653476834536f754271484e6d6b476f46584f6b6938437a30434f7a67694c48733057356d466a466e567854666c6746315f4f4e3967563071434558346671764f654b4149784f70427a464d2d5265424a732d763835664e4d79574d353674596776304548536e4c5333322d356e374166506b5851666256536c7173625a3745645a6647676331455353616b5a7751746d596644714464534a4d6b63427670785465466a75496162557474425733446a6e6250744578715f564c776751744f516d484265786c6136426c7165786c787a7a5f4471514c563876676b594e6866374f5f53415949323464544164357a2d6b786b564e646f2d2d37652d734479786d733372705f4337)

**Comment by kirchsth** [comment]
> But since the element or relation uses the default colors, if not defined in the procedure, I think we should use the same colors in the legend

Which color should be used with v1.1?  The "dark blue" person or the "blue" container? I think there is no logic rule which can be used. Therefore I introduced the undefined colors. You can overwrite it in your diagram

```
!global $LEGEND_UNDEFINED_BG_COLOR = "#D5CFEE"
!global $LEGEND_UNDEFINED_FONT_COLOR = "#8B77E4"
```

The legend texts are constants and can be changed too like below
```
!global $LEGEND_SHADOW_TEXT = "(shadow) "
!global $LEGEND_NO_SHADOW_TEXT = "(no shadow) "
!global $LEGEND_NO_FONT_BG_TEXT = "(no text, no back color) "
!global $LEGEND_NO_FONT_TEXT = "(no text color) "
!global $LEGEND_NO_BG_TEXT = "(no back color) "
!global $LEGEND_NO_LINE_TEXT = "(no line color) "
```

In #149 I implemented a better "undefined/default" color handling, maybe you want to check it too. 
(#149 changes the color constant names!) 

BR Helmut

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!global $LEGEND_UNDEFINED_BG_COLOR = "green"
!global $LEGEND_UNDEFINED_FONT_COLOR = "lightgreen"

!global $LEGEND_NO_FONT_BG_TEXT = "[no font/background]"
!global $LEGEND_NO_BG_TEXT = ""

AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#d73027")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange")

Person(user, "Customer", "People that need products")
Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="v1.1")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")
Container(archive, "Archive", "Audit logging", "Stores 5 years", $tags="backup")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
Rel(admin, spaAdmin, "Uses", "https")
Rel(spaAdmin, api, "Uses", "https")
Rel_L(api, archive, "Writes", "messages", $tags="backup")

SHOW_LEGEND()
@enduml
```

![](http://www.plantuml.com/plantuml/png/bLJlJzim4FtENs4oFXGD6jWF8Kr2eclB3wcqNLl4f6cgBl4rzUROaUsKxR_VNT8IA1tJFZcwUtVltld55pw02sMkz_QLINKfKIn3AFodE7RmqCvKM9P9wT6brWGqePtQF2uq6Auvza5gbSJT3yTZ3jtT3k8SV417eNcNAa0PTEs2--_jPzeceCN1e7_L7_RcTyDU__9csE_DFr_DkwF1Q2BEHPGvH1Ez0huS3MSDNAji6UgQbmp3KONc_hF-rndZlnah5ZHOd43wCtEsDF9xjAlmIGrrxaZPrvYZ2JF8Mj7gj7qI7Oc3n3g9hckrTUVH6tds_kJTMNIu0ttAQERz5vR7Aeijj7LWCYGmeoUejv01VsqXAQXfyo_An-YyDIs-poCHTKiVR8wEuD4ORQ5HX2K4OH2bA9oLPHeybQshGERA4BJ3f_B1GR0lQg59egSGFZOIAmLLmE23u9K8ib9X3IdtbGh8_7crAw9yz4xB5q0Kqt67cKX7gQ4YdL6dd212cO1k0MazGCMGheNLEM3o1p9oDG5VtJEwasswpbETOZSpFDt1_uwmMS0hgg5GFC7uXWb_m0hul0OZDNe1Mekaz0JqNcYRgLIq-ETjDwibHw3noXf_-5pisssgNjAI2JNlGO04F3BHhKgTzNOHnFJBe6AsMlhDJHw9olM2fY5rAwjIf7DXNGw169_hSEbIhP2rr5yHVvPI1HuyKoRZm9IMIBe-Yjy8hZ73nk9aN3BzshMr7-uyCYwgtYe2SBxAqE9sf-UJUgcLs0c2zF6zKm7NwOsxc_lVoT6a_quqg8aQwJKFmtBq7ZBSAN5wFRgVr-zFwt3l0eqiS_q7)

**Comment by dannief** [comment]
@kirchsth I don't think this implementation would be useful to me. This is because, it doesn't adhere to how I think the legend should work and doesn't follow the legend entry patterns for default items like `person` and `container`. What I mean is, the `person` entry in the legend has the same font color and background color as the actual element and so you are easily able to correlate the legend entry to the element type in the diagram. However, for the new tag, v1.1, for example, the legend entry has a background color of green, while the tag is applied to elements with background colors dark blue and light blue respectively. I think you can't easily correlate the legend entry with the actual elements in those cases, which makes the legend not so useful

In  your example above, I think there should be 2 different `v1.0` tags, one for the `container` and the other for the `person`. In that case the 2 legend entries would have a font color and background color that matches the elements they are trying to describe. See below:

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("v1.0", $borderColor="#d73027", $bgColor=$CONTAINER_BG_COLOR, $fontColor=$ELEMENT_FONT_COLOR)
AddElementTag("container_v1.1", $fontColor="#d73027", $bgColor=$CONTAINER_BG_COLOR)
AddElementTag("person_v1.1", $fontColor="#d73027", $bgColor=$SYSTEM_BG_COLOR)
AddElementTag("backup", $fontColor="orange", $bgColor=$CONTAINER_BG_COLOR)

AddRelTag("backup", $textColor="orange", $lineColor="orange")
AddRelTag("db_read_writes", $textColor="blue", $lineColor=$ARROW_COLOR)

Person(user, "Customer", "People that need products")
Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="person_v1.1")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="container_v1.1")
Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+container_v1.1")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")
Container(archive, "Archive", "Audit logging", "Stores 5 years", $tags="backup")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes", $tags="db_read_writes")
Rel(admin, spaAdmin, "Uses", "https")
Rel(spaAdmin, api, "Uses", "https")
Rel_L(api, archive, "Writes", "messages", $tags="backup")

SHOW_LEGEND()
@enduml
```

![image](https://user-images.githubusercontent.com/6110488/121272740-59a69c80-c88c-11eb-8849-f21937ad75f6.png)


The above code and resultant image shows how I typically define new tags to ensure correct legend entries.

So I suppose what I am really looking for then, are specialized `AddElementTag` and `AddRelTag` procedures that will set default styles based on the element the tag is being applied to. Perhaps as below:

```plantuml
AddPersonTag()
AddSystemTag()
AddContainerTag()
AddComponentTag()
```

I think we can currently set defaults for `AddRelTag` without introducing a new procedure?

**Comment by kirchsth** [comment]
you can change the default person,... and relations style with calls like 

```
UpdateElementStyle("person", ....)
UpdateRelStyle(....) 
```

Is this what you want? (source of the image is in [Read.me](https://github.com/plantuml-stdlib/C4-PlantUML#custom-tagsstereotypes-support-and-skinparam-updates))

BR Helmut

![](http://www.plantuml.com/plantuml/png/dP9lRvim4CRVyoaegwPKoXz2I8CcHMh9q5Q99bN-Q7k7R7n9K8s9RAEsttu6i-5cT9EYlcb-Ty_Ty_Yu4n9nMURKkifOIai2zb7Aa_Wo6d7qCZnaybZYKW1F2oQ1oM5QvACJHQpI38GaDCEZXJzugj3kCHxbI4ZW2YMBIl4gXwTgkdLrlLZ5gtLodqpjkUryckqds0qSW_irnvDfuDwQV59pS0Dlx9lSg_cUuE1sOlAnvW0kDkOiezrsVH_hsgpwQsjXeo41GO1DhdTW3s7YcLnx2jpP1AKcrncclZSB0fFhp1vnNT-OluxY97vOHXt3T74R_To-Argx4q4I8WevCBcHRnHwpWcuA9ZJjw_nOL7GWi_RjrPmh-xGulOfglw24-1dch4gY2CYnKl63dD7yXAScyx5whh06QB9Xmx22noeQtIl4sz2GjwPqxyWf_UVK1-k2ozO5xRhra3rgckQCMYxZ0-YRt-MoaTRCxw76yjwgf-xbvP25ZdmlkreWgWT8lQipcOlcfgwtAREqSEwqiHIcWTM1GNvHwCRbQAH9D6hxEKeewqc6bI_RT5qdZMoFKSvgBR7t_ztp5Rn3UT_kTe94AfDTIKXIf-DrlTEDi28iA7s8snPD9ebP8SZBlXPt7-gjRHBeKEqhgpDzzMF98w-HSkllHlhJaqfS_eB)

**Comment by dannief** [comment]
@kirchsth No, I am not trying to update the default element and relation styles as that will change the style of all the element and relation types specified in `UpdateElementStyle` and `UpdateRelStyle` respectively. I am referring to creating tags that will affect just the elements and relations they are applied to.

The issue is what happens when we use the procedures to add a tag to an element or relation and we do not specify all the arguments. What I am proposing is how the library should set the unspecified arguments for display in the legend.

If I have 2 containers, where I would like to add a tag to one of them, then I use the AddElementTag procedure. However, I only wish to change the fontColor of the default container styling. I achieve this as expected by calling the `AddElementTag` procedure as below. And this produces a tagged container that will  have only the font color changed, while the background color and borders still have the default container styles. However, the legend, in my opinion is incorrect. The legend entry for `tagged` has background color of pink and does not show the rectangle denoting the border color of the element. It is not obvious what that legend entry relates to.

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag(tagged, $fontColor=red)

Container(default, Container 1, tech)
Container(tagged, Container 2, tech, $tags="tagged")

SHOW_LEGEND()
@enduml
```
![image](https://user-images.githubusercontent.com/6110488/121387834-9ae09000-c910-11eb-988e-33fb5c44749b.png)

In my opinion, the legend should be displayed as below.
![image](https://user-images.githubusercontent.com/6110488/121388536-2ce89880-c911-11eb-821a-119a45f11b5e.png)

The unspecified `AddElementTag` arguments should not use random colors that results in the legend entry not directly correlating to the displayed element i.e. not having the same bgColor, fontColor and borderColor as the element.

But since the current `AddElementTag` and `AddRelTag` procedures cannot know the element to which the tag will applied, in order to achieve the legend entry as in the 2nd image, I typically specify the default style values manually like so:

`AddElementTag(tagged, $fontColor=red, $bgColor=$CONTAINER_BG_COLOR, $borderColor=$CONTAINER_BORDER_COLOR)`

So I will then only apply that tag to a container element.

In order that users do not have to always specify all the argument values to generate a proper legend, I am proposing that new procedures be created e.g.

```plantuml
!procedure AddContainerTag($tagStereo, $bgColor=$CONTAINER_BG_COLOR, $fontColor=$ELEMENT_FONT_COLOR, $borderColor=$CONTAINER_BORDER_COLOR, $shadowing="false")
  AddElementTag($tagStereo, $bgColor, $fontColor, $borderColor, $shadowing)
!endprocedure

!procedure AddPersonTag($tagStereo, $bgColor=$PERSON_BG_COLOR, $fontColor=$ELEMENT_FONT_COLOR, $borderColor=$PERSON_BORDER_COLOR, $shadowing="false")
  AddElementTag($tagStereo, $bgColor, $fontColor, $borderColor, $shadowing)
!endprocedure
```

Or alternatively we can extend UpdateElementStyle and UpdateRelStyle to accept a stereo name so that it will only update the style of elements with the given tag e.g.

```plantuml
' Only update default styling for given `elementName` tagged with `tag` value
UpdateElementStyle(elementName, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?tag)

' example
UpdateElementStyle("container", $fontColor="red", $tag="tagged")
```
Or even

```plantuml
AddElementTag($tagStereo, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?elementName)

' Style will only be applied to elements with stereo <<tagged>> AND <<container>>. 
' Since we know we are applying the style to a container, we can used container bgColor and borderColor if not specified
AddElementTag("tagged", $fontColor="red", $elementName="container")
```

This pattern should apply also to the current functionality of `UpdateElementStyle`.

Given the below code

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' AddElementTag(tagged, $fontColor=red)
UpdateElementStyle("container", $fontColor=red)

Container(default, Container 1, tech)
Container(tagged, Container 2, tech, $tags="tagged")

SHOW_LEGEND()
@enduml
```

Since I didn't specify a bgColor, I get the following legend with a pink background and a text specifying "no back color"
![image](https://user-images.githubusercontent.com/6110488/121425405-fa05cb00-c937-11eb-98fb-3ff4883e7266.png)

I would have expected the following instead. (Assumed that since bgColor is not a required argument, the bgColor of both the legend and element specified (container) would use the default color of `$CONTAINER_BG_COLOR`
![image](https://user-images.githubusercontent.com/6110488/121425815-70a2c880-c938-11eb-9a3b-633fd0ada31d.png)


Hope this is clearer

**Comment by kirchsth** [comment]
I think I understand your wish, following source 

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("tagged", $fontColor=red)

Container(c1, Container 1, tech)
Container(cTagged, Container 2, tech, $tags="tagged")
Person(p1, Person 1)
Person(pTagged, Person 2, $tags="tagged")

SHOW_LEGEND()
@enduml
```

should be displayed like

![](http://www.plantuml.com/plantuml/png/XP5HRu8m58NV-oiwumCaAj7iQOc93ebRugX1bpsIsjuXIMb9MxA_lmjEvuRBdk3SVlUSGraupwrlAaNkIYrK8u4UlQ_TGnHP_Z4fIdzi3eq3AupseFr4c2gg5TVjpjXvgSf35D-Fj-tezMKJLTnvi3ZAOzpWfGOxgLj_ifGoKL2XoPuNmS3peW0v6D7XEuAnKSREBSZmDaV5sQstWVfGT8hEwJ1cwNxvd2PP_hZEOxPXMNjkh0HxYs7P2XyTzrTo3TOP_K_iDibsBErdze0VWUHoHu6OZkX5KHGUn36y1lPTdMjgTg8m3AkwUV-gGhBjoWSr6fvUwVHxU7RyEfdzCZf_EVOakoVsbc-ITPAkWf0iG4lyfvy0)

But PlantUML offers only few preprocessor calls ([details](https://plantuml.com/preprocessing)). You could try to extend SHOW_LEGEND()  with missing functionanlity and create a PR (please don't forget the combination of multiple tags, ....).

BR Helmut

PS.: source of the diagram based on the current implementation 
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("tagged", $fontColor=red)
AddElementTag("tagged container", $fontColor=red, $bgColor = $CONTAINER_BG_COLOR, $borderColor = $CONTAINER_BORDER_COLOR)
AddElementTag("tagged person", $fontColor=red, $bgColor = $PERSON_BG_COLOR, $borderColor = $PERSON_BORDER_COLOR)

Container(c1, Container 1, tech)
Container(cTagged, Container 2, tech, $tags="tagged container")
Person(p1, Person 1)
Person(pTagged, Person 2, $tags="tagged person")

SHOW_LEGEND()
@enduml
```

**Comment by kirchsth** [comment]
@dannief in #157 I showed a soution to hide default tags and uses only explicit defined tags (which could represent a tag combination too) maybe this is an approach for you

**Comment by kirchsth** [comment]
Hi @dannief, 

with #173 I added **Element specific tag defintions with element specific default colors** like

* `AddPersonTag(tagStereo, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?shape, ?sprite, ?legendText, ?legendSprite)`
* `AddExternalPersonTag(tagStereo, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?shape, ?sprite, ?legendText, ?legendSprite)`
* `AddSystemTag(tagStereo, ?bgColor, ?fontColor, ?borderColor, ?shadowing, ?shape, ?sprite, ?legendText, ?legendSprite)`
* ...

that repeated color defintions can be avoided like below 

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

' AddElementTag("tagged", $fontColor=red)
AddContainerTag("tagged container", $fontColor=red)
AddPersonTag("tagged person", $fontColor=red)

Container(c1, Container 1, tech)
Container(cTagged, Container 2, tech, $tags="tagged container")
Person(p1, Person 1)
Person(pTagged, Person 2, $tags="tagged person")

SHOW_LEGEND()
@enduml
```
![](http://www.plantuml.com/plantuml/png/RP1HIyCm4CVVyodY46nXDcpu90mcjUZ3r84J7qTCpgQO9YMveX_VSyKOi6-z__tkrp_PHfG1nzwoiyufEshW1d68rq84-Lcr7PhnROmGb7S83YlbU_7H1MKY6b5VNUwjTFZoi1FmHNiDci9ZJR3i78Hg-56p2twZTMEX9yD1jiK2PTk2NYpv-JkXjRS-R0BeaX6NZZEIgzzm_cOF8NgN7modP8PcoL-erPAdYTE0e4oP0uUJBAVM4qLU-b7S_EzNigbCCP1m-kIhlt0ofiqw4-MzgUVp_TFhSTVSDO-tHScsu3IzvJS0)

Maybe this helps.
BR Helmut
