### ISSUE TITLE
Bottom-left alignment for Deployment Node label

### ISSUE THREAD

**Issue by 0n3d3r3r** [plantuml-stdlib/C4-PlantUML#155]
Hello.

I'd like be able to align the text of a C4 deployment node to the bottom left of the box so it looks like in the C4 model notation ([C4 Deployment diagram example](https://c4model.com/img/bigbankplc-LiveDeployment.png)).

I know your objective is not to necessarily make diagrams look like whatever is displayed in the C4 model site examples, but I think in this case makes a lot of sense, because the nested Containers show text at the top and centered, so having deployment nodes showing their labels at the bottom and left aligned would make a clear differentiation between a Container and a Deployment Node, and also separate text a bit in a way it's not all cluttered when nesting more Deployment Nodes and a Container in a Deployment Node.

Before:

![before](https://user-images.githubusercontent.com/79170102/121225986-0f0b2d00-c858-11eb-98b6-8b9d001f097a.png)

After:

![after](https://user-images.githubusercontent.com/79170102/121226019-16cad180-c858-11eb-9c1b-152b3ba6d584.png)

Thanks.

**Comment by kirchsth** [comment]
Based on the current PlantUML implementation (details see [forum question](https://forum.plantuml.net/12894/how-can-i-align-the-text-of-components)) I think it cannot be realized atm.
BR Helmut

**Comment by 0n3d3r3r** [comment]
That post refers mainly to horizontal alignment, but an also important part of my request is the vertical alignment, and I would say that even more relevant from the stand point of differentiating Containers from Deployment nodes in terms of the labels, specially when nested.

Is there a way we could work on being able to position the Deployment Node label at the bottom of the box instead of the top? That would be a great addition. Look at this example:

![Screen Shot 2021-06-08 at 2 20 13 PM](https://user-images.githubusercontent.com/79170102/121237127-b68e5c80-c864-11eb-97d4-e663786b672f.png)

There is a Deployment Node (O.S.) nesting another Deployment Node (D.B. SW) hosting a DB Container. Wouldn't mind seeing the Deployment Nodes labels in centered fashion if at least the label was at the bottom like this.

**Comment by kirchsth** [comment]
Vertical alignment is not possible too (at least I don't know it)

**Comment by 0n3d3r3r** [comment]
Thanks! Just took a look at the PlantUML documentation and indeed there's nothing there in terms of vertical text alignment within basic shapes.
I'll see if I can create a feature request in plantUML for it to eventually be available there first, so I can maybe later make a case of leveraging that here.
