### ISSUE TITLE
Relation tags support line styles

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#159]
Relation tags uses basically the arrow color skinparams. The (new) arrow color supports line styles like below too

``` 
@startuml
class foo
foo --> bar : normal
foo --> bar1 #line:red;line.bold;text:red  : red bold
foo --> bar2 #green;line.dashed;text:green : green dashed
foo --> bar3 #blue;line.dotted;text:blue   : blue dotted
@enduml
```

![](http://www.plantuml.com/plantuml/png/JStDgWCX38RXlLVnWUivSDhT39Iv5Qtf3qG5ZT3Bhncdu48Itl3WNiKLQP7DdLsjUEHi-iEotE1TmOgKItGyntzOVYTQ2uLDbp-VEMn27z64RdHedDK5zbc8qY31rHUTwCXTZJakixp2UcvqmYpoWrgX_ntBk9YTKcYHlm00)

Based on that added relation tags could support line styles too like

```
AddRelTag("backup", $textColor="darkgray", $lineColor="darkgray", $lineStyle = DashedLine())
```

**Comment by Potherca** [comment]
Fixed in #160
