### ISSUE TITLE
Q: Is there an option that an arrow gets drawn through a component?

### ISSUE THREAD

**Issue by chkpnt** [plantuml-stdlib/C4-PlantUML#162]
I'd like to have an arrow between two components, but that arrow should cross another component (a firewall in my example) in the background or foreground. Is something like this possible?

**Comment by kirchsth** [comment]
Hi @chkpnt,

I think this is not possible (PlantUML does not support it, or at least I don't know how),
but you could extend the relations with a firewall sprite (and colored line tag that it is part of the legend too)

BR Helmut

![](http://www.plantuml.com/plantuml/png/pLP_Rnf74FsVJp6baM97sDZKgQAgheB1pG_PmG9Sjr8bQsvtEBRUkptjxc6xLRvxP-uW-0nHagQg2XAw7MRUpBnxixilGqGVoyoslZ6vigKccCTOX1-wNO-t-wc9yp8f0tdbyaXvt5SkwnOMSudP2r5RatG7HtiNOheyF-jc629vDbqFgR3kFfEWGXAiC_pe0dPdnjCjMllXuQTMgw_rgIK9cMAwqvwnDK5rq-x0aoGTEElySVjRTI3VzgvuZybkU4QwYqrViLgJqyfwzDsBuV1v4s5X45QLF4BHw6yywIRAa_vuFBgw7epEHkFTLkifABIgj1X9WwMKSWqcG1bukOCgcaNrZyd1Ca4WEBiSTDR_RNGvlRvwCtrzVNRwwlJTS8V1eecMOCqV30sc7ZEOEGzlSkOtfmWdcD-OF8N9FJEUmHwScGMrMkkmwtTEqqvXLGVQ9oQj0e2NxKThq1WH50bmU_Ul5l3dCOhEEIWnQS8nUrYOPy-U_HxlNWZKPLAo6k3m-_s38pYRJbOGss2mG3Kd3kfN3p1rcSBOVco05_jtQvZwCs018jFc6SH8mCKRw1U5DUnlN2uORt61WCpyfF32pFal0p5VUBSmci8cTRCoLnACriHx40aWl9sCtdLVJwSN4-0K-woILGNlMzNlLdwMrEZauF01KRByKegSHsM5eb7rmE_rmfiC_NrxRJligO_ICqnsTCAkGuoOO209Ov5ZtIUip31XkZEKVoVHUQgqwi5JQaBqbJUOd0MNLSyTc6EOamOiuvnhNR8EofEM9ThG0LIAGW3hKbvGL5zENgz9NcyhUJATc8RZzTJlmgVux3qaT4BAvNgJqey3RsUvzt-XURFmpoG-UKZuBINrM1_zix7kVULSStuEkABaC-TwIDOio0TWgY14TbUmFAR4MyoR8n_unn8Kc1BWEiqsgRxVt4mp9oKEoX1THlvf03OOXjEqCAhIW9JEQKSJS1xwkVREQ6cvsMeTnkxdTJn7IV2lc25tsDYq4Ap9Z1mUeKm2HN0pwUnJcrbqe9Pb1jdP9CRuPhtSzBOcbSkAPfTYAULqa8gDLowuMOGhasjt6wIWkkiCrKXqibrhddt9Bz_mYQngm5VEoHiPp3rdwy2v-zDOY_2pyJHpTvqbzWHdJ8sGUcwKhmiurIcjqZNv3GNAnDNl-W9JsYQfYVAcgANIpzFIecyIR-tNSSrwXcNNpFHQL6Eo7mHGdsNdUCC9vKHJd3Kme5JoHt1vVHB9W0VMVgJZzkgIqWdiIyS7-uVFEwgwagplAVLkqBpJx4fU8UO_JtfzMOysvsvChQkuLMkPFI3it-kuQhOw4SU4Ei2CPLQzyrj1NxNzTdWoQ0RqFYTYsyOh7O_vT5Y3rCgZK5-qecEdrkJrw6fzvNj9kIup-pS0)

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

!include <osa/firewall/firewall>

AddElementTag("fallback", $bgColor="#c0c0c0")
AddRelTag("fallback", $textColor="#c0c0c0", $lineColor="#438DD5")
AddRelTag("via firewall", $textColor="darkred", $lineColor=$ARROW_COLOR)

' calculated legend is used (activated in last line)
' LAYOUT_WITH_LEGEND()

title Deployment Diagram for Internet Banking System - Live

Deployment_Node(plc, "Big Bank plc", "Big Bank plc data center"){
    Deployment_Node(dn, "bigbank-api***\tx8", "Ubuntu 16.04 LTS"){
        Deployment_Node(apache, "Apache Tomcat", "Apache Tomcat 8.x"){
            Container(api, "API Application", "Java and Spring MVC", "Provides Internet Banking functionality via a JSON/HTTPS API.")
        }
    }
    Deployment_Node(bigbankdb01, "bigbank-db01", "Ubuntu 16.04 LTS"){
        Deployment_Node(oracle, "Oracle - Primary", "Oracle 12c"){
            ContainerDb(db, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
        }
    }
    Deployment_Node(bigbankdb02, "bigbank-db02", "Ubuntu 16.04 LTS", $tags="fallback") {
        Deployment_Node(oracle2, "Oracle - Secondary", "Oracle 12c", $tags="fallback") {
            ContainerDb(db2, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.", $tags="fallback")
        }
    }
    Deployment_Node(bb2, "bigbank-web***\tx4", "Ubuntu 16.04 LTS"){
        Deployment_Node(apache2, "Apache Tomcat", "Apache Tomcat 8.x"){
            Container(web, "Web Application", "Java and Spring MVC", "Delivers the static content and the Internet Banking single page application.")
        }
    }
}

Deployment_Node(mob, "Customer's mobile device", "Apple IOS or Android"){
    Container(mobile, "Mobile App", "Xamarin", "Provides a limited subset of the Internet Banking functionality to customers via their mobile device.")
}

Deployment_Node(comp, "Customer's computer", "Mircosoft Windows of Apple macOS"){
    Deployment_Node(browser, "Web Browser", "Google Chrome, Mozilla Firefox, Apple Safari or Microsoft Edge"){
        Container(spa, "Single Page Application", "JavaScript and Angular", "Provides all of the Internet Banking functionality to customers via their web browser.")
    }
}

Rel(mobile, api, "Makes API calls to", "json/HTTPS", $sprite="firewall,scale=0.15,color=darkred", $tags="via firewall")
Rel(spa, api, "Makes API calls to", "json/HTTPS", $sprite="firewall,scale=0.15,color=darkred", $tags="via firewall")
Rel_U(web, spa, "Delivers to the customer's web browser", $sprite="firewall,scale=0.15,color=darkred", $tags="via firewall")
Rel(api, db, "Reads from and writes to", "JDBC")
Rel(api, db2, "Reads from and writes to", "JDBC", $tags="fallback")
Rel_R(db, db2, "Replicates data to")

SHOW_LEGEND()
@enduml
```

**Comment by chkpnt** [comment]
Many thanks for your suggestions! :-)
