### ISSUE TITLE
Background of boundaries is white in sketch-mode

### ISSUE THREAD

**Issue by chkpnt** [plantuml-stdlib/C4-PlantUML#163]
I've just updated to v2.2.0 and noticed that the background color of boundaries in my diagrams that uses `LAYOUT_AS_SKETCH()` changed to white. I guess that this is an unintended behaviour, as it's different to the example in [LayoutOptions.md](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#layout_as_sketch)

Unfortunately, I didn't mange to set the background color manually:

<img width="971" alt="grafik" src="https://user-images.githubusercontent.com/1956979/123398331-ac2dcb80-d5a3-11eb-8e21-e0809ab8f873.png">

**Comment by kirchsth** [comment]
HI @chkpnt,

you can use following workaround 

```
!$BOUNDARY_BG_COLOR = "#EEEBDC"
skinparam package {
    StereotypeFontColor $BOUNDARY_BG_COLOR
    BackgroundColor $BOUNDARY_BG_COLOR
}
skinparam rectangle<<boundary>> {
    StereotypeFontColor $BOUNDARY_BG_COLOR
    BackgroundColor $BOUNDARY_BG_COLOR
}
```

I added in following sample a node and legend that it contains other combinations too

```
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Deployment.puml

LAYOUT_AS_SKETCH()

!$BOUNDARY_BG_COLOR = "#EEEBDC"
skinparam package {
    StereotypeFontColor $BOUNDARY_BG_COLOR
    BackgroundColor $BOUNDARY_BG_COLOR
}
skinparam rectangle<<boundary>> {
    StereotypeFontColor $BOUNDARY_BG_COLOR
    BackgroundColor $BOUNDARY_BG_COLOR
}

Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")

Node(n1, n2, "hkjhkjh")

SHOW_LEGEND()
@enduml
```

![](http://www.plantuml.com/plantuml/png/jL5VQzim47_tfr3TGHt8ObhsDBfIs_4IM1g7s5dfar7iMwn5VuHq9WkZtttdBIE1iSSAmw7x_RcVTOyUkSDUoU1Aw4RsBR0EqVgFSUpuOR8JsFNRteDhZ4RGE6cCYlV2DPt7Biu-l5z9hd7pj8ZX1-4jjDIifs2bEQg1RmVlO96y59kgJigw_99NsJmQ1S7LkxJOBAV9-gLEPtLMB8er-yJ2wppFqsaM1duljEMEAsPvi-SxO3y3HgT4S63mQE4pPSgCD8xzQ_MRcf9mvqols__INY_cE6YGwvs4-_lj8EBk-F3mHbFfhC1veoFUAg77B4o6AZmwZiQ5ew0yUWHLfwSaKNCxPZSbLrR2pUYKAgCiN6XmqG6sDRUMV9vXon9hfMWu2gD3QcNNOvQKgyaohqZYWDrDRjdJrsp04YdDmRDXnvwXORHWoucYUec2Ph7g8131CHGA9CtobEtrb2x2Fo3vd6W41ckGV__g76lZIKbrNbMhabX4EeS-sym0FLrXAD-SKPUIO6bQY3IzWxwZThV_Fdm3KCwBvtgHp_BbDABh8-YsL_8N)


BR Helmut

**Comment by kirchsth** [comment]
@chkpnt: related to wrong picture: This is "basically" not possible,  because all pictures are generated based on encrypted urls. But the urls have to be updated if a branches of different developers are merged and therefore it could be overseen. decoded url uses a differnt branch

``` 
@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_AS_SKETCH()

Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml
```

I will fix the url and the current implementation

BR Helmut

**Comment by chkpnt** [comment]
Thanks for your hint about how to change the color!

But I don't get your second comment. 😕 In case you are refering to the URL I used in my example to include C4-PlantUML: Yes, I've written that I updated to v2.2.0, but this only belongs to my actual diagrams, where I'm using an offline version. In the example I've just used the master-URLs for the sake of simplicity.

**Comment by kirchsth** [comment]
>> second comment
It's not related to your sample. In layoutOptions.md we uses Plantuml-sever generated urls and the url in the LayoutOptions.md document it was not correct updated during a PR. And this I will fix.
