### ISSUE TITLE
Preparing a v2.3.0 release

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#165]
Hi @Potherca, @adrianvlupu, @IOrlandoni, @michiel and @stawirej:

Can we create a new v2.3.0 with all open pull requestes?

I have an updated [structurizr/dotnet-extsions C4PlantUmlWriter](https://github.com/structurizr/dotnet-extensions/pull/6) and would prefere to use a official <C4/> include with all available features.

Thank you and best regards
Helmut

PS.: Based on an official Structurizr v1.0.0 model it generated pictures (with v2.2.0) like 

![grafik](https://user-images.githubusercontent.com/21959385/123664702-de575b80-d837-11eb-8f19-1cfe461ed225.png)

and with v2.3.0 like 

![grafik](https://user-images.githubusercontent.com/21959385/123664821-0050de00-d838-11eb-96b9-fe2f0b53730f.png)

**Comment by Potherca** [comment]
I plan on creating a 2.3 release this coming weekend, with all currently open MRs.

**Comment by kirchsth** [comment]
thank you

**Comment by Potherca** [comment]
Comment moved over from #161:

> @Potherca: I would create a new release with following Issues/PR:
> solved issues: #159,#157,#149,#146,#145,#139,#134,#21,#12
> PRs: #161,#160,#158,#150,#147,#143,#141,#59
> 
> (#156 could be obsolete as soon it is merged into PlantUML)
> 
> NOT included: #155,#154,#148,#85
> Rejected?:#104
>

**Comment by Potherca** [comment]
All branches could be merged to the same branch without conflicts or issues. Will now commence merging all MRs.

**Comment by Potherca** [comment]
All done! Release [v2.3](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.3.0) is now a fact!

**Comment by kirchsth** [comment]
@Potherca, Thank you

Can you
a) update the moved comment and remove all issues which are not part of it
> (156 could be obsolete as soon it is merged into PlantUML)
> NOT included: 155, 154, 148, 85
> Rejected?:104

b) add/link/close #159, #157 and #149 too (corresponding implementations were part of the PRs #160, #158 and #150) 

BR
Helmut
