### ISSUE TITLE
Element inside intersection of 2 or more Boundaries

### ISSUE THREAD

**Issue by RePrete** [plantuml-stdlib/C4-PlantUML#166]
Hi,
I have search in different places without an answer, is it possible to have an element (container for example) contained in the intersection of 2 or more System_Boundary?

**Comment by kirchsth** [comment]
Hi @RePrete,

I found following [PlantUML forum entry](https://forum.plantuml.net/13423/intersection-of-rectangles-of-different-groups-in-plantuml). It is not possible

Best regards
Helmut

**Comment by RePrete** [comment]
Thanks anyway
