### ISSUE TITLE
Typo in doc - &textColor should be $textColor

### ISSUE THREAD

**Issue by victoria-pinzhen-liao-en** [plantuml-stdlib/C4-PlantUML#167]
Hi team,

Thanks a lot for the wonderful tutorial, but I notice some typos

In L#custom-tagsstereotypes-support-and-skinparam-updates

in paragraph #Custom schema definition

The code is

```
UpdateRelStyle($lineColor=$COLOR_REL_LINE, &textColor=$COLOR_REL_TEXT)
```
but the `&textColor` should be  `$textColor` instead
```
UpdateRelStyle($lineColor=$COLOR_REL_LINE, $textColor=$COLOR_REL_TEXT)
```

I wonder if you can kindly update it , thanks a lot 

Best regards,
Victoria

**Comment by Potherca** [comment]
Hi, thank you for taking time to report this! I've opened an MR to fix the docs.
