### ISSUE TITLE
Typo in doc - notice an extra ` symbol in #Element properties

### ISSUE THREAD

**Issue by victoria-pinzhen-liao-en** [plantuml-stdlib/C4-PlantUML#168]
Hi team,

In #element-properties

`AddProperty(col1, col2, ?col3,` ?col4)\`  has an extra \` symbol after ?col3, and should be `AddProperty(col1, col2, ?col3, ?col4)`  instead

Screenshot

![image](https://user-images.githubusercontent.com/84942550/125173905-be218800-e1b9-11eb-93c2-313c3fa357b7.png)

**Comment by Potherca** [comment]
I've opened an MR to fix this. Thanks again! :+1:
