### ISSUE TITLE
Question - when colour is defined via UpdateElementStyle the legend is not updated

### ISSUE THREAD

**Issue by victoria-pinzhen-liao-en** [plantuml-stdlib/C4-PlantUML#169]
Hi team,

According to doc #Custom schema definition, 

> if the custom (color) schema is defined via UpdateElementStyle() then the legend of existing elements is updated too.

However, when colour is defined via UpdateElementStyle the legend won't be updated

![image](https://user-images.githubusercontent.com/84942550/125174088-c9c17e80-e1ba-11eb-99a8-96c7942b3f63.png)

It's updated when `SHOW_LEGEND()` is added

![image](https://user-images.githubusercontent.com/84942550/125174099-db0a8b00-e1ba-11eb-97c1-96aa46a46f14.png)

Can you kindly suggest ? Thanks a lot

**Reproduction**

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/twitter_square.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

!$COLOR_BG = "#542788"
!$COLOR_FONT = "#f7f7f7"
!$COLOR_BORDER = "#b2abd2"

UpdateElementStyle("system", $bgColor=$COLOR_BG, $fontColor=$COLOR_FONT, $borderColor=$COLOR_BORDER)

!$COLOR_REL_LINE = "#000080"
!$COLOR_REL_TEXT = "#2E8B57"
UpdateRelStyle($lineColor=$COLOR_REL_LINE, $textColor=$COLOR_REL_TEXT)

Person(admin, "User")
System_Boundary(app, "App") {
    System(backend, "App Back End")
    System(ui, "App UI")
}
ContainerDb(twitter, "Twitter", "DB")


Rel(admin, ui, "uses")
BiRel(backend, ui, "data")
BiRel(backend, twitter, "data")

SHOW_LEGEND()

@enduml
```

Best regards,
Victoria

**Comment by kirchsth** [comment]
Hi Victoria,

`SHOW_LEGEND()` is the replacement of `LAYOUT_WITH_LEGEND()`. But `SHOW_LEGEND()` has to be the last entry in the diagram, therefore we still have LAYOUT_WITH_LEGEND() that old diagrams are working. 

(If you have a better comments we could update README.md)
> **Comments**
> * `SHOW_LEGEND()` supports the customized stereotypes
>      (`LAYOUT_WITH_LEGEND()` cannot be used, if the custom tags/stereotypes should be displayed in the legend).
> * `SHOW_LEGEND()` has to be last line in diagram.

If you use `SHOW_LEGEND()` then `LAYOUT_WITH_LEGEND()` is not required anymore.

Best regards
Helmut

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/twitter_square.puml

' LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

!$COLOR_BG = "#542788"
!$COLOR_FONT = "#f7f7f7"
!$COLOR_BORDER = "#b2abd2"

UpdateElementStyle("system", $bgColor=$COLOR_BG, $fontColor=$COLOR_FONT, $borderColor=$COLOR_BORDER)

!$COLOR_REL_LINE = "#000080"
!$COLOR_REL_TEXT = "#2E8B57"
UpdateRelStyle($lineColor=$COLOR_REL_LINE, $textColor=$COLOR_REL_TEXT)

Person(admin, "User")
System_Boundary(app, "App") {
    System(backend, "App Back End")
    System(ui, "App UI")
}
ContainerDb(twitter, "Twitter", "DB")


Rel(admin, ui, "uses")
BiRel(backend, ui, "data")
BiRel(backend, twitter, "data")

SHOW_LEGEND()
@enduml
```

**Comment by kirchsth** [comment]
Hi @victoria-pinzhen-liao-en,
did it solve your problem? Can we close it?
BR Helmut

**Comment by victoria-pinzhen-liao-en** [comment]
yes, thanks a lot
