### ISSUE TITLE
Add element to boundary

### ISSUE THREAD

**Issue by yababer** [plantuml-stdlib/C4-PlantUML#176]
I am wondering if there is a way to add an existing element to the boundary.  Here is a pseudo-code example:

---
file  shared_socket.puml
```plantuml
@startuml
Component(shared_socket, "socket", "c++", "shared socket component")
@enduml
```

---
file  my_app1.puml
```plantuml
@startuml
!include shared_socket.puml
Container_Boundary(my_app1, "my app1") { }
Add_Boundary(shared_socket, my_app1)
@enduml
```
---
file  my_app2.puml
```plantuml
@startuml
!include shared_socket.puml
Container_Boundary(my_app2, "my app1") { }
Add_Boundary(shared_socket, my_app2)
@enduml
```
Something like that would be awesome.

**Comment by kirchsth** [comment]
Hi @yababer,

you could try it with included subparts like below. Details see
https://forum.plantuml.net/6577/ability-include-blocks-code-from-plantuml-file-into-another
https://plantuml.com/preprocessing "Including Subpart"

```plantuml
' file Shared.puml ------------------------

@startuml
!include <C4/C4_Component.puml>

!startsub shared_socket
  Component(shared_socket, "socket", "c++", "shared socket component")
!endsub

!startsub shared_socket2
  Component(shared_socket2, "socket 2", "c++", "shared socket component")
!endsub

@enduml

' file App1.puml ------------------------

@startuml
!include <C4/C4_Component.puml>

Container_Boundary(my_app1, "my app1") { 
  !includesub Shared.puml!shared_socket

  Component(app1, "App 1", "c++", "exe")
}

@enduml

' file App2.puml ------------------------

@startuml
!include <C4/C4_Component.puml>

Container_Boundary(my_app1, "my app1") { 
  !includesub Shared.puml!shared_socket

  !includesub Shared.puml!shared_socket2

  Component(app2, "App 2", "c++", "exe")
}

@enduml
```

Shared.png
![Shared](https://user-images.githubusercontent.com/21959385/129416700-f5e449d0-4cc3-4cd8-83f3-4879b606f25b.png)
App1.png
![App1](https://user-images.githubusercontent.com/21959385/129416718-4c049583-a0d1-462b-8e83-734dfead27de.png)
App2.png
![App2](https://user-images.githubusercontent.com/21959385/129416727-044cb207-e8e2-4e5f-9e33-21c453809cf5.png)

Best regards
Helmut

**Comment by yababer** [comment]
thanks.  Let me give it a try this morning.

**Comment by yababer** [comment]
This worked thank you.

**Comment by kirchsth** [comment]
Hi @yababer, second diagram of https://github.com/plantuml-stdlib/C4-PlantUML/issues/191#issuecomment-934746859 could be an alternative solution.
BR Helmut

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

' -------------------------
' this part defined in a central file

!unquoted procedure foo($alias="foo", $label="FOO", $techn="SPA", $descr="long-text here")
Container($alias, $label, $techn, $descr)
!endprocedure
!unquoted procedure bar($alias="bar", $label="BAR", $techn="SPA", $descr="long-test here too")
Container($alias, $label, $techn, $descr)
!endprocedure

' -------------------------
' this is part of the concrete diagram

foo($descr="changed description")
bar($descr="")
Rel(foo, bar, "do something")
@enduml
```

![](http://www.plantuml.com/plantuml/png/dP11ImCn48Nl-HNJKB25jdln92oq5ZmfBHNFaYQpcs0sMPC9-lETLNVne2Zcb9UNUVFDR3EfHANpOkQ2ziKWMA8-NrLLKY-Rrf4jvv8nwHW80srqxAedbxJDPAlzvVheLQ27kziANzatQFZnSS-VbGkODlqGBIvW_TDXZwpBq3C666ouoe0Be41pkwGyDCwZ4BCIdaiaDliKDPgI49eO5tFbdSgrvBjSmTohC_fQtXmEWoBKDjJo_hWRbC6iKorz3EsQ61Si9fHBCT5-XeqnOy1OkXGpdd1g_otIMQK9YUzVaAvtfz-GyWSIK8p_n_hJjiU5nuOrWev19oG4urIRL2V4iDgHJbiLMZJmBbrFBWR6u-cc7onFw1TSj09-Nu4q4NBia9k5bjqj4vRElm40)

BR Helmut
