### ISSUE TITLE
Force relationships to be straight lines

### ISSUE THREAD

**Issue by rolandobloom** [plantuml-stdlib/C4-PlantUML#183]
Is there a way to force relation line to be straight?

**Comment by kirchsth** [comment]
You could try PlantUML feature

``` plantuml
skinparam linetype ortho
' or 
skinparam linetype polyline
```

BR Helmut

**Comment by kirchsth** [comment]
Hi @rolandobloom,
did it solve your problem? Can we close it? 
BR Helmut

**Comment by rolandobloom** [comment]
@kirchsth 
Thank you for your reply. Yes, we can close it.
