### ISSUE TITLE
Provide fallback font cascade for sketch style

### ISSUE THREAD

**Issue by languitar** [plantuml-stdlib/C4-PlantUML#186]
The current skinparam for the sketch style uses Comic Sans as the only font. This font is proprietary and might not exist on some systems. Moreover, it lacks a few important characters. With font fallback support now available in plantuml (https://forum.plantuml.net/10498/is-there-a-supported-way-to-specify-fall-back-fonts), it would be nice if there was a larger cascade of appropriate fonts.

**Comment by Potherca** [comment]
Good point! 

We'll need to decide on the exact order of the font stack, but in the past, I've seen this being used for Comic-style fonts:

```
DefaultFontName: "Comic Sans MS", "Comic Sans", "Chalkboard SE", "Comic Neue", cursive, sans-serif;
```

**Comment by Potherca** [comment]
I think the main use-case for this would _not_ be standard plantuml server but a local or custom setup.

Besides starting with a `comic`, and ending in a generic `sans-serif`, I think DejaVu Sans (or Sans Light) might be a good match for somewhere in between.

**Comment by kirchsth** [comment]
You are right, local I have >100 fonts.
But I still have the [problem](https://forum.plantuml.net/14842/specify-fall-back-fonts-is-not-working) with the font stack, some combinations are working some not (I see no pattern).

**Comment by Potherca** [comment]
I'm inclined to move forward with the suggested changes regardless of the font-stack issue in PlantUML, as that will most likely be resolved eventually. Playing around with the stack might even lead to the discovery of the root cause of things n ot working?

**Comment by kirchsth** [comment]
Hi @languitar, @Potherca

I try to support configurable sketch styles (incl. fonts) with a new call
```
SET_SKETCH_STYLE($bgColor="_dont_change_", $fontColor="_dont_change_", $warningColor="_dont_change_", $fontName="_dont_change_", $footerWarning="_dont_change_", $footerText="_dont_change_")

' and it can be used like 

SET_SKETCH_STYLE($bgColor="lightblue", $fontColor="gray", $warningColor="white", $fontName="A not existing, cursive, Comic Neue, Comic Sans MS, Comic Sans, Chalkboard SE, Comic Neue, cursive, sans-serif", $footerWarning = "Sketch", $footerText = "Created for discussion")
```

But I found following problems:
a) changed font color changes all font colors (is a new bug in PlantUML, I expect a fast bugfix)
b) if only one font is defined the support depends on the output formats (see below), but it can be changed
c) font cascade is not working (here I don't know if we get a bugfix)

Best regards
Helmut

SVG
![](https://www.plantuml.com/plantuml/svg/ZPRVK-Cs4CVVyrSiFcP8Xa1Afq_CGI_aSXpJa33O7BqdZsnjOZMov9Da0jFh_ruf3YP6STed_zZTpwvslzxaapP4cJBddGCcKbvIXCoOGfyF1egiJXVCP6LIQbIf50Q5EKrbFYWu4IxcH1lAMJ8O_NPovruzt4u6ET46bNqLZsm4OGBLQU7udOC5bmdXS1Z-COv6N-EhwtWqcypkuGA23-Fn-EhpA03Fwyji6htv1PxzSNW_lPbkeHJIO3TbEhmTEu-Hp5aA8H4QRiDTlhDeVFyATW6FH0ac5kUjlj7upsXDLaWCKfXB1PJfjDIQIT47WKWr60a9mXFXZ3glmBQa53zAwI8A9LEafK88nr6yeOVHzycuUvWiHf9BTH74L0eJfnaH2uo3FXpExNERRLKLlIzqIdBSQP86rURGhVO8dyrxOy-gQ0wl1SF11Rnpw02qow0Ex1oWe6pkO5MX-t7jUgc2FMJTcdRgVfNL28zTzxMDswxBEhJ1QmoZ5RfVm4s8XwzcsSfk5_nsU4srbrhCLk7rFKo6tsSFKJmCD_BkzYnVBvaeY28vs9nqfPWnAC2e4brzlaWk8GWQOGb9bmibIq7Ni_0Y6gVrDUBnACv9oSsNMdLUK3lI3JBSYtJZzMDye3T41uMVFtVEOPFmu90pWMuDLLE1ZqvGa5OB08vRn7mCmMLmt9RNMZyE7ESIAeINtcPU9suHmD6-XSRP8ZC9B_7TCbieykBli5N633Ptrn24D83FJ1lhruUqL9ezOH-g7J_5qjutzltsextF25ycaYXgosn6rIXjFKyqAZRtbgDhThX4asRDlTZ-Ms1NPEV_DCG_FILggP3w2tfd1HTxyX_1h401TaW9n_mSFh-NVFNzQnXE9l2c8GrTrsmf-0kO3A4KLjXC8Es1mbm-8VLdQ7DrRo2J1S8DBD00WJbxNjV4J6-NE3p4ZeAxkIsN5HnxuBprMWGhgPPE0-lQKgaKfgvOX8oy_lGkXLm988928HRTttiWIrEK1fW6XJzAff3QNDPsNXrxxjQAPO16zOGADAC8NVraxGvYrJv7XSAyyquvSo-TTyyVzfPw_-9vdEOvE_ibw5M9ArAJOItx8DycS2rDnjAgKucz1w9mkoT0313EuJz8qyQdz5PS7-eSZQ_1vjknqpjtgBGKNK9p9leG3DtLGXKnKjcOy4KRpEChrosYNhhfMH-EGf8N78zwy7S70A3-wzXTOHAJeh2SHqnWM1ISfSGu8TjNemzz68PtfzDnP4CKmg-dPt3xRUHiGyxbIaEfKQt7dygyS6rvbGv4AsOCAZ0iHxU_jAtjdqrrNLCPBMVZvWvxZ_prL6zbFMZKBj_NABeBhPTpggrlc6iqsZwYkyoLpBT3Fg6WPSx_1G00)

PNG
![](https://www.plantuml.com/plantuml/png/ZPRVK-Cs4CVVyrSiFcP8Xa1Afq_CGI_aSXpJa33O7BqdZsnjOZMov9Da0jFh_ruf3YP6STed_zZTpwvslzxaapP4cJBddGCcKbvIXCoOGfyF1egiJXVCP6LIQbIf50Q5EKrbFYWu4IxcH1lAMJ8O_NPovruzt4u6ET46bNqLZsm4OGBLQU7udOC5bmdXS1Z-COv6N-EhwtWqcypkuGA23-Fn-EhpA03Fwyji6htv1PxzSNW_lPbkeHJIO3TbEhmTEu-Hp5aA8H4QRiDTlhDeVFyATW6FH0ac5kUjlj7upsXDLaWCKfXB1PJfjDIQIT47WKWr60a9mXFXZ3glmBQa53zAwI8A9LEafK88nr6yeOVHzycuUvWiHf9BTH74L0eJfnaH2uo3FXpExNERRLKLlIzqIdBSQP86rURGhVO8dyrxOy-gQ0wl1SF11Rnpw02qow0Ex1oWe6pkO5MX-t7jUgc2FMJTcdRgVfNL28zTzxMDswxBEhJ1QmoZ5RfVm4s8XwzcsSfk5_nsU4srbrhCLk7rFKo6tsSFKJmCD_BkzYnVBvaeY28vs9nqfPWnAC2e4brzlaWk8GWQOGb9bmibIq7Ni_0Y6gVrDUBnACv9oSsNMdLUK3lI3JBSYtJZzMDye3T41uMVFtVEOPFmu90pWMuDLLE1ZqvGa5OB08vRn7mCmMLmt9RNMZyE7ESIAeINtcPU9suHmD6-XSRP8ZC9B_7TCbieykBli5N633Ptrn24D83FJ1lhruUqL9ezOH-g7J_5qjutzltsextF25ycaYXgosn6rIXjFKyqAZRtbgDhThX4asRDlTZ-Ms1NPEV_DCG_FILggP3w2tfd1HTxyX_1h401TaW9n_mSFh-NVFNzQnXE9l2c8GrTrsmf-0kO3A4KLjXC8Es1mbm-8VLdQ7DrRo2J1S8DBD00WJbxNjV4J6-NE3p4ZeAxkIsN5HnxuBprMWGhgPPE0-lQKgaKfgvOX8oy_lGkXLm988928HRTttiWIrEK1fW6XJzAff3QNDPsNXrxxjQAPO16zOGADAC8NVraxGvYrJv7XSAyyquvSo-TTyyVzfPw_-9vdEOvE_ibw5M9ArAJOItx8DycS2rDnjAgKucz1w9mkoT0313EuJz8qyQdz5PS7-eSZQ_1vjknqpjtgBGKNK9p9leG3DtLGXKnKjcOy4KRpEChrosYNhhfMH-EGf8N78zwy7S70A3-wzXTOHAJeh2SHqnWM1ISfSGu8TjNemzz68PtfzDnP4CKmg-dPt3xRUHiGyxbIaEfKQt7dygyS6rvbGv4AsOCAZ0iHxU_jAtjdqrrNLCPBMVZvWvxZ_prL6zbFMZKBj_NABeBhPTpggrlc6iqsZwYkyoLpBT3Fg6WPSx_1G00)

the complete sample

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!global $SKETCH_BG_COLOR = "#EEEBDC" 
!global $SKETCH_FONT_COLOR = ""
!global $SKETCH_WARNING_COLOR = "red"
!global $SKETCH_FONT_NAME = "Comic Sans MS"
!global $SKETCH_FOOTER_WARNING = "Warning:"
!global $SKETCH_FOOTER_TEXT = "Created for discussion, needs to be validated"

!unquoted procedure SET_SKETCH_STYLE($bgColor="_dont_change_", $fontColor="_dont_change_", $warningColor="_dont_change_", $fontName="_dont_change_", $footerWarning="_dont_change_", $footerText="_dont_change_")
!if $bgColor != "_dont_change_"
  !global $SKETCH_BG_COLOR = $bgColor
!endif
!if $fontColor != "_dont_change_"
  !global $SKETCH_FONT_COLOR = $fontColor
!endif
!if $warningColor != "_dont_change_"
  !global $SKETCH_WARNING_COLOR = $warningColor
!endif
!if $fontName != "_dont_change_"
  !global $SKETCH_FONT_NAME = $fontName
!endif
!if $footerWarning != "_dont_change_"
  !global $SKETCH_FOOTER_WARNING = $footerWarning
!endif
!if $footerText != "_dont_change_"
  !global $SKETCH_FOOTER_TEXT = $footerText
!endif
!endprocedure

!procedure LAYOUT_AS_SKETCH()
  skinparam handwritten true
!if $SKETCH_BG_COLOR > ""
  skinparam backgroundColor $SKETCH_BG_COLOR
!endif
!if $SKETCH_FONT_COLOR > ""
  skinparam defaultFontColor $SKETCH_FONT_COLOR
!endif
!if $SKETCH_FONT_NAMES > ""
  skinparam defaultFontName $SKETCH_FONT_NAME
!endif
!if $SKETCH_FOOTER_WARNING > "" || $SKETCH_FOOTER_TEXT > ""
  !$line = "footer <font color=" + $SKETCH_WARNING_COLOR + ">"+ $SKETCH_FOOTER_WARNING + "</font> " + $SKETCH_FOOTER_TEXT
  $line
!endif
!endprocedure

' SET_SKETCH_STYLE($bgColor="lightblue", $fontColor="gray", $warningColor="white", $fontName="A not existing, cursive, Comic Neue, Comic Sans MS, Comic Sans, Chalkboard SE, Comic Neue, cursive, sans-serif", $footerWarning = "Sketch", $footerText = "Created for discussion")

SET_SKETCH_STYLE($bgColor="lightblue", $warningColor="darkred", $footerWarning="Sketch", $footerText="Created for discussion")

' Open problem: DefaultFontColor changes ALL font colors (not only the undefined) removed $fontColor="gray"
' (I hope I get a fix for it)
' SET_SKETCH_STYLE($fontColor="gray")

' Open problem: (multiple) fonts not working, the correct one has to be known and png(?) output is required
' png: font found on server side (svg: a different font found on client side)
SET_SKETCH_STYLE($fontName="jlm_cmmi10")
' png font on server side
' SET_SKETCH_STYLE($fontName="VL Gothic")

' both are not working at all 
' SET_SKETCH_STYLE($fontName="Not existing, jlm_cmmi10, VL Gothic, sans-serif")

LAYOUT_AS_SKETCH()

Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml
```

**Comment by kirchsth** [comment]
Problem c) it could be that we get a bugfix
https://forum.plantuml.net/14842/specify-fall-back-fonts-is-not-working

**Comment by kirchsth** [comment]
@languitar,  @Potherca: A first version can be tested via my extended branch
Independent of c) it works.
But I have questions related to the $fontColor. 
   a) Which parts of the diagram should get the changed font color too (e.g. unformatted arrows, borders, ...) 
   b) Or can/should I skip the $fontColor (there could be only a problem if the background color is lightgray(?) too)

What do you mean?
Thank you and best regards
Helmut

```plantuml
@startuml LAYOUT_AS_SKETCH Sample
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

SET_SKETCH_STYLE($bgColor="lightblue", $fontColor="darkblue", $warningColor="darkred", $footerWarning="Sketch", $footerText="Created for discussion")

' PNG with font jlm_cmmi10 (typically another font is used)
' SET_SKETCH_STYLE($fontName="jlm_cmmi10")

' SVG with fallback fonts MS Gothic,Comic Sans MS, Comic Sans, Chalkboard SE, Comic Neue, cursive, sans-serif (typically without "MS Gothic")
SET_SKETCH_STYLE($fontName="MS Gothic,Comic Sans MS,Comic Sans,Chalkboard SE,Comic Neue,cursive,sans-serif")

LAYOUT_AS_SKETCH()

Person(admin, "Administrator")
System_Boundary(c1, 'Sample') {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml
```

PNG with font `jlm_cmmi10`

![LAYOUT_AS_SKETCH with custom style png Sample](https://www.plantuml.com/plantuml/png/VP9lQnf14CRV-occru06BjgKlYe8iOSaqCHAxvAGLyVUtkXjtJ_7xcojb7xtpg962srzixVpF3FFRrXl0WbFqUZ16sMbZYr2HzI7ZvE95zlnMb4NcnZGIsS9BOsbCvEDyh8Br4sA3rTBBImzFjnFy0VhBRPSh0is2sNHZ_iqUb3EgxhyFA-AkxgiNkxdeujcNJZj_3JJQjrHeoDcELoikEzGRuNV7CjRuQsowpF5OxltEqB_l9UdMRb1ajr9g9XfcXKU1M4BA-UXLK7649IpsULWC8JbuXQsl2EaPFYcJIsDKTVlO4IxNacXzGw4TTIXtrjKW1YmlVpBIabV28FJx3Hddr8-7LDuO2Fa1f8tm4C9jpnRoRnmHaaeXKt574vN_kw4tZHE-1RA-L5QOCGSPFH1VUUFmCwhW5wjpi5Jf8i4sMiEumpXV-J_8Ze3-fFd3ET8Su99sz_FNhuyLlMiF6IEkBP47vmTYTOecqCsIwSAv0KvpptbBX2Q-fEBjXL-DvBNEGnBONgDmqluEG3-lVx3HbjiQj7tFESP6vZrlURrARqmbugtESpAvNWnhxZ58xmVNyF3Kv6qcTPkcvwJQO0SI6TwmHOJDIdEWcghYD03AOEQimAp_JhGZMWlyfo3BItx5VLngnFMO-1EFk-gQbcoAvbUrTEOMwJ0Lqp7oZjptdA3jer6_mO0 "LAYOUT_AS_SKETCH with custom style png Sample")

SVG with fallback fonts MS Gothic,Comic Sans MS,Comic Sans,Chalkboard SE,Comic Neue,cursive,sans-serif

![LAYOUT_AS_SKETCH with custom style svg Sample](https://www.plantuml.com/plantuml/svg/VP9FQzj04CNl_XHJDH055BifFHKCSOL9e8bhAZaX9x5QZQsjzu_O7TKrfT-zizYEN4hhosfdthpt6zQtWOIdtkZH6sMbxXk4bgWB7oSJBtRZZQAsh_k0NZfBQ6aidPbibPTje7QIVxXUQc5fzVWmmH_SRx3XOfMpM2YBVjn5wr4nBwlYyxpCxwkYV7cOfnVr9dVQ-McYrQQbMlUOP72nvhbZlH5-UohlXBVARiuw7fk3tX7wvqDxcXHR9DaEZPAPfadkKH0si7OU6XLa7u9oDhaQZIvXkRY37Uy8CHc-QLD9OzJDEqXftoafjDw3i8vQz0U92j07RAvuzk-bec8X34wJmUcGKpoTSjYo5d8BKHlWiO0xTbSoovrH4WfXOp63uShVhT3RsWdVSEQfjS0UCv2z3-exVmHMNWVqQdsE7YDTJv2yvZ3E_xZ_nNE6yoVD6So9PK29kp_CNhwiocfM73DJhYtH1sTJqHXbCqXcyLI1l23d8-0-49hga-jj8_m-bJSPN1R2T1elh-3d2FZt-WzBTrXNeklOvnbhc7MTvkKflZ2NyhSPp8hbU34lUSGZl1_VmEDJ7diphTqkFYVJ03cGpdI29QRNf3WBofqYGW-a36hE2ipswqYNqg79FaTPNFOhwjDM0zOgy2IVzsMvB5Z5eW5wiBb32dp5UAozC-SZjsYRtkZV "LAYOUT_AS_SKETCH with custom style svg Sample")
