### ISSUE TITLE
Difficulties with Lay_ and  Rel_ 

### ISSUE THREAD

**Issue by marymoleva** [plantuml-stdlib/C4-PlantUML#187]
Hello. We are faced with the difficulty of using the tool. Could you help me?

1. Arrows are stuck together. The pieces of text are overlapped what causes inability to track up coherence.
2. Connections work unpredictably. When you set a lot of connections, then the containers are scattered in different unintended directions (Rel_*) . Why that happens?
3. Layout options  work unpredictably (Lay_*) . Why are directions ignored?

![Screenshot at Sep 29 16-01-12](https://user-images.githubusercontent.com/89629712/135273469-16dbd2f2-9fca-41f8-a506-7fca6fb923d4.png)

**Comment by Potherca** [comment]
Hi! Could you post the contents of your diagram, so we can look along with what is happening?

**Comment by marymoleva** [comment]
Hi, sure!

1. Difficulties with Lay_ : Look at the location of the "b" and "c". 

`@startuml

!include <c4/C4_Container.puml>

Container(a, "a", "")
System_Boundary(s1, "s1") {
        Container(b, "b", "")
}
Container(d, "d", "")
Container(c, "c", "")

Rel_D(a, b, "")
Rel_D(b, d, "")
Rel_D(c, d, "")

Lay_R(b, c)

@enduml`

2. Arrows are stuck together. The pieces of text are overlapped what causes inability to track up coherence: 

`@startuml container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/java.puml
!include DEVICONS/scala.puml
!include DEVICONS/go.puml
!include <logos/kotlin>
!include DEVICONS/postgresql.puml
!include DEVICONS/msql_server.puml
!include <logos/oracle>
HIDE_STEREOTYPE()
'Systems
System_Boundary(s1, "s1") {
    Container(a, "a", "java", "text", "java")
    Container(b, "b", "java", "text", "java")
    Container(c, "c", "java", "text", "java")
    Container(d, "d", "java", "text", "java")
    Container(f, "f", "java", "text", "java")
    Container(g, "g", "java", "text", "java")
    Container(h, "h", "java", "text", "java")
    Container(i, "i", "java", "text", "java")
    Container(j, "j", "java", "text", "java")
    ContainerDb(postgres, "k", "PostgreSQL", "text", "postgresql")
}

'External systems
Container_Ext(l, "l", "scala", "text", "scala")
Container_Ext(m, "m", "go", "text", "go")
Container_Ext(n, "n", "go", "text", "go")
Container_Ext(o, "o", "kotlin", "text", "kotlin")
Container_Ext(p, "p", "go", "text", "go")
Container_Ext(q, "q", "text", "postgresql")
Container_Ext(r, "r", "Oracle", "text", "oracle")
Container_Ext(s, "s", "Microsoft SQL", "text", "msql_server")
Container_Ext(t, "t", "java", "text", "java")
System_Ext(u, "u", "text")
System_Ext(v, "v", "text")
System_Ext(w, "w", "text")
Container_Ext(x, "x", "scala", "text", "scala")
Container_Ext(y, "y", "kotlin", "text", "kotlin")
Container_Ext(z, "z", "scala", "text", "scala")


'Relations
Lay_L(a, b)

Rel_U(i,l,"text","Kafka")
Rel_U(y,a,"text","REST")
Rel_U(u,b,"text","Kafka")
Rel_U(a,r,"text","REST")
Rel_D(i,g,"text","Kafka")
Rel_U(i,r,"text","Kafka")
Rel_L(h,i,"texttexttexttexttexttexttexttexttexttexttexttext","Kafka")


Rel_R(h,q,"text","SQL")
Rel_L(q, h,"text","SQL")

Rel(a,o,"text", "REST")
Rel_U(a,m,"text", "Kafka")
Rel(a, x, "text", "REST")
Rel(a, o, "text", "Kafka")
Rel(v, b, "text", "REST")
Rel(b, v, "text", "REST")
Rel(b, r, "text", "SQL,Kafka")

Rel_U(a,n,"text", "REST")
Rel_U(v,a,"text", "REST")
Rel_U(l,a,"text","REST")
Rel_D(f,w,"text","REST")
Rel_D(a,d,"text","REST")
Rel(a, o, "text", "Kafka")
Rel_R(s,a,"text","Kafka")
Rel_U(a,m,"text", "Kafka")
Rel(a, x, "text", "REST")
Rel(a, r, "text", "SQL,Kafka")
Rel(a, z, "text", "Kafka")

Rel(c, p, "text", "REST")
Rel(c, o, "text", "REST")
Rel(c, r, "text", "Kafka")
Rel_D(c,postgres,"text", "SQL")


Rel_D(n,d,"text","Kafka")
Rel_U(d,l,"text","Kafka")
Rel(d,a,"text","REST")
Rel(d,i,"text","Kafka")
Rel(d,m,"text","REST")

Rel_D(g,u,"text","Kafka")
Rel(g, m, "text", "Kafka")

Rel_D(t, j, "text", "Kafka")

Lay_R(o, b)
Lay_D(b, x)
Lay_D(a, s)
Lay_U(r, i)
Lay_D(h, g)
Lay_U(b, r)




'Lay_R(notifier,scheduler)
@enduml`

![image](https://user-images.githubusercontent.com/89629712/136531457-bad78832-72c0-47e6-9c13-1dcb97c8b175.png)
![image](https://user-images.githubusercontent.com/89629712/136531499-e2768b4c-6905-4a4f-bcdb-d0ff587a7454.png)

**Comment by kirchsth** [comment]
at 1) I have opened a [plantum-forum question](https://forum.plantuml.net/14723/relative-simple-layout-but-right-arrow-not-working), maybe we get a solution for it
