### ISSUE TITLE
Notes element

### ISSUE THREAD

**Issue by Ramin2c** [plantuml-stdlib/C4-PlantUML#189]
Hello
There are times when a designer needs to write an extra description but not within an element on the diagram. It would be very nice  then to be bale to write notes or comments in a separate box and attach to any element like container, system or even relations.
I have looked around in the forums and looks like this is not supported yet by the PlantUML.

Best Regards
Ramin Toussi

**Comment by kirchsth** [comment]
Hello @Ramin2c

C4-PlantUML has no special note support, but there are some note features in plantuml itself
```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' change note style
' https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html#note
skinparam NoteBorderColor lightgray
skinparam NoteBackgroundColor darkgray
skinparam NoteFontColor white

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
' define a note after a relation
' https://forum.plantuml.net/7855/notes-on-arrow
note on link
  this is a note
end note

' define a note relative to a component
' https://plantuml.com/en/component-diagram#d50d8f9219a41435
note right of personAlias
First line
        second line (indented)
        third line (indented)
Last line
end note

' define a floating note
note as AFloatingNoteAlias
A floating note
end note

' assigne a note to a component via Lay_*
note as ANoteAlias
ANote line
        second line (indented)
        third line (indented)
Last line
end note

Lay_U(ANoteAlias, systemAlias)
@enduml
```
![http://www.plantuml.com/plantuml/png/jL9DRzGm4BtxLvZsm2xgnXIwekNKKjJJ0XNGSpMD9ubLPnoD9wtstsCdxJPi4EB2QgNOps_UcuyvZm8iVUlLAqUbxotgHgIB7urXU2ng9qr_rqVaCf0WIL66rdGUACUiebZlxipboUewGpTVDgQ5ACW9khrC4U08kUYoldgjomQeHar1K4VPUapOizjEquQoRv44n0Kg6C5AWmcCXGi6oNWGZ6Agm2s8EAeD-9J9lQDL1mnjB1ff_M4sKHaTGFqrNJy5jiYNmGVMtjMDr0pRVGwKzpM7dkp8iy3fFgDT1PAHyDWuGQMkaMEWHJTyBho3UAGFDd27_Y0TldMv6F3wCyQItN0xMAfTXnRbysaM-XFBXf9JlVsBq8zj56mNSVZygxlwZlxtXETPp2GcwIpJz2nMYQzXd2bKWfmkZ1uoVpBUAd3V5iz3BWZ5V3XThqsEYwj0As0EZsgG2QIzetkbjJGkwlGVzHMI7GzgPZrQFg2MaA0oj5qW9Fd3WWqRZ6Hsd9LrK3EqXtRzrfvMP--Ep-3a-EJzMetAULDqgFIaLUhASPIS9Ihzz8jO1h83fXUEB9AWNUwUfN4yVzt0A3EfRLfQvGFa5HzVnXv7VN7r1ETD7FEvsADErI16L-ywjTSW_U10Rs1x--P5VYARZ_-fp6nwitWnEzAJzLsgyyHCq_e5]

I hope it helps
BR Helmut

**Comment by Ramin2c** [comment]
Hi
Thanks for the answer. This is what I've been after :)

Bests
Ramin
