### ISSUE TITLE
[Question] How to export the preview to file?

### ISSUE THREAD

**Issue by wimdeblauwe** [plantuml-stdlib/C4-PlantUML#19]
I just tested this extension and it works fine. I have a nice preview in VS code. The readme does not mention how to export this preview to an actual file. Could this be added?

**Comment by mindgazer** [comment]
click right mouse button, choose "Export current Diagram" or "Export current file Diagrams"

**Comment by mindgazer** [comment]
> I just tested this extension and it works fine. I have a nice preview in VS code. The readme does not mention how to export this preview to an actual file. Could this be added?

 click right mouse button, choose "Export current Diagram" or "Export current file Diagrams"

**Comment by Potherca** [comment]
Closing this issue as the asked question is specific to VS Code, not this repository and a useable answer has been given.
