### ISSUE TITLE
Ability to hide descriptions

### ISSUE THREAD

**Issue by languitar** [plantuml-stdlib/C4-PlantUML#191]
When building a set of related diagrams it might be useful to define entities like containers in a central file and to use the include feature for individual diagrams. That way, definitions are not repeated and typos and inconsistencies are less likely. What currently prevents me for doing this successfully is that I often like to have a description in the diagram first introducing an entity, but not in subsequent diagrams. The description uses some amount of screen estate and therefore blindly repeating it in every diagram can make the diagrams look cluttered.

What I'd like to have is some kind of control parameter (via tags?) to hide or show the description text of an entity selectively, at least, on the granularity of a whole diagram, ideally per element.

**Comment by gobravedave** [comment]
well it's not part of stdlib. but I had a similar requirement and created the following [plantuml helper](https://github.com/gobravedave/C4-Plantuml-Helper).. this preprocessor macro also supports drill in/out of published C4 contexts and containers....

**Comment by Potherca** [comment]
In the past, I've had a similar requirement that I solved using something like this:

```plantuml
@startuml
    !if (%variable_exists("$description_shown") == false)
        !$description_shown = true
        /' Your description goes here... '/
    !endif

  /' rest of the diagram... '/

@enduml
```

That way the "description" part of the diagram is only ever shown once. @languitar  Would (something like) this solve your issue?

**Comment by languitar** [comment]
@Potherca I don't quite understand how that works.

Right now I have a file `containers.puml` with content such as this one:
```puml
@startuml

/' catalog management '/
!startsub foo
Container(foo, "foo", "SPA", $descr="long-text here")
!endsub
!startsub bar
Container(bar, "bar", "SPA", $descr="long-test here too")
!endsub

@enduml
```

In my actual diagrams I then do this:

```puml
!includesub ./containers.puml!foo
!includesub ./containers.puml!bar

Rel(foo, bar, "do something")
```

How does that combine with your proposed solution?

**Comment by kirchsth** [comment]
Could it be that the final solution is a model based definition (and the mode is stored in json) like 

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Component.puml

AddPersonTag("teamred", $bgColor="#red", $legendText ="member of team red")
AddPersonTag("teamblue", $bgColor="#blue", $legendText ="member of team blue")

!$data={"partlen": "2", "game": "GamePlantuml", "participants": [
{"name": "XYZ" ,"as": "xyz", "team": "A", "persons": ["A1", "A2", "A3"] },
{"name": "RST" ,"as": "rst", "team": "B", "persons": ["B1", "B2" ]},
{"name": "UVW" ,"as": "uvw", "team": "B", "persons": ["B2", "B3" ]}],
"color": {"A": "red", "B": "blue"}
}

!foreach $part in $data.participants
  Component($part.name, $part.as, "techn")
  !foreach $member in $part.persons
    !$teamTag = "team"+$data.color[$part.team]
    Person($member, $member, $tags = $teamTag)
    Rel($member, $part.name, "develop")
  !endfor
!endfor

SHOW_LEGEND()
@enduml
```

![](http://www.plantuml.com/plantuml/png/VP9HJzim58NV_IlCNHzQBMkqiYUaIgGTOWziGr36DbGXDxaaqH8xiXrWg_hVTwyJbZ8XNXhd-DmlnwS-TbvPtzQLE2XrMhKPoiBxnXt5iLKFqxpqHRjf7ThKQ8_QJrDJnxzAcnRE5_7omxlpIcb_zVainaVQpp0ZyNPfwiPejZUC5acMdQDrHgzKFWQFghQOGIH7ctnfAcFdyAONAio9iYAOd4EDzGQjD7UIHoHR9Y-mDbMBps6zyYgDFOGJuc2KAQ_cMsYeYGer74cOqJJagaP-EQKd7vDhOfrzPLesf3ZQln5RqBtr-u-V82DGhCFZxpzivw_nQn9cG_Gm1ibxLf9P-3s4jTn5UwYBozM0iixlenR_enO1jPY1N3-3N7sx7Y3j_SFha5c0739a7Gb8kKtQsKB2VgwVztaTojk97RLtPoogj90ZhaMMMeOwf_ib2Id_tOXny4qvO2IxjN8XLLfec91r8FR_63E3iGzB7dAD-1nq1-IyFzBRxiCXzKqtmFewsBihC-wHaHmMNkME64-uIR1VO3LuznD3XlTOcQPBYZgZiEBfAIu_VRs-FJivFVdoSJmHnoJJbVaB)

My sample defines the diagram itself.

@languitar you could define your components with a similar pattern and then you could replace some arguments 
(the generator part is missing, but I think the idea is clear)

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

!$model={ "containers": [
{"alias": "foo" ,"label": "FOO", "techn": "SPA", "description": "long-text here"},
{"alias": "bar" ,"label": "BAR", "techn": "SPA", "description": "long-test here too"}
]}

' this part has to be generated based on the model
!unquoted procedure fooContainer($alias="foo", $label="FOO", $techn="SPA", $descr="long-text here")
Container($alias, $label, $techn, $descr)
!endprocedure
!unquoted procedure barContainer($alias="bar", $label="BAR", $techn="SPA", $descr="long-test here too")
Container($alias, $label, $techn, $descr)
!endprocedure

' in the diagram the definitions can be reused or changed
fooContainer($descr="changed description")
'description removed with empty ""
barContainer($descr="")
Rel(foo, bar, "do something")
@enduml
```

![](http://www.plantuml.com/plantuml/png/fP91Qzmm48Nl-XMpOY49EEjBJm53qa1FBGafFPLIP6bYYSgIAusQbh3_lIFlEZX9eOLU5e-UzFIzfxtCf1ALqOkD2zeNWs29fdpHjaazx0P7jlGbOz8n40RQwJYstrpIDfDjhz-StteLwDE7zot-PDsWuSMlrxnPkO1fDrLhiTcEqQ3l7a7gHSho0ZwBHwcyK_LRtiSeeP5UzUZh_ExcHZOW2RKDTVvuUrLdWradDv6BywgFOJWdlXmi9fJxPctPg_JCyktLtRzRveCb47FjnPUz42T0rcMOL699PLQWHnYGqoX20xtA_1i3RqEO4ujD2TzBhEAKeaPJs923FXLqkfrXkpbz0ziPjJjctywWtH5pEsDsBnEVYPTcYyrYi1mz4niCvedZZspSs6isNbonSOb_OrjLznzytBSxT6cS6f8Q3zzuxuAhRvL1gr1V866PYq-WhGe36l6iuWNkACBgkPdkP3MoqnX_y9O7HnPmdEWNI2au_sitFdg7_fHlQcfhzMyK8SSHoRemi7h9OSheVmC0)

BR Helmut

**Comment by kirchsth** [comment]
Hi @languitar, can you please complete/update my sample with your expectation?

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

' -------------------------
' this part defined in a central file

!unquoted procedure foo($alias="foo", $label="FOO", $techn="SPA", $descr="long-text here")
Container($alias, $label, $techn, $descr)
!endprocedure
!unquoted procedure bar($alias="bar", $label="BAR", $techn="SPA", $descr="long-test here too")
Container($alias, $label, $techn, $descr)
!endprocedure

' -------------------------
' this is part of the concrete diagram

foo($descr="changed description")
bar($descr="")
Rel(foo, bar, "do something")
@enduml
```

![](http://www.plantuml.com/plantuml/png/dP11ImCn48Nl-HNJKB25jdln92oq5ZmfBHNFaYQpcs0sMPC9-lETLNVne2Zcb9UNUVFDR3EfHANpOkQ2ziKWMA8-NrLLKY-Rrf4jvv8nwHW80srqxAedbxJDPAlzvVheLQ27kziANzatQFZnSS-VbGkODlqGBIvW_TDXZwpBq3C666ouoe0Be41pkwGyDCwZ4BCIdaiaDliKDPgI49eO5tFbdSgrvBjSmTohC_fQtXmEWoBKDjJo_hWRbC6iKorz3EsQ61Si9fHBCT5-XeqnOy1OkXGpdd1g_otIMQK9YUzVaAvtfz-GyWSIK8p_n_hJjiU5nuOrWev19oG4urIRL2V4iDgHJbiLMZJmBbrFBWR6u-cc7onFw1TSj09-Nu4q4NBia9k5bjqj4vRElm40)

BR Helmut

**Comment by languitar** [comment]
Sorry for the delay.

@Potherca that looks like a reasonable workaround for me at the moment. I could actually generate two `startsub` entries, one with description and one without for being able to select descriptions on a per-container basis.

**Comment by kirchsth** [comment]
Hi @Potherca , @languitar if you want a "toggle" solution you could do something like 

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

' -------------------------
' this part defined in a central file
!$showDescr = %true()

!procedure ShowDescription()
  !$showDescr = %true()
!endprocedure

!procedure HideDescription()
  !$showDescr = %false()
!endprocedure

!function $OptDescription($descr)
!if $showDescr 
  !return $descr
!endif
!return ""
!endfunction

!unquoted procedure foo($alias="foo", $label="FOO", $techn="SPA", $descr="long-text here")
Container($alias, $label, $techn, $OptDescription($descr))
!endprocedure
!unquoted procedure bar($alias="bar", $label="BAR", $techn="SPA", $descr="long-test here too")
Container($alias, $label, $techn, $OptDescription($descr))
!endprocedure
!unquoted procedure bar2($alias="bar2", $label="BAR2", $techn="SPA", $descr="long-test here too")
Container($alias, $label, $techn, $OptDescription($descr))
!endprocedure
!unquoted procedure bar3($alias="bar3", $label="BAR3", $techn="SPA", $descr="long-test here too")
Container($alias, $label, $techn, $OptDescription($descr))
!endprocedure

' -------------------------
' this is part of the concrete diagram

' change description call specific
' foo($descr="changed description")
' bar($descr="")

' Show(default) or hide description
foo()
HideDescription()
bar()
ShowDescription()
bar2()
bar3($descr="changed description")

Rel(foo, bar, "calls")
Rel(foo, bar2, "calls")
Rel(foo, bar3, "calls")
@enduml
```
![](http://www.plantuml.com/plantuml/png/pPJFRXen48VlVefXHHMG-2D1JvMGagQgUcX5bAZdojXZRDNOMtkivF4x3bsoD21wQii1rZ_FVFwyxFewaqnKTbuCN52-Q0HBrEPtytcIZxEj8ris9MDICH06cgcuctztITbCTdxxTdhdPQ2lNpxFyOddDMeElzroiNG1qwojQ745qtCVdYFhChIi0HeDTsbm0IGe39Ia1-CyYi4ms_Zu0RDAi88tb0gEna8CsXGLwf8G7hfvrvABWMS1JdSDsFFGTyJuv3HUO1Zfyoc8AK7L7XYkM-epXheEkC4PwA4gEI6L561VyKnqHdHfqpmd7PUNAE57YOGQNeHDZAEXz4xcLSFNpGI6NcxGhvgFwtKT4IeRLit3tGsFzWkj6X_3TahuH60nOJCMX__h5wp3T839kLtzTXzEEcvaEZZoTS_n_Stz9SUyTmIAyIzuBlgYYsFJnV-bkkohBezLb_z8zK_Uy-vLZuR722e6bP0Gj9FR97ULeQmCMqvU5WGblOVSedB6AIwfptstftsvxjVpfgxgJJhKSC19FI966eqidiOG4rYdZzOHbJiMhuy1Pl5txN-LB_O_omi-uXxzYF6JwZM1fkueSzwF5sVoPI-_ng3Bply4)

BR Helmut

**Comment by jupeng1982629** [comment]
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Component.puml

AddPersonTag("teamred", $bgColor="#red", $legendText ="member of team red")
AddPersonTag("teamblue", $bgColor="#blue", $legendText ="member of team blue")

!$data={"partlen": "2", "game": "GamePlantuml", "participants": [
{"name": "XYZ" ,"as": "xyz", "team": "A", "persons": ["A1", "A2", "A3"] },
{"name": "RST" ,"as": "rst", "team": "B", "persons": ["B1", "B2" ]},
{"name": "UVW" ,"as": "uvw", "team": "B", "persons": ["B2", "B3" ]}],
"color": {"A": "red", "B": "blue"}
}

!foreach $part in $data.participants
  Component($part.name, $part.as, "techn")
  !foreach $member in $part.persons
    !$teamTag = "team"+$data.color[$part.team]
    Person($member, $member, $tags = $teamTag)
    Rel($member, $part.name, "develop")
  !endfor
!endfor

SHOW_LEGEND()
@enduml
