### ISSUE TITLE
Chineses descript of component container will not wrapped

### ISSUE THREAD

**Issue by Gowa2017** [plantuml-stdlib/C4-PlantUML#193]
The code:

```
@startuml
!include C4_Component.puml

Component(a, "this is a component, and it will wrap this descripttion", "technology")
Component(b, "这也是一个组件，但是这段文件不会自动换行下去，这是为什么呢。 ", "technology")
Component(c, "这也是一个组件， [我]的前面有个空格，所以换行了。 ", "technology")

@enduml
```

The output:

![1](http://42.192.43.15:9999/plantuml/svg/SoWkIImgAStDuLBCp4lEAKr9LN0sYNVEpot8pqlDAz4h04bnmVaQYJeAIYKPcSKAG9Iea0mJrr58p4jHo2nHAC_CoL4eBqeiK02hIaajJYxAB2WfoSpFKm9fJKtEoClFoK-lLD94CZK9AFLY_ymdE-S_cx7-oOw69pjMFT_TycJtjlTxUfxiRGCA0cMVhTlwR5exKF39ZjudUsQzQ5_rj6l5izv5BnRsFDdH_RHlDr0nI1d8X5rFTZSysTdnTEAYnmrD2dXiJiPZiqBqiuw9iSzdjJpjx7qvTz6pEPqWsPMxdYtO0vHzrjdmPFTIgFsxsh3Qm-MGcfS23440 "1")

**Comment by kirchsth** [comment]
Hi @Gowa2017,

the plantUML team updated there implementation (better coma,.. handling). Can you please [check it](https://forum.plantuml.net/14830/something-planed-that-chinese-text-supports-word-wraps-too?show=14922) and add your comments?

![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuIh9BCb9LV1BBLSeIoqgpipFuohEpimhI2nAp5KeBqei2CzCASbGC38mu5BCp4lEAKr9LR1nDj5tDebtpiyjoCzBpIlHAm0QPCS5vsiawYWelTW_yydE-Szch7-oe-79ZbNFTxSysRtj_PwU9tlRW890sMVhjZwRrWuKVBAZzycUMI_QLptjMl6iTz6BXJrFTdG_xTiDL0nK1ZPXrvFT3KzsTZoTkEXnGvC2K1HkxikvyvxksF5qoN9az7nMozEfNN0sLlH-J-FxFHtlztI-tpFx_PvPGCk0ZW1Q3xH62UZyajJaZBpydFpqIYLDBeVKl1IW5m40)

Thank youu and best regards
Helmut

**Comment by kirchsth** [comment]
Hi @Gowa2017, 
plantuml [V1.2021.14 (12 Nov, 2021)](https://plantuml.com/changes) is released with the new implementation.
BR Helmut

**Comment by Gowa2017** [comment]
Oh, I think it is not so good.Now it will wrap the description when there is space or a fullwidth punctuation when the description length is longger than wrap width, and the fullwidth punctuation will be on the preline.
I prefer to use the '\n' to do it, the best is to hard limit the line width.
