### ISSUE TITLE
I am getting this error from Confluence PlantUML plugin

### ISSUE THREAD

**Issue by hkutluca** [plantuml-stdlib/C4-PlantUML#194]
![plantuml7740602227603103697](https://user-images.githubusercontent.com/27637182/139113703-65e644c6-0fec-43e2-8b79-1dffd5284433.png)

**Comment by Aykuth** [comment]
Hi kirchsth,
Thanks for the previous responses, I am the Confluence Admin where hkutluca works. Our confluence is rather an older version so it is not using the one you have referenced. (The most recent compatible version of the plugin is **6.42** (for Confluence Server 5.8.2 - 7.5.2 2020-05-18 Upgrade to PlantUML v1.2020.10) thus the PlantUML v is 1.2020.10. Do you think we could upgrade the PlantUML version independently from the plugin (by replacing some files).

Thanks again.
Aykut

**Comment by kirchsth** [comment]
Hi @Aykuth,

I don't know Confluence (incl. the plugin) details, but PlantUML (incl. C4-PlantUML files) is released as java jar with the name "plantuml.jar" or "plantuml-[versin].jar" (e.g.  "plantuml.1.2021.13.jar" ) and if you find a file with a similar name in your confluence installation then you could try to replace it with one of the last releases.

You can download it from https://github.com/plantuml/plantuml/releases

Best regards
Helmut

PS.:  plantuml.1.2021.13.jar contains the last released C4-PlantUML v2.4.0
