### ISSUE TITLE
How about supoort code level diagram?

### ISSUE THREAD

**Issue by Gowa2017** [plantuml-stdlib/C4-PlantUML#196]
I can  use plantuml, but the style not so the same, support class and object diagram is good.

**Comment by Potherca** [comment]
Hi! Thank you for opening this issue.

Do you mean class or object digrams to look more like this?

![](https://c4model.com/img/bigbankplc-Classes.png)

<sup>(example taken from https://c4model.com/)</sup>

I'm not entirely sure, but I _think_ @simonbrowndotje didn't mean for code-level specific styles to be part of the a C4-model. 

That said, it is not _too_ hard to create PlantUML styling that makes code-level diagrams look different. But I'm not sure if such styling should be part of the C4-PlantUML library. It might be better suited as a separate project and/or part of an existing PlantUML styling project.

I'd be willing to help and/or point you in the right direction, though.

**Comment by Gowa2017** [comment]
Yes, what I mean is like you said.I like the c4 plantuml project very much.Now, all of my project diagram is make by this project.
But, the code level diagram seems very ugly, so I want to we have same style.
I know, we can use many skinparam to set the style of plantuml, but I'm not feel so good for choice colors.

**Comment by Potherca** [comment]
To get the effect of the images I posted, not much is needed:

```plantuml
hide circle

skinparam {
    classBackgroundColor #FFF
    classFontStyle bold
    interfaceFontStyle bold
    monochrome true
    shadowing false
    ranksep 120
}
```

![](https://www.plantuml.com/plantuml/png/ZLBBZjim3BphAmZq7ACFzEB3Ofj5NUoXb-uNC3AJ294eLQIxNRJzzognW6mXk8vFbcOu78vuBufPf-3DqOq4rcNhoHWvEKwOCS0l0-Mp7aMsQ4-772SU7wAF6TuCmt15XyZwf2-UO1VzUBbth9JtQAd584IEzfXZ8D0yqULEZZZ6PyS7sAEN-IuZduGIl7l_zdBcEDBv_E6Z-MDCAfRmG61Zw7Rki2lav6ntQSoavtEHwmgS8XDh5z3nFcEWEXZkH3DQXK_rvnjzdqXq2PIYCpkhMS7NgaZRkTdJYoY50IsE1DTu5dYVVrfAwYAlCQlYOqZ-5VKBwHOzigLNlYlsJ_L3P2PxRTHKry5AfZFsM2DSS6l-E_Pcipx46W6wtDsjfTQ37dDybXlKYbYJLWys4ohTMD_crKF2B3VMBxr83zDPed5NOlnzroncQsBcDJkwqAquQSazPBBaVf3SM5RZ4-9HpCeZmMOg1jSswhv8JS7_1G00)

<details><summary>Full diagram</summary>

```plantuml
@startuml

hide circle

skinparam {
    classBackgroundColor #FFF
    classFontStyle bold
    interfaceFontStyle bold
    monochrome true
    shadowing false
    ranksep 120
}

package com.bigbankpic.internetbanking.component.mainframe {
    abstract AbstractRequest
    abstract AbstractResponse
    circle MainframeBankingSystemFacade 
    class MainframeBankingSystemException
    class MainframeBankingSystemFacadeImpl
    class GetBalanceRequest
    class BankingSystemConnection
    class GetBalanceResponse
}

class InternetBankingSystemException

MainframeBankingSystemFacade -- MainframeBankingSystemFacadeImpl
MainframeBankingSystemFacadeImpl .r.> MainframeBankingSystemException: throws
MainframeBankingSystemFacadeImpl ..> GetBalanceRequest: creates
MainframeBankingSystemFacadeImpl ..> GetBalanceResponse: parses
MainframeBankingSystemFacadeImpl ..> BankingSystemConnection: uses
GetBalanceRequest --|> AbstractRequest
GetBalanceResponse --|> AbstractResponse
BankingSystemConnection ..> AbstractResponse: receives
BankingSystemConnection ..> AbstractRequest: sends
MainframeBankingSystemException -u-|> InternetBankingSystemException
@enduml
```

</details>

Beyond that, adding colors is a matter of personal taste/opinion, I think...

**Comment by Gowa2017** [comment]
Thanks so much.I will try it

**Comment by simonbrowndotje** [comment]
> I'm not entirely sure, but I think @simonbrowndotje didn't mean for code-level specific styles to be part of the a C4-model.

Correct - no styles are a part of the C4 model, it's notation independent.

**Comment by kirchsth** [comment]
Hi @Gowa2017,

if you only want a different colors/styles you could try `!theme` like below

```plantuml
@startuml

' you could use different themes like in https://the-lum.github.io/puml-themes-gallery/
' all available are listed here https://github.com/plantuml/plantuml/tree/master/themes

' E.g. I checked following
'!theme materia
'!theme spacelab
'!theme aws-orange

!theme spacelab
' you can hide the circle with following line
' hide circle

package com.bigbankpic.internetbanking.component.mainframe {
    abstract AbstractRequest
    abstract AbstractResponse
    circle MainframeBankingSystemFacade 
    class MainframeBankingSystemException
    class MainframeBankingSystemFacadeImpl
    class GetBalanceRequest
    class BankingSystemConnection
    class GetBalanceResponse
}

class InternetBankingSystemException

MainframeBankingSystemFacade -- MainframeBankingSystemFacadeImpl
MainframeBankingSystemFacadeImpl .r.> MainframeBankingSystemException: throws
MainframeBankingSystemFacadeImpl ..> GetBalanceRequest: creates
MainframeBankingSystemFacadeImpl ..> GetBalanceResponse: parses
MainframeBankingSystemFacadeImpl ..> BankingSystemConnection: uses
GetBalanceRequest --|> AbstractRequest
GetBalanceResponse --|> AbstractResponse
BankingSystemConnection ..> AbstractResponse: receives
BankingSystemConnection ..> AbstractRequest: sends
MainframeBankingSystemException -u-|> InternetBankingSystemException
@enduml
```
![](http://www.plantuml.com/plantuml/png/ZLBBajGm3BpxAyHfJadkEMmjIotK7BZ05oYE9d6D7y6oTvW2_Xq5psQXKY6JasDrjrfjFNB2cBApIXtW6ZBea6qFcGbwSpfH99yWZUI8mPepWV4mfZHnspHoNTdiwi6aCNUr2SqaGbL1LmDQI_7QYAwS05_GMEmi0KOIAKxKmqYH5hcRZ0wkcIpwsTJR8KMYng6mObCQp8QVww668-YHz5daJi7QS35-K8TtVq3WK0W6bt-UK9FOM2xmmbM8w0TIQeKfWQ1CR7e2gO8sKLk2YrXzwoRJU5A7WYe8fKJaZ0E1Z5DtPkZGdoUZQ-F5aASq_mjrddOANaAk7Hf_YYW6VYYG3pjE4NM2zxV35_gMYTDMaKM7QQw-klpyglXKcdszIdpk8seKdmLeaNa3z_nTqvHCyBl8edXqa_qB-edI4rhqcXRVI-qVzeVWFUbRepLx6UoNKgLsl4MuuLRzT-ogsXzY3m1rh1_sKcjbNsAuy1rg8hPAgmKT2HFTor_brSA4aU_bRxn82tcMMBcJ67y-h1PpRQBWLZkwqKsShC4jHD9aNeZleYtnCVcUrSuZGPN5uDv6FOfKTlOt)

BR Helmut
