### ISSUE TITLE
MarkDown navigation uses absolute paths

### ISSUE THREAD

**Issue by tomschreck** [plantuml-stdlib/C4-PlantUML#197]
Hello.  Is it possible to generate the navigation aspect of mark down files to use relative paths instead of absolute paths?  I have my c4Builder in a subfolder (.beer-keepers-docs) instead of root.  

c4Builder generates the README.md file with navigation like this:

![image](https://user-images.githubusercontent.com/2521463/140580926-151e3ee4-ad58-4178-985e-54f98960a2d2.png)

The navigation uses absolute paths and navigation fails.

**Comment by tomschreck** [comment]
I put this issue in the wrong GitHub repo.  My apologies

**Comment by Potherca** [comment]
No problem. Happe developing!
