### ISSUE TITLE
Fatal parsing error in IntelliJ plugin

### ISSUE THREAD

**Issue by Chessray** [plantuml-stdlib/C4-PlantUML#198]
Hello,

As my current client's network is highly secure, we're trying to use the C4 files in local mode. I know that the IntelliJ plugin itself is working fine because we can create all standard PlantUML diagram types without issues.

I changed all the relative paths in the C4 files to point directly at the others, but now I'm faced with the error pasted below. I tried the master as well as releases 2.3.0. and 2.4.0.

![grafik](https://user-images.githubusercontent.com/770876/140747582-e6fbfcb0-258f-4d1a-8271-59fcf8aa2ed6.png)

**Comment by kirchsth** [comment]
HI @Chessray 

I think it is related to an outdated version of the plantuml.jar file. Which version are you using by generating

```plantuml
@startuml
%version()
@enduml
```

![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuL8jIoqgpipFqz3aSaZDIm4A0G00)


Thank you and best regards
Helmut

PS.: If you use the last released version 1.2021.13 then you can directly use C4-Stdlib with version 2.4.0 (e.g. `!include <C4/C4_Container>` is enough, no url based include `!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml` or local files  are required)

**Comment by Chessray** [comment]
🤦🏼 Yeah, that was it indeed - outdated plugin. Thank you @kirchsth, and especially for the extra hint.
