### ISSUE TITLE
Technology option missing for external systems

### ISSUE THREAD

**Issue by wlfbck** [plantuml-stdlib/C4-PlantUML#199]
Simply compare the example here:
https://c4model.com/img/bigbankplc-Containers.png

with the one at the top of the README.md. (Talking about the small print [Software System] here)

I think its also missing for all entities listed [here ](https://github.com/plantuml-stdlib/C4-PlantUML#supported-diagram-types)under macros.

Would be nice to have that ;) Otherwise i have to awkwardly place the technology being used in the description text of the external system.

**Comment by kirchsth** [comment]
HI @wlfbck,

a) In your sample "[Software System]" is not a technology it is only the element type "(Software) System" itself and an alternative to the e.g. color/legend. The "Mobile App" is a "container" uses the technology Xamarian; and this it is written like [Container: Xamarian].
In C4-PlantUML it is basiscally supported with the combination of `<<stereotype>>`  and `[technology]` (like below).
`
b) If you compare it with the C4 model then the system has no technology at all 
![grafik](https://user-images.githubusercontent.com/21959385/142915813-f07ccbec-bf37-420e-9ac2-ca4590378c05.png)

c) One workaround could be a "System tagged container" like

```plantuml
@startuml
!include <C4/C4_Container.puml>

' <<<<<  defines the required tags
AddElementTag("sys", $bgColor = $SYSTEM_BG_COLOR, $fontColor = $ELEMENT_FONT_COLOR , $borderColor = $SYSTEM_BORDER_COLOR, $legendText="System")
AddElementTag("sys_ext", $bgColor = $EXTERNAL_SYSTEM_BG_COLOR, $fontColor = $ELEMENT_FONT_COLOR, $borderColor = $EXTERNAL_SYSTEM_BORDER_COLOR, $legendText="External system")
' >>>>>   defines the required tags

System_Boundary(c1, "Internet Banking") {
    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
}

Container(email_system, "E-Mail System", "technology", "The internal Microsoft Exchange system",$tags="sys_ext")

SHOW_LEGEND()
@enduml
```
![](https://www.plantuml.com/plantuml/png/bP9VYzD05CNVvrDSOs5Rg8gmZzjbs-ou2cqZRS3rQPXcRjB1-HDd9gL1_ExED6u4Lr3d8N1oxvpxkoUvyu6xq6b5NaXJgKuWtEJNR_9hbbiJk3JeNhUnV4l85Toa0o2mZkyzX2E2mw-TT2WWyCO3Dm8qhvprP2a4LQZHX98tqyptFfl3vD3aLba72vZiF-zBkc6h1vONws8NYtMSE9RfccxejcJlYlYuT42wRvr0zyoZsDtJtUYZi44ZIZo7HRRlVK2TpVx0msB3RqpqiQIxxNBD_XlkETlezNT8UWxe35VWdsYlu3OT-CUm2HdsP2lR6S5TFwtUpY7xO98l1bXnyqMQ9fl1DmBnZDzsgkr1AcIyRMF_vY9WsRPPLFdBEJnopPqqINvqzYH59E6Wf9OXOlZkuAExhIzquxJ3C0tgpbH1shYO33q42rNdWzNeF9maJtUaWm4019vaXN7pxuJyeaFDfM93AX61ljf43SEkYIbWTJGnyAPFgemGqloCSYDJChOEGC_LaPi6dzATJr9yY_4NcCNqtXUVs9e-qEtzT4Rkq8XEgny0)



Would this be a solution?

Best regards
Helmut
 


![](https://www.plantuml.com/plantuml/png/bLLHRzis47xNhxXb3tC1fS60FWv34zjOMyIfLsLhtumJTRQ9KgJ0EparXlttdHX5ifm2MT_4yzttVVpuaNxBWb7QscK_MMzSMn7yDdzpDN-pcGSlQ3t5rut-_7kMYHL7C9IXihYBMCCsH7ZlXQ8dWHlqNwtVGN5aeJhBrXGv-9bfMK9DCOVvy7Ln3Kzb25kGFK6fqpayMDb3amRHfHgWCQ7rmXUlikmHUdEZXGhZSMP-LQnp0HUlu9yC04QzimSgDzWqsloPIhXk6cSDYWt-GaiVy80v54tinA_-ddUr1JbxK1b96els6Z0AHru0VPNA0s_vjF7rjOgSCdE32bVepuukrxYZZls9jJ3HDfB3jT-r3cDNNiTmi1Kne7FVPzcstdJIqLavWWHrCXd9SB3OZTW8kbyeOtXWYiyKrQ6qZdexLjrYq3J_EOSlMACwCTK2pjPMg09kIoQ1iFtVslYPk4S1KD716ZgNjoXd5GgMoDGTG__PgId-l8N9Ma8aXfOfGgITPOdfIC5wZMMTldFO8-zLDxQo1nEf8YyM7UTTh8WPNDZfWiIyVcPKYUOh-KgTibrYr--_7vn5qBOupasSUy6XpXG5Lkf_Xt0llycCQhHkmwcWSClBbQxxYzNXtwlvDa6ZWvKrCN3O2Yo_cJtw7S7ZfCAUOFOAHbJ5zDk8DPtTtD7S5CB-h8qMXbsSM0nOXbR6Wyw72vk3HFICQR-ZoTadSYUFmdWr_sBYZllT_VswqCPf7pVuOayVxH6kfzlSaTtjop0-10bklEOzKYfEZdqWH3vwayE7ukFTrIdvIFc3aviRxHw5ZQ6VedmYh1YsCTJftNc8LeX1GeVS0ozkvWevO9xuSHQZGc4PwBAh9enHo2HnvngcSorh0aRwOdM_Lg29ovFnQUv6OzByLU_EbzNjO4xso-FVm1OTKugW3aOASco80ID1PRbnUAGA98IiUFVny-Ps-SVoRZ5BCmhnLkdRslq7)

```plantuml
@startuml
!include <C4/C4_Container.puml>

title Container diagram for Internet Banking System

Person(customer, Customer, "A customer of the bank, with personal bank accounts")

System_Boundary(c1, "Internet Banking") {
    Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA")
    Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to cutomers via their web browser")
    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
    ContainerDb(database, "Database", "SQL Database", "Stores user registration information, hashed auth credentials, access logs, etc.")
    Container(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API")
}

System_Ext(email_system, "E-Mail System", "The internal Microsoft Exchange system")
System_Ext(banking_system, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(customer, web_app, "Uses", "HTTPS")
Rel(customer, spa, "Uses", "HTTPS")
Rel(customer, mobile_app, "Uses")

Rel_Neighbor(web_app, spa, "Delivers")
Rel(spa, backend_api, "Uses", "async, JSON/HTTPS")
Rel(mobile_app, backend_api, "Uses", "async, JSON/HTTPS")
Rel_Back_Neighbor(database, backend_api, "Reads from and writes to", "sync, JDBC")

Rel_Back(customer, email_system, "Sends e-mails to")
Rel_Back(email_system, backend_api, "Sends e-mails using", "sync, SMTP")
Rel_Neighbor(backend_api, banking_system, "Uses", "sync/async, XML/HTTPS")

' with false all stereotypes are displayed too
SHOW_LEGEND(false)
@enduml
```

**Comment by wlfbck** [comment]
>a) In your sample "[Software System]" is not a technology it is only the element type and an alternative to the e.g. color/legend. 

Aaaah i did not notice that. Explains why it says "software system" :P

>c) One workaround could be a "System tagged container" like

Should work, thank you for the suggestion! Although it would of course be cool to have that technology field (or whatever one wants to call it) there in general.

**Comment by kirchsth** [comment]
Hi @wlfbck,

you can use new defined macro 'System2()' and 'System_Ext2()' that you hide the internal $tags like below
(I added the $tag email as sample that I check the $tag handling too)

```plantuml
@startuml
!include <C4/C4_Container.puml>

' <<<<<  defines the required tags and macros
AddElementTag("sys", $bgColor = $SYSTEM_BG_COLOR, $fontColor = $ELEMENT_FONT_COLOR , $borderColor = $SYSTEM_BORDER_COLOR, $legendText="System")
AddElementTag("sys_ext", $bgColor = $EXTERNAL_SYSTEM_BG_COLOR, $fontColor = $ELEMENT_FONT_COLOR, $borderColor = $EXTERNAL_SYSTEM_BORDER_COLOR, $legendText="External system")

!unquoted procedure System2($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
  !$tags="sys+"+$tags
  Container($alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure

!unquoted procedure System_Ext2($alias, $label, $techn="", $descr="", $sprite="", $tags="", $link="")
  !$tags=$tags + "+sys_ext"
  Container($alias, $label, $techn, $descr, $sprite, $tags, $link)
!endprocedure
' >>>>>   defines the required tags macros


' custom tag (which defines technology too)
AddElementTag("email", $techn="EMail Server", $sprite = "&envelope-closed,scale=4", $legendSprite = "&envelope-closed", $legendText="Email server")

System_Boundary(c1, "Internet Banking") {
    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
}

' $techn is defined via $tag (only "" is set in the call)
System_Ext2(email_system2, "E-Mail System2", "", "The internal Microsoft Exchange system", $tags="email")

' $techn is defined explicite
System_Ext2(banking_system, "Mainframe Banking System", "technology", "Stores all of the core banking information about customers, accounts, transactions, etc.")


SHOW_LEGEND()
@enduml
```
![](https://www.plantuml.com/plantuml/png/hLFlRzem4FsUl-BmgXK4xRIf7qlLbdhT92WJ8Atx51dx0AkEdTeE0qtxtsSd8NJzqMbIaPhwplQzT--TpvrdrXUPIbfISrK8XDF1oOV1IJemsZEfqHxdOViiIGxXDFu012v2te5V8LYyBwH50Puj7J0j86FS6fTS244LPgZzZ2tRn6qTwS71V3amobZemy7qntH6H-dbTJeO3yUJiBa8YCqs7T8HlPcbdyVXKvw0UDzOWVP9ZV7aYawQEWgNgCKCDxvFfbldCIETP_YauS0ZJlHsHYSt5yFqlyazvTRK-ZT9kl5eDLFWTcoJLg7l2-DHG6uDHr5OXAgNJ-q3fYHpiGQRemh_FVALxfFOZ437RRLqkPKUgtLqfrefgU_2gfC0jEfqGEsIRXc4REFx2pWxa0QXBb_NxYIjq5T3-hLEqj3tctTJVg4BfBkp-ErxEeIp-8DNdiBk6SHdmmldJHRJqFwvadorlnR1ZJBBBNXZdWmfPamgifU4Za8CKxHhj7jDe0_aFUerAfFZ4LV6eUWvpXJsJqWpQTCNpvB7qnXHmLKeOHHhiovDeGMpspR_s0FoLSUHHG-NJDz9lIGT-9K0F9GwCtEfC6Lv7iwFoW0kyfo4QF2k1xSiOrRg67wpPYq5Ec2WP2RZhBXYxj23MPJIDcZp2WqMXUPU6isKz56xMcEq3jQInJlIGaK01Aubnz39xsX6fIL8LviWueMGZUOOhRP0IDoCu5ANu459rKaUZcpfI-ggvnZuqwFAc2eHEuf_it1NwlfbZsGS1xFmG3TynVGIeRg_d-VAxSxp976JAyc3D7yHgUMegKIPW_GBopBS-LAJYdpsmnQZgJSsAgxKJcGU4et0eOon6OiQ0vkRmkyLxW7ZF0o33ojlcNQij294wFbnR22PVXb_JuVqcjvSjJl9EMfHPEeF)

BR Helmut
