### ISSUE TITLE
How to show relationship line formats in legend

### ISSUE THREAD

**Issue by huornlmj** [plantuml-stdlib/C4-PlantUML#204]
The very first image on the readme shows a legend with dotted and dashed lines for sync and async as an example.  But I do not see how this is achieved?  Should this not be included in the readme?

**Comment by kirchsth** [comment]
**Theoretically I would write**

Maybe we have too much in the readme in the meantime and should make it more explicit. 

You can define all styles via [Custom tags/stereotypes support and skinparam updates](https://github.com/plantuml-stdlib/C4-PlantUML#custom-tagsstereotypes-support-and-skinparam-updates). Following line types are supported: 

> * `DashedLine()`: This call returns the name of the dashed line and can be used as ?lineStyle argument.
> * `DottedLine()`: This call returns the name of the dotted line and can be used as ?lineStyle argument.

You can find a sample incl. source before [Supported Diagram Types](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/README.md#supported-diagram-types) (Rel: `Writes[messages]` )

You can use the styles directly in a diagram too like
```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddRelTag("dotted", $textColor="orange", $lineColor="orange", $lineStyle = DottedLine())
AddRelTag("dashed", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())

Person(a, A)
System(s, S)
System_Ext(e, E)

Rel(a, s, "calls via UI", $tags = "dotted")
Rel(s, e, "calls external", $tags = "dashed")

SHOW_LEGEND()
@enduml
```
![](https://www.plantuml.com/plantuml/png/fOzFIyD04CNl-HHhyB21jBbu4WejRL2XQZ4MZs6Q7PB0P3ViJhJzzau2yGzuyxXlV-_7ctLWy3nq55srjgB1e6gO-t2RPHu-bdNBpN0Q0lhAMKRBoyfrMKzWnyuYiA7sb6rl5eSnEZxkimu2evUet4e3Mej-sO_-Q6FC2z8hr3esZXbDdAfhnZDl7Jc_Yfq7M-COahJ-30k-4AgLsatzlIGwINw98JJ_4al_MnmTq0TdDQHgaqJ59J1sEgIgc1zbVcQDgSg5bGaZADzn1KH1lRUWZW_J5gY3oEUpauaL4BzO6OlU0lsWvrj4NTm_lvNx_2v_skaaMgCrGqUV)

BR Helmut

PS.: the source of the first image is stored in https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/samples/C4_Container%20Diagram%20Sample%20-%20bigbankplc-styles.puml

**Practically I have to write**

It looks like we found a bug in current PlantUML version and the line styles are not working any more (I will add a entry in the PlantUML forum and try to get a solution). If you have an older local version it should work without any problems.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be fixed now. Tell us if you find other issues!

**Comment by kirchsth** [comment]
Hi @huornlmj
thanks to PlantUML team we have a fix on the PlantUML server and the different styles are working again.
Now the theorethic part is valid again ;-)

I created a new sample with a changed color that we don't get an old (potentially not working) cached diagram.

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddRelTag("dotted", $textColor="$ARROW_COLOR", $lineColor="$ARROW_COLOR", $lineStyle = DottedLine(), $legendText="a dotted relation")
AddRelTag("dashed", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine(), $legendText="a dashed relation")

Person(a, A)
System(s, S)
System_Ext(e, E)

Rel(a, s, "calls via UI", $tags = "dotted")
Rel(s, e, "calls external", $tags = "dashed")

SHOW_LEGEND()
@enduml
```
![](https://www.plantuml.com/plantuml/png/VL3FQ_em5B_thyYtU6YXsiltD12KMhP1DwLLTfHdywY1D97aTTF_VY-A6sLintn-voqyWQEXrz4_PLezI1H7efD_o7C77xDEqN4u31vTQmsXeLbh-_oamGJFr9FKwf0N_wUR0ErUghm7J-WOsXVi06NGpKuXFrfAMQFUGfV4qXAXZ3Cn8JnJORLrytYohElrsxvOL-iwK9gzVr0DNJIAkLXTiof6aZHGsA6HMuwTno1kHSAX1bBMnEbe1VZZZnNMWUbmt3y6lvlP_tipa-FcQ8FEMvD09fPfr5myOP_uJ3JtnxuyKuAPA5dB6uEGwRW5hRruLo1spzUnq7bklnyn3TgGWrzQde3EW1wfRv_bwEQ9JrcLZ-NhAacZ1HevzFeJ)


I hope it helps.

Best regards
Helmut

**Comment by kirchsth** [comment]
@huornlmj, can we close it?
