### ISSUE TITLE
Lay_D too much space in most cases

### ISSUE THREAD

**Issue by acristu** [plantuml-stdlib/C4-PlantUML#205]
Hello, thanks for your work on this library.

If there is no `Rel` the spacing between containers looks good:

![image](https://user-images.githubusercontent.com/6796822/154037551-2d4c1440-7f6a-4fd9-8165-38133b40c8bc.png)

With one `Rel` there is too much space between the containers using `Lay_D`:

![image](https://user-images.githubusercontent.com/6796822/154037837-f6e80e39-f41a-4939-b158-2712b4547a2b.png)

For a small diagram like the one above it is really not much of a problem, but large diagrams become unreadable:

![image](https://user-images.githubusercontent.com/6796822/154038896-22eff470-764b-478a-93c6-db812fd04680.png)

```plantuml
@startuml 
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

skinparam linetype polyline
skinparam linetype ortho

Deployment_Node(Node1, "Node1", "", "") {
  Container(container1_1, "container1-1", "bla bla")
  Container(container1_2, "container1-2", "bla bla")
  Container(container1_3, "container1-3", "bla bla")
  Container(container1_4, "container1-4", "bla bla")
  Container(container1_5, "container1-5", "bla bla")
}


Deployment_Node(Node3, "Node3", "", "") {
  Container(container3_1, "container3-1", "bla bla")
  Container(container3_2, "container3-2", "bla bla")
}

'Rel(container1_1, container3_1, "rel")
'Rel(container1_2, container3_2, "rel")

Lay_D(container1_1, container1_2)
Lay_D(container1_2, container1_3)
Lay_D(container1_3, container1_4)
Lay_D(container1_4, container1_5)

LAYOUT_WITH_LEGEND()

@enduml
```

**Comment by kirchsth** [comment]
Hello @acristu, 

I'm happy that it is useful for you.

I cannot reproduce the problem with the extra "empty line", If I take your source it looks on the plantuml server like
![](https://www.plantuml.com/plantuml/png/ZP5DIyCm6CVl-HInfnNSofBkucco3HNg5DaGJo5jWotc9IGfKiJlRbFGcQvY3sbU-llbUVXdRHqrhX4SNDIou4t9OEMSjbT9OkZxuhLsLPCtbfb2ISUaMnHA99fJwPsvTIMlysIJpX_zqV4-ImIrZfdkY6oPvgeLNjA-0B1ljTJKK05vBPbhDODQyTPlnlufuoe5mEaQibSbc_dFyX96_HnrYtx4y0D0kEcQf9rlPiNtQaayVDhEUoVd57OZYl-IK2YXIH8E9Jn9IaCfdIIjGcaLIfzWF3RVNp__7niEOyEJOiC4XH8ww-k9yS7R34eQngDuYA40GpyOo6XBjeCBVtlnEO420eyGE23I4I8DY9LlvFhbuNWWptU7MvBjRdRxxIm6QoRBHl0l)
Or did I overseen something?

Are you using an older local PlantUML version? Maybe an update could help.

Related to the distance itself I found  (maybe there are more)
```plantuml
' skinparam nodesep x (where x is an integer > 0) will increase the horizontal margin
' skinparam ranksep x affects the vertical margin
```
With that I can generated a diagram like (I used SHOW_LEGEND() that only the required entries are displayed)
![](https://www.plantuml.com/plantuml/png/ZP51xz8m5C3l_HHFBcw9CDd6nOCX0Q87HACn7fUoFLX3rpPj9qxZTxUTKVvb8_yTIbyVlz_hwzlQMAfjst3oWecIjnL2RQqoRv94q-lYp6pT7bk3kfJ2eh2BKZQ9ubHuPsvinTansUJpJpxrzSC-QQYng5sgsABYickyfFm5v2MO2nEAQjg0a1KQLF03eckD6bt03501J5WyeuQty3g6A-FSPKgDr23OsZKdDVlfMg4S6ghFJ0HLDHMNlrNfwOIbDRtp7RLbvSqOTh4aWnekzoJ9cK3RAGGbUUSFO_z9RMj9oEtTnS7LZ_pFyXNC-dtcWdx5y8i0RFnJdA-Zyb-qB3nyEyvxvyWfk3MB7qbfAAMJf2oKiabI7ahv96aLIgjG-at6n-Rxw_VdnvQ5OykcZCr9QIYbWxu-8x_xDdTNQkIElCFI04l_OsHFksBxgA3puY6H1aGsGcG1aOyGUK2iN2DVtd_yLkntxtQ7RHIJDOggRVWV)

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' skinparam nodesep x (where x is an integer > 0) will increase the horizontal margin
' skinparam ranksep x affects the vertical margin
skinparam nodesep 1
skinparam ranksep 1

skinparam linetype polyline
skinparam linetype ortho

Deployment_Node(Node1, "Node1", "", "") {
  Container(container1_1, "container1-1", "bla bla")
  Container(container1_2, "container1-2", "bla bla")
  Container(container1_3, "container1-3", "bla bla")
  Container(container1_4, "container1-4", "bla bla")
  Container(container1_5, "container1-5", "bla bla")
}


Deployment_Node(Node3, "Node3", "", "") {
  Container(container3_1, "container3-1", "bla bla")
  Container(container3_2, "container3-2", "bla bla")
}

Rel(container1_1, container3_1, "rel")
Rel(container1_2, container3_2, "rel")

Lay_D(container1_1, container1_2)
Lay_D(container1_2, container1_3)
Lay_D(container1_3, container1_4)
Lay_D(container1_4, container1_5)

SHOW_LEGEND()
@enduml
```

Thank you and best regards
Helmut

**Comment by acristu** [comment]
Hi, thank you for the quick reply. I am using a local kroki server, I will try to upgrade and check if the problems till persists...

**Comment by kirchsth** [comment]
Hi @acristu, did an update help?
BR Helmut

**Comment by acristu** [comment]
Hi @kirchsth ,

It seems this setting does the trick even with our current older version `skinparam ranksep 1`.

Thanks, the issue is fixed for me.
