### ISSUE TITLE
VSC snippets not functioning as expected

### ISSUE THREAD

**Issue by huornlmj** [plantuml-stdlib/C4-PlantUML#207]
Following the guidance here (https://github.com/plantuml-stdlib/C4-PlantUML/blob/311ff3842e47ae9fb77cba4ac86da2481b240909/.vscode/C4.code-snippets), upon creating the .vscode directory and placing the C4.code-snippets file there and then starting a new .puml file, typing 'Container' does not provide the pre-populated holder as shown in the readme gif.  Perhaps there are more steps required?

**Comment by Potherca** [comment]
Hmmm. I'm not sure what is going on here. I'll have a look at reproducing (and fixing) this in the coming weekend.

Thank you for pointing this out!

**Comment by kirchsth** [comment]
Hi @Potherca, 
do you have time for it?
If yes we could add it to 2.5.0
BR Helmut

**Comment by kirchsth** [comment]
@huornlmj: I cannot reproduce the problem.
Did you solve the problem in the meantime?
Was it a problem with the wrong active language?

**Comment by kirchsth** [comment]
@Potherca: Can you reproduce it? Otherwise I would it `Close as not planned`

**Comment by Potherca** [comment]
Could not reproduce.
