### ISSUE TITLE
Wasted space on some diagrams

### ISSUE THREAD

**Issue by jasonculligan** [plantuml-stdlib/C4-PlantUML#209]
Consider the following C4 PlantUML.

```
@startuml Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

System_Ext(a, "A")
System_Ext(b, "B")
System_Boundary(c, "C"){
    System_Boundary(d, "D"){
        ContainerDb(e, "E")
        System_Boundary(f, "F") {
            Container(g, "G")
            Container(h, "H")
            Container(i, "I")
            Container(j, "J")
            ContainerDb(k, "K")
            Container(l, "L"){
                System(m, "M")
            }
            ContainerDb(n, "N"){
                System(o, "O")
            }
            Container(p, "P")
        }
    }
}

Rel(m, p, "1")
Rel(e, k, "2")
Rel(a, o, "3")
Rel(b, m, "4")
Rel(i, o, "5")
Rel(p, o, "6")
Rel(o, o, "7")
Rel(l, o, "8")
Rel(p, o, "9")
Rel(g, o, "10")
Rel(h, o, "11")
Rel(o, a, "12")

@enduml
```

When rendered with plantuml-1.2022.1.jar diagram.puml it appears like so.

![Diagram](https://user-images.githubusercontent.com/15697557/154587788-bdd8a515-9c5a-472c-9986-0b7110d1f22a.png)

As you can see, lots of wasted space, bad layout.  But If I render [the same puml at the online plantuml.com web server](http://www.plantuml.com/plantuml/uml/ZP9RJ_8m7CRlzodsxcfBNfWW7lGAONXGKABncdHRtQOzB5qN9ORlxjEqYO2PiHSal__lUKgRTTneedJBcPzKf524U_ygaR4sftwfTTsSnx4Yx_sYqcMRjWrLcHIQ2jtF98zhHeJfzXgTiogDfwFUqeoU5_EOaqPJXT4geJMJQsvADSAUzxI6uglPXmx9Vp-u2ABjKOhHv7iqaQt8YLg76URJ8FhqVAnzcKCcLjernJ599QXAqf12peB8kP_b5_ZB8F9TUt-7i82_2g8EMy9UTzeAzgRJliBUTbcS_0t-hhFDOEVRbzwzOCZX5tljJUT_2QJlVzbDmZ_yRRUmHdQ9x4uElnlFUwJC7Cma1aW0pVSn5nqwn9kGm4E7U0ySE79OMNlaiBPux51QF778B9xkXiyS5XO71uvBnmF7069u2FR6LEHulLy0) it appears much nicer and with a better layout...

![image](https://user-images.githubusercontent.com/15697557/154588024-7de4afec-bfda-4b01-a389-212cf1b4280e.png)

I've tried multiple versions of PlantUML and they all show the same issue.

Any suggestions what might be wrong?

**Comment by jasonculligan** [comment]
Answering my own issue here.  I found that it was caused by the version of graphviz I had installed.  I had 2.40.1 from apt package for Ubuntu.  I had to uninstall it and compile and install graphviz 2.50.0 which worked.

**Comment by Potherca** [comment]
@jasonculligan Good to hear your issue is resolved! Thank you for taking the time to report this, it could help other users who face the same problem :+1:
