### ISSUE TITLE
README.md Hyperlinks not HTTPS

### ISSUE THREAD

**Issue by HeteromorphicHedgehog** [plantuml-stdlib/C4-PlantUML#21]
Make links in README.md HTTPS so that organizations where HTTPS is enforced can still view the link content locally.

**Comment by kirchsth** [comment]
@Potherca can you add this to next milestone (should be fixed with my last MR #141).
PS.: I added  [https opens wrong diagram in the plantuml forum](https://forum.plantuml.net/13383/https-uml-link-cannot-be-opened-on-plantuml-web-server?show=13383#q13383) too, but I got no response until now
