### ISSUE TITLE
[Feature request] Provide display text as well as alias for AddRelTag

### ISSUE THREAD

**Issue by huornlmj** [plantuml-stdlib/C4-PlantUML#210]
When using a custom format with AddRelTag, when SHOW_LEGEND() is used, currently only the name of the AddRelTag is used.  It would be nice though to have a display text that would be displayed in the legend, instead of the alias.

**Comment by kirchsth** [comment]
Did you see the `$legendText=` property?

I assume you want something like 

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag("v10",  $fontColor="orange", $borderColor="orange", $legendText="v1.0 container")
AddContainerTag("v11",  $fontColor="red", $borderColor="red", $legendText="v1.1 container")
AddRelTag("usev10", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine(), $legendText="use v1.0 calls")
AddRelTag("usev11", $textColor="red", $lineColor="red", $lineStyle = DashedLine(), $legendText="use v1.1 calls")

Person(userA, "A via 1.0")
Person(userB, "B via 1.1")
Container(spa10, "SPA v1.0", "angular", "The main interface that the customer interacts with via v1.0", $tags="v10")
Container(spa11, "SPA v1.1", "angular", "The main interface that the customer interacts with via v1.1", $tags="v11")
Container(bff, "Backend for frontend", ".net core")

Rel(userA, spa10, "uses", "https", $tags="usev10")
Rel(userB, spa11, "uses", "https", $tags="usev11")
Rel(spa10, bff, "uses", "https")
Rel(spa11, bff, "uses", "https")

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/hLDDRzD04BtxLmnM3exKsbc94rAb9ca5Xm0H2U9ORUpnXrZlHhFZ5luziqti5Zi88N6ptvlttkopzzQp9kvQ4xrfR6ww0g5cFlftMKRwAQqQhhj3vv5oPnajfxbhiwFHDcYkFHUcEMJhjzVR07tzkCbQxHb9e8UrA7HZaT9Zy8-MHJ50UrqbyQDQn5S0irBGjJEERc97sbOewEpWg42Qm0OhjCKUV_2DwDC5vBrbFB-KeCO9XCN4Nh0Btchi_GNDiwlKSLfznZ8xNL4K5y4T_pG8Dt2dVOt5Hf1aFeeLQpWTInlZByIgKQoiFieKvDy3rH0ORP6yiuaGjBo2U0cFZGPPIRXNr4gerPbIGWsz9_werKBOtLQaGIVFqa9dD8N7VOtGoYGqbf5AdIDmhHbOyBppx5ga4wTpzl3KS1rYUgiPwyg7pxEOXAgNKFN_GjNhqDzFUYZBq8BElqkTK3g2aeIKbv2PMcJ87M4eLRvXtsZVZxpwCFTytOQG_kUQ3vBLIQB-8b5doTbUTfi8NWRKdmQYtOVFtnusz-_lFzqby-XMpY9tznS0)

BR
Helmut

**Comment by kirchsth** [comment]
Maybe not good enough (I checked it right now. In the readme we have  22 times the term "legendText" and 10 times in samples with "$legendText")

BR Helmut

**Comment by huornlmj** [comment]
Thank you for the info!  This works great.
