### ISSUE TITLE
Also have 'longopts' for Lay_L

### ISSUE THREAD

**Issue by oliv3r** [plantuml-stdlib/C4-PlantUML#215]
The `Lay_L`, `Lay_R`, `Lay_U` and `Lay_D` options related closely to the `Rel_L`, `Rel_R`, `Rel_U` and `Rel_D` options, however those also accept  `Rel_Left`, `Rel_Right`, `Rel_Up` and `Rel_Down` forms.

As it is often good to be explicit in code, having `Lay_Left`, `Lay_Right`, `Lay_Up` and `Lay_Down`  would be good to be able to better express ourselves.

While here, maybe this help text should (also) be available  https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md as it does very much describe layout options :)

**Comment by Potherca** [comment]
@oliv3r Thank you for bringing this to our attention! It would indeed be better if there was more consistency across `Lay` and `Rel` . 👍

**Comment by kirchsth** [comment]
OK, I will add it

**Comment by kirchsth** [comment]
Hi @oliv3r and @Potherca,

fixed it with #217. You can test it via my extended branch.

BR Helmut
