### ISSUE TITLE
Ability to add styles for System_Boundary, Container_Boundary

### ISSUE THREAD

**Issue by vellala2000** [plantuml-stdlib/C4-PlantUML#227]
Add support to style System_Boundary, Container_Boundary

**Comment by Potherca** [comment]
## Styling all boundaries

The style of _all_ boundaries can already be changed by using `skinparam` and the `<<boundary>>` stereotype:

<table><tr><td>

```plantuml
@startuml
!include <C4/C4_Container>

skinparam rectangle<<boundary>> {
  BackgroundColor #FEFECE
  BorderStyle solid
}

System_Boundary(sb, "System_Boundary") {
  Container_Boundary(cb1, "Container Boundary") {
    Container(c1, "Container")
  }
}
@enduml
```
</td><td>

[![](https://www.plantuml.com/plantuml/png/NOz1YeGm44NtTOeQPwCmC0ou5163Ni03I4mA2SPagCI5DDwzjMdiRhV_lV-fgaAK79VPmfTnoYwQi13vhyXxuLsKnX6N064oxb-od959HUb6IqKn-CLfoMjPuWqGQwccaOzCUEiPlzkcRKHp4C-Qk8kh9GpU6WqRGBU6I7DVFqVICFnWSWcJxB5yNlAorV2twoV0I-EjaweFCybslC465Jczltq7)](https://www.plantuml.com/plantuml/uml/NOz1YeGm44NtTOeQPwCmC0ou5163Ni03I4mA2SPagCI5DDwzjMdiRhV_lV-fgaAK79VPmfTnoYwQi13vhyXxuLsKnX6N064oxb-od959HUb6IqKn-CLfoMjPuWqGQwccaOzCUEiPlzkcRKHp4C-Qk8kh9GpU6WqRGBU6I7DVFqVICFnWSWcJxB5yNlAorV2twoV0I-EjaweFCybslC465Jczltq7)

</tr></table>

## Styling individual boundaries

Although it is currently not possible to style individual boundaries as one would for elements (using `UpdateElementStyle`), it _is_ possible by setting a `$tags` and changing the `skinparam` for the tag`s stereotype:

<table><tr><td>

```plantuml
@startuml
!include <C4/C4_Container>

hide stereotype

skinparam rectangle<<boundary>> {
  BackgroundColor #FEFECE
  BorderStyle solid
}

skinparam rectangle<<BOUNDARY_TAG>> {
  backgroundcolor #ABC

  border {
    color green
    style dotted
    thickness 2.5
  }

  Roundcorner 10

  Font { 
    Color red
    Name SansSerif
    Size 14
    Style plain
  }

}

System_Boundary(sb, "System_Boundary") {
  Container_Boundary(cb1, "Container Boundary\nwith tag") {
    Container(c1, "Container")
  }
  Container_Boundary(cb2, "Container_Boundary", $tags='BOUNDARY_TAG') {
    Container(c2, "Container")
  }
}
@enduml
```

</td><td>

[![](https://www.plantuml.com/plantuml/png/TP5HJy8m4CVV-obED04IeaBm3GbiWc-OC7qmCI7TTew6hYNjBMOIlhjTDm4D97lOVdVt-xUtYILkgCWbkn8gaKMAC0g7T-5m5Mf5N2WqOyRMmd5BQ51JkKN6x4QeBJSy1uC9SPL978rYNQYKct8yXXq327YooKp5GYsrWUlvR3uBPrL5cnHDHALqLYr5olONbC7Bs-9fkdnVlKwV6sryq2QrTXg4hE9Uwbi0wb9c49N_jZuhrKIOUa1haMmKMWk3smT7zfLYMLkDSfx-VKNcMX7im8_Kjp2DOC5pX8Wh6w4Hdnv5uXkXFwpVVU1MSg5gktkYqXBcgw1PKyV6FMZzWwskly5X-SVk9EwxzaC1VWiVwalG6eXdpUp9T2VvCzFg-hDSq0zEMuy7wi6DSzl7zkc_Q9-96fo9shC9ghJ8vGy0)](https://www.plantuml.com/plantuml/uml/TP5HJy8m4CVV-obED04IeaBm3GbiWc-OC7qmCI7TTew6hYNjBMOIlhjTDm4D97lOVdVt-xUtYILkgCWbOrT29R984KRXy2uShaAjY0k5PipOMZXk2GrgAhV8cDq8jUM6vs0m8QuoYQDHh0kLSbEEnx1Z005FDfcfMAYbDd0zdyrduQogQ9EYYQYKpggbIDd-WZ9uULiyJPVlgzVfSwED3zgaraw3a5NSItqBG5tA3ABotzPdfPe8KmzeBPADGcjXSFlWoBvIB6khKSxJlw_8N2k27VYH-XQc4InuZX1nPICqujEZI7mZz8Vrkm_SIYvKRNTFL5h2V1KqQ-hOk0UjVx3LzJSuBF_OdSHzrtuem6_XGtq9MWFnh9azcUuaVsPQNN-M2_h1QUlnG3suSMxxs3xz5-qpKOCpKNisGPKMkVm1)

</tr></table>

@vellala2000 does this suffice for your usecase, or is there something else you need?

**Comment by kirchsth** [comment]
I checked the current implementation and $tags are basically supported via the AddElementTag() too (incl. legend support)
there are only few limitations

1. no sprites are displayed (node specific, not supported at all)
2. added $tags are not displayed as part of the type, e.g., `special system boundaries`  has fix `[System]`
3. missing AddEnterproseBoundaryTag(), AddSystemBoundaryTag(), AddContainerBoundaryTag() (and generic AddBoundaryTag()) calls
4. "non-tagged" boundaries are not added to the legend

```plantuml
@startuml
!include <C4/C4_Container>

AddElementTag("special", $bgColor="green", $fontColor="white", $borderColor="blue", $shadowing="true", $shape = RoundedBoxShape(), $techn="A SPECIAL SYSTEM BOUNDARY", $legendText="special system boundary")

AddElementTag("existingContainersBoundary", $bgColor="red", $fontColor="white", $borderColor="white", $shape = RoundedBoxShape(), $techn="A SPECIAL SYSTEM BOUNDARY", $legendText="existing containers boundary")

System_Boundary(sb3, "A System Boundary") {
}

System_Boundary(sb1, "Special System 1 Boundary", $tags="special") {
  Container_Boundary(cb1, "Container Boundary\nwith tag", $tags="existingContainersBoundary") {
    Container(e1, "existing 1", "xyz")
    Container(e2, "existing 2", "xyz")
  }
  Container_Boundary(cb2, "Container_Boundary") {
    Container(c2, "Container", "xyz")
  }
}

System_Boundary(sb2, "Special System 2 Boundary", $tags="special") { 
}

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/hP1Hwvim5CNV_HHtOGyAVnXrVPoZQcKRTEse7QCmA6hkL8Yn997QZNxt6R6fhbttijUJStyvvooaIeHgAcQzAdd66ehmBfo_2UU7iEOgAJcAzvRbKnenh92hNPBRH1unAnD6Nk1rceSrguL7Se78jVAZknkqKr4gx5sre2W6DMLDByeYeVMfvBb7b33I4S63RTrmYZIesrWhjjEzASmAxX4VuYzH-CbVGRoFTz5d23PVrqj_kzVt37FaT8UjyguXGPwbmWfIZKp4cJXtTR0jfUfocCOo6CoJXWBfl_ePzN-tCHaXCo4dbUA-vU4Qt9RfsnVG-5w7m5ZXbtLvP9zrzdYOR3YQmNW7bUJIhDfp0CnYDrBMayo3GNpdfr8Lq54CxCdm0t_qWusQQsQOTHJIddyIvq-RExQvOzlbRudroUtXIOPiufom7w_gtg_gFbyLDAX3VTnyEwoY3z5wQJlM0ZbjAlOR)

I think I could fix missing `Add....Tag()` calls (3)  and display all stereotypes (2).
But I think we should not support sprites at all (1).
Related to (4) I think this I could fix. 

@vellala2000 and @Potherca: what do you think? Did I oversee something? Should I fix (4) too?

Best regards
Helmut

**Comment by Potherca** [comment]
> I think I could fix missing Add....Tag() and UpdateBoundaryStyle() calls (2) and missing legend entry (3, 4).

For the sake of consistency (or [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), I think that would be a Good Idea:tm: 

> I think we should not support sprites at all (1).

Agreed.

> Did I oversee something?

As usual, I think you got it [spot-on](https://www.wordnik.com/words/spot-on).

**Comment by kirchsth** [comment]
Hi @Potherca and @vellala2000
I added a better style support for border tags, can you please review my PR #231 
Thank you and best regards
Helmut
