### ISSUE TITLE
Person_Ext with tag "Person" rendered like an internal person, is this intentional?

### ISSUE THREAD

**Issue by dirkgroot** [plantuml-stdlib/C4-PlantUML#228]
I'm using [Structurizr exporters](https://github.com/structurizr/export) to generate PlantUML files. When generating PUML for external persons, this library uses the `Person` tag. For example: `Person_Ext(person, "Some person", $tags="Person")`. However, when declaring an external person like this, it is rendered like an internal person (see below for an example).

Is this a bug, or is this intended behaviour?

## Example

```puml
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person_Ext(person_ext_without_tag, "External person without tag")
Person_Ext(person_ext_with_ext_tag, "External person with Person_Ext tag", $tags="Person_Ext")
Person_Ext(person_ext_with_non_ext_tag, "External person with Person tag", $tags="Person")

SHOW_LEGEND()

@enduml
```

This is how it's rendered.

![example](https://user-images.githubusercontent.com/3872163/175910130-a8373713-a78f-4ce2-af91-347ab11e2e6c.png)

**Comment by kirchsth** [comment]
Hi @dirkgroot,

>Is this a bug, or is this intended behaviour?
 It depends ...
a) In C4-PlantUML context is it correct (see README `tags can be added to the existing element stereotypes (component, ...) and highlight,... specific aspects:`). And it contains no tag definitions and therefore it cannot be displayed (working sample see below).

b) related to [Structurizr exporters](https://github.com/structurizr/export) I think it should be extended that it
    1) creates the required tag definitions too.
    2) add the tags is reverse order
    3) mark "External_xxx" with new "External_xxx" tags or with an additional "External" tag which is added to all external elmements

Eg. based on following DSL

```DSL
workspace {
    model {
        enterprise "Customer" {
            dwh_developer = person "DWH Developer" "Developer of some DWH"
        }

        dhw_developer = person "DHW Developer" "Developer of DataHandwerk Toolkit" "External"
    }
    views {
        systemlandscape "SystemLandscape" {
             include *
             autoLayout
        }
        styles {
            element "Person" {
                shape Person
                background #FF4444
            }
            element "External_Person" {
                shape Person
                background #4444FF
            }            
            element "External" {
                background #4444FF
            }            
        }
    }
}
```

exporter generates PlantUML diagram like

```plantuml
@startuml
title System Landscape for Customer

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Customer") {
  Person(DWHDeveloper, "DWH Developer", "Developer of some DWH", $tags="Element+Person")
}

Person_Ext(DHWDeveloper, "DHW Developer", "Developer of DataHandwerk Toolkit", $tags="Element+Person+External")


SHOW_LEGEND()
@enduml
```

![current](https://www.plantuml.com/plantuml/svg/hP11J_9048RlyolcQxv32K8ldanCYBIn1rGID1oRfHrWmtQtcPqAnFZV7IGIBthojk-xCy-JNO195CFIjmx4YYDS7ADGYpFZcrYRZd0T6ATzbD0I0qZeK0AkWcY1ZMMgnGOFyC_wslKDuLQaYpTPncO_tbZPzgi-4jV12taPrw7DEcVyoJYAqZYxogRNe_cfUdcOPQrHFMirxdJYpwdLzBHna3CT2WtSiOrKtONUDuQFALswAqo-7fuCy0qGvyGn-3HVbZczaWiTiGvfn4jEjBW436kCkeyweXV_nMpYRL8uQjKoFDEI0Rm3dCzLSP0qBvVVwHf_eUT6J6byioVUuNC8RcVb9zDGwSJUE5K2BCgdPJKhxel7F1t0X7pp-IKV)

but if it would add the missing tag definitions and reverse the tag order it could look like 

```plantuml
@startuml
title System Landscape for Customer

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

UpdateElementStyle("person", "#FF4444", $ELEMENT_FONT_COLOR, $sprite="person2")
UpdateElementStyle("external_person", "#4444FF", $ELEMENT_FONT_COLOR, $sprite="person2")
AddElementTag("external", "#4444FF", $ELEMENT_FONT_COLOR)

Enterprise_Boundary(enterprise, "Customer") {
  Person(DWHDeveloper, "DWH Developer", "Developer of some DWH", $tags="Person+Element")
}

                                                                               ' $tags in inverse order
' Person_Ext(DHWDeveloper, "DHW Developer", "Developer of DataHandwerk Toolkit", $tags="External+Person+Element")
Person_Ext(DHWDeveloper, "DHW Developer", "Developer of DataHandwerk Toolkit", $tags="External_Person+Element")

SHOW_LEGEND()
@enduml
```

(with $tags="External+Person+Element")

![$tags="external+Person+Element"](https://www.plantuml.com/plantuml/png/jP9HQzim483VzIjktg0ENMCOVHeKkiNoyk0sPKd9er6iQoegIq8wjmrZ_ttd9VKA7Hk3JXZZE-w-JsVfF96Ar7TMa26BiDmbmWvgvNHgLK2uyH5cVIBVOHI2V03oiF742T0cOal6Eo7U6DVQNYFS4eNqiIYYUfXk3TtscpvXRBqZT3HjVLS4gznWF4cahTaKizEJgo5rVL4NdM9zvDGqSCMhKvlPqF58Uxgu3beHIeiTKvQqivXd0MFoBdiFsTkgEkN5d-zaBI_avQgf5loQBUh5Lqwc40tXsQ7ZGpRvBOzj69sopJFmWAsgVm1_qlf0NQdjB-PVOHCXfEDQ1YPiFllUQHLtEOuv1ZmTRZQ1RmBWwgSqBzVp4k_H-e2HYpY4CHwqOm3-1XBt0vSCco2rJMVPdd9ys3HFy5q8UDrrj7U1SVpSim_1HurHxDsDVAIydA-VJy7X7wOe5QcvSle1unsilBTtXiQ9ndz-_6Aqe_yZb4yNvuLGBEUBTLFBB_Aop2VY79tcw_m3)

or  (with $tags="External_Person+Element")

![$tags="External_Person+Element"](https://www.plantuml.com/plantuml/png/jP5HQzim4CVVzIbktg09NMCOVHeKkiNoyk0sPKd9er6iQoegIq8wjmrZtttdnVCA7Hk3LeJWE-v-F_tjyqGgKjTQGOOimcgV25kebDEfKG7XnaUOTubyYr48yW78mzOJDq2RY0qPxuHuOrnZEurmInJInpoFwc6sCtJRRRk4iV6EqD6iyMqUh7AzyIIHjcQRpqzFhlhMzKMLjuhraLkpm1ClJgtd_SOZ7UZYEcX5A2ssJ5dHtk8a2nYJTzbxoDwMvIaVVdmdAtaXBzTrkUI_-R9QVkLc2j4GdWqR7xBf7tbim-YKhP-0UsnP_WVuazO3TQrslvd_X4s5a8vd6PYm_kmxfrNSJt3iCU3Nnyscy4q0NFsKJehDei1xj3vWv24kOQnxxLY0lu74-y0Z_IL8xT9PTg0S3vVc1D-5W9SzHmSN6CU_U_OX-AWnYgCXGoqVQL8iDazpSFcN78KYjL1EFs2yWxNtzixGc6bywyVFmhsEJmw--fbFh1RBJLt9B_Aoc4p5EJhTjVO7)

Which is basically the original (and I assume expected) Structrizer output.

Best regards
Helmut

**Comment by dirkgroot** [comment]
Hi @kirchsth, thanks for your detailed answer!

From what I understand now, I think there's a little bit of a mismatch between Structurizr and C4-PlantUML when it comes to how tags are used.

Structurizr assigns default tags to each model element. See https://structurizr.com/help/notation#tags. As you can see, Structurizr assigns the `Person` tag to all person elements, regardless of their location (internal or external).

Structurizr's `C4PlantUMLExporter` just takes all tags of a model element, and translates them to C4-PlantUML tags. See https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/C4PlantUMLExporter.java#L206 and https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/C4PlantUMLExporter.java#L253.

Because of this 1-to-1 translation, external persons exported from Structurizr to C4-PlantUML end up having the `Person` tag in the PUML file, which in turn causes them to be rendered as internal persons rather than external persons.

Given that C4-PlantUML behaves as intended, I think this needs to be addressed in Structurizr export.
