### ISSUE TITLE
Should we reduce legend text width with line, border style symbols (instead of text)?

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#232]
Atm we have a lot of different line, border and shape styles and the legend text can be very wide like below

![](https://www.plantuml.com/plantuml/png/pLTTRziu5dtNhxZrT50RSEn9qwQ31GACRClJ3FpXjPns1ek5GOlN4b6Ar9AK4sCn_tr9VPYnqq5tT_PXzP2OvtwSe-ChYlv96w9CcVFW3IHI750PO0OUcSc0KCeCau9m6yfp8YXm9X28IiiSXO6hoJgQXPlxJz7sVZ6UFKoYkywW0qP2gH6uJ0Zdn-0LsyFt1w8OsN7SuXFJHdSxbvMTNW3mYec4bnHXC1mCXkDtsx4KXbXEDIYSnbV8DJxFoumfz5-6GqKU1wdLNEuiiqfibTKtiAg7NvXACcqos-rgnOam3_FP49zid2BzAeMWR1y4Rzm5cu_tCSJHU7E_N40ujeB3JHHRE895z1dYt-QZvIo6BaMI67OW1frxpgcZB2550oP3a8gb0w2eMIfWHv8lFO2685fCO3bjAO8W_hZyl5r5wtYvs2uVDhFxHTJj1LO8IJNeiYYaCY0aw88ag869Ya2G7A6x8nefo1eg1KN5cM0Y1MrGeJJ70dKV7ZEMP42bU6FQXcqt8ewvLDWRW6MytvzWXQ3m7oNQFhIbv9XQf_hDVp3ur4nDLGGPqMuETWWKzqmW3K9A8uvkRkozT3lE1bjuSh_JXzTxknXBBjNTwsWMpQF5PZjTsZ_ZvMovjl5TMaSxtztSl9-4xrsDpaY1Tn5BCnCpYZHswswlZb3vQE__hcDKYPsUax16Nj4JVHI9gxV2MyvmlRRcjsHkrFym49iZnxi9qHdI6HEMyAoxQpxytr18Opp5Gq69mVYe3UOZMGfArB7AwxQnnk8Qx5XYL8BmhQvAd9ZerqsqNeIpRVnRl8dcsz7FBUlNFN-HlrnFedKJRkrVEor8H_AfiRyN1BfGp22yLYusbagWYcleRzUtJzUtm-lRlyC_WnykBWzy64NJwVG4XDFmzkRwbF5-EdxxlEJ3z8FlKSLlpfg-hUCU24Tdj3RXxJdm8RmGDhgz0AAR2s1wVGdyy2tWylP_zyubfVblV7iNJRrlrVgTp_1h2_Yr1_pQ0Nxj0RzsGBFsGBlsW5z_svK_xrlxuFz7fjbh-W88Nm0__Zy1Ktyr6Q6_tjKbF_hh3qmpp724qpOCb95KaHpsKi6zSDi76XWHySMzIEgT9mXMgBGKtQJKHkQe-Z0-VUg4qC8WzzMhOcUh-_NBeQWA2Qym84aYIs6qtPg3klMstTMwoRNjTIcWqxDV8W1ulTr7t6r9KTZapxY3i2WuIuWxjNGiz0iva3wuIR3Yvv_63fiWPmShevAcZSrDe3amL2zk1vzuT-sDhq8hyfnP5yIsYssOuzMAfEZOMzOuKQmmVGX5MdAY7BnIyi0eQY2SVvrbNugaFd0nSmGZhPELaHeEZBWIfi3UB-oKVDIeNYZAvOvnREoOLujMq_YxFlnAScATEDS2dENC80LTxZGQaFj_Mvj-8QuM01GFBC5BUPDTbn93t2d5VGtDHwSc_kiCpjP6AjJWZdAWC6NQAEAuWGaxbddrkGzPzVO5KfeC4eKKXM64wxuRAzGQk4pj0aqoU65KS_YmJZ4tiQlxhm_EHDeqvUlEdFk6GyuKsxXw_vDKtxqyyFI2tqzZ7psPBkQ4jMzgInHTpUqQwWJ7lCaGM4LAECnPegIMUmFHKv8HaIBeEhFtl6UZpNUrFSLUaHmldcblknlFTWeI2xJtzzny83jP6Zy2_TEZt0UZYD2aSiBR7woHFzik_4Fxe54xxe-RpIgsYUTvkY3VpF53twRMTDi5iZJRIRz5LEty1j1qgi3pWMW9gnDS7twnX_5XHUw_pIhKTF0A_boZxSWMUzd-OJblkaP2DUoLpAlzwb4nWngCT4GDpsGqjYrFFP-vTJ5aiMsh0QySMlNmGYxcyLp3ULsfxNnu-dY-MTMD_CsSbLzCfVV9dvljRZMVNNhbmxPz_LDf5lqSBIRs-BkNqg02giYZgDyrxQyzE0pWU_U5CocwlSep_rlGHUtoKniEVh8govp_2m00)

(@Potherca:) Should we uses symbols that the legend size is reduced, like below?

![](https://www.plantuml.com/plantuml/png/pLXjZzku4VxkNp7HvH0RzNgpsMHpABh5oRQSzS4lhgND2uh2eAInJ4GcLPBQ5nJzxntAihcszfAWrm_LXrtpuSmyeuV38UrVjM7AbDkyzGeIAUvG6U06xhdP04jJRhWKBAUfxPQ9578k49ZAoYqA0sV3PJ3ne_77O3MU3IQtm-3QwtbW99GQ8PS9o_F7rWk-Xf_lcE8ipd653rmRtVPEFRrE2-055qbUfWYzyrxlVF1sDP32CE9KlSBc-09pZK_jDiOK-i_dvuhTzpBAkOo9MINaHVdrAElphrmb6sqs5EriaJDXRgUJStoW-HJJPob4ojUjrYlxG7Gp3Y4C1j5uFWD_G0dxKH0I7C0i-0JXbsb_FWcXdI9B3BzZ1grwLgb7MKA61im6GIgUzI15pJC1CKk-TW1QBx9SnYo7bvFWGp0Rhi8RVpZ_j8g2pn5SWzV-oqkzOQcy3ml53Vwr0rx3PJPlU0a9F-2udD_EXi5mrPz_hhcKB4Kwa8fq-8PVCFvm4wt2CVdMVabf6bwlgcMXLIa5JsIAPnePBK9Fe3b0WcsnXekymJESHn6bDndFWXtFxP_Ul7ljFvlJq0zl6hPlWsTjQR4QKI-_5RLlXVANNwnzR2LYwX6Q54t7QEdFmeM_36RHTu9qmIWcTC4K2bF9Pn-WM30VxMklrGflQ9aNmJASprRpsyY-HBj3KaSiqw3Bef3AW910WHBKm4LLULPcQCTCOmfo1n4_gfmBBZBG1XLAyrYWxiBzXYSRIALuPGu1wsXCF6wbmauFY76yFi0AGU4_IwGuwPuonmn5sgt_Wy67kfrKJh1X6eo46275DHUOjlmq3NAq3ONUfUtP_K6EXstfTU7bcWO3cKjr_JAO15ChwcXEVmRpoNn9yt6sc_L-khnyD_JVMH-zOGLU1ppRc92dc8PstEvqeTuUzFxNdb4bUXsRmXBpYfxfHv5OVvjupUalboJ-dipsmD-T2CrZZjT3fZUOJhWWmgFeDlZv_uP26kCeRekK6GmVjS5jlownogwzdwibte4U4QCIB5_foiKcGnqaMCxyoIhy4aR1TDN_S61zLlE6_Nmv39Rrz5x-fSq5qxvygENlj5gwwXJGR3dmzukhXukhyukhVy2_MgzF7WUyxmUZqUW0-2F_wlBYOF5kD7ZprENzwBsBKSrV7WLzG_D7WDy_eYM3DyV0U_yaiVxL2H1SdW2ZYrFWzRU1vkl_socNbEQ_qUrjCAfqS-EtpiAD2N1Z1xYn1TpO0TNO0VNO0VNO0JJ-SLN-k6xrnlynqTmpQW1-0_Zb_maOkQUsyDtpTkVoYtj-HpJ3JOvmQCEGSfOfjeMrL30MjdsWWJuJN-r1ikiyhTO2bPQYdPJQo2sgBWmEdpmVzZ38TNLKnEJTtHqEHUN8yWe3bYIo54Pxr2vseLVxhjPEBYZMQG9UXnOH05o-xNkCLwmeoFWJnk0NHSuJPg-p7a6_iJlM1Qe4c_pquy1YGypv7QLHfQODsIPGtoI1YRI23xpn_iKNljSvOTO5et0XJUTujc0PMlOzQvWeNfWk-28hSwOil53oZgUeWUNvyophKYIxcpWtZs0aALa9gU6EC-l25T3xGgpalKRLo6WhOvvZBSVK3Wuv3NxgmcUsPQJ4SIwGyoqtc88kOuq6vFg7SzEDv7O9G8ftFC7Jz8PnEsM6sLkANORweyqc_Di4ZiP6AjHWx_YWCEFQg6f9WGigostrkGkRwlG5LfeD90fJ58QpN7TjMQ7MaCkC1cYINaEe-l91Id5RiOlnyuKpb6IcdD-HSjzHo8f2WQlpdsNwkddXwTZjLvTzy63Qk6LyVr8JKN0sfN6zvInpj47W5IdBOSeJ9RLS6mWUaWqJ6K9zndUUngnpSr4ffbWhjiMJFUrahygpheA40AXZF1KVM2nBuqgWUzZAzJMNLKeu-LjBp9-q2xTfRpLgotqJHOkG38_jTC6-Q-EAlZQjwLOpvDacbgv5LE5S0wWZLU3JWd24rGsk2x_HPVoy8dUhMKtL4Lm6VopGga_EBcstMOw3Bf6b6jPARgj-TQ-uGGr6MgAQPzWVKCX3p2TgdHHPI64ru9b5gnWkaQDwFCgXuLTggWz77qwZ1GKwMeCZzvEgT3gvUpDrg-daL2itxNNghqgxhsDq_LrBQL11gjYzs9qr-vy1uAu7Fzi5vrAqEvLczaS2Dql3Z_lfrg-KPRdD_mC0)

**The disadvantage could be that the symbols are not clear for everybody.**

I found no useful color alternatives for "transparent", "no text color", "no back(ground) color" and "no line color" therefore this would remain unchanged atm. In most of the cases the e.g. "no text color" can be avoided at all (as soon a concrete color is defined).

Second question: should I remove (border) "transparent" from the legend at all?

Thank you and best regards
Helmut

<details><summary>PS.: source of the samples</summary>

```plantuml
@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include ./../C4_Container.puml
!else
  !include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml
!endif

''''' THIS SECTION ACTIVATES THE NEW SYMBOLS (deactivate it and you get the orig. design back)  
!global $LEGEND_SHADOW_TEXT = "(<$shadowSprite>) "
!global $LEGEND_NO_SHADOW_TEXT = "(no <$shadowSprite>) "
!global $LEGEND_ROUNDED_BOX = "(<$roundCornerSprite>) "
!global $LEGEND_EIGHT_SIDED = "(<$cutCornerSprite>) "
' http://unicode-search.net/unicode-namesearch.pl
!global $LEGEND_DOTTED_LINE = "(<U+250A>) "
!global $LEGEND_DASHED_LINE = "(<U+254E>) "
!global $LEGEND_BOLD_LINE = "(<U+2503>) "
!global $LEGEND_DASHED_BOUNDARY = "boundary (<U+254E>) "
!global $LEGEND_DASHED_TRANSPARENT_BOUNDARY = "boundary (<U+254E>, transparent) "
''''' END OF SECTION

SHOW_PERSON_OUTLINE()
' Tags support no spaces in the name (based on the underlining stereotypes, which don't support spaces anymore). 
' If spaces are requested in the legend, legend text with space has to be defined
AddElementTag("backendContainer", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#335DA5", $shape=EightSidedShape(), $shadowing="true")
AddRelTag("async", $textColor=$ARROW_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())
AddRelTag("sync/async", $textColor=$ARROW_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())
UpdateSystemBoundaryStyle()
UpdateElementStyle("external_system", $EXTERNAL_SYSTEM_BG_COLOR, $ELEMENT_FONT_COLOR, $EXTERNAL_SYSTEM_BORDER_COLOR, $shape=RoundedBoxShape())

sprite $roundCornerSprite [16x16/16] {
0000000000000000
0000000007BEFFF0
0000000AFA631000
000005FC20000000
00007F7000000000
0005F30000000000
002F700000000000
00AB000000000000
02F2000000000000
07A0000000000000
0B60000000000000
0E30000000000000
0F10000000000000
0F00000000000000
0F00000000000000
0000000000000000
}

sprite $cutCornerSprite [16x16/16] {
0000000000000000
0000000004EFFFF0
000000004E400000
00000004E4000000
0000004E40000000
000004E400000000
00004E4000000000
0004E40000000000
004E400000000000
04E4000000000000
0E40000000000000
0F00000000000000
0F00000000000000
0F00000000000000
0F00000000000000
0000000000000000
}

sprite $shadowSprite [16x16/16] {
0000000000000000
00000000000F0000
00000000000FA000
00000000000FA800
00000000000FA800
00000000000FA800
00000000000FA800
00000000000FA800
00000000000FA800
00000000000FA800
00000000000FA800
00000000000FA800
0FFFFFFFFFFFA800
00AAAAAAAAAAA400
0008888888888800
0000000000000000
}

title Container diagram for Internet Banking System

Person(customer, Customer, "A customer of the bank, with personal bank accounts")

System_Boundary(c1, "Internet Banking") {
    Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA")
    Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to cutomers via their web browser")
    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
    ContainerDb(database, "Database", "SQL Database", "Stores user registration information, hashed auth credentials, access logs, etc.")
    Container(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API", $tags="backendContainer")
}

System_Ext(email_system, "E-Mail System", "The internal Microsoft Exchange system")
System_Ext(banking_system, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(customer, web_app, "Uses", "HTTPS")
Rel(customer, spa, "Uses", "HTTPS")
Rel(customer, mobile_app, "Uses")

Rel_Neighbor(web_app, spa, "Delivers")
Rel(spa, backend_api, "Uses", "async, JSON/HTTPS", $tags="async")
Rel(mobile_app, backend_api, "Uses", "async, JSON/HTTPS", $tags="async")
Rel_Back_Neighbor(database, backend_api, "Reads from and writes to", "sync, JDBC")

Rel_Back(customer, email_system, "Sends e-mails to")
Rel_Back(email_system, backend_api, "Sends e-mails using", "sync, SMTP")
Rel_Neighbor(backend_api, banking_system, "Uses", "sync/async, XML/HTTPS", $tags="sync/async")

SHOW_LEGEND()
footer drawn with PlantUML v. %version() and C4-PlantUML v. C4Version()
@enduml
```

</details>

**Comment by Potherca** [comment]
Usually I am not a big fan of replacing information with symbols. It might be clear to the author of the diagram but most likely not to other people.

Before I can really comment, I would need to better understand why it is an issue that the legend can become rather wide...

Looking only at the legend:

![](http://www.plantuml.com/plantuml/png/fPFVQy8m4CVV-rS4VAcTOB7-SAC4jTAdlUvvdCsXnNgH9385__YrCGPNOIli2gNXFlryoRLPQ0FAd0vLeFSb7K71WRtZ5acif1AeCbb9nOm2qdKJoJnpKEotIfv8_CtcaioDwkMsWg2oZI3jnQu6_ebVqwA1ttfk7KKtJHIbGzlXx1fSwrVduz5inJqzIrRJdBFqusKqMURSmmvmsPmTKMb9xATidCpNwucN9Taip-8EiaAIWP9GjNoljhnllcok3Zuy6rG4rQU-Q8C75jePes0RUUwtCXvcxeF6jdu9kWFElsdqe2ui5A1tA0QFNx8Tc2IJzT8FoIqxR6e3nHv9P7vMeTw1a5zz5cAvtHccIu6YbUOSKrik98wVGZm0-aA5syP_NOrgU1TAOrf29E5-u4Lzgu_HDm00)

If the `transparent` is removed, things could also be made less wide by using a smaller font for the additional information:

![](http://www.plantuml.com/plantuml/png/fP9TQ_8m5CVlyoa2tZnF9zXPNvoKu8lqQhUx7iVceCNsH9B8TFZXPsC8hcMiiBytjkVVtuySiZ0Mj3rL9JE7WewWeUAlk4EIAwKbwhKgbUPM0vdR4CcsUv0VTbgTIFxUpHJPUwkNkJ36IZTXBEt5FltmJrpJlAxF_HiHHNTG5AK3Dn7yogwtJsUZuNGbGdkQh2QPuEdRqt2yp4Ge-uAt2tv4RHJnxx1HCjjinW6MhAVPEku0onLPA0XrW_VY4dYpPVthmCEpHKrGlfkBiLZnr1IVE7-EnJ-tRfHygyx_6xA7zGVZoELdOoXuqRR6Wxuy62MOFSgcB4d6csNOb7_iSB8jv0UiBqnOM12PFKZrqUTOxFQMcqAsh9urSV6oE6x9GW7CXVBcKVuAhPc35bbPso0p9Ebl-099dgho2m00)

The shortest it could be is this:

![](http://www.plantuml.com/plantuml/png/fPBFQeD048VlFiL2RhOGYJ7Q8alyWwTUUouR7KA8peRP3LJmuQkRPKbDIuN-176Opq-PdRtIWlIrQprrFk55aEZO6nm1crnI0rJ8LXBJ952DJK3zo8dwV2HvnUPljfAeRzIgCl6yrZIyT1NOFBidFgJr1B-kREtxDutlfslJuMpmXl7LPBk9S-xeECnt5MVf-zCcoYhkO0lORtDs0L8IsNVPDapACdAoi8Yh8bWWgoLgSKAWcU_5nFcIRBeM-E1J0w5eFrIlD7GpwzsKdNfhyhlQ0TPuc0vDK3zJXs5KPcu0jbpmmuTn4G2RukSvM7XdOcr1y61pW50zrlzJJ8QryTnf01kxSllnDYx-5m00)

If the user is willing to gain a shorter legend by losing some meaning, that would be easy enough to achieve.

**Comment by kirchsth** [comment]
I like the idea with the smaller size.

I could make following changes:

1. The user can define the legend text without the additional information via a new **$label=...** parameter of the `Add...Tag()`/`Update..Style()` calls (as an alternative to $legendText).

And if $label is defined then it will be combined with the (calculated) additional  information.
This has the advantage that no (calculated) additional information has to be added to $legendText anymore.

E.g. `AddElementTag("backendContainer", ... , $legendText = "backend container (shadowed) (eight sided)" )` and 
`AddElementTag("backendContainer", ... , $label = "backend container" )` produce the same output.

2. add to `SHOW_LEGEND()` and `SHOW_FLOATING_LEGEND()` a  **$showStyle(?)** parameter with the options "none", "normal", "small", "symbol"(?)
The **$showStyle(?)** parameter requires a tag definition with $label (and if $label is defined then the default is small)

![](https://www.plantuml.com/plantuml/png/lPJDZjCm4CVlVWfBom5AfJOVIPULPQsxT4xS42V4mIGc6stgh1nN82ZlZXkxJkEi53YKlzJ6_iruPZooVTzfhlHXtw3kgPRFNF4z_Y0g8SjjgqgX7jgcLLWhBZjZ559F_NZnLAds8CjvNsYbjbutq0jTk7IFl6o_rx8YfEczcHASKloDDvsuy5EYq5nMZGZyVY5izDMNKzX4QoThxJSLMdwRCfvLhGL-vJQYf50VBVeSvJ-YV1NbNqo6TQ01RBOx0F200SkJo7jay11VBjd0PXGZWsGKDFPs1zXsd3Q6U0msB2XicmTWbmG0eX2ivu3Nj7F5GVzZtz8T6EtICqZjq7wG6tY2_DmI0zpSaR1Uc0VJ666Mi8wmqd0lissof_olU-G44y0cu7O2qly6O93pO8FSajj1BaOwwEMc8Nl1iQghHus8lx5BFw97qj_cEqVeOc6VciM2h7eBnKTqFFt8JP9axrb6tOhp59DFR-EC0VKBpWxGY_PlogcCefMQrr8e_5gSAi9TNOfowLwkD_YQ6KbN_nHtx-YBcSdgPANugbicuHMdIqn6vvbUjmL1R6EqnmFTcx_3lla3)

<details><summary>source</summary>

```plantuml
@startuml
skinparam LegendBorderColor transparent
skinparam LegendBackgroundColor transparent
skinparam LegendFontColor #FFFFFF

skinparam shadowing<<legendArea>> false
skinparam rectangle<<legendArea>> {
    backgroundcolor #00000000
    bordercolor #00000000
}

sprite $roundCornerSprite [16x16/16] {
0000000000000000
0000000007BEFFF0
0000000AFA631000
000005FC20000000
00007F7000000000
0005F30000000000
002F700000000000
00AB000000000000
02F2000000000000
07A0000000000000
0B60000000000000
0E30000000000000
0F10000000000000
0F00000000000000
0F00000000000000
0000000000000000
}

sprite $cutCornerSprite [16x16/16] {
0000000000000000
00004EFFFFE40000
0004E400004E4000
004E40000004E400
04E4000000004E40
0E400000000004E0
0F000000000000F0
0F000000000000F0
0F000000000000F0
0E400000000004E0
04E4000000004E40
004E40000004E400
0004E400004E4000
00004EFFFFE40000
0000000000000000
}

sprite $shadowSprite [16x16/16] {
0000000000000000
00000000000F0000
00000000000FA000
00000000000FA800
00000000000FA840
00000000000FA840
00000000000FA840
00000000000FA840
00000000000FA840
00000000000FA840
00000000000FA840
0FFFFFFFFFFFA840
00AAAAAAAAAAA840
0008888888888840
0000444444444440
0000000000000000
}

legend right
<#00000000,#00000000>|<color:#000000>**Legend**</color> |
| |
|<#335DA5><color:#335DA5> <U+25AF></color> <color:#FFFFFF> backend container (eight sided, shadow) </color> |
| |
|<#335DA5><color:#335DA5> <U+25AF></color> <color:#FFFFFF> backend container <size:9>(eight sided, shadow)</size> </color> |
| |
|<#335DA5><color:#335DA5> <U+25AF></color> <color:#FFFFFF> backend container (<$cutCornerSprite>, <$shadowSprite>) </color> |
| |
|<#335DA5><color:#335DA5> <U+25AF></color> <color:#FFFFFF> backend container </color> |
| |
endlegend
@enduml
```
</details>

3. remove "transparent" (which is basically only a specific color like white and white is not displayed too) from boundary that we avoid a legend like

![](https://www.plantuml.com/plantuml/png/JKzDR-8m4BtdLyoo1uB49cArfpsHfWWEGACcb6DaacbZrH-MFL6AglxtJbGAzUN9ypxqtZAGyDHh5VsIfb5zYz0HkV0_JRqOaXT9NN_g0_h66a93IMDr-YfzqmNgqlpVdq89GuVTDiKtvbji-LZdB1RIe4_S61qLw8CriMYrD7EOP2FAG5wGzPDPL9u3eQxlR6zQuSznivZ3j1JQAPpEu3q2VjV8UC1JBPpZd2EU87DEoKQGj6R2f_pt7BAoIFQhYYqUuM-oWDrJFdAPKdO8CAu9G1PuYXCiqRqYwHH2DKWYz41Iev860tVxkBIBwOlad8kCoUWHrVUgMwr3O2VZfggAabMZwChUOjP8WRyumhEt-gSbAZSFntgxMg_sz_4iMg9fUwq-0G00)

What do you think?
And do you have a better name for `showStyle`?


Thank you and best regards
Helmut

**Comment by Potherca** [comment]
> 1. The user can define the legend text via a new $label=... parameter 

Sounds good.

> 2. add to SHOW_LEGEND() and SHOW_FLOATING_LEGEND() a $showStyle(?) parameter

Also good.

> 3. remove "transparent" from boundary

Also good.

>  do you have a better name for `showStyle`?

Naming a thing is always a bit tricky. 

What does the parameter do or represents to a user? :thinking: 

It doesn't really have to do with "style" as much as information representation. It gives the user an option to change how secondary information is display in the legend. `$legendSecondaryInformationDisplayMethod` is a bit verbose but it also doesn't fell "right".

For the user the information has meaning. That meaning is not "secondary" but is part of how they can identify items of a specific type.

`$legendTypeDisplay` is better but not there yet. Currently, I do not have a better suggestion yet.

Looking at the values  `"none", "normal", "small", "symbol"` I think "symbol" might be "pictogram"? Also not sure yet.

**Comment by Potherca** [comment]
Regarding 

> do you have a better name for `showStyle`?

and

> `$legendTypeDisplay` is better but not there yet.

Currently, I am oscilating between "shapeDescription" and "legendVerbosity" or something like that.

**Comment by kirchsth** [comment]
* I wouldn't use verbosity because normal and small displays the same information.
We could call it "(legend)Layout" or something like this.

* I don't like the current no color implementation too;
  1. text is long and not 100% clear
  2. the used colors
  but I have no better idea atm
  ![](https://www.plantuml.com/plantuml/png/FOn1IuT044VlVWfRElW7TI-TWi0mgOELKD5HHdVIXTrnsPab-lQj19rcUFpUwrWWIlAkkBAqkcImt4K2tseTuRlThEnfIOnnFKYGf5qFhuC3Efs6nJYxwFwccKxqyJng3omOCvhxR80bZ6qu-_V630uzahp3LYd_au-w51D6FgWATQd-NbMNrm8Rt_rFtfvUF-TnU1nU7gelS8oNeaCoEVeB)

PS.: I'm not sure if I implement the pictograms at all (only none, normal and small)
* without the pictogram I can implement it via the font size (0..none) and I'm finished
* and your argument that a pictograms is not so clear is correct
* Atm I have no preference, and therefore I think this will be the last of my 2.5.0 issues ;-)

**Comment by Potherca** [comment]
I think "legendLayout" is a good description. Lets go with that.

Skipping pictograms sounds like a good plan. Only having "none", "normal" and "small" is good enough.

As to "no-color", I have no clear solution. I guess an unsatisfactory solution is still better than no solution. :shrug:

**Comment by Potherca** [comment]
@kirchsth Do you want this to be part of v2.5 or should we bump it to v2.6?

**Comment by kirchsth** [comment]
please wait
