### ISSUE TITLE
How to hide/ modify box info text?

### ISSUE THREAD

**Issue by pascalbrunner** [plantuml-stdlib/C4-PlantUML#233]
Hi together,

if I have a system like:
System(test, "Hello")

How can I hide or modify "<<system>>" that is shown in the box?
Using ElementTags would enlarge it to something like "<<text>><<system>>"

Thank you for your help!

**Comment by kirchsth** [comment]
You can use `HIDE_STEREOTYPE()`
BR Helmut

**Comment by pascalbrunner** [comment]
> 

Thank you for the fast reply!

**Comment by Potherca** [comment]
@pascalbrunner: did @kirchsth's commnet resolve your issue? If so, I would like to clode this issue.
