### ISSUE TITLE
Is there an option to increase the space between connector lines?

### ISSUE THREAD

**Issue by jhueppauff** [plantuml-stdlib/C4-PlantUML#234]
Hi, 

I am facing a bit of a visibility issue with a quite complex diagram. 
Long story short, there are many connections between shapes in different boundaries resulting in multiple lines overlapping which is hard to understand the diagram 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/20532954/187673083-9ac78552-2961-4f6a-9d5b-1bdd2e5c3065.png">
 
If I use ```skinparam linetype ortho ``` it becomes a bit better readable, but still you can't really follow a line and some labels are overlapping with the connector lines.
![image](https://user-images.githubusercontent.com/20532954/187672937-f5021b3c-4edf-4639-876e-85e3fa156e41.png)

Is there any way to define the spacing between two connector lines?

**Comment by Potherca** [comment]
At first glance, this problem looks similar to that of #153 . The solution there was to use Lay_Distance:

```
Lay_Distance(from, to, ?distance)
```

@jhueppauff Could you try using `Lay_Distance` to see if that helps for your scenario?
