### ISSUE TITLE
spanish translation

### ISSUE THREAD

**Issue by rodverap** [plantuml-stdlib/C4-PlantUML#238]
It is posible to have a spanish translation of stereotipes names, person, enterprise, system, boundary, etc?

I have identified SetDefaultLegendEntries but I really dont know how to make changes

**Comment by kirchsth** [comment]
Hi @rodverap,

I would change the stereotypes itself. I would hide the stereotypes and show a translated legend
Another simple solution could be that you hide the stereotype (if you don't want to show a legend)

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

UpdateElementStyle("person",  $fontColor=$ELEMENT_FONT_COLOR, $bgColor=$PERSON_BG_COLOR, $borderColor=$PERSON_BORDER_COLOR, $legendText = "persona")
UpdateElementStyle("container", $fontColor=$ELEMENT_FONT_COLOR, $bgColor=$CONTAINER_BG_COLOR, $borderColor=$CONTAINER_BORDER_COLOR,$legendText = "contendor")
UpdateElementStyle("system", $fontColor=$ELEMENT_FONT_COLOR, $bgColor=$SYSTEM_BG_COLOR, $borderColor=$SYSTEM_BORDER_COLOR,$legendText = "sistema")

Person(personAlias, "Persona 1", "Descripción")
Container(containerAlias, "Contenedor 1", "Tecnología", "Opcional descripción")
System(systemAlias, "Sistema 1", "Opcional descripción")

Rel(personAlias, containerAlias, "Label", "Optional Technology")

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/bPB1Yjim54Nt_WhLPE61JCn0LuM1cJfgMd3iO3kKhenilpe2MJQIJ9kFwggVa1_hKvIu96r2kp7etNUlZYzwqOOfCtR2UyDbBSO6oCwOGRyBGyM-BLfkTcCrQb1rBmr8iwZxBXm4azRpg4qZU1L6RnytThHTns77j065ep921-CIr6Am-TvsQ9W1Ag33dDpi1GJ-04htqfyJClkAwr4lUlKyep5TqwGeFwJuYT8upUPaLhKdTKEpF4tAzwlVKgyQK5TocYrfDgq8Q44s1Nmtv9cShcN-mr-XwZCuSlqxLeJJrqy9pMwIJHkNS5TihkYcLpVez1uBxluBBV-I5tHzayl9Tw4qjvVQmhpDiRl0LVWgEDDpuhiX8qy-7fQWQyM7cXz-IdHCxo2OYZtRh0GIy6UTiu1Q8bDx-C7iCSKCJ1MakKpCZnK4hebpLkuGoTCzfvU1k4J_Wobc5GYNOLm6KksEM7kRa7zCFvSnNT5a6JnuBrWIlkvV)

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "Persona 1", "Descripción")
Container(containerAlias, "Contenedor 1", "Tecnología", "Opcional descripción")
System(systemAlias, "Sistema 1", "Opcional descripción")

Rel(personAlias, containerAlias, "Label", "Optional Technology")

HIDE_STEREOTYPE()
@enduml
``` 

![](https://www.plantuml.com/plantuml/png/bPBHQjim58Rl_HIQ2So5D6Qmgq6XdQEr1ISAjilebL6iiqGWIqQIsV9GkzeZzCLs53KPwPQotXXqZlvV7n--TfvRF_OgUITrfqO1PElzu3xbkUNVPnlfj-DwT60xepreF-jCdm-Awv2vT5uekSwBZvUhC7fOb7dFdGUBexR019SQx6m8_Sd38BW7gg37djhl56Jf0DOPdKu9cNp3wuLHnbvDQ4aNTDcqNnX-2bQoQaecwytpTaMhcYtRpxT_LiOAi2_Mh9hJwdX5mGQqQE279rVa-LcUNlmJgZk08zV_OnKulRbVqkeisV76ATmBjYXQ67k6pkrGSFycjFgnRkZYB5TSlmhbP7Wq24jMUtTPL7YZ97TJaiOX9nzIFCp1TLOEdNpwfJ5n_0-oezX3BAn0Wp0s9XleD39jddxoS6JOWQsAYDF6UgyWYoOENNL4nA9Naaa5wXJzBwQIhq753Xyxa6gxnzg5XlUalcDVsvBUqkKykqZkxkUqHO4LPStZYkBa6iMDlVeD)

I hope it helps, best regards
Helmut

**Comment by kirchsth** [comment]
Hi @rodverap,

was it useful for you? Can we close the issue?

BR Helmut

**Comment by rodverap** [comment]
Yes this is helpfull Thank you a lot
