### ISSUE TITLE
Please add the Robot shape

### ISSUE THREAD

**Issue by dgutson** [plantuml-stdlib/C4-PlantUML#244]
Please allow the Person() macro to specify the shape.

**Comment by Potherca** [comment]
Hi! I assume with "Robot" you mean an automated system that represents the User?

The reason for asking is that, looking at the C4 documentation, I can not find mention of the Robot _shape_.

It is currently already possible to change the _sprite_ for a user, using a parameter `$sprite="{name-of-sprite}"`:

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.4.0/C4_Container.puml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0/font-awesome-5/robot.puml

LAYOUT_WITH_LEGEND()

Person(user, "Robot", "Non-human User", $sprite="robot")

Container(container, "Some Container", "Technology", "Optional Description", $sprite="robot")
System(system, "Some System", "Also non-human", $sprite="robot")

Rel(user, container, "Label", "Technology")
Rel(system, container, "Label", "Other Technology")
@enduml
```

![](https://www.plantuml.com/plantuml/png/bKzRIyCm57xlhuZ3XmviApfV165Z6ohKRUo2-3JIzhW6qYJad3ZsxqqwEo_inQVaVEUxV6U8n2svHaONGfNILS1g8eFtMMRvFjq9gbtX46of5O6YjDHDPYHNGPCWLL8KsNYGB0AqUScpZvjqa5vxQ3ls2YuKsDJyqv-SuPMz_SuHVfkyUqQ2nWe2x69QZEy1TGF9NMPreUaO5-MZj_bclNrzNZzjy-dZT3Q9-r6q08jQnI7nYlMMWT_pdvdthrt35TluZKSkZq4FFTjIlF9qJbnsFozS-M1sMWMhDPIrqbBl3c6Q6n9QSSacWAKLxNJEVdL0WYR6zkbyZs2m6KdKJ7Kbp_PRWlmwwsU_d1SW_zJg1suNTPuzfnei-wKPWgfS8py1)

Would that suffice for your use-case?

**Comment by dgutson** [comment]
> Hi! I assume with "Robot" you mean an automated system that represents the User?

Yes, for example a user of an API, or automation.

> 
> The reason for asking is that, looking at the C4 documentation, I can not find mention of the Robot _shape_.

Oh yes there it is: https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#element-style
check the Robot shape.


> 
> It is currently already possible to change the _sprite_ for a user, using a parameter `$sprite="{name-of-sprite}"`:

I actually did that, imported the sprite, etc. But it would be much simpler if I could just name the sprite "robot" in the same sense I can with "person" and "person2".

> 
> ```wsd
> @startuml
> !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.4.0/C4_Container.puml
> !include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0/font-awesome-5/robot.puml
> 
> LAYOUT_WITH_LEGEND()
> 
> Person(user, "Robot", "Non-human User", $sprite="robot")
> 
> Container(container, "Some Container", "Technology", "Optional Description", $sprite="robot")
> System(system, "Some System", "Also non-human", $sprite="robot")
> 
> Rel(user, container, "Label", "Technology")
> Rel(system, container, "Label", "Other Technology")
> @enduml
> ```
> 
> ![](https://camo.githubusercontent.com/96a0b11c1eb9f88402a12b1eabf50e78a0e152d64142f75d6f9c076fc1cf8750/68747470733a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f706e672f624b7a524979436d3537786c68755a33586d7669417066563136355a366f684b52556f322d334a497a68573671594a6164335a7378717177456f5f696e51566156455578563655386e32737648614f4e47664e494c533167386546744d4d5276466a71396762745834366f66354f36596a4448445059484e475043574c4c384b734e594742304171555363705a766a716135767851336c733259754b73444a7971762d5375504d7a5f53754856666b79557151326e576532783639515a457931544746394e4d50726555614f352d4d5a6a5f62636c4e727a4e5a7a6a792d645a543351392d72367130386a516e49376e596c4d4d57545f70647664746872743335546c755a4b536b5a71344646546a496c4639714a626e73466f7a532d4d31734d574d68445049727162426c33633651366e39515353616357414b4c784e4a4556644c30575952367a6b62795a73326d364b644b4a374b62705f5052576c6d777773555f643153575f7a4a673173754e5450757a666e65692d774b505767665338707931)
> 
> Would that suffice for your use-case?

**Comment by simonbrowndotje** [comment]
> The reason for asking is that, looking at the C4 documentation, I can not find mention of the Robot shape.

Correct. A point many people miss is that C4 model does not prescribe any notation in terms of colours, shapes, etc. From https://c4model.com/#Notation

<img width="1167" alt="Screenshot 2022-10-21 at 09 02 15" src="https://user-images.githubusercontent.com/1009874/197145272-828b20db-07ae-4ff0-b3e1-2eaf418e4484.png">

> Oh yes there it is: https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#element-style
check the Robot shape.

The robot shape you're referring to is from the Structurizr tooling, which is my implementation of a tool that supports the C4 model. It also implements many other shapes too, but these aren't a part of the C4 model. C4 model != Structurizr.

![image](https://user-images.githubusercontent.com/1009874/197146033-16374eda-b99f-47c5-9a97-778342ad81c3.png)

**Comment by Potherca** [comment]
@simonbrowndotje Thank you for chiming in!

Adding other shapes was discussed in more detail in #145. As Simon mentioned, C4 model != Structurizr. 
We do not want to make this project a copy of Structuriz or add (too many) new shapes, otherwise we would have to make a very generic implementation and we lose the C4 relation and create a new "Meta" notation.

There is also the problem that there is no "Robot" equivalent shape in PlantUML, so we would need to fall back to using sprites anyway (which is already possible).

It would be possible to create a `Robot` and `Robot_Ext` method yourself, but I am not convinced that would be more productive than just using icons.

To give you an idea what such an implementation would look like:

```plantuml

!global $ROBOT_SHAPE = "actor"
!global $ROBOT_BG_COLOR = "#0D559C"
!global $ROBOT_BORDER_COLOR = "#0D559C"
!global $EXTERNAL_ROBOT_BG_COLOR = "#7E7E7E"
!global $EXTERNAL_ROBOT_BORDER_COLOR = "#7E7E7E"
!global $defaultRobotSprite = "robot"

AddElementTag('robot', $bgColor=$ROBOT_BG_COLOR, $borderColor=$ROBOT_BORDER_COLOR, $sprite=$defaultRobotSprite)
AddElementTag('external_robot', $bgColor=$EXTERNAL_ROBOT_BG_COLOR, $borderColor=$EXTERNAL_ROBOT_BORDER_COLOR, $sprite=$defaultRobotSprite)

UpdateElementStyle("robot", $ROBOT_BG_COLOR, $ELEMENT_FONT_COLOR, $ROBOT_BORDER_COLOR)
UpdateElementStyle("external_robot", $EXTERNAL_ROBOT_BG_COLOR, $ELEMENT_FONT_COLOR, $EXTERNAL_ROBOT_BORDER_COLOR)

!unquoted procedure Robot($alias, $label, $descr="", $sprite="", $tags="", $link="")
    !$sprite=$toElementArg($sprite, $tags, "ElementTagSprite", "robot")
    rectangle "$getRobot($label, $descr, $sprite)$getProps()" $toStereos("robot", $tags) as $alias $getLink($link)
!endprocedure

!unquoted procedure Robot_Ext($alias, $label, $descr="", $sprite="", $tags="", $link="")
    !$sprite=$toElementArg($sprite, $tags, "ElementTagSprite", "external_robot")
    rectangle "$getRobot($label, $descr, $sprite)$getProps()" $toStereos("external_robot", $tags) as $alias $getLink($link)
!endprocedure

!function $getRobot($label, $descr, $sprite)
    !if ($sprite == "") && ($defaultRobotSprite != "")
      !$sprite = $defaultRobotSprite
    !endif
    !if ($descr == "") && ($sprite == "")
      !return '=='+$label
    !endif
    !if ($descr == "") && ($sprite != "")
      !return $getSprite($sprite)+'\n=='+$label
    !endif
    !if ($descr != "") && ($sprite == "")
      !return '=='+$label+'\n\n '+$descr
    !endif
    !if ($descr != "") && ($sprite != "")
      !return $getSprite($sprite)+'\n=='+$label+'\n\n '+$descr
    !endif
!endfunction

!procedure LAYOUT_WITH_LEGEND()
    hide stereotype
    legend right
        |<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
        |<$PERSON_BG_COLOR> person |
        |<$ROBOT_BG_COLOR> robot |
        |<$SYSTEM_BG_COLOR> system |
        |<$CONTAINER_BG_COLOR> container |
        |<$COMPONENT_BG_COLOR> component |
        |<$EXTERNAL_PERSON_BG_COLOR> external person |
        |<$EXTERNAL_ROBOT_BG_COLOR> external robot |
        |<$EXTERNAL_SYSTEM_BG_COLOR> external system |
        |<$EXTERNAL_CONTAINER_BG_COLOR> external container |
        |<$EXTERNAL_COMPONENT_BG_COLOR> external component |
    endlegend
!endprocedure
```

![](https://www.plantuml.com/plantuml/png/nLPlRwCs67_Fft1OT8Ls2QVjgccdItMvb5qhqH0Hgksaav033a4pDZDcTvNkmy_6mGqnIvTfqjeN2VRlp_FyC4zuNtF8U5DYQrIG53SP0ZlEg_gjvp7uPPeNVDTicXgnb1AE29-cjFHuKy6C_UXL61B9dHHYTx8LY4bTiOAZsllpX-cRwMklNODVK4rBDBds6DrGFgtEjDCsDSzmiV4MRoOhkVJu4Enzn5Ao40nO4CIKlZNACTr03CPH-26Ca_NTVEM36R1XoYcpZxS_V4mMOH164l7TwzlhwvyN9YQCRlte5Cx_BVQZvJn81aH_ykN_CDXK7o9aQ0iRp2CPuhhDMUBQJ6tBccUPZr6928zXxboqonVVW_4cNr1CsUoeKRb3MOQOsZLRb0XrDsS3pkwn7_hA4ICG9wQnRlHq1HfsTYdMOvL1ZlRbhFaJHiu-5y4qNFt0V_2NSV9Bk8precdg3ihgFhM-sTv9enDjYav63VcZeHnbe68qHLd346XxTSOG5x0M0XXk41QV6QfJDhDj7Oxwpc5Ugs-u8B-BRwu5nDz89yZflgCvovtzgk89TVlvdgfqXT0-IgN3KCeXoJ42zZX7NDNMhqaNv4h4Yj6gTbmR2EEro0xHMjySvUe2M0FL7f2CGDJjjDMxrWYHJ2Tn8fx4__g_HgIFnN-VbPR-rw5j6vBoWXBmSXKgY68BkhR1R0P4GE3LA-0CJQ2Ht5OqGTGaC81LsgAsOljiemeuTD4QFMM6UCC8k9ZDBgvKyMVAZKmv5OWghiEvLnUVoJyp6PrVinJ_B5QkbCIPwkUty8Ad_EWEXpWdpyzKCFyKFiR9h_VnNHBu7_tbhQDyTqM6GDqUJVvKgLkAKIvq02lo7HSBwk_RkrIEzRTZHK_Y-pZmrPYxkRmCMihbvJklHTs0RmV4ySgFrk5IJz8RK25MKz83TGDROzgdemzPVrh7_iC1fduIfPTzq48Cv_dzqeyES6dtBd4CVLY5Ip7HUz2oeWIH8sizvOrUkiTvg2dZny5WwJQ7IBfVWwKR7wBf10QOHXG6MMTYaerm4CdKOJaUKTRWWRDMRKIEV24KCrPToMbxrvIGW4UnRBjxKFi3e4Vbdk5tXJnJvuJodUYc9w5cOXkjWBHN4hkaPB8pS7sdZgIjDBjpCbJqcwgZmnNmDIqHq5jI84RfZb1CyoTv5LQyeDBWLZx5HNjrADOlwq1P5tA-k1KXtCLog1Z8kIBsvRQA-czsZPpqzOi4fNiI_nwHh2dnNm00)

<details><summary><sup>Full PlantUML Diagram</sup></summary>

```plantuml
@startuml
!include https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0/font-awesome-5/robot.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.4.0/C4_Container.puml

!global $ROBOT_SHAPE = "actor"
!global $ROBOT_BG_COLOR = "#0D559C"
!global $ROBOT_BORDER_COLOR = "#0D559C"
!global $EXTERNAL_ROBOT_BG_COLOR = "#7E7E7E"
!global $EXTERNAL_ROBOT_BORDER_COLOR = "#7E7E7E"
!global $defaultRobotSprite = "robot"

AddElementTag('robot', $bgColor=$ROBOT_BG_COLOR, $borderColor=$ROBOT_BORDER_COLOR, $sprite=$defaultRobotSprite)
AddElementTag('external_robot', $bgColor=$EXTERNAL_ROBOT_BG_COLOR, $borderColor=$EXTERNAL_ROBOT_BORDER_COLOR, $sprite=$defaultRobotSprite)

UpdateElementStyle("robot", $ROBOT_BG_COLOR, $ELEMENT_FONT_COLOR, $ROBOT_BORDER_COLOR)
UpdateElementStyle("external_robot", $EXTERNAL_ROBOT_BG_COLOR, $ELEMENT_FONT_COLOR, $EXTERNAL_ROBOT_BORDER_COLOR)

!unquoted procedure Robot($alias, $label, $descr="", $sprite="", $tags="", $link="")
    !$sprite=$toElementArg($sprite, $tags, "ElementTagSprite", "robot")
    rectangle "$getRobot($label, $descr, $sprite)$getProps()" $toStereos("robot", $tags) as $alias $getLink($link)
!endprocedure

!unquoted procedure Robot_Ext($alias, $label, $descr="", $sprite="", $tags="", $link="")
    !$sprite=$toElementArg($sprite, $tags, "ElementTagSprite", "external_robot")
    rectangle "$getRobot($label, $descr, $sprite)$getProps()" $toStereos("external_robot", $tags) as $alias $getLink($link)
!endprocedure

!function $getRobot($label, $descr, $sprite)
    !if ($sprite == "") && ($defaultRobotSprite != "")
      !$sprite = $defaultRobotSprite
    !endif
    !if ($descr == "") && ($sprite == "")
      !return '=='+$label
    !endif
    !if ($descr == "") && ($sprite != "")
      !return $getSprite($sprite)+'\n=='+$label
    !endif
    !if ($descr != "") && ($sprite == "")
      !return '=='+$label+'\n\n '+$descr
    !endif
    !if ($descr != "") && ($sprite != "")
      !return $getSprite($sprite)+'\n=='+$label+'\n\n '+$descr
    !endif
!endfunction

!procedure LAYOUT_WITH_LEGEND()
    hide stereotype
    legend right
        |<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
        |<$PERSON_BG_COLOR> person |
        |<$ROBOT_BG_COLOR> robot |
        |<$SYSTEM_BG_COLOR> system |
        |<$CONTAINER_BG_COLOR> container |
        |<$COMPONENT_BG_COLOR> component |
        |<$EXTERNAL_PERSON_BG_COLOR> external person |
        |<$EXTERNAL_ROBOT_BG_COLOR> external robot |
        |<$EXTERNAL_SYSTEM_BG_COLOR> external system |
        |<$EXTERNAL_CONTAINER_BG_COLOR> external container |
        |<$EXTERNAL_COMPONENT_BG_COLOR> external component |
    endlegend
!endprocedure

LAYOUT_WITH_LEGEND()

Person(user, "Person", "Human User")
Person_Ext(external_user, "External Person", "Another Human User")
Robot(robot, "Robot", "Non-human User")
Robot_Ext(external_robot, "External Robot", "Another Non-human User")
Container(container, "Some Container", "Technology", "Optional Description")
Container_Ext(external_container, "Another Container", "Technology", "Optional Description")

Rel(robot, container, "Label")
Rel(user, container, "Label")
Rel(external_robot, external_container, "Label")
Rel(external_user, external_container, "Label")
@enduml
```
</detail>

and that's assuming I didn't forget anything (which I probably did).

Although I can understand that is not satisfactory, I'm afraid I'm going to have to close this issue as "Won't Fix"

**Comment by dgutson** [comment]
@Potherca ok I understand.

I solved this with this snippet:
```
!define FONTAWESOME5 https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/tupadr3/font-awesome-5
!include FONTAWESOME5/robot.puml
!include FONTAWESOME5/users.puml

'do this only if we're generating C4-puml:
!if (%function_exists("AddElementTag"))
AddElementTag("users", $sprite="users")
AddElementTag("robot_user", $sprite="robot")
AddElementTag("multi", $shadowing="true")
HIDE_STEREOTYPE()
!endif
```

Excuse my ignorance: what's the difference with your code above? Of course, in functional terms. What misses my implementation?

**Comment by Potherca** [comment]
> What misses my implementation?

That depends mostly on how much of the underlying functionality you use.

My example includes rudimentary support for a `Robot` and `Robot_Ext` method, so this can be done:

```plantuml
Robot(robot, "Robot", "Non-human User")
Robot_Ext(external_robot, "External Robot", "Another Non-human User")

Rel(robot, external_robot, "Label")
```
as well as various configuration options.

**Comment by kirchsth** [comment]
Hi @dgutson and @Potherca,

we could add the 2 robot sprites like the person sprites that it can be used like e.g. (external) systems/components.

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!include <tupadr3/font-awesome-5/robot.puml>

sprite $robot2 [48x48/16] {
000000000000000088888888888888880000000000000000
000000000000000AFFFFFFFFFFFFFFFFA000000000000000
00000000000000CFFFFFFFFFFFFFFFFFFC00000000000000
00000000000004EFFFFFFFFFFFFFFFFFFE40000000000000
0000000000000AFFFFFFFFFFFFFFFFFFFFA0000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000888FFFFFFFFFFFFFFFFFFFF88800000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000000888FFFFFFFFFFFFFFFFFFFF88800000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000004CFFFFFFFFFFFFFFFFFFC40000000000000
000000488888848CFFFFFFFFFFFFFFFFC848888884000000
00000CFFFFFFFFC888888888888888888CFFFFFFFFC00000
00008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000
0000CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0000CFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFC0000
00008FFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFF80000
00000CFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFC00000
000000488887578888888888888888888864688884000000
}

AddExternalSystemTag(humanoidRobot, $legendText="humanoid robot (external)", $sprite="robot")
AddSystemTag(cleanroomRobot, $legendText="cleanroom robot", $sprite="robot2")

Person(pA, "Person A", $sprite="person")
Person(pB, "Person B", $sprite="person2")

System_Ext(robA, "Roboter A", $tags="humanoidRobot")
System(robB, "Roboter B", $tags="cleanroomRobot")

SHOW_LEGEND()
@enduml
```
![](https://www.plantuml.com/plantuml/png/xTP1RzCm50VmUpv5g7P8fRKPm-kU44DBJGg70HCCSK2eSXlJHahio7Qq8CHtnqxeN69JvOAGfZxrKFcztpzEgrYvbee8LPT5y2HdwwBEQBXLgfBFurYG--acLzjwLKigrfmfojHqpSkuAWWpPY9LLkIh6AF9hLdwzFOcBebKLEYb9JQYKTFAfDlu5wgkI2QUnTzqVqBkgUGbdLp4WgzuD_mo26GbSaN3atRnFFo2e44GFvrz3Ny4Pxs2NlNxVP0iUfKS1dZX53u4KEg25Fc1ko5tKou07u3_203y0C0FzBGVwCyH3FzPX_znZneWtoEAV011MmWSWM7NsmVOjfsoFGjWCQZW0U1X0Ey0B0OM7C4H_2lm5mcF4PpXOG3RGs0O0EUOEGomSv1TNbo2fsPejd-G_Go29ClIHb71IF7nkrIql2ERQ5kNXF4y-s3UiKx3au9kAClkQAEkHhjUA4mpZEXlFHxfmUxbx6hKzaPZasvJrmKbJ71U-c8Vcbsk4tQkqu9RAYHdKPMSXgFkUvZiJrRjcfxS3SxjuDmTR3Ex_ItJHaNwGYQvtHuLNRGY6sblkcrfrI43vdjWRi6VzzfUvytxpykRz7NwxbKq3gufo-go-0K0)

BR Helmut

PS.: @dgutson: if you use `!include <tupadr3/font-awesome-5/robot.puml>` from the stdlib then no external url access is required

**Comment by kirchsth** [comment]
I changed the "robot" sprite, maybe it looks better

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

sprite $robot [48x48/16] {
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000005BFFFFFFFFFFFFFFFFFFFFFE9100000000000
0000000000AFFFFFFFFFFFFFFFFFFFFFFFFFE30000000000
0000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFE1000000000
000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000000000
000000004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFC000000000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFD000000000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000
000699405FFFFFFC427FFFFFFFFFC427FFFFFFE009982000
008FFF705FFFFFE10006FFFFFFFE00007FFFFFE00FFFF100
00CFFF705FFFFFA00001FFFFFFF900002FFFFFE00FFFF500
00DFFF705FFFFFB00002FFFFFFFA00003FFFFFE00FFFF500
00DFFF705FFFFFF4000AFFFFFFFF3000BFFFFFE00FFFF500
00DFFF705FFFFFFFA8DFFFFFFFFFFA8DFFFFFFE00FFFF500
00DFFF705FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00FFFF500
00DFFF705FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00FFFF500
00DFFF705FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00FFFF500
00DFFF705FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00FFFF500
00DFFF705FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE00FFFF500
00CFFF705FFFFFF87777777777777777CFFFFFE00FFFF500
008FFF705FFFFFF100000000000000009FFFFFE00FFFF100
000699405FFFFFF76666666666666666CFFFFFE009982000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000
000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE000000000
000000004FFFFFFFFFFFFFFFFFFFFFFFFFFFFFC000000000
000000000EFFFFFFFFFFFFFFFFFFFFFFFFFFFF7000000000
0000000005FFFFFFFFFFFFFFFFFFFFFFFFFFFD0000000000
00000000004CFFFFFFFFFFFFFFFFFFFFFFFF910000000000
000000000000011111111111111111111110000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
}


sprite $robot2 [48x48/16] {
000000000000000088888888888888880000000000000000
000000000000000AFFFFFFFFFFFFFFFFA000000000000000
00000000000000CFFFFFFFFFFFFFFFFFFC00000000000000
00000000000004EFFFFFFFFFFFFFFFFFFE40000000000000
0000000000000AFFFFFFFFFFFFFFFFFFFFA0000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000888FFFFFFFFFFFFFFFFFFFF88800000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000008FF8FFFFFFFFFFFFFFFFFFFF8FF80000000000
00000000000888FFFFFFFFFFFFFFFFFFFF88800000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000008FFFFFFFFFFFFFFFFFFFF80000000000000
00000000000004CFFFFFFFFFFFFFFFFFFC40000000000000
000000488888848CFFFFFFFFFFFFFFFFC848888884000000
00000CFFFFFFFFC888888888888888888CFFFFFFFFC00000
00008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000
0000CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0008FFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFF8000
0000CFFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFFC0000
00008FFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFF80000
00000CFFFFFF8FFFFFFFFFFFFFFFFFFFFFF8FFFFFFC00000
000000488887578888888888888888888864688884000000
000000000000000000000000000000000000000000000000
}

AddExternalSystemTag(humanoidRobot, $legendText="humanoid robot (external)", $sprite="robot")
AddSystemTag(cleanroomRobot, $legendText="cleanroom robot", $sprite="robot2")

' only that sprites are displayed in legend too
AddPersonTag(user, $legendText="user", $sprite="person")
AddPersonTag(admin, $legendText="admin", $sprite="person2")

Person(pA, "Person A", $sprite="person", $tags="user")
Person(pB, "Person B", $sprite="person2", $tags="admin")

System_Ext(robA, "Roboter A", $tags="humanoidRobot")
System(robB, "Roboter B", $tags="cleanroomRobot")

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/xTXFRzCm503mUpw5gIRHIkkoT6xZ88QMk2aS1ammn06XoMjC6ob_eiJHEY6-Et7SBLdicbO845NVgR7zUyzouiJgHS58pieuCfw5oJmg0mgMZ6N52zFCoTt98cJByhOiQ3vF4qOJTZ9FOpEBICBDi6115DwQ60wlUDEdjvTcJ0f6ywhf1dEnOYSPpzwaVydAZ0JvcVcjwX-IErgaCHsEpJozJSNWLuPHP7d8A3Yg6y4NY5OGcTRaA_XkdEuO1x07OEpDLE4xbXguiqtXdwc0FTiSlgK0CrqW6K0jm38OQy5qL-3_7fWu3dm068x4ShKk170SD180LGss06Bz9ksqGlXY5QqQu1Pm-HXh3Hn-CMg3SGscBU0rOzRwJ0zciFsCy2V2qm2H5l7hzeKUoB6V0BS1iZk1PO3Qm3hjXDC6blpmsPDEOEdX-nlxOUSzBSBN0Li6sZbDbMy-Y3UDTomPYB2KiHSVb0FuONIEKoFzUGfrGZy3nQVMrGEisYeQ07qP-506-c-_gm581T0_10Yf0K8A8DAhGLFa07PVLisDssi0LLiKgW14TK0a2OmU-je0DzrID7qDGBEj0Zq2l1t0DP0AQ0BzAN001x11ely0dEBj09Rsz2y0ajuQUe2bzv8zjf4Y9d0YlPTsF4-vGU2l6CqJ4dsyBnYDhycYlonZagHXy86ViOx1KKGND0ckwOgTznxwWFW_gq_NUj2h1eh3sNclxkiDUFOcwpoY9CdJD5QbVUmKUQLaeogRyHoaINGFs98m87eBG78AWh388d9F0n0cG6G5B4rv-IkQ5sd2ovS5pJj5ULExKbOF5lDk80dYCEd8kasczIo5x6VkCUY9ty2LXjQOaKMndiNWaNaDynGL6YVcK1KKItpZhrY_MYjUjbvXcWEt6VtadbPA80wy5l0QyFHsrNNUlFzyS-c_zjzD-mFZWYP16KS_0G00)

**Comment by Potherca** [comment]
Looks good to me. :+1:

**Comment by dgutson** [comment]
@Potherca @kirchsth you guys rock!
