### ISSUE TITLE
Question: stereotypes automatically showing up when hiding legend

### ISSUE THREAD

**Issue by dgutson** [plantuml-stdlib/C4-PlantUML#258]
This comes from https://github.com/structurizr/export/issues/29 specifically https://github.com/structurizr/export/issues/29#issuecomment-1305643465

Could you please confirm that the stereotypes are shown when not calling `SHOW_LEGEND()`, thus having to call `HIDE_STEREOTYPE()` ?
This is my understanding from https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_stereotype

Thanks!

**Comment by kirchsth** [comment]
if you mean

```plantuml
```

**Comment by dgutson** [comment]
Thanks!

**Comment by dgutson** [comment]
CC @simonbrowndotje
