### ISSUE TITLE
Update in plantuml-stdlib, request to tag version

### ISSUE THREAD

**Issue by Potherca** [plantuml-stdlib/C4-PlantUML#26]
Hi! I'm in the process of opening MRs in `plantuml-stdlib`. It looks like changes have been made since the `*.puml` files were last updated in plantuml-stdlib, but since there is no versioning available in this repo, it's not something I can easily automate.

Would it be possible to add git tags to this project?

**Comment by Potherca** [comment]
👋 This is the obligatory 6 months ping. Any chance this issue can get some love? ❤️

**Comment by IOrlandoni** [comment]
@Potherca Not sure if you're still interested, but I'm doing tags [over here](https://github.com/IOrlandoni/C4-PlantUML/tags).

**Comment by Potherca** [comment]
I am still interested. :grin: I'm not in any kind of hurry so I think I'm going to see if anything happens in #80 first.

**Comment by Potherca** [comment]
Closing this, since [v2.0.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.0.0) has been tagged.
