### ISSUE TITLE
Plantuml syntax error 

### ISSUE THREAD

**Issue by stocksund** [plantuml-stdlib/C4-PlantUML#263]
hey peeps,
i get a syntax error every time i use a component. Does anyone have an idea what this could be. Thanks a lot. 
Kind regards Stocksund
![image](https://user-images.githubusercontent.com/52630389/201954245-ce150a49-bfc7-4de2-b4af-9a0e4e924e75.png)

**Comment by kirchsth** [comment]
Can you add  the source?

**Comment by stocksund** [comment]
Sure 
![image](https://user-images.githubusercontent.com/52630389/201957702-a0e1dfbe-5ec1-4582-9f2a-9a4c3622f107.png)

**Comment by stocksund** [comment]
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()
ContainerDb(data, "Database", "Database", "measurement data are stored")
Container(single, "Single-Page-Application", "Javascript and Vue.js", "Provides users with all possible functions for analyzing the IT infrastructure via a web browser")
Container_Boundary(api, "API-Application"){
  Component_Ext(alias, "label", "technology", "description")

}

**Comment by stocksund** [comment]
Oh boy, thank you so much, this was my salvation

**Comment by kirchsth** [comment]
You are welcome
Helmut
