### ISSUE TITLE
Deployment diagrams support

### ISSUE THREAD

**Issue by bflorat** [plantuml-stdlib/C4-PlantUML#27]
As an infrastructure architect
I want to be apple to skin plantuml diagrams as C4 deployment diagrams
So that I'll get all my diagrams with the same look and feel

**Comment by kirchsth** [comment]
I added deployment (and dynamic) diagram support. Maybe it is useful for you https://github.com/kirchsth/C4-PlantUML

**Comment by bflorat** [comment]
Excellent ! I'll try it out against one of my UML deployment diagram ASAP. 
Thanks a lot, KUTGW !

**Comment by adrianvlupu** [comment]
This has been merged. Dynamic and deployment diagrams are now supported. Thanks @kirchsth
