### ISSUE TITLE
[v2.5.0] Question about `relative/absolute` path

### ISSUE THREAD

**Issue by The-Lum** [plantuml-stdlib/C4-PlantUML#271]
Here is a issue from:

- https://forum.plantuml.net/17086/cannot-open-url

Just by testing your first example on Online PlantUML servers, as:
```puml
@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml
```

See [output link here](https://www.planttext.com/?text=ZK_1Yi8m4BtdAsfF5RIvUFBaKhqfA-gU9Kq76vXCGcRAujyR2okAxBAdUVDuxysR5Oj9CdWiciLvW-21XDN4aSMXWw8NYRpKEfdl-kAa7zg18Tb0adMr3Lv7D7JtprawTArk5lFzdVhQRRKtB90oTMwompY2LCUiLMeFYGDLSHmVw0pFYd9hMi0oWyyeBf31OWrianktSgeU8PNzGM_M4zYU0eRBzO-WupNtyXMFux_NrG7mjV3lBHuHJtMcQWNKvUzl).

---

And on the same topic as your #248:
>- Update the !include paths to point to the new release URL
So users that include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.4.0/C4_Component.puml actually get related v2.4.0 files instead of files from master.

When include:

```puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
```

We observe that this line go noway...
https://github.com/plantuml-stdlib/C4-PlantUML/blob/d729c55c55218faff1a1329370d2655163e9468a/C4_Container.puml#L5

Perhaps change
```puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.5.0/C4_Context.puml
```
to:
```puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/release/2.5.0/C4_Context.puml
```

_Or fix with other change..._

Regards.

**Comment by The-Lum** [comment]
I think it's because the tag `v2.5.0` doesn't yet exist.
How to make the examples work while you building a new version.... ?

Thanks for your enhancement.

**Comment by kirchsth** [comment]
Sorry my fault, I merged the pull request #270 too fast therefore the not release v2.5.0 is referenced

@Potherca: Can you release the v2.5.0 that the branch is fixed, and updated the release text after that?
Or create the tag manually until you create the release that the "mixed master" branch is working again.

@The-Lum: how make the samples working: PlantUML server caches images if the source is not changed and therefore it does not detect the broken in the included C4_Component.

**Comment by kirchsth** [comment]
@Potherca: I create a pre-release that the build are working again. Can you please check/update the release notes,...?

@The-Lum: the master branch should work until the finale 2.5.0 release notes... are written

**Comment by The-Lum** [comment]
The [v2.5.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.5.0) tag creation fixes this issue.
Thanks @Potherca, @kirchsth.
