### ISSUE TITLE
Icons & font awesome 404 in exmaple code

### ISSUE THREAD

**Issue by TonyK-FmGroup** [plantuml-stdlib/C4-PlantUML#274]
In the readme, the following code is used ut both URLs return 404

```
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
```

**Comment by kirchsth** [comment]
it is only the root of all sprites/icons, the combination with the concrete sprite file it is working

```plantuml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
...
!include DEVICONS/angular.puml
```

https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/angular.puml

What is your concrete problem?

BR Helmut

**Comment by TonyK-FmGroup** [comment]
Thank you, sorry, it turns out that it's java on my PC that's refusing to access the URLs. Switching the VS Code plugin to use the PlantUML server instead and it's fine. 
Apologies for taking your time.
