### ISSUE TITLE
Update Rel_Back() are layout neutral with [norank]

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#277]
Hi all users,

I found that PlantUML offers relations \(arrow with '[norank'\) which does not influence the layout.

I think this would be a good option that we get better layouts if `Rel_Back()` calls uses `[norank]`.

E.g. if we have simple diagram with 3 components and layout like a L (down, right)
```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Customer")
Container(spa, "SPA")
Container(api, "API")

Rel(user, spa, "Uses")
Rel_R(spa, api, "Uses via message calls")

' uncomment produces b)
' Rel_Back(spa, api, "returns message response")

' uncomment produces c)
' [spa] <<-[norank]- [api] : "**returns message response (with norank)**"
@enduml
```
a) then it works without any back relation
![](https://www.plantuml.com/plantuml/png/TSonRi8m4CRnFKznpLA86h9qGWnGfagj554n8OICSo8MzjdodSlhrrOgr0wi_xlljsPHKPAprPCXRTE0C8e4NdPTLBV5nSYOpeanQa-290ljNHUieh9fMGPhpjtsjUrBsdz-T4wnOCpfjCqBPGZZ8XI_wZ6ofrd1Ng3U9XRlCDRpwluuuw3owQlV_Aigc5mt_NkkrGxjBp4zxnavzvnFksa_lPSEtqQ1GsPrGT3AMYx2CoJItZaaWH3za7J-FCzpByYRqjU_JaH9aVZEHEJWYV6Xf8jqoC8HLglsG3ugkXvRE6Jl24kec-QH2RERaH6coRnfwcgDD2HdVm00)

b) but with `current Rel_Back()` the layout is lost
![](https://www.plantuml.com/plantuml/png/TSonRi8m4CRnFKznpLA86h9qGWnGfagj554n8OICSo8MzjdodSlhrrOgr0wi_xlljsPHKPAprPCXRTE0C8e4NdPTLBV5nSYOpeanQa-290ljNHUieh9fMGPhpjtsjUrBsdz-T4wnOCpfjCqBPGZZ8XI_wZ6ofrd1Ng3U9XRlCDRpwluuuw3owQlV_Aigc5mt_NkkrGxjBp4zxnavzvnFksbVtgSEtqQ1GsPrGT3AMYx2CoJItZaaWH3za7J-F4_4czBNlqf4IP7uZaJau8dneQFdkH-oS8JLgZsGZugknnOEsJl24kgcUMJ2x6PaX6aoRvgwMYCDoTaV)

c) with new `[norank] Rel_Back()` implementation the layout would remain
![](https://www.plantuml.com/plantuml/png/TOmnRy8m44Rt_8fhbfAe8Kidn01bgjHA4HKJGiWu9x2mpvRlNFv-RQL2xS3wlk-z5OkAafojdWnfcqQ4YqZWHTz7TPkVZLpIAJ56xKcGPAwzwuDLL9oEPRJcr6zUkw6WtUT7xnGBneoEcsmeGnZdeVIh0IDxcfNO2zIRnE8TnhgfxiSP1vMdhs7zZwfWCbqFxvbMMxI_YUcyO-JCCpvk9t-w5mxVHe53PdL6qChQygoU8P7spY49XEZ7fFFpr6HU8czAN_zs8agAnFTCH0wU61-MT5Fjit-0vRBRau-AheSEzhbsW0NKRVke2BERaGjCIjEsTRL26fEpFm00) 

best regards
Helmut

**Comment by kirchsth** [comment]
Another sample of new "layout neutral" REL_BACK implementation

![](https://www.plantuml.com/plantuml/png/RP11QuCm583l_ehCorgPbQgdiaDP5JPmh6Y5ZJ6ArR2MQY99fDs_Nrum8raz-hqlx-6tvg9YOkXQv-v4wdPeC3eAqVDL4B3gilW-YUDm63XcDIK24x6eQHVqRKNWZSz5qvuEmIRsju3AropeAYumasY_eLrF2RpfOR_p_9Aa-sANvkdRxcERpkQEiyMCKpAxFY3ttPqxnOzysytuKduNImE40483H00Y0yG0OWcS7BVx4bQgDGF779MI0yuL3ZNEHvme76cSZ3XJEDOuW-LNzEX_4iegSlxovOKLSZsFu0iwLFKPbPxd_bT2MyadbCXMaWabjfKC55sFGZxQDiX8IE7d5IoM9Wqr3KqQQHgPDDRKo0gtw5HODPXAgmOJSSU1dVSUmUn9_g9ngHuOmqICYQL68OuFKrN5daEPFo6y5N9BY6w5n19YKp3Yhp5fXgxz1G00)

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

Person(x, "X")
System(s1, "S1")
System(s2, "S2")
System(s3, "S3")
System(s4, "S4")

Rel_U(x, s1, "uses U")
Rel_R(x, s2, "uses R")
Rel_D(x, s3, "uses D")
Rel_L(x, s4, "uses L")

x <-[norank]- s1: "**new back U**"
x <-[norank]- s2: "**new back R**"
x <-[norank]- s3: "**new back D**"
x <-[norank]- s4: "**new back L**"

Person(ox, "old X")
System(os1, "old S1")
System(os2, "old S2")
System(os3, "old S3")
System(os4, "old S4")

Rel_U(ox, os1, "uses U")
Rel_R(ox, os2, "uses R")
Rel_D(ox, os3, "uses D")
Rel_L(ox, os4, "uses L")

' Rel_Back(ox, os1, "current back U")
ox <-- os1: "**current back U**"
ox <-- os2: "**current back R**"
ox <-- os3: "**current back D**"
ox <-- os4: "**current back L**"
@enduml
```

**Comment by kirchsth** [comment]
@Potherca: I was too optimistic and thought that Rel_Back was only used as additional response message, but now I found samples which use this call without any Rel() call like [here](https://github.com/rithala/m365-plantuml/blob/43044c90734690c17484516fc88fa9f9d43db5e8/samples/C4%20usage%20-%20IoT%20Reference%20Architecture%20-%20Stateful%20stream%20processing.puml)

with orig implementation
![](https://www.plantuml.com/plantuml/png/ZLHDKniv4BtxLtJO0wRAna183dkACGH8aLtAOogr9qeUjMUqqSUir39nVlssviCsyL2LWrrIT-kzfwVk-HH8U8f63zvLNXH6WCUr2ifPE1yCZk6TihcE4g4agiAVauaNBwU5eZ8kOq2VEqjewJHtPl9T-RmCL4vcb-D7BImzVNsOu0_EIvGSV9vnCUzFgqJN0KUlVmExIdXyR1n8QhLyHM548FGTWL0MVKCnU2TnnLluclq6XUUeq69Ytd_yCExuEd2f0krBPiZ9p1dZR4rraBgyP-322r9lL7oEDa_9QLNrvZFoACpK2hqXbOSlRjbRThDc-NUnFpdz6JtEN30kN5_rLbnfj-HV_hqtU-yMM-Z1m_IVlvyMpmytdnVFy_lRkqKN-NQ_kEFmxSrVryEJmI3R148pbDn5EOOH75qtgoFEDO13vP9aJl4UU7N4ouo4bS9BoCxJzjuM7aE0oYbBi78UXDP0gD4W-Sq8Ob2sW6LKciRAGei4SnS9Gtt0yv9h4c_dqX3RnM8BrEc3RMXVpGW-mEA9Rt49ZyAJIYyM6dqWfAptG0wen9sMupdcgDO8ZGTZSkDSkoZ1O0YYm70CA-zCfva5xZN3S7l7BiXiMstmw1rxcUwULApFHy1d84DVto5rBJo-Nr-COFP7AY0lR60p32W2TjA10AbMA_JOs6e4ZG1FYrFubvrEbgQ1zLPeBc_oB84blkgbuOlm9YFdHT76cEiRnw0D9kwBqTdP6SoVQhyO2dBsBfeg0RQSKWMMl05daouHogLZqzEB7RR_CBmECMXJ1DjG8le8MSCegaflcDDK6d_0Vn6zmW1kZHv86VQA0quo33cDNX0dDV_3C5OSWejp5hG99o2i11Tfx5PZvoNwhi1PXD95Vm9rKuLVdb4mQ6g_lLUSjg6ahdwYdH_routWIvRklXtAOUwqJBlMLJutuyY-oRTeMRo6n-Wh5n0QNAT7C9-ER-TPxOHEZybEC3T8GG8yvdoN0C8Z__AIcrLoIVsrL8Jico3GxeNj2pIgBKYbA89AkRnkmQN6UiwMWl8IgbrZyXNcg7TVWEsuPsZbReQ1N5VQLVIDPplHV8bVZ_B9vol1DdN73pkaNl_auoZoie6lPuzFx_CU-lmswuwsHstVyBOZ-wQ80zKzhRFmgYZGDnysbbP5Qdp7i6TZ3tlle7hLtMtxVK3P26lXFg6LqUZ_0G00)

with new `layout neutral` implementation (includes my extended branch)
![](https://www.plantuml.com/plantuml/png/ZLHDKniv4BtxLtJO0wRAna183dkACGH8aLtAOogr9qeUjMUqqSUir39nVlssviCsyL2LWrrIT-kzfwVk-HH8U8f63zvLNXH6WCUr2ifPE1yCtYcRwoWHIg8g_3cPUF5oMYWgup86zBcpX9PESsSctvNFoq3bP7OvVjJ2qjFNXmd-uBn4oS7d6HVp_hHAPCVGGKUlVmEzIeXyS1n8QhLyHM948FGTXL0MVKt2yYMkU0jViz-Wy1mLMapC-uyVnXrV1ovLeC6UP8QSp9mnpjPK1wdBUmOkl23rHiNdQFEKd5PLRpuZZy9ChT0RKdduufQzPJThbdyN-vFJdz7Zp0NZmlLLRyMLTal-vTzxi_TkiOKUF4p_-VjfyVnmytdnFB-_lLjqaM_tYpiEtzxyTJqy6GooJI0qGybTb6COmT5riphYN0CuL2v9vXJlWLT7lCn8M2cyXEmyRUzjuJ44g9oo12ldGMWDX1eDaj-C80Pb2rX6fMciBBH8C7UHCDG7F2-v9l5sBWsnNImweAq-s8RsrOpW0ooU-1QNy2WygVHYeT47Gifw3-I0IjnfEPvZZcgDq7Wm9ZVEjOiI38OW2Wp7iFBET9fPu5up3BTtx8BCjjK6Zzwnb-dkISNwV0Hy1ZBqzHrIryBZ-_N526P_f0BomWOsmu0YO2ST291gjKAFZQr6q0Zmj3Y5VzdfP6aQMM-5vl8cpn9OugjU6hu8Rp9oNXHjZBc-SGpQOEA-69sTdS7ygVQBeI1dxwAf4c3BALLWoHjmDkaIeLmwDZszs67x3yFh48CsHT25QgAFa3MCeghqXZbDfV47_1VHAmpWrkY1b66lEE0amv3Jw0LnKlC_36F58RWuPq6RS0B2Id2HncurTbwYxmgSHIXTz2TGDrNuvHa5WwRsstl5QHjAwkedslbHlzm8lcJfxjkX7EPEoxHhNULpCuxictoBbiLhU8o-SW6XmNLw1FFf-7QUrKxez9Zi17E352J0Oyvt2I0yyYylkLabbzHVIqN8lWa2xLxOla2Zse9KYYAebClh5bnghETiAIWleTer9bzXZdht1TYEUuPMxcOOo7MbNKNVUBOJpPVuzIYVVBuIR5Dt_B13wlLFFeuYBnluUlRuz3xleSzli-veUzJs3Myxic-AE53TqpeBhue2VQWDPsbLfCPt37iszh3t3gfNsxjrtmUKZR0MxXDQ6Ot-7m00)

Should I 
- a) add a new call like or `Rel_Back_Neutral()`, (with the abbreviation) `Rel_BN()` or .... (I would have no better name  atm)
  -   a1) and add `Rel_B()` as abbreviation of `Rel_Back()`? 
- b) or add a new layout option?
- c) or ...?  

What do you think?

Thank you and BR
Helmut

**Comment by Potherca** [comment]
I think we should opt for a new layout option. It feels more like an option to the existing functions, rather than a new funtion.

**Comment by kirchsth** [comment]
@Potherca: Tried some ideas, but at the end I think a new layout option introduces only complexity.
My last remaining solution would be a new Rel_xxxx() call, but I don't want to introduce a new call atm therefore I closed it
BR Helmut 
PS.: If somebody requests it, we can reopen it
