### ISSUE TITLE
System() etc. with sprites, but no label

### ISSUE THREAD

**Issue by mtnpke** [plantuml-stdlib/C4-PlantUML#281]
Hi!

I think a nice feature to have would be to be able to declare systems, containers etc. that only contain a sprite and no label. This is useful for including a logo sprite that already has text in it, so having it as label text would be repetitive. Right now, if you write for example `System_Ext(Test, "", $sprite="img:test.png")`, you will get an extra blank line in the rectangle after the image, which is visually unpleasing.

**Comment by kirchsth** [comment]
@Potherca:  Thank you for the implementation.

I think it is complete I only would 
- add the check to the $getRel() call too - here we can have sprites with text too
```
  !if ($link != "")
    !$usedNewLine = ']]**\n**[[' + $link + ' '
    !$rel = $rel + '**[[' + $link + ' ' + $breakText($label, $usedNewLine) + ']]**'
  !else
    !$usedNewLine = '**\n**'
    !$rel = $rel + '**' + $breakText($label, $usedNewLine) + '**'
  !endif
```
- and maybe introduce a common `$getElementBase()` base call too  (maybe with a better name instead of Base)
```
!function $getElementBase($label, $techn, $descr, $sprite)
  !$element = ""                                                         ---------------- rename 
  !if ($sprite != "")
    !$element = $element + $getSprite($sprite) + '\n'
  !endif
  !if ($label != "")                                                       ----------------- I would use for all arguments the same check
    !$element = $element + '== ' + $breakLabel($label)
  !endif                                                                   ----------------- 
  !if ($techn != "")
    !$element = $element + '\n//<size:' + $TECHN_FONT_SIZE + '>[' + $breakTechn($techn, '-1') + ']</size>//'
  !endif
  !if ($descr != "")
    !$element = $element + '\n\n' + $descr
  !endif
  !return $element
!endfunction

!function $getComponent($label, $techn, $descr, $sprite)
  $getElementBase($label, $techn, $descr, $sprite)
!endfunction

!function $getContainer($label, $techn, $descr, $sprite)
  $getElementBase($label, $techn, $descr, $sprite)
!endfunction

!function $getPerson($label, $descr, $sprite)
  !if ($sprite == "") && ($defaultPersonSprite != "")
    !$sprite = $defaultPersonSprite
  !endif
  $getElementBase(.., $techn="", ...)
!endfunction

!function $getSystem($label, $descr, $sprite)
   $getElementBase(.., $techn="", ...)
!endfunction
```

- and update $getNode(), $getNode_L(), $getNode_R() with a common $getNodeBase() implementation (but with very low priority)

Please be aware that I didn't check anything. 

**And I think we should at least test if all arguments are empty that it is not "crashing".**

Thank you and best regards
Helmut

**Comment by kirchsth** [comment]
Hi @mtnpke,
I implemented it in https://github.com/plantuml-stdlib/C4-PlantUML/pull/285.
Can you please check it? 
Thank you and BR
Helmut

**Comment by mtnpke** [comment]
@kirchsth Yeah, it's working great :)
@Potherca Thanks, much obliged!
