### ISSUE TITLE
Layout not respecting Lay_

### ISSUE THREAD

**Issue by AshDevFr** [plantuml-stdlib/C4-PlantUML#283]
Hi,

I have been struggling to align vertically some Boundaries.

Here is the code of the test I am using:
```puml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Enterprise_Boundary(Ent, "Enterprise") {
    Boundary(B1, "B1", "") {
        Component(app_B11, "App B11")
        Component(app_B12, "App B12")
    }

    Boundary(B2, "B2", "") {
        Component(app_B21, "App B21")
        Component(app_B22, "App B22")
    }

    Boundary(B3, "B3", "") {
        Component(app_B31, "App B31")
        Component(app_B32, "App B32")
        Component(app_B33, "App B33")
        Component(app_B34, "App B34")
    }

    Boundary(B4, "B4", "") {
        Component(app_B41, "App B41")
        Component(app_B42, "App B42")
        Component(app_B43, "App B43")
        Component(app_B44, "App B44")
    }
}

Lay_D(B1, B2)
Lay_D(B2, B3)
Lay_D(B3, B4)

@enduml
```

The result for the code is this:
![domains-test](https://user-images.githubusercontent.com/7372540/210665475-411803f8-7d09-49b0-97a1-9a2b3885532c.png)

Since I'm using `Lay_D(B3, B4)` I would expect `B4` to be placed under `B3`

Here are my version info:
![version](https://user-images.githubusercontent.com/7372540/210665433-747b7176-3890-4a61-930d-13ea7b70e556.png)

Any idea of what I can do to enforce the top to bottom here?
This is a simple example but on my real graph it's making thinks difficult to read since everything is pushed to the right.

**Comment by kirchsth** [comment]
Hi @AshDevFr,

I would have only following workaround

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Enterprise_Boundary(Ent, "Enterprise") {
    Boundary(B1, "B1", "") {
        Component(app_B11, "App B11")
        Component(app_B12, "App B12")
    }

    Boundary(B2, "B2", "") {
        Component(app_B21, "App B21")
        Component(app_B22, "App B22")
    }

    Boundary(B3, "B3", "") {
        Component(app_B31, "App B31")
        Component(app_B32, "App B32")
        Component(app_B33, "App B33")
        Component(app_B34, "App B34")
    }

    Boundary(B4, "B4", "") {
        Component(app_B41, "App B41")
        Component(app_B42, "App B42")
        Component(app_B43, "App B43")
        Component(app_B44, "App B44")
    }
}

Lay_D(B1, B2)
Lay_D(B2, B3)
Lay_D(B3, B4)

' Lay_R(app_B11, app_B12)

' Lay_R(app_B21, app_B22)

Lay_R(app_B31, app_B32)
Lay_R(app_B32, app_B33)
Lay_R(app_B33, app_B34)

Lay_R(app_B41, app_B42)
Lay_R(app_B42, app_B43)
' 2 x 2 would be an option in this group again
' Lay_D(app_B41, app_B43)
Lay_R(app_B43, app_B44)
@enduml
```

 ![](https://www.plantuml.com/plantuml/png/XP9HQy8m58NV-okolip2j7XldlRagdjpC0PxBj4M3RH9Q1ESZFtt9QEvhe8re7ZF-NBF4RBghUYiQvlaGQfzuwgQ7Qqr_NEUT-AqE4XxT3lNrzrUArihkzZhDZUDKE7ElBTL8tVvci_VW_JvjirRqTkwyrAvrgtHAjmnON_oghnXEjdNPQ6TgaHtdddjYQKN9ytOTyBy8Q9OUg1OflwRp71e-qmOKnRBWBqOm_olDBj90L4mK3_9LHw4FBYN1vG74ta0HDtCmv27z_AGyd0Y3u4ecA2GA9oWE57yLlU05FnUTqxT-KHt3aJ118L4uGJ5YRfqz-stubnk_fvK0LcSm4z84_g9Pqdoo8BmSNbTmmEwjY1Q4An_1aO38Hlf47KSwnXrFbx4uo9EYuOnwfZvJi2-_EUaNLEnNSs4OjfOgHMJYjcZxDcXqyumSH1I3NzXSns0um2Ckc-qgbNbskON)

![](https://www.plantuml.com/plantuml/png/XP9HQ_em5CNV-odoxylVmhHuRvxsvEhsvc0CzboYBHfeaz0cE1dxxak6kQw2CQ1up_dbdYDaDLenMDTtsJ-fTfrhMdQmreoFPJc8us8lxS5jtTWEEwrig-nYf_lIT4A5E_FHDftSbci-VmlIn-kcxCLesy5BzLhtHgjmnuJzsOloXXdasDQLTgeHmsdcjGUMNvoyO5yPyuU8Qkc1QfdxRpB3eUqpOKnTBGFsP0ppl_BY9WL4mPdwpgxo0bB1lJoWF4Za0H1rCmz37jxBGyh3H1u2KP2Wa2XCK9meVgjxG2f-hpkdxZpHdGDHaA2GA4nGdAXBTzz-8qxry--Jgg284_W9QK8_yIBB_hCWl5zUr_a1NLiGBGZM7mEZWL1CT8WwJdMCEfykud4HXsAQpI4w61nWd_vprAvhsBPbGZ5jhDIAISNiGOviFsXdcDWBgSv_zofWseXZr7sZLQiQrtS_)

 BR Helmut

**Comment by AshDevFr** [comment]
Hi, 
thanks for the answer but as I mentioned this is just an example and my graph has way more things in it so the workaround won't really work for me.
It seems to be a bug whenever a `Boundary`/other has more than one line of items.

**Comment by Potherca** [comment]
I could be wrong but I thing this is similar to #229 in as far as this is somewhat beyond the control of C4-PlantUML. The instructions are given to PlantUML, which uses Graphviz to create the layout.

When given a (dummy version of) the actual diagram, we _might_ be able to offer advise that is sufficient, but generally speaking, because of how things work internally, the more nodes (or containers, or relationships) there are, the less control we have over the layout.
