### ISSUE TITLE
Extend System() and Person() with [.....] notation

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#287]
Related to #199 and #282

The C4 basic meta model has container, components and relations with `$techn` property (which is displayed as `[techn]`),
but no corresponding counterpart for systems and persons (they have only location).

But sometime is it useful to add a technology/type/category/characteristic/... as attribute/property to a system or person too.
For now this can be modeled/visualized via sprites (e.g. system with robot sprite), colors, tags, legend ...
And if this is possible why shouldn't systems and persons support a "[....]" notation too.

**$type=...** could be a good argument name
(1-already used by Node(); 2-Person and $techn doesn't match;  3-If system is used in an ARC42 business context diagram then $techn sounds wrong for me too)

@Potherca, @mtnpke, @wlfbck: or do you know a better name? As soon the argument name is defined I could finish the implementation.

A first prototype with $type is defined with following extensions:

- AddPersonTag(), AddExternalPersonTag(), AddSystemTag(), AddExternalSystemTag() is extended with $type as last argument.
- Person(), System(),... is extended with $type as last argument.
- cleanup of AddNodeTag() that it can use $type like in the Node() call itself.

```plantuml
@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="./.." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include %get_variable_value("RELATIVE_INCLUDE")/C4_Container.puml
!else
  !include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml
!endif

' e.g. during first discussions no sprites are available but the categories should be displayed in the UI
AddExternalPersonTag("anonymous_ext", $type="anonymous user")
AddPersonTag("customer", $type="aggregated user")
AddPersonTag("admin", $legendText="administration user", $type="administrator")
AddExternalSystemTag("git_repository", $type="web-based Git repository")

Person_Ext(anonymous_user_v1, "Bob", "simplified version during first discussions ($type defines the role), after discussion the $type can be replaced with concrete $sprite", $type="anonymous user")
Person(aggregated_user_v1, "Sam, Ivone", $tags="customer", $type="replaced with customer")
Person(administration_user_v1, "Bernd", $tags="admin")

System(system1, "System 1", $type="new developed system")

System_Ext(github, "GitHub", $tags="git_repository", $type="graphical web-based Git repository")
System_Ext(gitlab, "GitLab", $tags="git_repository")

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml

Person_Ext(anonymous_user_v2, "Bob 2", "Update with sprites", $sprite="osa_user_black_hat")
Person(aggregated_user_v2, "Sam, Ivone 2", $tags="customer", $sprite="osa_user_large_group")
Person(administration_user_v2, "Bernd 2", $tags="admin", $sprite="osa_user_audit,color=red")

HIDE_STEREOTYPE()
@enduml
```

![](https://www.plantuml.com/plantuml/png/ZLHXQ-D64FtkNp4nFUg0RN6cdmg6kpgcPqZRSB4B_IJ6sh6qt6fNpCuwyR_lo4igftNI-oJOcVVUphod_HG5MLBhHZz25VoHMC0AF5bf08snOeD7fwMsHM_0MK-0NAUMlC3ixklw_lDsy-UwtFo-kj_ThPVZUJ6VZq42f4ZWGeNEdKOtzW0VZiWMzuvAUhPHucJyR_3uTWHmOttbaY7uK9EK_s2Ew19TWnIhdyfLy8BM4y-xVf8RSf4kgHgHBlvS58nFyredI_iKYIj5aPUvpbPyirmrKHfbcpquzBBxxRwWPwqRCbSblB67aIwDvlKSJ6BhQpXOZWB6nYh5Q8EFu0F4ZgrG16G2FA9r_JomJmBI45GeL0UssX2Ra9o1FVKCdSCJ6R3-tBNRZ3uRizRxi4VtG1o3ts8z6QCF_jI657MfCfx23tBgQ3aSzowmxbNH5oYzdeIM-09Grqmr2fdh23IjzNsxevgysQhQCX_QA8nzIZ9mO1oAGVakx_zuYaBjcLVTA9cw4ArsdGRq4-rdUunau5ShC7GeqIXVgrIsoJ1-BruUFqvX_4lOAyyushPpzc2LuaZSk_6sIvEpAXWwM4_nl74EZcwdW0SX7dgp6xcxGjzxnQHMLMJoBrC5Np69zcJRtx4aZp4PDdynmoEsKzWSWyy4MCVb5TDUI-Vw9VLhVovNHEpDm9pDrSrcOoRn_EaRym5y73GzFO6X8xdGgN3k7A1dK_8VfcYrxalQ3pflcLqpTesjqC4xjhyMS9W5v1xV5j1htMHF8KHyIAtxZfTWnHWRwZTYYfUNOAR3-aXLOYidvAgnGfKafiNCAZOMBKOX7hqyE2zonIgqRV3voVXFSQVA1JgNo-_5Uf5Z3Oi-sBlEe53sF8Siwd7EcovJsJDgxx3wLZOexsHjyIfhiBYMjYlK3hccikQGklz9s-8bRPVSvywhn9YCbMaLNE0ba-aT_BAvMvUFs_NNzH_RlnxMazlH9_96D_Ot)

It can be tested with [my extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)

BR
Helmut

**Comment by mtnpke** [comment]
I agree `$techn` would be too limiting in the intended use, so another name is a good idea. `$type` has the downside of being extremely generic, though, so it might be easily misinterpreted 🤔 I had some other ideas (`$detail`, `$details`, `$category`) but I guess they aren't too convincing either. What about `$trait` maybe? In the end, I personally don't have any strong argument against `$type`.

On another note, I tested your extended branch, and it worked well for the use case that I have 👍 Thanks.
