### ISSUE TITLE
Missing relationship documentation

### ISSUE THREAD

**Issue by rcavaz** [plantuml-stdlib/C4-PlantUML#289]
There is no documentation describing the behavior of the `Rel_Back` and `Rel_Neighbor` relationships.

These relationships are shown as part of some of the examples but their behavior is unclear.

**Comment by kirchsth** [comment]
Hi @rcavaz,

- `Rel_Neighbor`:
  `neighbor` elements are logical on the same "level" and should not introduce an additional "level" between the elements.
  
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(c1, "Internet Banking") {
    Container(mobile_app, "Mobile App", "C#, Xamarin")

    Container(main_backend_api, "Main API App", "Java, Docker Container")
    Container(other1_backend_api, "Other1 API", "Java, Docker Container")
    Container(other2_backend_api, "Other2 API", "Java, Docker Container")

    ContainerDb(main_db, "Main DB", "MySql, Docker Container")
    ContainerDb(other1_db, "Other1 DB", "MySql, Docker Container")
    ContainerDb(other2_db, "Other2 DB", "MySql, Docker Container")
}

Rel(mobile_app, main_backend_api, "Uses")
Rel_Neighbor(main_backend_api, other1_backend_api, "Uses")
Rel_Neighbor(main_backend_api, other2_backend_api, "Uses")

Rel(main_backend_api, main_db, "Stores")
Rel(other1_backend_api, other1_db, "Stores")
Rel(other2_backend_api, other2_db, "Stores")

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/dP9TRx8m68RF-olwyfv8eXB9ZdRa1sPpySECcEsCjD18Oscxjcmno_xxMWqwIHSpEO4-tDS5DsMe3LAchXZuHtdEweB0qXYfxwD8eO_-bfgonhKcAXVS46xwkQWYoH1tJ4-RWb4SJUvwQpVQBEPHXRGXoewoYIKGvKJrfVE3T6_lLDbOrBn0Qj_91rqOpBXDSsBW6F4TvTiWX9y0skD4Tog1AICPajBc5uS574aPsDNaVnU-eWefoeCGj3bxoZ3ATuGNbgQEjYCuMiyQ_WczeovCXCseCnc4BPCm9L63bcjr63hRNqsnpnHVDLsg4dmiME2cLp8EtEK-VMDUleKthGfyAdER8lwXYAyglW1u9knYKpqRjT541w5BPaj2joKMllqyDhWTZVseOpt8-NEdHgZc8TwVupZxBHpxNgKL1kdZwYMRJn-cowGJWg5DrnNx1W00)

If you remove `_Neighbor` like in following sample you should see the difference.

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(c1, "Internet Banking") {
    Container(mobile_app, "Mobile App", "C#, Xamarin")

    Container(main_backend_api, "Main API App", "Java, Docker Container")
    Container(other1_backend_api, "Other1 API", "Java, Docker Container")
    Container(other2_backend_api, "Other2 API", "Java, Docker Container")

    ContainerDb(main_db, "Main DB", "MySql, Docker Container")
    ContainerDb(other1_db, "Other1 DB", "MySql, Docker Container")
    ContainerDb(other2_db, "Other2 DB", "MySql, Docker Container")
}

Rel(mobile_app, main_backend_api, "Uses")
' remove _Neighbor add level
Rel(main_backend_api, other1_backend_api, "Uses")
Rel(main_backend_api, other2_backend_api, "Uses")

Rel(main_backend_api, main_db, "Stores")
Rel(other1_backend_api, other1_db, "Stores")
Rel(other2_backend_api, other2_db, "Stores")

' add Lay_Neighbor that all dbs are on the same level again
' ups... this call is missing, but it can be simulated
' Lay_Neighbor(other2_backend_api, main_db)
Lay_Distance(other2_backend_api, main_db, 0)

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/dP7FRjD048VlVeeX76WanwOMft1f4rTGbBGLKGKtQzOUsQlk7xEx3eeGxywuIPickAt0bzMEVz-tExDdFg0BdLRH6sbArLK4JGYjdwQfmvz9BKFJYSwJAwq9P49IMfss2atFJ7oeb1Jf_CFafY_TBXUfHX_8SQcOCu7Ia4lQtX-jDln75pFRcGhTvgGyZM5qQJXjAC0CpPqqzMWCloBWxv4-qLP8HGMsBUUNzniuRziHx-PlO_YE6fqqet5qpF5I22plo5HCovxc4fpVN3xmNt2DCUIMCsvFikhGP4D3xlJ8TNrVx6t_Qig6JDchfaDLBhODLkAXhtpMuylDweSQue_nNLSis3VpNuhiYI9xLV4xYhwIEdZKWOUwzUGv_0uSQRicAAv8resm3h2gGD6Qr5Rp5xhhQaZt4f4D4yyW-yclWdMFxg6pTxLdmjdWLGx3F8M-wGLkzbC83GP0fQ0I7j0HM0FCWaTDs_40rYWDirthaoI1wSV9U1fpI7eeUv9NBRsNfev1T05auBe1mHAfEuM1AgQVdZfuvTqenb6VpAKFQ4fwAHd3U-vfzVdwMx6u-7HnbP-CepCETLhz0G00)

- `Rel_Back`:
  back relationships model a logical response back from a target to the source,
  e.g. like an observer pattern

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' only that it is more visible
AddRelTag("back (after register)", $textColor = $ARROW_COLOR, $lineColor = $ARROW_COLOR, $lineStyle = DashedLine())

System_Boundary(c1, "Earth Weather") {
    Container(backend_api, "Meteorological Station API", "Java, Docker Container")
    Container(mobile_app2, "Mobile Weather App2", "C#, Xamarin")
    Container(mobile_app, "Mobile Weather App", "C#, Xamarin")
    ContainerDb(weather_archive, "Weather Archive", "MySql, Docker Container")
}

Rel(mobile_app, backend_api, "register")
Rel_Back(mobile_app, backend_api, "send weather data update", $tags="back (after register)")

' based on Rel_Back the logic is known that mobile_app2 initiated the connection
' Rel(mobile_app2, backend_api, "register")
Rel_Back(mobile_app2, backend_api, "send weather data update", $tags="back (after register)")

' with Rel() it would create a complete different logic/layout 
Rel(backend_api, weather_archive, "send weather data update", $descr = "but weather_archive is not specified via register call,\nits specified via e.g. config in backend_api")

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/hPFjQnfF4CVVtrynl_i5UWT6QUYhGY16GnymJT2Mz4L1vcx7koLxkzVTEQsK_k-TrIfHKakX8hZEmsU_yx1NWT5prvZaFsrBqoc2chaDhmS3Zwj-fRdkYYwGBvrbijmlNJDe3TgOSnvO6LqCHg_ExwFfq-raq61WycAQZoG3jINVRoC_UG7EcZLmZGnQlW4QvmcMEkZ2K39KQahc8rPPMc3v21ak10IUAXs9UTg3CwPlF7B6URY4i-5qUlSm7zrDxgRYCjhI2TUCruR4DSPGavg89Slp99cjXTtChrrd5VfrLhxiGNg3dcju8EIQV9h3zmJaioydY_B8gZcsMg9lYSbvkRdI9HgOCR9s5eRtxrBnliSbzc3i9CFl4G8zGZQkq8Q4s5v4vERVJW4CnHfPe_zxy1aRzDgU03oR_uVqSP6jji5pz6MjboJn-_Ij9OtWzUohURQS7qaYqpkGSTYctHmbLWBdr-8y4Hta2ByaWK96w5hveSqIO1KkVxCZkQoPe08fS1Ps5u5WO3EWk7MFrgtiTWsVj1sqrQoHIMsYPTqjbN6I0ZoixEBlIhlufxMjDDSRFJbeXfNhZ8BI2um0HNJJ6fAZqei5URAyhNfWSEqwXYZlS7kFftvQdQ9GnlUL5XqVfyREMiSGMYhrGfE2fSQzUYZHcDuNgpaSHL2_wiTkBtG5sZvjLInuzbRUyUJcpSs7SPOdL-Bf6lCJ)

I hope it helps

BR Helmut
