### ISSUE TITLE
How DDD and C4 together in PlantUML

### ISSUE THREAD

**Issue by phpmaple** [plantuml-stdlib/C4-PlantUML#290]

**Comment by Potherca** [comment]
Hi! I would like to help you, but I am niot sure I understand what you are looking for...

- Do you already have a Domain mapped out and are you looking to create diagrams? (System Context Diagram, Bounded Context Map, Business Use Case Diagrams, Domain Concept Diagrams, etc)
- Do you already have diagrams and are you looking to create those in C4-PlantUML?
- Do you have C4 diagrams (created elsewhere) and are you trying to (re)create them in PlantUML?

Or something completely different? Could you provide more information about what you are trying to accomplish?
