### ISSUE TITLE
No documentation on how to change font size of each elements individually (e.g. technology, relationship text)

### ISSUE THREAD

**Issue by ProtoSlayer** [plantuml-stdlib/C4-PlantUML#291]
Hello,
I cannot find any documentation or functionality on how to change the font size for relationships or any element individually.
When using "skinparam DefaultFontSize 20" the text of the relationship and technology is not effected.

**Comment by Potherca** [comment]
Hello! Thank you for reporting this. We do indeed seem to be lacking documentation in regards to fonts.
I'll see what can be done.

**Comment by kirchsth** [comment]
Hi @ProtoSlayer,

I created a PR #295 that you can define themes and change the technology and relationship text size too (like in the https://github.com/kirchsth/C4-PlantUML/blob/extended/themes/puml-theme-C4_FirstTest.puml).

If you set $TECHN_FONT_SIZE or $ARROW_FONT_SIZE before the "normal" C4_* files are loaded you can overwrite the size. Can you please see/check it there if it works for you.

Thank you and best regards
Helmut

**Comment by kirchsth** [comment]
Hi @ProtoSlayer,

the PR #295 is merged into master. Now you can use and define your theme  (e.g. with your noted `skinparam DefaultFontSize 20`).  Additional I extracted all internal used constants that you can overwrite them as part of your themes file or before you include the C4_* files (a complete list of all values see [here](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/Themes.md#write-custom-themes)).

```plantuml
@startuml
' !theme C4_united from https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/themes

' could be moved into an e.g. theme file
skinparam DefaultFontSize 20
!$STEREOTYPE_FONT_SIZE = 30
!$PERSON_BG_COLOR = red

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")

SHOW_LEGEND(false)
@enduml
```
![](https://www.plantuml.com/plantuml/png/hL9TRzD047o_Nx49I2HIQrFe4n9IKzTDaTBOYbqgUB4kzgOvSH-dkpLHGVntzaXf-G7uPUMTsPsTqLr4ae56eyKRcD0U3K9nterM4Gwm2yx0diZ73taUv25xKBGVjsF4q3jBQ2dhdSczbZQjE8qqQBNDY_FJEhNkRbUvaP4mv7ysHy4YlHlr05i4uxwpXBBaG5h0x263e_vEQHJncx9U1cdW2dTor7JDWetwWV3khPYyRjfoKrRjbxhihgjrspMVlfRm4Tudh2utJRNkBfTTKQsg3RS33a9CbEtrEE3_CSGX5JmXbSMG-PIVg354PsToCCgUm7IHgeeK9BamdOlcaGTDT-b6EyZmEElFcDH8upN24PlEuQS0_futpmwuxQJtpBp7BIoyrwgNf9oTSgjuTGABfixMPSiZWQF9pk3sSv6mXTRk424vYq0Es9QNJ34SfKgIxK4H6m5I1ZLhHJxnrzEHCpg2lEU9ng3OeFvhxkMikyYJN6_QjcwObKZFwCkQ9LBaNqmblQf_HqHpKzrtgt9PhgzcEwaZpiK5se53_Gq0)

BR Helmut
