### ISSUE TITLE
Element specific tag functions (AddContainerTag, AddComponentTag etc.) are updating bgColor and fontColor globally

### ISSUE THREAD

**Issue by dannief** [plantuml-stdlib/C4-PlantUML#300]
I think this bug was introduced with this commit: https://github.com/plantuml-stdlib/C4-PlantUML/pull/251

Essentially the expectation is that AddContainerTag will use the default styling of the container element. This worked in v2.4.0. 

See below example output for v2.4.0 and current version (2.5.0)

**v2.4.0**

```plantuml
@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.4.0/C4_Container.puml

AddContainerTag(my_custom_tag_1, $bgColor=lightyellow, $fontColor=darkgreen, $legendText="This should have new styles")

AddContainerTag(my_custom_tag_2, $legendText="This should have default styles")

Container(regularContainer, Regular Container)

Container(taggedContainer1, Tagged Container With New Styles, $tags=my_custom_tag_1)

Container(taggedContainer2, Tagged Container With DefaultStyles, $tags=my_custom_tag_2)

SHOW_LEGEND()
@enduml
```

![v2.4.0](https://www.plantuml.com/plantuml/png/XP31QW8n54NtVaKgNIZeJ3kuAWWMbNPXRQbJN0vnyan2toIIl6Zz-qO7GbkeBdF8FJSt4q_SKMYmSwDDZK40Oufevn_otF539ZMfi0aUN6qDWQ6ijas-GsvEeQ4dWNgJJqV3jnFwU5da-o8RPNSHLTEOuDg0otQdWiwZ40cLNFQQOrK7JxQfYClgVi1kDt9gqRenQgde28Zs4EasXbekkFkK3i14YY31Y1A-QDmjbVRCAnjGCCNtm0mScASZWk_shnKNrsG2jZmW_H0cMy-13CXT0WFstXAMqA_xiL22IESukZmJbX1RQr9i6GUipdtnTJ7antz-wvAr-CywQvTS4XTHl7f-NLUB-TDyEUlrEnCm8ZJu3G00)

**v2.5.0**

```plantuml
@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddContainerTag(my_custom_tag_1, $bgColor=lightyellow, $fontColor=darkgreen, $legendText="This should have new styles")

AddContainerTag(my_custom_tag_2, $legendText="This should have default styles")

Container(regularContainer, Regular Container)

Container(taggedContainer1, Tagged Container With New Styles, $tags=my_custom_tag_1)

Container(taggedContainer2, Tagged Container With DefaultStyles, $tags=my_custom_tag_2)

SHOW_LEGEND()
@enduml
```

![v2.5.0](https://www.plantuml.com/plantuml/png/XP1DQm8n48Rl_efKUb1GbqfF1S6YqXwiBNMBnoLknYHqaaWogVNVTrJOVa3rc8TvdpSpuqGoKdROkhA-ngn024EqJNT54ULke2sPlCu9OXqyWQT17LonHUaFeNuYXNPTJ6xxBmVqzZGld4m4aL4ruOIq7k9WUoXetIlLe5BgZjjNTKuKN4LILpSzSRtMau0XZj1gGtj033kc6mwTk9BnNKS0pnH1WrSbVDAeNHgRH38Xen96Ve3mi1E9zWYftRrKFBmaKx2H6Uc7iB5r8kYCCZQW9rvFH3JerpmNQb3DcvSkZ-HxNApuv6B12ooFVVmx3gNHdskTimx_iqvFcvmJ3rcyV7nULVFPmsmnxNHRO_0gE_m2)

**Comment by kirchsth** [comment]
Hi @dannief,

thank you for the finding. I hope it is fixed with my PR #301. 
Can you please test it with my [extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)

Thank you
Helmut

**Comment by dannief** [comment]
This is fixed. Thanks.

Ques. When will v2.6.0 be released?

**Comment by kirchsth** [comment]
@dannief: [v2.6.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.6.0) is released ;-)
