### ISSUE TITLE
Include / link to mweagle/C4-PlantUML-Themes

### ISSUE THREAD

**Issue by Potherca** [plantuml-stdlib/C4-PlantUML#303]
As mentioned by @mweagle in https://github.com/plantuml-stdlib/C4-PlantUML/issues/295#issuecomment-1511620596, we might want to add / link to the themes there.

> Thanks for adding theme support! I've published a handful of themes based on ColorBrewer and Seaborn palettes to [https://github.com/mweagle/C4-PlantUML-Themes](https://github.com/mweagle/C4-PlantUML-Themes) if you're interested in including/linking. Thanks again.

**Comment by kirchsth** [comment]
@mweagle themes can be used with a `!theme` line like below.

```plantuml
@startuml

!theme cb_seq_OrRd_9 from https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")
Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml
```

![](https://www.plantuml.com/plantuml/png/ZS_DJiCm30VmUvyYwwb8jBbmWTFGE0vj6kDSfQbf8paVsAwclJrf9GO8WNQo4ya__xrcCIIJns8b8tXGjciPtjiT7VhsNhrHz6eKIVoWDPbJCpWPfsvY81k3G936Hg_z2So0e3TtzHvDaDVdRNsSETRUkA2JGH01BegL2nQd7gv0KvRcP3LBZwxxZcUL1IX_jPiyaLS0DMc-OW_4CLHfAO_e3D-gSciwm38tkoGk1eFg2TYIMrxbJN4nAllP_HezWXr3n3YS_u5UpYpWArxAjTiFW3_pNaByBNoboS0QGfzl_m00)

A list of all possible themes [see](https://github.com/mweagle/C4-PlantUML-Themes).
The corresponding theme name is without `puml-theme-` and `.puml` (e.g. file `puml-theme-cb_seq_Blues_9.puml` corresponds to theme `cb_seq_Blues_9`)

**Comment by kirchsth** [comment]
@mweagle:  The next PlantUML v1.2023.8 supports calculated themes and stdlib themes (details see [forum](https://forum.plantuml.net/17811)). I will update our docu. Maybe you want to use the feature via the already existing [PlantUML v1.2023.8 beta](https://github.com/plantuml/plantuml/releases).

[![](http://www.plantuml.com/plantuml/svg/hL9XQy8m4FsUNn7BPFM3oUOA0zd4qScGEJTake-IjZSDfAbBBlhtrzgfPLJ6eD-ETtVllNlSqA8mw595MXUHi30tYjvJRusuiNtEZTYnbSIrYvm54sSQGIEBivHlbD35NjTYecJ4mw3xLa3pbmbFXKKm7Y6NzEDrzZoUFlMfrB5o2L0HsKmv14fQ1wW9COvhIC7oJJ6rhxjXi7HQ8YIi06lDb7IK-WQ-d3HWwPPUizvLxuRTTau6xyBWJ_v1hK0iLEoKo8UeVyYNCLRXFg3_Es0_G7TvMAT0FqsMabRPEQxkqIOJFcUZt2lbwbrKOXoSOQdcLPup6qqUtiUBqN8y3IVpnr5pprdliRq2N6w5aI9Ia1VAWU_zDk5rZc5KVoIN-Nc5C5Y0iJBJVeUqjyTo23h9-zy0)](http://www.plantuml.com/plantuml/uml/hL9XQy8m4FsUNn7BPFM3oUOA0zd4qScGEJTake-IjZSDfAbBBlhtrzgfPLJ6eD-ETtVllNlSqA8mw595MXUHi30tYjvJRusuiNtEZTYnbSIrYvm54sSQGIEBivHlbD35NjTYecJ4mw3xLa3pbmbFXKKm7Y6NzEDrzZoUFlMfrB5o2L0HsKmv14fQ1wW9COvhIC7oJJ6rhxjXi7HQ8YIi06lDb7IK-WQ-d3HWwPPUizvLxuRTTau6xyBWJ_v1hK0iLEoKo8UeVyYNCLRXFg3_Es0_G7TvMAT0FqsMabRPEQxkqIOJFcUZt2lbwbrKOXoSOQdcLPup6qqUtiUBqN8y3IVpnr5pprdliRq2N6w5aI9Ia1VAWU_zDk5rZc5KVoIN-Nc5C5Y0iJBJVeUqjyTo23h9-zy0)
