### ISSUE TITLE
Themes not working locally

### ISSUE THREAD

**Issue by MaheshvaranP** [plantuml-stdlib/C4-PlantUML#306]
Hi

I might be missing something, please help me figure out what might be wrong about how I am using themes?
Here is a view of the code and output.

Thanks!

![image](https://github.com/plantuml-stdlib/C4-PlantUML/assets/52629973/857344a1-6375-41a6-96c2-1b67cd8fcabd)

**Comment by kirchsth** [comment]
opened in [plantuml-forum](https://forum.plantuml.net/17811/theme-supports-no-calculated-from-path-and-stdlib-from-path) an issue that "!theme via stdlib" `!theme C4_united from <C4/theme>` and "calculated !theme" `!theme C4_united from $baseUrl/themes` should be fixed.
