### ISSUE TITLE
Can autonumber be supported?

### ISSUE THREAD

**Issue by gc-robotics** [plantuml-stdlib/C4-PlantUML#31]
Hi Ricardo,

Can autonumber be supported? A bit like in Sequences.

Thanks.

**Comment by adrianvlupu** [comment]
I can't find autonumber support in anything other than a sequence diagram. Although this would be nice to have, I don't think it can be done. 

If it was supported, you would just add `autonumber` before any `Rel(a, b, "label")` group and it would already work.

**Comment by kirchsth** [comment]
I added dynamic diagram support with Interact(). This is basically Rel() with automatically numbering, 
Maybe it is useful for you https://github.com/kirchsth/C4-PlantUML.
I think https://github.com/kirchsth/C4-PlantUML/blob/master/samples/C4_Dynamic%20Diagram%20Sample%20-%20message%20bus.puml covers all possible scenarios. 
I plan to integrate it as part of the open pull request #27  (as soon my other open changes are in too)

**Comment by n-alex-white** [comment]
That looks really useful - I look forward to seeing it get into the master!

**Comment by adrianvlupu** [comment]
This has been merged. Dynamic and deployment diagrams are now supported. Thanks @kirchsth
