### ISSUE TITLE
Adjust thickness of element border

### ISSUE THREAD

**Issue by qtzar** [plantuml-stdlib/C4-PlantUML#315]
I would like to be able to adjust the thickness of the element border on diagrams.

**Comment by kirchsth** [comment]
Hi @qtzar,

I couldn't test all shapes, but I could try to support it like the Rel() implementation via tags. (details see #254)

```plantuml
@startuml
!include <C4/C4_Component.puml>

' SHOW_PERSON_PORTRAIT() ' not working??
' skinparam actorBorderThickness 15.0  ' not working??
' skinparam actorBorderStyle 15.0  ' not working??

SHOW_PERSON_OUTLINE()
skinparam personBorderThickness 15.0
skinparam personBorderStyle dashed

skinparam rectangleBorderThickness 5.0
skinparam rectangleBorderStyle dashed

Person(P,"Person")
Component(C,"Component","techn")


AddRelTag(special, $textColor="$ARROW_FONT_COLOR", $lineColor="$ARROW_COLOR", $lineStyle=DashedLine(), $lineThickness=5)
Rel(P,C,"uses",$tags=special)

SHOW_LEGEND()
@enduml
```

![](https://www.plantuml.com/plantuml/png/ZL9HQy8m67pFhyY2O0l5RQ1lwzJLRXDAKsB77ajeFcen9YM9RFltovnqAWfx-pxklhlBaPbrtBZTLgARLjLo9m0_9EFRP5mbUjjf1SgDEWy_8ZJ4grVwNXKfMz6yAYWhsNnP1Y4UOgKT_j1cqwfcElL4wwUE6xx5l7RQF6aZm9Jhjjuei1RVJqPt-BzdA_SbuSe9Eav4tyficQT1YFvqEZ1Mgql-bqYzc-1s3G8TSGpKZgj6mhcMbxf6ErShzZv14P7VYOIeBpb88j8l928EwlKF0Q6v40naoPl0Tb2tN4PuuE3J9Lfg4vF1d37VmJFDoogX6MN4ux9LS8AVGljOyM8VA_Dx41w0_bdn94JUrMVrkNOMB8a6ZZSsFcG83zLdwKkQBtpbCr32VvDl)

BR Helmut

**Comment by kirchsth** [comment]
If possible AddBoundaryTag() and UpdateBoundaryStyle() should be extended too

**Comment by kirchsth** [comment]
Atm border thickness cannot be changed per component. Opened a question in [forum](https://forum.plantuml.net/18148)

**Comment by kirchsth** [comment]
Hi @qtzar,

I have a first version: the border style and thickness of all elements and boundaries can be defined via tags.
Can you please check it via in my [extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended).
Does it match your expectations?

[![](http://www.plantuml.com/plantuml/svg/dPDXQzi-4CRV-rDSHKjjI9D_uLy6Wq0Jnzi2QHAST7jf5EiQYyYIaUIsOUoxJufZPoqfZBsCdhldxlbTV6yirROkHN0DkPBFg2rm2o_S5a0PuvOhIOMJof9A1e9B1AgtTOdImiqaJMQZzVHxaatdyUnnaWn9Vz3l4x0AQeCWL4w5s0SN_0ckdgdcT2CmmrTkh0d9-sOI1G0NNEQYPWXNMxHPr_DCHOtdMWRn_rcioaf9bBPV-IGNA0p-QLLOMvdFWu6cB_sjIrPlt7BQnRM-nsKRxBZE2sCBvtQp55JQnuVP05-Tpf2T7I4PVmeSjCfNkoSmbWi1KZbuIk-ut89JLzyMFx9baguMysovIDVfQBeE8wyOLr9HJKkWkLLwh3H3lIvulfDe3DpUzV-33-jMTYyG63K5CWY2nufHYub0VnMlEL8LQgCawS7bvj0IAw7qa6XatLjZCnmhmMPSOXX5PvtoDlhVc4tyJaUxJkfY3ScTEt8mOcnvM6zDjo6XhEJoNtokGQD1stBOq7m7Le5HWZC_exkP6zF4U3zbvKe_7d8RjMXNUsEn7AjQCght3PTp3C_xV78-RMyuxW5fVv08VWO03OjmsMkF5fqUHvE7wTorZ5f8bcxDi67cwdu5GRDRrWrOkUhcxMZVOGZZ7ebFnoGMy-BawVbuGqykHU6PcGfpJeMlm5TxFFhbA4tTd_hBOhxEuiLiaNe7uRA_rTz8Ps_gXHEakoXmKnq4jsHjq91UizPn1uVmy2tDag_9V196mJrALfVYDm00)](http://www.plantuml.com/plantuml/uml/dPDXQzi-4CRV-rDSHKjjI9D_uLy6Wq0Jnzi2QHAST7jf5EiQYyYIaUIsOUoxJufZPoqfZBsCdhldxlbTV6yirROkHN0DkPBFg2rm2o_S5a0PuvOhIOMJof9A1e9B1AgtTOdImiqaJMQZzVHxaatdyUnnaWn9Vz3l4x0AQeCWL4w5s0SN_0ckdgdcT2CmmrTkh0d9-sOI1G0NNEQYPWXNMxHPr_DCHOtdMWRn_rcioaf9bBPV-IGNA0p-QLLOMvdFWu6cB_sjIrPlt7BQnRM-nsKRxBZE2sCBvtQp55JQnuVP05-Tpf2T7I4PVmeSjCfNkoSmbWi1KZbuIk-ut89JLzyMFx9baguMysovIDVfQBeE8wyOLr9HJKkWkLLwh3H3lIvulfDe3DpUzV-33-jMTYyG63K5CWY2nufHYub0VnMlEL8LQgCawS7bvj0IAw7qa6XatLjZCnmhmMPSOXX5PvtoDlhVc4tyJaUxJkfY3ScTEt8mOcnvM6zDjo6XhEJoNtokGQD1stBOq7m7Le5HWZC_exkP6zF4U3zbvKe_7d8RjMXNUsEn7AjQCght3PTp3C_xV78-RMyuxW5fVv08VWO03OjmsMkF5fqUHvE7wTorZ5f8bcxDi67cwdu5GRDRrWrOkUhcxMZVOGZZ7ebFnoGMy-BawVbuGqykHU6PcGfpJeMlm5TxFFhbA4tTd_hBOhxEuiLiaNe7uRA_rTz8Ps_gXHEakoXmKnq4jsHjq91UizPn1uVmy2tDag_9V196mJrALfVYDm00)

Thank you and best regards
Helmut

PS.: I extended all Add...Tag() with (...,  $borderStyle="", $borderThickness="") too, but I forgot the update in the readme

**Comment by qtzar** [comment]
Just got a chance to test this, grabbed one of my puml files, changed the imports to point to your extended branch and added the borderStyle and borderThickness declarations to a few of the AddElementTags in the puml and generated an diagram. 

It looked great and exactly what I was looking for. Plan for using this is to be able to set border colors and styles for containers that are being change in future state diagrams.

**Comment by kirchsth** [comment]
@qtzar: v.2.8.0 with border styles released
