### ISSUE TITLE
C4_Dynamic no longer numbers all relationships

### ISSUE THREAD

**Issue by hansensmythe** [plantuml-stdlib/C4-PlantUML#320]
Until recently (mid-July?) diagrams could get relationships automatically numbered in order of use by using
`!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml`

This was useful for diagramming auth chains, for example, where each relationship relies on a change of state from a previous relationship, e.g.
1: Get the object from Container 1
2: Send the object to Container 2 for modification
3: Send the object to Container 3 for further modification

However, the same diagrams now fail to number some relationships - it appears that 'Rel_L', 'Rel_R', 'Rel_U', and 'Rel_D' relationships get numbered, but plain 'Rel' relationships do not.

**Comment by kirchsth** [comment]
Hi @hansensmythe,
thank you for the finding, I will check it.
BR Helmut

**Comment by Potherca** [comment]
Using this diagram:

```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

Boundary(a, 'Direction ""Rel""'){
    Rel_Down( Rel_Down,  X, "")
    Rel_Up(   Rel_Up,    X, "")
    Rel_Right(Rel_Right, X, "")
    Rel_Left( Rel_Left,  X, "")
}

Boundary(b, 'Direction ""Rel"" Shorthand'){
    Rel_D(Rel_D, Y, "")
    Rel_U(Rel_U, Y, "")
    Rel_R(Rel_R, Y, "")
    Rel_L(Rel_L, Y, "")
}

Boundary(c, 'Plain ""Rel"" and ""BiRel""'){
    Rel(Rel, Z, "")
    BiRel(Birel, Z, "")
}
@enduml
```

It can be seen that `Rel` and `BiRel` do not contain numbers, confirming @hansensmythe report.

![](https://www.plantuml.com/plantuml/png/RL71QeGm4Btx5MakcuMiNdhgQTdQcuLY4TfUbXZJDQ29n95bAVttZh4RqwM2mtippybxPZ-2S33rNNAdZUocHf4MO1WViio9SthIq4xrD2edhG5b89MspuPEcFcRtGXDf-liyNxtChUgvoBhnGZAOUkONupejKo7UNjoi9DfXBimmSacrqv9qDOGIalLKRhPVYK47oJ7t9uD2uWJyiO9lLAw3RfgO06XAkYGHgfIdrfW0N6l2ZGI5keJM43hiPwYxZlAKF-NWRosra4hJFCd3VELa_ThYZW2ytKTLh7pnVKwB6EtpDTrMDnOb6WHBqMlzj0OueE-_U4CNqu-bZs_HtWLUrhQVerVlrUcmTly0G00)

Doing a regression check, none of the versions show a number for `BiRel`.

- Version 2.0 to 2.6 show numbers for all relations (except  `BiRel`) 
- Version 2.5 shows `****` for  `BiRel`
- Version 2.6 _does not_ show numbers for `Rel`, `Rel_Right` and `Rel_Up`
 
<details><summary><strong>Full Regression Details</summary>

<table><tr><th>Version</th><th>Diagram</th>

<tr><th>2.0</th><td>

![](https://www.plantuml.com/plantuml/png/RP31QuCm6CNl_XMPbwQGQXaxxLISHmV5KTXsAJ5czOEOIFooKiR-zoKUugRpy7Y-z_duuM54Rj7rAha3BPHh9UaGX_4npos_PXV0pZLkb5OOZL9Z9aoV3uhhyCrkn5P1apyzx8uXEZrN-UTzji_sFZgNDyrx4DaGrXC4L9A4DaaAutJBxOroHZObM2aGZ2PfMakLffljLqByur_EfRbg6XqZv9NvistiJmEDphUhlePBXpGwjkmh-O4qkdd_-nTaynyaUUcCnOxhzWykdPIHjmKcdNILrtJILLxHINs-nX4UvwWup2WUmli2bdylZ33oFazF9xG06_CmVP2wTRtw0G00)

</td></tr>
<tr><th>2.1</th><td>

![](https://www.plantuml.com/plantuml/png/RP11JuGm58Jl_8hAPRj95zHuyhH1ZfXiC9kebqqfTNb9QKbvTRCn_dTR3aL13fDXvZ7vmdv4Rj7rAha1BPHh9UaGX_4npos_P6V0pZLkb5OOZL9Z9aoV3uhhyCrkn5P1apyzx0uXEZvN-UTzTfVT-kXKNZNlGMH3M4yGK4aIsYGfZDCjjrVA6TcKOAL0C9gaQIrLccwsNmdnZtyvbUQYQNICa5VcpxQnFmuqEj-k-XhE7TBesBAlv0VIwERzxr-GpN-GvAKp5Zkksp-uT596tXQOTD9LNjD9Ltb59mtv2aTud8FYCADu2EyBMFwzCCB8-pmzdT02x9pxwRtKhUlL3m00)

</td></tr>
<tr><th>2.2</th><td>

![](https://www.plantuml.com/plantuml/png/RP31QuCm6CNl_XMPbwQGwYWxxLISHmV5KTXsAJ5czOEOIFooKiR-zoKUugRpy7Y-z_duuM54Rj7rAha3BPHh9UaGX_4npos_PXV0pZLkb5OOZL9Z9aoV3uhhyCrkn5P1apyzx8uXEZrN-US-ssVtFZgNDyrx4DaGrXC4L9A4DaaAutJBxOroHZObM2aGZ2PfMakLffljLqByur_EfRbg6XqZv9NvistiJmEDphUhlePBXpGwjkmh-O4qkdd_-nTaynyaUUcCnOxhzWykdPIHjmKcdNILrtJILLxHINs-nX4UvwWup2WUmli2bdylZ33oFazF9xG06_CmVP2wTRtw0G00)

</td></tr>
<tr><th>2.3</th><td>

![](https://www.plantuml.com/plantuml/png/RP11JuGm58Jl_8hAPRj95unwyhH1ZfXiC9kebqqfTNb9QKbvTRCn_dTR3aL13fDXvZ7vmdv4Rj7rAha1BPHh9UaGX_4npos_P6V0pZLkb5OOZL9Z9aoV3uhhyCrkn5P1apyzx0uXEZvN-UTTTf_T-kXKNZNlGMH3M4yGK4aIsYGfZDCjjrVA6TcKOAL0C9gaQIrLccwsNmdnZtyvbUQYQNICa5VcpxQnFmuqEj-k-XhE7TBesBAlv0VIwERzxr-GpN-GvAKp5Zkksp-uT596tXQOTD9LNjD9Ltb59mtv2aTud8FYCADu2EyBMFwzCCB8-pmzdT02x9pxwRtKhUlL3m00)

</td></tr>
<tr><th>2.4</th><td>

![](https://www.plantuml.com/plantuml/png/RP31QuCm6CNl_XMPbwQGwXWzxLISHmV5KTXsAJ5czOEOIFooKiR-zoKUugRpy7Y-z_duuM54Rj7rAha3BPHh9UaGX_4npos_PXV0pZLkb5OOZL9Z9aoV3uhhyCrkn5P1ap_jTySGdPwh_FCXssVtFZgNDyrx4DaGrXC4L9A4DaaAutJBxOroHZObM2aGZ2PfMakLffljLqByur_EfRbg6XqZv9NvistiJmEDphUhlePBXpGwjkmh-O4qkdd_-nTaynyaUUcCnOxhzWykdPIHjmKcdNILrtJILLxHIKE-mX4UvwWup2WUmli2bdylZ33oFazF9xG0E-T--Y1rwthr0m00)

</td></tr>
<tr><th>2.5</th><td>

![](https://www.plantuml.com/plantuml/png/RP51QuGm48Nl_ehKosOXgwMqbvuMwz52iIoqlImnfkj0J2IENPRI_zxHGcor7eRdU-FZOzptA3qEhOckm2epr9erY5r_dwPUdfCJO3DKGw-zSXQrnKIvDksCjECtknvh0rNwSBjx6gt3Ov5-t2HtoJLPn_nYPGigwSRs206DPcCQHPaRR2tzXKl1DZbuhH2SPN5SQXF7c-rdnEYXbsFkpfO79HXx4RIs3VcXuq5HkifBE3N8WnBBlD3lo8EQ-xz-GLR_GRBdndbifAt_uF9f2lQwmEJJNFdb3zhAB_WqoL_ZACAXQyECGX2aCrXURomHx6skdbPu1dxsgNglRKs_w1i0)

</td></tr>
<tr><th>2.6</th><td>

![](https://www.plantuml.com/plantuml/png/RP51QuGm58Jl_ehKosOXgwMK7dfQh4SBnRBGzhB4cAuFOYBnsMKf_UzzUeYjheTXd8d3HzptA3qEhObkm2epr9erY5t_cAPUdfCJO3DKGw-zSXQrnKIvDksCjECtknvh0rNwTBzx6QF3Sv5-tIKFoIr5n_nYPGigwSRr206DPcCRHPaRR2tzXKl1DZbuhH2SPN5SQXF7c-rtnEYXbsFkpfO79nXx4tHi6_f3nuEZTjMNS6gG1oUMVQ4_aGStx__yWQokGRBNndbifAt_uV991NjVOF99Ltd99rtb1P-KyZME8XowRPXH289y1ilR6qS4-vYdfoCy0p_dDBtNjgPVz0i0)

</td></tr>

<tr><th>2.7</th><td>

![](https://www.plantuml.com/plantuml/png/RP11QuGm58Jl_ehKosOXgwKK2ZqjrgE5nRBGzhB4cAuFOYBnfSjI-j-RU8YjriCmpZo73_SZSekkLyaDQA5SAqc7E8oFUMxv9Ji3TgvnexJ2Q9GQCs7wV51SXszs8xOAclpfVdS8qV6voZ_lieViraUdygfv3o8Rmdg2W4gIq2P9OPnkkRrIpiYc12i5Wj4aJMkfqdIp_Kg8V_pBgJGNJQDZXBmoVxQD_N6WqVbsrTTmxf16nvPz9J-GHZVlV_-2RFw392-TiTXntVx1fPCoyhR0f9EkyffEkiehEcd8LpZ2unmKXnd5GtXVmFBlXH56tkVfwOGMOEVSJ--bRbslVW00)

</td></tr>

</table>

</details>

**Comment by kirchsth** [comment]
Hi @hansensmythe,

I have a bugfix in my extended branch, can you please test it with your diagrams?

```plantuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Dynamic.puml
```

[![](http://www.plantuml.com/plantuml/svg/NPDBRzim3CVl-HHSJydG9jZMqu1XpQDOE_GHDEc6dG9QOcoXicHGTBDWs7SVvRH8lHibFlu__MbV946MjlQ3TouOtrg2IgH9doSJnjsuT5ArHPk8JGn2GSOcrfCdnwPAKatcvsTBZq4URsycz5lpbgnURXRxWBKpuoOF7jnCVzq_hZS_hzTNcvlBRvTtY-5eC9ZhG7I1U54CpVafd2nGiC149ne_a4TnCQ27rsjOcOfgpDcLHAO46GkOIfU4ksfmOHkvxk9Jg31LP05RgHJScKE9ORBvY3wT0Xf3AO6FfHv8pFXaTEGQcWzPouNIqzaIIu9fq_YNEHdZEpxZoh1h131Oc8QozSWvi-JuxAmYelSGjw04S1s4E910WU59XyAs3URmHYTxa0YcJH9huWJF3dEFOzXH0GN7NIBkmMrciGqMUJyiL6-wlEx1ZU3F060UwoO62Z8qd_9BoBIiKiVxpik6CyoCCFJ8-tJTFiXcokJAa3kSMcmg36K-D9ZIBh8zsjYJ_vY5j4zDWFm4ZjuJlv6__J5NZIJ_PQVUnzrXqUbLMuKrx5iwUx5qjKz2TPR_Er3apKEtmuDyMzHEqjlzwvXkZQlxkydLUhrSQPzsTRYTOtFqMkNIzFW9aHsE83lyEb_hkgytaISZy1ws7EiNubr5J5qSi2Ru0byxlSLihlqN56p-FVu1)](http://www.plantuml.com/plantuml/uml/NPDBRzim3CVl-HHSJydG9jZMqu1XpQDOE_GHDEc6dG9QOcoXicHGTBDWs7SVvRH8lHibFlu__MbV946MjlQ3TouOtrg2IgH9doSJnjsuT5ArHPk8JGn2GSOcrfCdnwPAKatcvsTBZq4URsycz5lpbgnURXRxWBKpuoOF7jnCVzq_hZS_hzTNcvlBRvTtY-5eC9ZhG7I1U54CpVafd2nGiC149ne_a4TnCQ27rsjOcOfgpDcLHAO46GkOIfU4ksfmOHkvxk9Jg31LP05RgHJScKE9ORBvY3wT0Xf3AO6FfHv8pFXaTEGQcWzPouNIqzaIIu9fq_YNEHdZEpxZoh1h131Oc8QozSWvi-JuxAmYelSGjw04S1s4E910WU59XyAs3URmHYTxa0YcJH9huWJF3dEFOzXH0GN7NIBkmMrciGqMUJyiL6-wlEx1ZU3F060UwoO62Z8qd_9BoBIiKiVxpik6CyoCCFJ8-tJTFiXcokJAa3kSMcmg36K-D9ZIBh8zsjYJ_vY5j4zDWFm4ZjuJlv6__J5NZIJ_PQVUnzrXqUbLMuKrx5iwUx5qjKz2TPR_Er3apKEtmuDyMzHEqjlzwvXkZQlxkydLUhrSQPzsTRYTOtFqMkNIzFW9aHsE83lyEb_hkgytaISZy1ws7EiNubr5J5qSi2Ru0byxlSLihlqN56p-FVu1)

Thank you and best regards
Helmut

**Comment by kirchsth** [comment]
@Potherca
I saw you have done some tests, can you repeat it with my bugfix too?
Thank you
Helmut

PS,; BiRel_* was never supported

**Comment by hansensmythe** [comment]
Looks good to me! Well done, and many thanks.

Steve Hansen Smythe

Software Developer, AppDevices
AppDirect
236 508 5480

**Comment by kirchsth** [comment]
@hansensmythe: v.2.8.0 with fix released
