### ISSUE TITLE
error a001 on all diagrams 

### ISSUE THREAD

**Issue by gsantandrea** [plantuml-stdlib/C4-PlantUML#323]
Hello,
commit a0e50963 seems to introduce a bug so that diagrams are not rendered and it returns an error.
https://forum.plantuml.net/17566/global-%24variable-default-variable-produces-error-a001

For example:
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml

@enduml

The problem does not appear on online editor, only in local PlantUML server instances or with PlantUML VSCode plugin (because uses local PlantUML server by default).

**Comment by kirchsth** [comment]
Hi @gsantandrea and @james-airbox,

@gsantandrea: thank you for the fix.

the fix is merged, master should work again.

@james-airbox: For Visual Studio Code, add the following to your settings.json:
```json
"plantuml.jarArgs": [
  "-DRELATIVE_INCLUDE=."
]
```

BR Helmut
