### ISSUE TITLE
Question: How do I split functions over multiple lines?

### ISSUE THREAD

**Issue by rcdailey-studiodesigner** [plantuml-stdlib/C4-PlantUML#331]
Some calls can get very long and I'd like to organize them over multiple lines. Take this line for example:

```
System(jobs, "Long Running Job System", "Processes requests for unrelated background tasks with some output", $type="Software System")
```

Through experimentation, I found that this works (at least, it renders in VS Code using the Plant UML extension):

```
System(jobs,\
    "Long Running Job System",\
    "Processes requests for unrelated background tasks with some output",\
    $type="Software System")
```

This is tolerable, but I dislike the `\` I have to add at the end of each line. I was hoping that since comma is a delimiter for function arguments, that the parser would be smart enough to ignore whitespace.

Is there a simpler / different syntax I can use?

**Comment by kirchsth** [comment]
Hi @rcdailey-studiodesigner 

I think there is no other syntax possible. And "C4-PlantUML" (it is only a library on top of PlantUML) cannot define a new one.
But you could make a PlantUML specific enhancement request in [Forum](https://forum.plantuml.net) or [Github](https://github.com/plantuml/plantuml).

BR 
Helmut

PS.: I like PlantUML and I'm happy that I can use PlantUML (for free) and I don't think that the current functionality is (only) "tolerable".
