### ISSUE TITLE
Support of "all" PlantUML elements can be enabled 

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#336]
Based on multiple requests #145, #104, #329 and #309 I think I found a relative good compromise for the support of "all PlantUML elements" as additional shapes. 

If all PlantUML elements are required
 
- it can be enabled via "ENABLE_ALL_PLANT_ELEMENTS = 1"
- and the "PlantUML element" can be defined via an additional `$plant=....` argument in combination of systems, containers and components.

The solution has following advantages
- it is optional, if it is not enabled the internal required skinparam overhead is very small
- no new function calls have to be defined

@Potherca, @jlesueur,@mdreano, @crgardner, @adrianvlupu, @dannief, ...: can you please give me your feedback before I start with a merge request?  

Details see below and it can be tested via my [extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended)

Thank you and best regards Helmut

## Optional support of additional PlantUML elements

More often a full support of all PlantUML elements are requested.  
They can be set via the new optional `plant="...."` argument of the calls

- `System(..., ?plant)`,
- `System_Ext(..., ?plant)`,
- `Container(..., ?plant)`,
- `Container_Ext(..., ?plant)`,
- `Component(..., ?plant)`,
- `Component_Ext(..., ?plant)`

The already specified `...Db...()` and `...Queue...()` calls are not extended.

But based on the additional (internal) overhead it has to be explicit enabled
via `ENABLE_ALL_PLANT_ELEMENTS`. It can be set with following 2 options

- `!ENABLE_ALL_PLANT_ELEMENTS = 1` directly in the scripts file
  BEFORE the first C4\_\* file is loaded, like e.g.

```plantuml
@startuml
!ENABLE_ALL_PLANT_ELEMENTS = 1
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Component.puml
...
@enduml
```

- or via additional command line parameter `-DENABLE_ALL_PLANT_ELEMENTS=1`

If `ENABLE_ALL_PLANT_ELEMENTS` is not set, the diagrams displays the requested "PlantUML element"
but the style is not correct displayed.

**A simple sample with additional "PlantUML elements":**

```plantuml
@startuml
!ENABLE_ALL_PLANT_ELEMENTS = 1
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Component.puml

Component(comp, "Copy component")

Component(config, "Config component", $plant="package")

ComponentDb(dbA, "DB A")
' alternative syntax for ComponentDb() with $plant="database"
Component(dbB, "DB B", $plant="database")

Rel_U(comp, config, "Configured by")
Rel_L(comp, dbA, "Reads from")
Rel_R(comp, dbB, "Writes to")

SHOW_LEGEND()
@enduml
```

![Sample with PlantUML elements](https://www.plantuml.com/plantuml/png/NP1FQy904CNl-HHZA5J16Wez5GGJ3UrXJSK_U0oRx6Y2oMxOdLJzzjsjDiJUPkVzPjwRdHdYcjgwyWPn4aOiJaF6qXKBasqQitWP9ziDJE7L6vGohrg1K10rvZq8D3zFZYKLRTOQrBcIX98ckQg3Kwdpmb0HpDzULXMNj5ko02zM5oXiCvshkb7IuOrpzhhtCBVL6FovQgwG_tNzqICY3-NHGRz53nl3K-Fifdx3ynC_uiFW8XkABBHpYmX2gpm3hmYrv5H-8vYh97w1WzBGdnZ1sPxOxHMSUCOD-hqy8ejkIwCkG0-q2TPOfRlxPV_2jne5P5TBEOZTeLlCDN9XuA1LVPVNdUmCzxeaD43AMMm-l_OfYp_YP34SUJEKmlxh3m00)

### List of supported PlantUML elements

| PlantUML element | Support  | Comment                                                                                                               |
| ---------------- | -------- | --------------------------------------------------------------------------------------------------------------------- |
| rectangle        | &#x2705; | already supported (works even without ENABLE_ALL_PLANT_ELEMENTS)                                                      |
| database         | &#x2705; | already supported (works even without ENABLE_ALL_PLANT_ELEMENTS)                                                      |
| queue            | &#x2705; | already supported (works even without ENABLE_ALL_PLANT_ELEMENTS)                                                      |
| node             | &#x274C; | **should not be used**, already defined for Node() (works even without ENABLE_ALL_PLANT_ELEMENTS)                     |
| person           | &#x274C; | **should not be used**, already defined for Person() (works even without ENABLE_ALL_PLANT_ELEMENTS)                   |
|                  |          |                                                                                                                       |
| actor            | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| agent            | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| artifact         | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| boundary         | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| card             | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| circle           | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| cloud            | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| collections      | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| control          | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| entity           | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| file             | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| folder           | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| frame            | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| hexagon          | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| interface        | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| package          | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| stack            | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| storage          | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| usecase          | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
| usecase/         | &#x2611; | requires ENABLE_ALL_PLANT_ELEMENTS                                                                                    |
|                  |          |                                                                                                                       |
| actor/           | &#x274C; | requires ENABLE_ALL_PLANT_ELEMENTS, not working (font color not changed to $bkColor) - and/or conflict with existing? |
| label            | &#x274C; | requires ENABLE_ALL_PLANT_ELEMENTS, not working (font color not changed to $bkColor)                                  |

If `ENABLE_ALL_PLANT_ELEMENTS` is not set, the diagrams displays the requested "PlantUML element"
but the style is not correct.

[![Sample with all PlantUML elements](https://www.plantuml.com/plantuml/png/h5HHQziy57tthxWnBKq-qlXhDnWKokQc7XJSfBJfnfwCObt78hAKITTjy-ydENLYXiiesqFWHkVSSuwaAt-nn0pLbGnEuAQ0P1PVfKaMfsbsbyQpHPQaoMqoMpo0i62Hu2hvEhzFW4g4GXXBCFsO_UTAYPuXDUF8nqvB8JDo2o6JCeGxoHGztgQ04YjKP25d2fO8jKKEKgpHTG1CTRNHok731zA6hJ0UG_XQGWpX68usNkaojBl5S1GCtavy2MU1qysrUa9380YU1PN0E1Saj6BIGLN5b4-W49XPrJuSd5xV9scykFcMP3UpQVfudLo6asWo2O6qJmnIvqpARJ0G1Hm_CIFOKcA6ByAI7OQ_DxkG02UmGPDlmTJAmj3g2abKQ4UxI6UJy__FFqm-DSG1bLYXFzTQ2K8EXT4L7A-GijRB5RB6FgkeQRO1l27Zzt7WTCrM1b7raGP2vRBck5jspFqrJJP-RWOeBRvfM19jx4KK6VOyMRczrilQeicr8Y_WBY1Q2vENbaedVTeEIeGl3kV8_vZrd-cts_nhnRuJKbmKGP36F-QFYsmnlykkvzzdmv4VJuu5goM1i60m9wPM4eF3IzXNOmYdBWCJ2ate_lXV37aBXoEdnQH1nhTWwyr66q9-ST0S0sV4biowwcUDTTTaJ-frEsXup-wVRe3T9E_Hzgbt7ksXSzJnRbFrMxUeDslhNkCMxF7TztLjcoFezsmWR-ABVZUFz5dvTU_pxhiuy3aMGY67uPDWeAb4CxfmC83IVZYP1GPS50KQdyRILY8CSwQK9iXB9-zwMKswOYIQprGp63bf4u7dF6kp5ce5mq8hrw6bDj3j9Gr7o_NKhu_W59ZYaJQEfmefyjVjDvyw9_BPIKksHFbkvQ1p5KsuNtpNGOxQC1o5yQjqouexj2Tn7KCZqgHoWbHkNvvViFAllinYXWSVveUKnMJYfTYtlxUkW0TTYbRWKlZ4vN_d-uylfAifBx2S07E8sltzcwsM17YWf0AGJmIdRkCjvJFArLhV13gYwHJPdyjp7b9zCVkfeleczXE1xUSktmvkJdLWKqM67y5I0AUz_t8anfgdmeXROxm8SWBA8MBJyXpOQac01qeg0Fb4S9PfAbdtFIjhXpU82az1FdJo3wVZjvYtkamdty3HkYVARgIw1F7zCsul1js4U27d19f3m7GRp9IAFjwFm2W0efSZiKn3gOouDSQB82UW729Mq-_2Lai2F51I8KYl1-TN-PlkoypI7aNq2ThUmDjB4CTvA_MMSc6pPr7z2RgzWjnRiDjVJ7PR4kD1NYjW-SJHqGq3CohwS3y2eW26NWx4dvGVwNwYE3R0aoqtulOInLBNPMRGJOWNSawWEGHitL9-iDMI00-IMW789uBZVsTF94TRdgYvaUSInETQSbfFHCV6UBBeHg8BYdp_rSrhHxr9TJnd_pLQXpXJ154KXVsi17Q1O0A2W40WCOnZC81Wzz1vEPtEuVwvprMbadjAVeV3RYVdXttdzIhzoClpTSjBEl0obypBtEgyf3QyZ2tpCfGwB-c0lvXAl4p1FI_9Wh-OZRnKTitBQtPqcPBMfLDTboJGPOfObmhjTKbiT9bRrcKeLLtIkUeorOekNTxhKhyONSOV15swlDSbHNIPWjQbSdjT4XjTffHrwKpL9Gbq6IFMfKDRNH8RNQPMrALANPTqq6KiPLswjjGbnTDzkPbr6RjxNT8UNQPkrALwNPTqHfSfOrqgqdL90bt6IjQbMqjTKaINCMXTEhVL9R7HPMf5NQhKTKa7NUPIrgLhErrIH9Unc7MfOjTbBBx4hwnBL_Uw_Fpdvw_7SyWtvtzZSuYedAUTADaUJdhTaFH-LoI58QJsXKUjTpco3Ueydy7eo4gBf82SKnc9Jgs4IEh0d381XinN5J8xSFEmCUZnBa42mq3j2u1Qx_fZ-u8n5GhwL5kBZpBSSpL3JxMkF2e3CKK2xfJeiYDm84pp0NHCLyqnE-3oi17dyIuu0iCtxGjkMgzgOnkoUJrZZS9QQbHEGBcJWURMLcVqXcPg2MLgT96nVU39quOOmrrXp48mBsTyiR-M5vN1aIC6bnDTMmI6MjeNihHUXSKslD9wXfKANLLK08ug6LEgT4cvyZyxCg1ogUlf_QSlNp_Stzq_ldtr-lRcyUFRx-Vtlm00)](https://www.plantuml.com/plantuml/uml/h5HHQziy57tthxWnBKq-qlXhDnWKokQc7XJSfBJfnfwCObt78hAKITTjy-ydENLYXiiesqFWHkVSSuwaAt-nn0pLbGnEuAQ0P1PVfKaMfsbsbyQpHPQaoMqoMpo0i62Hu2hvEhzFW4g4GXXBCFsO_UTAYPuXDUF8nqvB8JDo2o6JCeGxoHGztgQ04YjKP25d2fO8jKKEKgpHTG1CTRNHok731zA6hJ0UG_XQGWpX68usNkaojBl5S1GCtavy2MU1qysrUa9380YU1PN0E1Saj6BIGLN5b4-W49XPrJuSd5xV9scykFcMP3UpQVfudLo6asWo2O6qJmnIvqpARJ0G1Hm_CIFOKcA6ByAI7OQ_DxkG02UmGPDlmTJAmj3g2abKQ4UxI6UJy__FFqm-DSG1bLYXFzTQ2K8EXT4L7A-GijRB5RB6FgkeQRO1l27Zzt7WTCrM1b7raGP2vRBck5jspFqrJJP-RWOeBRvfM19jx4KK6VOyMRczrilQeicr8Y_WBY1Q2vENbaedVTeEIeGl3kV8_vZrd-cts_nhnRuJKbmKGP36F-QFYsmnlykkvzzdmv4VJuu5goM1i60m9wPM4eF3IzXNOmYdBWCJ2ate_lXV37aBXoEdnQH1nhTWwyr66q9-ST0S0sV4biowwcUDTTTaJ-frEsXup-wVRe3T9E_Hzgbt7ksXSzJnRbFrMxUeDslhNkCMxF7TztLjcoFezsmWR-ABVZUFz5dvTU_pxhiuy3aMGY67uPDWeAb4CxfmC83IVZYP1GPS50KQdyRILY8CSwQK9iXB9-zwMKswOYIQprGp63bf4u7dF6kp5ce5mq8hrw6bDj3j9Gr7o_NKhu_W59ZYaJQEfmefyjVjDvyw9_BPIKksHFbkvQ1p5KsuNtpNGOxQC1o5yQjqouexj2Tn7KCZqgHoWbHkNvvViFAllinYXWSVveUKnMJYfTYtlxUkW0TTYbRWKlZ4vN_d-uylfAifBx2S07E8sltzcwsM17YWf0AGJmIdRkCjvJFArLhV13gYwHJPdyjp7b9zCVkfeleczXE1xUSktmvkJdLWKqM67y5I0AUz_t8anfgdmeXROxm8SWBA8MBJyXpOQac01qeg0Fb4S9PfAbdtFIjhXpU82az1FdJo3wVZjvYtkamdty3HkYVARgIw1F7zCsul1js4U27d19f3m7GRp9IAFjwFm2W0efSZiKn3gOouDSQB82UW729Mq-_2Lai2F51I8KYl1-TN-PlkoypI7aNq2ThUmDjB4CTvA_MMSc6pPr7z2RgzWjnRiDjVJ7PR4kD1NYjW-SJHqGq3CohwS3y2eW26NWx4dvGVwNwYE3R0aoqtulOInLBNPMRGJOWNSawWEGHitL9-iDMI00-IMW789uBZVsTF94TRdgYvaUSInETQSbfFHCV6UBBeHg8BYdp_rSrhHxr9TJnd_pLQXpXJ154KXVsi17Q1O0A2W40WCOnZC81Wzz1vEPtEuVwvprMbadjAVeV3RYVdXttdzIhzoClpTSjBEl0obypBtEgyf3QyZ2tpCfGwB-c0lvXAl4p1FI_9Wh-OZRnKTitBQtPqcPBMfLDTboJGPOfObmhjTKbiT9bRrcKeLLtIkUeorOekNTxhKhyONSOV15swlDSbHNIPWjQbSdjT4XjTffHrwKpL9Gbq6IFMfKDRNH8RNQPMrALANPTqq6KiPLswjjGbnTDzkPbr6RjxNT8UNQPkrALwNPTqHfSfOrqgqdL90bt6IjQbMqjTKaINCMXTEhVL9R7HPMf5NQhKTKa7NUPIrgLhErrIH9Unc7MfOjTbBBx4hwnBL_Uw_Fpdvw_7SyWtvtzZSuYedAUTADaUJdhTaFH-LoI58QJsXKUjTpco3Ueydy7eo4gBf82SKnc9Jgs4IEh0d381XinN5J8xSFEmCUZnBa42mq3j2u1Qx_fZ-u8n5GhwL5kBZpBSSpL3JxMkF2e3CKK2xfJeiYDm84pp0NHCLyqnE-3oi17dyIuu0iCtxGjkMgzgOnkoUJrZZS9QQbHEGBcJWURMLcVqXcPg2MLgT96nVU39quOOmrrXp48mBsTyiR-M5vN1aIC6bnDTMmI6MjeNihHUXSKslD9wXfKANLLK08ug6LEgT4cvyZyxCg1ogUlf_QSlNp_Stzq_ldtr-lRcyUFRx-Vtlm00)
(sometime the PlantUML server has no access to the referenced files, if this is the case please try it with your local system)

**Comment by kirchsth** [comment]
I don't like plant too, but I didn't want to use 'planetUML....' we have basically no UML context.
I could call it baseShape?

I know, the better solution would be if we combine $shape,  but 
a) $shape is part of tags (atm we ComponentDb() and this means "database" is part of the component definition without any tags)
b) and if would combine $shape with $plant and make it as part of the elements then the internal logic==filesize/performance would be increased independent whether the feature is enabled or not 

@Potherca: what do you think? (should I combine it and add it to the elements)

**Comment by jlesueur** [comment]
Flattered to be asked. For me, the plant=... is acceptable. to be more agnostic in naming, you could use `renderAs` or something like it?

**Comment by Potherca** [comment]
I wouldn't bother combining `$shape`, either `renderAs` or `baseShape` sound like good alternatives to me. 👍
