### ISSUE TITLE
Line styling not recognized when using ELK

### ISSUE THREAD

**Issue by StephanPirnbaum** [plantuml-stdlib/C4-PlantUML#340]
I'm using C4-PlantUML with ELK, as it regularly produces better outputs.
However, I ran into an issue when using e.g. lineColor or lineStyle.

In the following [example](https://www.plantuml.com/plantuml/uml/LS_1IiGm4CRn-pp5RFJGGekNFTfbqwuUn9Fs9YAZ6R9bfydIJiM-Zs_YYvaM5Rp--1B-in-L1frwWKqNtcHoZDVDzghPlZInFyV0GNUmEG_aUqAXEKwAB2S0wzm3Iqi-CuURMrFWfR3du5h-qChSqJkLzlNuzHbyvq_SwRhe0ZTHue0LceiuKF3ywuyw2oS_H5LszqcoF0VugyXiWSQQVrGdgXUoM3xz_5Su6e_idiiTrW0fSNcu35iUrmWbFrPhSmxx59nk_mO0), the relation defined using standard PlantUML syntax is correctly rendered, whereas using the C4-PlantUML it is not.

    @startuml
    !include <C4/C4_Component>
    !pragma layout elk
  
    AddRelTag("DEF", $legendText="Java-Abhängigkeit", $lineColor = "#blue", $lineStyle = DottedLine())
  
    Component(A, "A")
  
    Component(B, "B")
  
    A -[#orange,dashed]-> B
  
    Rel(A, B, "Test", $tags="DEF")
    @enduml

This leads me to the conclusion that ELK itself has no issues with styling lines (which would have had me wonder, tbh).

When not using ELK, the [example ](https://www.plantuml.com/plantuml/uml/LS-nJeKm5CRn_Jn5BGwGG5mOXL2A3iP9sOmnnPwKnj8QUZ3wFhw9BsOXkJUvwozVq__f8gcLjiN1bVNlRjF8RcLz8-it6PRFuD5J2o2qVa8tAfFpuUwUb-pQeK6lH_ocXZ-eBrM9QVxxzSQQ3xHqBAn76LnOMSDuDhaDJ_fCFmwJ3e48zMEIl2W0pX_cecHSy0lg4_Kx2LQzP65Ltc2fLPnHlrOjwm5IuFvm7uuOZmHI9ZP7SG5Toard_WC0) is working, however.

    @startuml
    !include <C4/C4_Component>

    AddRelTag("DEF", $legendText="Java-Abhängigkeit", $lineColor = "#blue", $lineStyle = DottedLine())

    Component(A, "A")

    Component(B, "B")

    A -[#orange,dashed]-> B

    Rel(A, B, "Test", $tags="DEF")
    @enduml

For me, that looks like an issue of the combination C4-PlantUML syntax and ELK.

**Comment by kirchsth** [comment]
Hi @StephanPirnbaum,

thank you for the finding, but I think your conclusion is wrong. I think it is elk related, I can reproduce the problem without C4 too. Samples see below.

I entered a [bug in the PlantUML forum](https://forum.plantuml.net/18723/elk-layout-ignores-arrow-skinparam)

BR Helmut

[![](https://www.plantuml.com/plantuml/png/bP11JiD034NtFiMdB029S02eeZR97LWW5XOPXIZEk78SHHNYxgHJ2a7AXjqVVR_npDiDpkPZBtG3DjC9GzV60nltcDIw0HhbYAdrTnqTGJe87-T8LmVZfkTqF3T4lsowQxkrK5Vg7keynmS1GAcYXkkvU98sXeSwrVIv1gzXQTJ2ctDi962_oCKYbujS4UsHlPpW-_Ewron7WKTidh__zRDxGmMokItnv_6NsOMTsvEJ92Ig9rTjREukV9Nu_v6x4Eknboy0)](https://www.plantuml.com/plantuml/uml/bP11JiD034NtFiMdB029S02eeZR97LWW5XOPXIZEk78SHHNYxgHJ2a7AXjqVVR_npDiDpkPZBtG3DjC9GzV60nltcDIw0HhbYAdrTnqTGJe87-T8LmVZfkTqF3T4lsowQxkrK5Vg7keynmS1GAcYXkkvU98sXeSwrVIv1gzXQTJ2ctDi962_oCKYbujS4UsHlPpW-_Ewron7WKTidh__zRDxGmMokItnv_6NsOMTsvEJ92Ig9rTjREukV9Nu_v6x4Eknboy0)

[![](https://www.plantuml.com/plantuml/png/bP11JiCm44NtFiMdB029S02eeZR97LWW5YDYXIWJJpMPAAeGTySnBHYf6tPVVlCyzjzDHchpoEu6f2eBfg4F1r8QiOWE4oJm4Kjlxp8RF0zWEiOOvwyEIjr8fuELEVThfzksM_Lj8sQ-BKjyE02eXKLn7S4Jzy4_j0cxpqlo9IsDgdyp2XrxxBDSPRdESkFS7iNBAjz_htijIbHunERvzBEVtHjNeOYqnf_7dsUpVcxNLb8bGMnjAvBkxkmtoV-VkVEXdKV-0W00)](//www.plantuml.com/plantuml/uml/bP11JiCm44NtFiMdB029S02eeZR97LWW5YDYXIWJJpMPAAeGTySnBHYf6tPVVlCyzjzDHchpoEu6f2eBfg4F1r8QiOWE4oJm4Kjlxp8RF0zWEiOOvwyEIjr8fuELEVThfzksM_Lj8sQ-BKjyE02eXKLn7S4Jzy4_j0cxpqlo9IsDgdyp2XrxxBDSPRdESkFS7iNBAjz_htijIbHunERvzBEVtHjNeOYqnf_7dsUpVcxNLb8bGMnjAvBkxkmtoV-VkVEXdKV-0W00)

**Comment by StephanPirnbaum** [comment]
Hi @kirchsth 

thank you for the fast investigation and reply. You're right, I was not considering using skinparam which would explain the difference to my example. I can confirm your conclusion.

**Comment by kirchsth** [comment]
Hi @StephanPirnbaum,

the last PlantUML beta has a first fix: line color, thickness and style are correct (details see [PlantUML PR - Elk: Allow full style on arrows (except fontcolor)](https://github.com/plantuml/plantuml/pull/1833).

You can download a *.jar file from [PlantUML Releases-snapshot - Assets section](https://github.com/plantuml/plantuml/releases/tag/snapshot) (I tested it with `plantuml-mit-SNAPSHOT.jar).

The $fontcolor is not correct supported, but if you use `$textColor = $ARROW_FONT_COLOR` then the legend uses the same $fontColor as the diagram itself. 

e.g. following source

```plantuml
@startuml
!theme C4_united from <C4/themes>
!include <C4/C4_Component>
!pragma layout elk
'!pragma layout smetana

'known issue: $textColor is not working with elk/smetana
' AddRelTag("DEF", $legendText="Java-Abhängigkeit", $textColor = "#green", $lineColor = "#blue", $lineStyle = DottedLine(), $lineThickness=7)
' AddRelTag("DEF", $textColor = "#green", $lineColor = "#blue", $lineStyle = DottedLine(), $lineThickness=7)

' $textColor is not working, but if the unchanged color is defined then the legend displays the correct color again
AddRelTag("DEF", $textColor = $ARROW_FONT_COLOR, $lineColor = "#blue", $lineStyle = DottedLine(), $lineThickness=7)

Component(A, "A")
Component(B, "B")
A -[#orange,dashed]-> B
' WithoutPropertyHeader()
AddProperty("PropC1", "ValueC1")
AddProperty("PropC2", "ValueC2")
Rel(A, B, "Te<$person>st", $tags="DEF")

SHOW_LEGEND()
@enduml
```

produces following output

![image](https://github.com/plantuml-stdlib/C4-PlantUML/assets/21959385/3e72bcf1-a1fc-4bb5-828b-99e0a1b2a381)

Can you please check the fix with your diagrams too?

Thank you and BR Helmut

**Comment by StephanPirnbaum** [comment]
Hi @kirchsth 

thanks for your work. The provided Snapshot resolved the issue for me.

Best
Stephan

**Comment by kirchsth** [comment]
Hi @StephanPirnbaum,

@arnaudroques  create a fix for $fontColor too (details see https://github.com/plantuml/plantuml/issues/1834) that the newest snapshot supports $fontColor too.

![image](https://github.com/plantuml-stdlib/C4-PlantUML/assets/21959385/974a330e-4bc6-41d2-ba4a-4ed20e999ddc)

BR Helmut
