### ISSUE TITLE
"Cannot open URL" on Online Server

### ISSUE THREAD

**Issue by flyisland** [plantuml-stdlib/C4-PlantUML#341]
I copied and pasted the content of "https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/samples/C4_Context%20Diagram%20Sample%20-%20bigbankplc-landscape.puml" on the [Online Server](https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000), and got the below "Cannot open URL" issue:

![image](https://github.com/plantuml-stdlib/C4-PlantUML/assets/547085/fa425c4f-5294-45e6-9a64-96613c157e4d)

But I can generate the image of this puml on my laptop with the local jar plantuml installation.

**Comment by kirchsth** [comment]
Hi @flyisland,

sorry, yes this is a known problem of the online server, depending which server answers your response (details see [forum](https://forum.plantuml.net/18563/beta-release-include-errors-at-plantuml-com?show=18599#a18599)).
This means a non deterministic solution is that you refresh the browser and after some tries it is working.

I think the simplest and practically solution is that you use the already integrated [C4 Library](https://plantuml.com/stdlib#062f75176513a666) version (it is up to date, already part of PlantUML and no URL include is required).

This means, if you replace e.g.
```plantuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
```
with 
```plantuml
!include  <C4/C4_Container.puml>
```
then it works with all PlantUML online server versions.

(If you click on the following image you see the updated source)

[![](https://www.plantuml.com/plantuml/png/TLDDR-Cs4BthLqnzgGCaSGzxAefY7SVeBkfy8BOHz2HGrCWYJ95Q3XN7AFhVEwGbhVpXayIPDs_U31-_aXVEDvLEVlr56QcR7A7qlgRV9nCdTlSRvSicQmYTjCQZyVVILfDQ2nEAxiZdMcMJsPUxrn1QFoqcbI2FZaFfB5Hy-liwqaDZkBHY2l0bGc6rjZjbDg2LGH0cXwEqSiH_5hWrQ2k5rdlcw3MUqdCkA32i01J7Dqvup1a62vKvuVRmWOwKDU3mHwCS4XWB8i-Lvw3Gi7vRG4jEKStEkYq15t1h_aILX8vfM9Q5f9Von-pBwRH_ifx5z9-NzIfTlRocZo_lp-ERFZHTfik_vwlPDuwreVVlgs_fOlxN_FcHWubNNYCiz-InWWMh8IbgX5m9dglYtJbuK1ju46OBjPP9yegEh1dBXhojqDt2w10HEeB2ccTjRiJ9ANH8i4NSTyQeMzZnRKFTLOOO22bjOppTZrZNd4TqjLE4wGD7SzxhMFx6X4CrenluDm60LlyuEmX8AHuP_3sm6FITj1OOXGLJKA-EWWC-5Ev06Hww4k6oG6IsYIvHxbZZRRouIcmHQh6li9Kz49FEF_rO-2gqMZrTwnZMaBFxGGegcU6Ke19A_nndVXVEGFqGgnAZ1rrOufEIpf8jFCm_PIdC1W671PS4SjeKJbJ8P4_T_uLjBRrrIC6WtJLA3a2xy0ixwwUy7UpCEs58o03Z4thPIpfuA4hgAjFm19GCoZf3mV8GWgKNHJ4QPbemKCZ4jIhJsutRd7R9XDocjYWE3Hxu12zy6d9FyqePHTwrSvaSgAbhw_prBlyboHlgz1dLfioi6poJCs-k2Oah0lnjW3jOvhtr1KLZG4DSseA3rW7-s25BD3crrnuCnZLd7IuiU4fRWXyDKfWqr4LpeSQwj0OxaiUp1tQz-P7ajyD369fjEFqnxNNWuxatha7N_GLVGoKBiMV6AEou_t6kQtaJW-lXYnmcl_BiJQN_1m00)](https://www.plantuml.com/plantuml/uml/TLDDR-Cs4BthLqnzgGCaSGzxAefY7SVeBkfy8BOHz2HGrCWYJ95Q3XN7AFhVEwGbhVpXayIPDs_U31-_aXVEDvLEVlr56QcR7A7qlgRV9nCdTlSRvSicQmYTjCQZyVVILfDQ2nEAxiZdMcMJsPUxrn1QFoqcbI2FZaFfB5Hy-liwqaDZkBHY2l0bGc6rjZjbDg2LGH0cXwEqSiH_5hWrQ2k5rdlcw3MUqdCkA32i01J7Dqvup1a62vKvuVRmWOwKDU3mHwCS4XWB8i-Lvw3Gi7vRG4jEKStEkYq15t1h_aILX8vfM9Q5f9Von-pBwRH_ifx5z9-NzIfTlRocZo_lp-ERFZHTfik_vwlPDuwreVVlgs_fOlxN_FcHWubNNYCiz-InWWMh8IbgX5m9dglYtJbuK1ju46OBjPP9yegEh1dBXhojqDt2w10HEeB2ccTjRiJ9ANH8i4NSTyQeMzZnRKFTLOOO22bjOppTZrZNd4TqjLE4wGD7SzxhMFx6X4CrenluDm60LlyuEmX8AHuP_3sm6FITj1OOXGLJKA-EWWC-5Ev06Hww4k6oG6IsYIvHxbZZRRouIcmHQh6li9Kz49FEF_rO-2gqMZrTwnZMaBFxGGegcU6Ke19A_nndVXVEGFqGgnAZ1rrOufEIpf8jFCm_PIdC1W671PS4SjeKJbJ8P4_T_uLjBRrrIC6WtJLA3a2xy0ixwwUy7UpCEs58o03Z4thPIpfuA4hgAjFm19GCoZf3mV8GWgKNHJ4QPbemKCZ4jIhJsutRd7R9XDocjYWE3Hxu12zy6d9FyqePHTwrSvaSgAbhw_prBlyboHlgz1dLfioi6poJCs-k2Oah0lnjW3jOvhtr1KLZG4DSseA3rW7-s25BD3crrnuCnZLd7IuiU4fRWXyDKfWqr4LpeSQwj0OxaiUp1tQz-P7ajyD369fjEFqnxNNWuxatha7N_GLVGoKBiMV6AEou_t6kQtaJW-lXYnmcl_BiJQN_1m00)

I hope it helps.
BR Helmut

**Comment by flyisland** [comment]
Hi @kirchsth, thanks for the quick reply, it works!
