### ISSUE TITLE
Getting started is not clear enough

### ISSUE THREAD

**Issue by Diokuz** [plantuml-stdlib/C4-PlantUML#35]
> At the top of your C4 PlantUML .puml file

What need to be done, to understand Getting Started section? I have no idea, what is `your C4 PlantUML .puml file`)

I could create it and fill it with example code, but the next question is: how to transpile .puml file to .svg file?

**Comment by Shimajda** [comment]
This project is an bunch of predefined elements and styles for PlantUML.
To learn how to use PlantUML You should use official docs:
[PlantUML SVG Support](https://plantuml.com/svg)

**Comment by Potherca** [comment]
Closing as this issue lies in the upstream project PlantUML and can not be fixed in this repo.
