### ISSUE TITLE
Descriptions for boundaries

### ISSUE THREAD

**Issue by NathanDotTo** [plantuml-stdlib/C4-PlantUML#350]
Hi

It seems to me that adding a description to a boundary would be a good thing. That way we could describe what the boundary contains in a general sense. This also seems like an obvious idea, so I am wondering why it is not already possible.

To explore whether boundary descriptions might be possible,  I am looking at the `Enterprise_Boundary`, `System_Boundary`, and `Container_Boundary` procedures. For example:

```
!unquoted procedure Enterprise_Boundary($alias, $label, $tags="", $link="")
  !if ($tags != "")
    !$allTags = $tags + '+enterprise'
  !else
    !$allTags = 'enterprise'
  !endif
  ' $type defined via $tag style
  Boundary($alias, $label, "", $allTags, $link)
!endprocedure
```

Which leads to, in C4.puml:

```
!unquoted procedure Boundary($alias, $label, $type="", $tags="", $link="")
!$boundaryTags = $addBoundaryPostfix($tags)
' nodes $type reuses $techn definition of $boundaryTags
!$type=$toElementArg($type, $boundaryTags, "ElementTagTechn", "boundary")
rectangle "$getBoundary($label, $type)" $toStereos("boundary", $boundaryTags) as $alias $getLink($link)
!endprocedure
```

Which leads to:

```
!function $getBoundary($label, $type)
  !if ($type == "")
    !return '== ' + $breakLabel($label)
  !endif
  !if (type != "")
    !return '== ' + $breakLabel($label) + '\n<size:' + $TECHN_FONT_SIZE + '>[' + $type + ']</size>'
  !endif
!endfunction
```
Does anyone reading this know whether/how a rectangle can have a description?

Am I thinking about this in the right way please?

Thanks

Nathan

**Comment by kirchsth** [comment]
HI @NathanDotTo,

I will try to implement it in one of the next weeksends.
But in the meantime you could use following workaround for e.g. System_Boundary:
- extend `{` at the end of  `System(...)` and combine it with `$tags="system_boundary"` to
  `System(..., $tags="system_boundary") {`
- close the boundary with a `}` after all included elements

like (follow the image link then you see the code)
[![](https://www.plantuml.com/plantuml/png/VOx1IiD048Rl-nHhy920JIwU1A7I5Zr4MwpYHGYRpP0iR6R3pYmIn7Tt4x5Kf3tDxF_pVJjBOkKvz5PS6DGsD20xve5kYiAhZxmrt8Kw47Zja04vrwul1gjmOXR4ZJLriRfUxARezR4iUaKCFaRLAXBA8FXycFnYFyQcJsaUTzOekf99gMgmILos0nk7ohxZ6aXxCpzZSScgfTlaXwfg5x1HVamo-Icat84dX-amZvDAUMpC8dQuBDM_sp_u1NI7phfsFAFw4k8PxD__JoiFaYDt9iJ-OVjMbPlxpTCwpSGIi0cz_GO0)](https://www.plantuml.com/plantuml/uml/VOx1IiD048Rl-nHhy920JIwU1A7I5Zr4MwpYHGYRpP0iR6R3pYmIn7Tt4x5Kf3tDxF_pVJjBOkKvz5PS6DGsD20xve5kYiAhZxmrt8Kw47Zja04vrwul1gjmOXR4ZJLriRfUxARezR4iUaKCFaRLAXBA8FXycFnYFyQcJsaUTzOekf99gMgmILos0nk7ohxZ6aXxCpzZSScgfTlaXwfg5x1HVamo-Icat84dX-amZvDAUMpC8dQuBDM_sp_u1NI7phfsFAFw4k8PxD__JoiFaYDt9iJ-OVjMbPlxpTCwpSGIi0cz_GO0) 

BR Helmut

**Comment by NathanDotTo** [comment]
Cool, that worked, thanks! :-)

**Comment by NathanDotTo** [comment]
I have also had cause to use the `type` too, like this:

```
System(a_system, "A Cloud Platform", "X-as-a-Service (XaaS) ", $type="GCP", $tags="system_boundary") {
  Container ...
}
```

**Comment by kirchsth** [comment]
If you want a different type, then I would directly use a boundary and define its own $type like

```plantuml
Boundary(anotherBoundary, "Another Boundary", $type="BOUNDARY TYPE", $tags="v1") {
```
details see https://github.com/plantuml-stdlib/C4-PlantUML?tab=readme-ov-file#sample-with-different-boundary-tag-combinations

BR Helmut

**Comment by kirchsth** [comment]
Hi @NathanDotTo,

sorry, I forgot my implementation (indention) related to the $type support of a (System/Container/...)Boundary.
You can define it via the tags `AddBoundaryTag(tagName,  ...,  $type="NewType", ...)` and then e.g. all Systems which uses the $tag displays the updated $type automatically too.
Sample see below (follow the image link then you see the code):

[![](https://www.plantuml.com/plantuml/svg/XP0zRy8m48Pt_mfZCIGIKXV61X52r0wKI2HLnMGPV9X8_eZiYzIewdyl8Kc7CdJqSy_hU-rrGE6nDPhCy0e6QBRahQqH9BruP-Xpjdow3yAAp6fxrgs4ExnvcJEDis1nHKWgvSQrLWhVLK95B3HmheNceGi8XYte_AGofvrFcAxL5PKNNKylpkB0v-MnhF8tlYdUzzlqSEHPiIiEVT1v2VuV2Ri64bOEMsdvkrM30Yih-CI4fJICyx5LJCXWygbx54uBUXC7J2VCOlf5lX_jwPLZQZm-fFj-GeNaxwzCjxuM7toNl-JxRHIJDLZP6lq3)](https://www.plantuml.com/plantuml/uml/XP0zRy8m48Pt_mfZCIGIKXV61X52r0wKI2HLnMGPV9X8_eZiYzIewdyl8Kc7CdJqSy_hU-rrGE6nDPhCy0e6QBRahQqH9BruP-Xpjdow3yAAp6fxrgs4ExnvcJEDis1nHKWgvSQrLWhVLK95B3HmheNceGi8XYte_AGofvrFcAxL5PKNNKylpkB0v-MnhF8tlYdUzzlqSEHPiIiEVT1v2VuV2Ri64bOEMsdvkrM30Yih-CI4fJICyx5LJCXWygbx54uBUXC7J2VCOlf5lX_jwPLZQZm-fFj-GeNaxwzCjxuM7toNl-JxRHIJDLZP6lq3)

BR Helmut

**Comment by kirchsth** [comment]
Hi @NathanDotTo,

I implemented a version in my extended branch (details see #352) can you please check it via my branch?
(the only difference is that you have to use my extended branch `!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/...`

```plantuml
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

AddBoundaryTag("chatGPT", $type="ChatGPT", $bgColor="red", $fontColor="white", $borderColor="darkred", $sprite="robot2")

Person(admin, "Administrator",$sprite="person2")
System_Boundary(c1, "Sample System", $descr="ChatGPT with model gpt-3.5-turbo. It has been updated to feature higher accuracy", $tags="chatGPT") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")

SHOW_LEGEND()
@enduml
```

[![](https://www.plantuml.com/plantuml/svg/JLBDRjim3BxxAJXl1mT87BJRBWC2DFE2T43R1Okx7WDPOcoX-X4a6bamxDr7jMaoNmZn-o7rMJU9HAJHckATTjAC2c4W2kdBV1x5eUur3MCt9epIEq97jVHs_goZ718Dy-RJR6E4eyVxkpd-PboXukQkORBG3cCTidMnLEgh7vqIyTYAlYhb86YzQSifVA1Zm4NPN1fTttZZuwACgF9vprwdpc7GX2yS7nN6KvTTdq_S528pMEexJzVbf2Ws69DtbL1MkocKornreYZ8nt9w5eGNMbPiZudGxjxMhUGLoxR21eFmYkL12fECvxNXm361zGeDz85c7-lFCnfZvsluJZ2811sYWp4eGQY0FEnHC86prls04OIKOnJocAr9z6bnJcW2VmhWxvneTS1k9qBWhPwmWsK8Haj1shkIMytxAIotc_fXrRA41rpNLt3_gydOqXX_I91_PiexI6-3O8eT3UbylPQlGHY1j4N3inB7yVSKI4Ml8FkSQ0mMFz6yHNjPwp6nakjjsswspCgaCtgnMICbFc8k--Zj_v9YU_lZQNUtMgyUlbMJuWQTok_e7m00)](https://www.plantuml.com/plantuml/uml/JLBDRjim3BxxAJXl1mT87BJRBWC2DFE2T43R1Okx7WDPOcoX-X4a6bamxDr7jMaoNmZn-o7rMJU9HAJHckATTjAC2c4W2kdBV1x5eUur3MCt9epIEq97jVHs_goZ718Dy-RJR6E4eyVxkpd-PboXukQkORBG3cCTidMnLEgh7vqIyTYAlYhb86YzQSifVA1Zm4NPN1fTttZZuwACgF9vprwdpc7GX2yS7nN6KvTTdq_S528pMEexJzVbf2Ws69DtbL1MkocKornreYZ8nt9w5eGNMbPiZudGxjxMhUGLoxR21eFmYkL12fECvxNXm361zGeDz85c7-lFCnfZvsluJZ2811sYWp4eGQY0FEnHC86prls04OIKOnJocAr9z6bnJcW2VmhWxvneTS1k9qBWhPwmWsK8Haj1shkIMytxAIotc_fXrRA41rpNLt3_gydOqXX_I91_PiexI6-3O8eT3UbylPQlGHY1j4N3inB7yVSKI4Ml8FkSQ0mMFz6yHNjPwp6nakjjsswspCgaCtgnMICbFc8k--Zj_v9YU_lZQNUtMgyUlbMJuWQTok_e7m00)

Thank you and best regards
Helmut

**Comment by NathanDotTo** [comment]
Thank you for this. I will be able to test this next week.

**Comment by NathanDotTo** [comment]
I have tested this, and it works, thank you :-) 

I note that the description is bounded in a box such that the description occupies several lines vertically. See the attached images.

The use of the System_Boundary is from the new code in your branch. That shows the description over several lines.

The use of the Boundary is from the existing released code. That shows the description over one line.

This is simply an observation, not a judgement about which is the correct rendering.

![Screenshot 2024-05-03 at 11 00 10](https://github.com/plantuml-stdlib/C4-PlantUML/assets/13392790/f98fc88b-4b00-4c92-bc19-b1ec0aa1ebd6)
![Screenshot 2024-05-03 at 11 02 21](https://github.com/plantuml-stdlib/C4-PlantUML/assets/13392790/8bdc549d-b9e9-4741-af25-6ef0d81c3f34)
