### ISSUE TITLE
Separating model and view

### ISSUE THREAD

**Issue by NathanDotTo** [plantuml-stdlib/C4-PlantUML#353]
Hi

I would like to achieve an outcome such that I can define common model elements - systems, containers, components - in a model.puml file and reuse those model elements in other model files, but *not* have the reusable model elements rendered unless I explicitly want them to be.

This is intended to allow model elements to be defined in one place, and used in other parts of the overall system model in a way that is consistent.

I can create model elements in a file, and include that file in other files. That is fine. But, the model elements from the included file are all rendered. This is as expected given current functionality.

It is conceivable, I think, that there are other possibilities.

For example, there could be a form of `!includeInvisible` such that the included elements are not rendered by default, but are rendered when used in a `Rel` of some sort. I haven't found documentation that descried the `!include` functionality, so I have not been able to check whether this exists already.

What do others think please? I realise that there might be a better forum for such questions, so please feel free to direct me elsewhere with this question as appropriate.

Thanks

Nathan

**Comment by kirchsth** [comment]
Hi @NathanDotTo,

I think [PlantUML Q&A](https://forum.plantuml.net/) is the best place if you have PlantUML specific questions, findings, ...

In concrete I found `remove @unlinked` which could solve your problems.  But during some fast checks I found following problems
- it produces sometimes internal exceptions
- if an element (like System)  has a sub element (like component) then the referenced System remains invisible as long the component is referenced too. I added some combinations that you see the current state 
 
[![](https://www.plantuml.com/plantuml/svg/NS_1JWCX40RWEqynpiLkGkAbHsFQtMqVG1_0R64g4s7OBE1gJDzTjcbquuM43_ZvPvVoCEKIlBfZCRvOWiTk-z1jNxiOnYWa-Kcfbw-KAMnwZJqst-htQBFNkCS6r6LbdSOEcnMq6jiAwXxEqViuixo1fJCBPuu2unHjCPHW4A1FG-DLMS34S68PhjkPimESACGFWbqHp_9E5clchTj1uw5sg_3tyL7ZiRPRy0BBejJ_1AMUoTSnQkcIA65JhotIhgHI3_NXm0AEhINHC3is3fABnLkGcE54a1s16HBT8lfLn8x4bk1_0000)](https://www.plantuml.com/plantuml/uml/NS_1JWCX40RWEqynpiLkGkAbHsFQtMqVG1_0R64g4s7OBE1gJDzTjcbquuM43_ZvPvVoCEKIlBfZCRvOWiTk-z1jNxiOnYWa-Kcfbw-KAMnwZJqst-htQBFNkCS6r6LbdSOEcnMq6jiAwXxEqViuixo1fJCBPuu2unHjCPHW4A1FG-DLMS34S68PhjkPimESACGFWbqHp_9E5clchTj1uw5sg_3tyL7ZiRPRy0BBejJ_1AMUoTSnQkcIA65JhotIhgHI3_NXm0AEhINHC3is3fABnLkGcE54a1s16HBT8lfLn8x4bk1_0000)

Best regards
Helmut

**Comment by NathanDotTo** [comment]
Thank you :-)

**Comment by gobravedave** [comment]
I have built developed something similar using a collection json files..
See  https://github.com/gobravedave/C4-Plantuml-Helper for reference.

**Comment by NathanDotTo** [comment]
Thanks! :-)

**Comment by Potherca** [comment]
For future reference: It is also possible to use [the Subpart feature](https://plantuml.com/preprocessing#98ecfc06b2af9277) to only include part(s) of the central reference file.
