### ISSUE TITLE
Single column properties or header lead to rendering error

### ISSUE THREAD

**Issue by chriskn** [plantuml-stdlib/C4-PlantUML#355]
Hi C4-PlantUML Team,

I might recognize an issue with property rendering. Using single values for property headers (e.g `SetPropertyHeader("Property")`) or values (e.g `AddProperty("Property")`) lead to a rendering error. Using single column tables might sound odd, but would be handy to display lists.   

Error: 
![grafik](https://github.com/plantuml-stdlib/C4-PlantUML/assets/1077869/e7e0f4d3-316e-4d4d-8383-a104df4532d4)

Example for header
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' error
SetPropertyHeader("Property")
AddProperty("Prop2", "Value2")
Container(nodeAlias, "Label", "Optional Type", "Optional Description (with custom property header)") {

@enduml
```

Example for properties
```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

' error
AddProperty("Prop2")
Container(nodeAlias, "Label", "Optional Type", "Optional Description (with custom property header)") {

@enduml
```

versions tested: 1.2024.1, 1.2024.4

**Comment by kirchsth** [comment]
Hi @chriskn,

I created the MR #356  and updated my [extended branch](https://github.com/kirchsth/C4-PlantUML/tree/extended) with the new implementation.
Does it match with your expectation?

[![](https://www.plantuml.com/plantuml/svg/ROn1IqCn383lxrVKdjv0LnHFdZRSmSF4mT2J85qRzeffMf8KVV_URhZRJidt9NmhKS_QCWutYGAs26PIhVBa7FkVvJ7fr0vDW4CX1T9bADbz9mwJwEIU7-zsw4dVNxSEVlizGkpoQmCLovnF__NK7lQWEouLMESNy15uj1UsYs4TuuL6--6nmVrL-z3jVXQ5FCfvh35vkJLswm-0jYzlLLCXZsO34ZYTwPD6INH4CA5WosJgVtNHSyCAABQCVm00)](https://www.plantuml.com/plantuml/uml/ROn1IqCn383lxrVKdjv0LnHFdZRSmSF4mT2J85qRzeffMf8KVV_URhZRJidt9NmhKS_QCWutYGAs26PIhVBa7FkVvJ7fr0vDW4CX1T9bADbz9mwJwEIU7-zsw4dVNxSEVlizGkpoQmCLovnF__NK7lQWEouLMESNy15uj1UsYs4TuuL6--6nmVrL-z3jVXQ5FCfvh35vkJLswm-0jYzlLLCXZsO34ZYTwPD6INH4CA5WosJgVtNHSyCAABQCVm00)


Thank you
Helmut

**Comment by chriskn** [comment]
Awesome!

Thank you, Helmut

**Comment by kirchsth** [comment]
PS.: Hi @chriskn,

not direct related to your issue, but did you know that you can combine elements with Json too (details see [discussion](https://github.com/plantuml-stdlib/C4-PlantUML/discussions/322))?
Maybe it is useful for your [structurizr-c4puml-extension](https://github.com/chriskn/structurizr-c4puml-extension)
It has only one disadvantage that it can be only combined with elements (if you want to use it with Rel() then you would have to add a note to the Rel() and this note could again contains Json)

BR Helmut
