### ISSUE TITLE
Can't disable indexing on C4_Dynamic

### ISSUE THREAD

**Issue by bgowers** [plantuml-stdlib/C4-PlantUML#359]
Hi,

I'm a bit of a noob with PlantUML (I only started looking into it a couple of days ago), but I can't seem to find a way to turn off indexes when using a C4_Dynamic diagram.

I tried including the C4_Sequence diagram type and using the `SHOW_INDEX($show="false")` function, but that ended up changing the structure of my diagram (unsurprisingly to a sequence diagram).

Is there some way to turn off indexing for a C4_Dynamic diagram?

**Comment by kirchsth** [comment]
Hi @bgowers,

Why are you using a C4_Dynamic diagram at all, if you don't want to have the indexes?
What is your expected output?
 
Practically is the C4_Dynamic diagram a C4_Component diagram with indexing.
(I would switch to C4_Component, or did I oversee a missing feature?)

BR Helmut

**Comment by bgowers** [comment]
Ah, that's exactly what I wanted. I should've read up on the different diagrams on the C4 model before jumping straight in.
C4_Component is exactly what I need. Thanks @kirchsth!
