### ISSUE TITLE
LAYOUT_WITH_LEGEND Syntax Error?

### ISSUE THREAD

**Issue by Diokuz** [plantuml-stdlib/C4-PlantUML#36]
<img width="286" alt="Снимок экрана 2019-10-28 в 15 07 42" src="https://user-images.githubusercontent.com/2929442/67677318-c493b000-f994-11e9-8cd3-2941809fa7bb.png">

I use PlantUML extension for VSCode. Most of the examples from readme not working because of LAYOUT_WITH_LEGEND. After removing it I have additional captions in blocks:

<img width="568" alt="Снимок экрана 2019-10-28 в 15 09 34" src="https://user-images.githubusercontent.com/2929442/67677395-fad12f80-f994-11e9-847b-e73df86e63db.png">

How to remove these «component/container» captions?

**Comment by adrianvlupu** [comment]
You can call `LAYOUT_WITH_LEGEND()` like a function and it will work.

**Comment by n-alex-white** [comment]
I think this is a known problem and there are some outstanding pull requests to fix it!

**Comment by sdavids** [comment]
https://github.com/RicardoNiepel/C4-PlantUML/pull/20

**Comment by tooh** [comment]
+1

**Comment by jsiegmund** [comment]
+1

**Comment by jevin36** [comment]
+1

**Comment by nicholasf** [comment]
+1

**Comment by MichaelStoe** [comment]
+1

**Comment by ArneBachmannDLR** [comment]
Still not working with latest PlantUML and Graphviz 2.44.

**Comment by przemyslaw-lapinski** [comment]
+1

**Comment by drriguz** [comment]
+1

**Comment by IOrlandoni** [comment]
All samples are corrected [over here](/IOrlandoni/C4-PlantUML).

**Comment by Potherca** [comment]
Resolved in #29 by updating the example in the README.
