### ISSUE TITLE
Use the alias of a relationship

### ISSUE THREAD

**Issue by rokdd** [plantuml-stdlib/C4-PlantUML#360]
I am using just the default "Rel" without a direction. Now I want to add a note with plantuml like this:
```
Rel(c2_container16, c2_container17)
note top of c2_container16c2_relationships21c2_container17 #HotPink
What is this rel really doing??
end note
```
So I would be lucky do define also an alias for relationships? Because you [concat in the macro](https://github.com/plantuml-stdlib/C4-PlantUML/blob/acf5992a2d273f29c259f410886047508551e38c/C4.puml#L1516) as far as I understand alias1+direction+alias2 - but I don't know the direction? Or do I miss something?

**Comment by kirchsth** [comment]
HI @rokdd,

I think relationships have no alias in PlantUML itself. But if you want you can add a note to the previous relationship like below
(top is optional and defines the direction)

```
Rel_L(a,b,"sends(email)")

note top of link #lightgreen
this is a note
end note
```

a full sample see below
[![](https://www.plantuml.com/plantuml/svg/XP31IiD048Rl-nHZAYI5fT9IzAAsK0yUHH2FPR8PcyN9RibECRw3Z-P3EGaOMa4AITYPpFpVnwwJO2k7Xis53uuF5S7jPdcrMMutiTd7G47kpNWiqABjkkxxgviUTKjRZbtpJBnzAL1RMQ9GfO8Qz3pDz5U8Gb16aTX0V0FsuHqcx7Urx5gYO01UQnJm2QJMJqkiBp9_GXLzsArMHWEXJp7c2E-i6_4z_K7fxW_TNbQKN7kNdI6evc3PzbR_I0wh-k2WqWyXA1SSCiE7bnf-ORFPB3jspdMiS8kjYq7G1shdrnPEwXiBZ2NnrEH3kCHz3pZTqKhDKNmCgVRxj9YVPi3aCSgJYflyt8NcezrQJuU6Vm00)](https://www.plantuml.com/plantuml/uml/XP31IiD048Rl-nHZAYI5fT9IzAAsK0yUHH2FPR8PcyN9RibECRw3Z-P3EGaOMa4AITYPpFpVnwwJO2k7Xis53uuF5S7jPdcrMMutiTd7G47kpNWiqABjkkxxgviUTKjRZbtpJBnzAL1RMQ9GfO8Qz3pDz5U8Gb16aTX0V0FsuHqcx7Urx5gYO01UQnJm2QJMJqkiBp9_GXLzsArMHWEXJp7c2E-i6_4z_K7fxW_TNbQKN7kNdI6evc3PzbR_I0wh-k2WqWyXA1SSCiE7bnf-ORFPB3jspdMiS8kjYq7G1shdrnPEwXiBZ2NnrEH3kCHz3pZTqKhDKNmCgVRxj9YVPi3aCSgJYflyt8NcezrQJuU6Vm00)


BR Helmut

PS.: If you only want to add more details to a relationship, why do you not use the description argument `$descr="What is this rel really doing??"`? Details see [Element and Relationship properties](https://github.com/plantuml-stdlib/C4-PlantUML?tab=readme-ov-file#element-and-relationship-properties)

**Comment by rokdd** [comment]
Hello @kirchsth 
thanks for your fast response.. I use the description already for parameters etc of the request and the notes I want to add are really like a additional work layer what needs to be solved or discussed. They should look different and pop in the eye ;-) 
`link` is referring to previous line?

**Comment by kirchsth** [comment]
Does it solve your issue?

**Comment by rokdd** [comment]
Thank you, I just changed my code to follow the note directly after the relationship. A bit shaky but it works, would be great to have optional argument for the relationship to add an own alias but for the moment it is fine ;-)
