### ISSUE TITLE
Words overlap in container while using PlantUML in diagram.net

### ISSUE THREAD

**Issue by kobecai** [plantuml-stdlib/C4-PlantUML#361]
<img width="598" alt="image" src="https://github.com/user-attachments/assets/c9974679-2a7e-4069-9f89-bca1ef3c8a56">

**Comment by kirchsth** [comment]
Hi @kobecai,

for me it looks like that draw.io and the (internal) used PlantUML server/plugin do not support all or at least different fonts.
Ex. if I create in Draw.io a SVG and a PNG version of the same diagram then I would assume they use the same font.

But if Draw.io generates a SVG  and a PNG version then different fonts are used (I assume PNG is generated by the PlantUML server/plugin; and Draw.io displays the SVG font).

If I create a SVG and a PNG version of a PlantUML component diagram (without any C4-PlantUML) then you can see the different results:

```plantuml
@startuml
header plantuml %version()

[=SPA\n=Admin SPA\nSPA\nAdmin SPA]
@enduml
``` 
![image](https://github.com/user-attachments/assets/042899d2-5245-41f1-a50d-03a68b3c2512)

![image](https://github.com/user-attachments/assets/ec43e91d-d083-44a0-915f-d7cb1903aeb8)

As fast workaround I would suggest that you use "PNG" diagrams, but for a final solution I would suggest that you create a draw.io issue.

BR Helmut

**Comment by kirchsth** [comment]
Hi @kobecai,

I checked via the available fonts via following lines, and I think the used PlantUML server/plugin has only one installed font
(I see in the PNG output only one used font)

```plantuml
@startuml
listfonts Admin SPA
@enduml
```
![image](https://github.com/user-attachments/assets/3a6a37eb-f712-4ce1-9742-9ec3d0347ad9)

Ex. the PlantUML online server supports more fonts: https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh9B2v9oyyhALRWSaZDIm4A0G00

[![](https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuSh9B2v9oyyhALRWSaZDIm4A0G00)](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh9B2v9oyyhALRWSaZDIm4A0G00)

BR Helmut

**Comment by kirchsth** [comment]
Hi @kobecai,

I create a [draw,io issue](https://github.com/jgraph/drawio/issues/4699), maybe they can add the missing fonts on the used PlantUML online server/plugin.

BR Helmut

**Comment by kirchsth** [comment]
Hi @kobecai,

I received an update from @davidjgraph that they don’t want to add more fonts to draw.io (details [here](https://github.com/jgraph/drawio/issues/4699#issuecomment-2438185668)).

The best solution would be to:
- Set up your own draw.io server with with own PlantUML (docker based) server.
- And if needed, install the missing fonts by following these instructions: [Additional fonts inside the PlantUML docker container](https://github.com/plantuml/plantuml-server/blob/master/examples/additional-fonts/README.md).

BR
Helmut
