### ISSUE TITLE
Customize legend title text with `UpdateLegendTitle(newTitle)`

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#364]
Based on discussion [#363 Customize legend title text](https://github.com/plantuml-stdlib/C4-PlantUML/discussions/363) a new function is required to allow the legend title to be changed.

Currently, with the `Update....(..., ?legendText, ...)` function, all other legend labels can be customized. Therefore, a new `UpdateLegendTitle(newTitle)` function is added to allow the legend title to be changed as well.

For example, the following code:

```plantuml
...
UpdateLegendTitle("Updated legend title") 
...
SHOW_LEGEND()
@enduml
```

produces the following image:

![image](https://github.com/user-attachments/assets/cc863d0c-7985-4a83-8057-9955f3feeb26)

**Comment by Potherca** [comment]
@kirchsth This looks resolved by https://github.com/plantuml-stdlib/C4-PlantUML/pull/366, should this issue be closed?
