### ISSUE TITLE
decouple "hide stereotype" from "LAYOUT_WITH_LEGEND()", make an own macro

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#37]
If I don't want a legend I get automatically the stereotypes in the diagrams.
Wouldn't it be better if the stereotypes could be activated/deactivated in a separate call (too)?
like e.g. STEREOTYPE_HIDE() and STEREOTYPE_SHOW()? 

````
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
Container(alias, "label", "technology")
@enduml
````

![with stereotype](http://www.plantuml.com/plantuml/png/5Osngi9044NxV4LUgYTejh6o2gHL4S5Q9fiX6PYTMMPd4V_UfBjSpk4CnS6y9cx-I2BN6QjnkxhdSWd1uDClv6kTQa6BAexYVTGKdXJ1PhqJPkGmdayF1l7NxHeI54VRhlUeAQliHju3eue32Te_C44vjXt3XDnjmp6kegpBjpiq0ygyyJy0 "with stereotype")

````
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()
Container(alias, "label", "technology")
@enduml
````

![without stereotype](http://www.plantuml.com/plantuml/png/5Or1IuP048Rl_eelJvzGxgLJ9yEa0hC89Jh9k0wwC3kpxCuI_VjFRoylFC_J98MesLDnvzXINZ57kkog8JqP4-6ltfpkUSa9enLMPAsjUFFjBCHL1eS1oRIF3ry4hDD7RpmanNXSSoi-29z4E0Fzy-_dDCu_x-FRt7UltV1ohOfMMC4nnYkGWtH_AGaMfF8OYdPd8Td-owfeaDTJSWC0 "without stereotype")

**Comment by adrianvlupu** [comment]
It's actually pretty simple to do that. 

Instead of adding another function, you could use the plantuml syntax directly.

Just replace `LAYOUT_WITH_LEGEND()` with `hide stereotype`.

It seems like overkill to add this function

```puml
!function HIDE_STEREOTYPE()
hide stereotype
!endfunction
```

**Comment by kirchsth** [comment]
I know, but it would hide "C4/plantUML internals" like the existing function
``!define LAYOUT_TOP_DOWN top to bottom direction`` 
that an inexperienced user can deactivate it too

**Comment by adrianvlupu** [comment]
Fair point 🙂, I guess that could be added

**Comment by adrianvlupu** [comment]
This has been added, https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_stereotype
