### ISSUE TITLE
bidirectional relationship?

### ISSUE THREAD

**Issue by DTHerrera** [plantuml-stdlib/C4-PlantUML#43]
Hi, is it possible to have "bidirectional" arrows between two type of entities  (X <-----> Y) to abbreviate things? For example I'd like to represent that there is a response to the transaction request.

thanks in advance.
Domingo Tapia

**Comment by adrianvlupu** [comment]
There is no alias for that at the moment, you could do it manually like:

```
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Container(c, "C1", "Tech")
Container(d, "C2", "Tech")

c<-->d: tech
@enduml
```

![image](https://user-images.githubusercontent.com/4486850/73768652-0eedaf80-4782-11ea-98e9-cf59153cb310.png)

I don't know if the C4 model agrees with it though.

**Comment by DTHerrera** [comment]
Excellent ! I'll try it out against one of my UML deployment diagram.
Thanks a lot.

**Comment by DTHerrera** [comment]
Hello Adrian, how I can use new Bidirectional relationships, an apology for the inconvenience, but try to use the new BiRel option, but I had no success

**Comment by adrianvlupu** [comment]
Hi, sorry for the late reply but I added that feature to my repository not this one. It appears here because of the commit message where I referenced this issue.

**Comment by anorm** [comment]
I use the `Rel_()` function for this:
```
Rel_(c, d, "Tech", "<-->")
```
The extra parameter is the line style passed to PlantUML and can also be used to specify linestyle (ex. `"..>"`) or layout direction (ex. `"-LEFT->"`)

**Comment by DTHerrera** [comment]
Thanks Anorm.

**Comment by adrianvlupu** [comment]
Bidirectional relationships have been added. You can use them with BiRel(from, to, label, ?technology)

**Comment by stawirej** [comment]
@DTHerrera C4 model encourages using one directional arrows even for bidirectional communication. Direction of the arrow indicate which system/container/component starts the communication and response should be explicitly described by arrow label. E.g "Sends request **to** and receives response **from**"
