### ISSUE TITLE
Call JavaScript Functions instead of Links (URL)

### ISSUE THREAD

**Issue by DTHerrera** [plantuml-stdlib/C4-PlantUML#44]
Hello, there is some way to call a JavaScript function instead of a URL, for example:

I want to call the profiledetail function of javascrip: 

actor "This is [[javascript:profiledetail('/Architecture/PlantArchitectureDiagram?handler=DetailSystem','tibco_icc') Operator]] profile" as Operator

Instead of

actor "This is [[http://plantuml.com/sequence Operator]] profile" as Operator

thank you so much for your support.
DTapia

**Comment by Potherca** [comment]
Your question is more about how to use PlantUML rather than how to use this repo.

I would suggest asking this question in the PlantUML forums or on StackOVerflow. 

Closing as this issue lies in the upstream project PlantUML and can not be fixed in this repo.
