### ISSUE TITLE
Shapes for boxes

### ISSUE THREAD

**Issue by i-am-the-slime** [plantuml-stdlib/C4-PlantUML#45]
Users don't look like users and databases don't look like databases.

**Comment by i-am-the-slime** [comment]
Sorry, looks like I lied about the Databases.

**Comment by i-am-the-slime** [comment]
Still, person looks pretty bad. I guess that's a limitation of plantuml. Very sad.

**Comment by Potherca** [comment]
This seems to be addressed in https://github.com/plantuml-stdlib/C4-PlantUML/pull/49 and https://github.com/plantuml-stdlib/C4-PlantUML/pull/68.
