### ISSUE TITLE
Add custom stereotypes

### ISSUE THREAD

**Issue by Riduidel** [plantuml-stdlib/C4-PlantUML#51]
I would like to add custom stereotypes to `Container(...)` but the current syntax don't allow that.

My precise use case is two-fold : I have deployment diagrams built with Structurizr-plantuml and I would like to highlight

1. Containers defined in architecture diagram but not deployed (`<missing>` containers)
2. Container version (and the match of this version with the one defined in architecture)

How can I do that if I can't put a stereotype and have a custom rendering done with `skinParam` ?

**Comment by adrianvlupu** [comment]
Hi,

You can create your own stereotypes outside of C4-PlantUML

```plantuml
@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

skinparam rectangle<<missing_container>> {
    StereotypeFontColor $ELEMENT_FONT_COLOR
    FontColor $ELEMENT_FONT_COLOR
    BackgroundColor $CONTAINER_BG_COLOR
    BorderColor $CONTAINER_BORDER_COLOR
}
!unquoted procedure Missing($alias, $label, $techn, $descr="", $sprite="")
rectangle "$getContainer($label, $techn, $descr, $sprite)" <<missing_container>> as $alias
!endprocedure


Missing(missing_app, "Web APplication", "C#", "Description text")
Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA")
@enduml
```

![C4_Container Diagram Sample - bigbankplc](https://www.plantuml.com/plantuml/png/XL9HRnen37w_Ns5kFBGIurxsDBLLwPLEdQ0WsDP7v4ki8o8aMUBGJLF_Utsbi4wjj3pOYVrzyMVBbuanSjxQecUSibaJh9b3-bnL4H-6hU5rRdAYgBnZSZnKVbkXZWRTpkQGg_hJnxb5nz-dayeYKs89hMf1et4KXw7xkqWRum96t48anUXQIsTdMvEISUrA7S0N5_2d03bBfaYUVmUwaLpjhO_G7q_6q_7TjzNDJ4mzcymMpzZ_8wvGRTheizClk5hoezkxyM9rzUKrpaTDyIrcjhWMjySz5htiVcRFf254hqZdI33TTtBIHsim3Q1liI4hdacjdNXDISNpifHh2j4moVsqECu2odvBV1pQoVly8_cqXFUdXmds4eeUENtKLnJ5GU61XI4CeBod1aRpO8r2Djw9lBB-qDdhhfu9NH2OVh68_QlkWPhN_F0F_olkS01BqUbQcFwezxzPiwEOWDS4id1i5Bpi4w3Jp-5RUKP730swJSTTpaTIzLBwa0rw0W00 "C4_Container Diagram Sample - bigbankplc")

**Comment by kirchsth** [comment]
@Riduidel: I think my PR#107 should solve your requirements. You could check it via my local branch  https://github.com/kirchsth/C4-PlantUML.
E.g. 
Entities can be decorated with tags and explained via dynamic calculated legends, for example:

```cs
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

AddTagSupport("v1.0", $borderColor="#d73027")
AddTagSupport("v1.1", $fontColor="#d73027")

Person(user, "Customer", "People that need products")
Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="v1.1")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
Rel(admin, spaAdmin, "Uses", "https")
Rel(spaAdmin, api, "Uses", "https")

SHOW_DYNAMIC_LEGEND()
@enduml
```

![tags](http://www.plantuml.com/plantuml/png/bLFHRXen47pdAznh7mwLSgIj5AbIf228caYGKaWKzGajvmNS-koJTm_w-LqR0ZH1bVfaoJFUcPrTNnD3uAQohJV6bRRHgDRCDNqfYW3RxihmkbaqXA7qZj5nj_HLySk4SasyBWQVFqmiE7uSZmhyBRX6BPVpWP31E0pTEfPkzRL-WDMigMiVECys5zrUrb7l5Zve30DlVRZAtkhBJxsFbrdx3FiYifTIz1MtDS50tkNHOaTbWuROLnY4dqtGrnOLhu6LGzIg3but9PCysxy2NHadr7uy3N40zg_UmX54aYiy558R0-d2uLP5cqhIgRsJd2WwPbZHLV8laeTCSgf196QJVbG2jsei9D47gLG9HHc9EYoXt1k82kM-iHq6KNmhiqaEKfodShsNSltJFjLvPJZDu3yj70BuHzTGc-XWSXS5Vy86udaBJbia1TOgMJCX4YdhLwPKUTp7xZ7Qj5zalAFstys-VoarNEHw8SM7mB00mYWqDcNmv9UiPjz7ITbRJS-JxAYqYKhSI7SRRqgKS-b31IoASS-cQFTBjXlV8o75Ekct227Y2P4-pyFpwIw3v6sAeAbu2ePn3pylut5SPpMEy7cXrkpsszDy-EE-FxuRp4StNs_kXtcxTOrEnw_u1m00 "tags")

Best regards
Helmut
