### ISSUE TITLE
Support stereotypes in context diagrams

### ISSUE THREAD

**Issue by marcelstoer** [plantuml-stdlib/C4-PlantUML#53]
Contrary to component and container diagrams the context diagrams don't support a fourth parameter for systems and persons: https://github.com/RicardoNiepel/C4-PlantUML/blob/master/C4_Context.puml

As per http://static.codingthearchitecture.com/visualising-software-architecture.pdf systems and  persons can have stereotypes (those `[]` beneath the label).

**Comment by adrianvlupu** [comment]
Context diagrams don't support technologies because the entities can either be a system or a person.
The equivalent of those `[]` beneath the label in the pdf are the plantuml stereotypes

**Comment by marcelstoer** [comment]
> The equivalent of those `[]` beneath the label in the pdf are the plantuml stereotypes

True, I'll rephrase the issue accordingly.

**Comment by kirchsth** [comment]
@marcelstoer: I think my PR #107 should solve your requirements. You could check it via my local branch  https://github.com/kirchsth/C4-PlantUML.
E.g. 
Entities can be decorated with tags and explained via dynamic calculated legends, for example:

```cs
@startuml
!include https://raw.githubusercontent.com/kirchsth/C4-PlantUML/extended/C4_Container.puml

AddTagSupport("v1.0", $borderColor="#d73027")
AddTagSupport("v1.1", $fontColor="#d73027")

Person(user, "Customer", "People that need products")
Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="v1.1")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
Rel(admin, spaAdmin, "Uses", "https")
Rel(spaAdmin, api, "Uses", "https")

SHOW_DYNAMIC_LEGEND()
@enduml
```

![tags](http://www.plantuml.com/plantuml/png/bLFHRXen47pdAznh7mwLSgIj5AbIf228caYGKaWKzGajvmNS-koJTm_w-LqR0ZH1bVfaoJFUcPrTNnD3uAQohJV6bRRHgDRCDNqfYW3RxihmkbaqXA7qZj5nj_HLySk4SasyBWQVFqmiE7uSZmhyBRX6BPVpWP31E0pTEfPkzRL-WDMigMiVECys5zrUrb7l5Zve30DlVRZAtkhBJxsFbrdx3FiYifTIz1MtDS50tkNHOaTbWuROLnY4dqtGrnOLhu6LGzIg3but9PCysxy2NHadr7uy3N40zg_UmX54aYiy558R0-d2uLP5cqhIgRsJd2WwPbZHLV8laeTCSgf196QJVbG2jsei9D47gLG9HHc9EYoXt1k82kM-iHq6KNmhiqaEKfodShsNSltJFjLvPJZDu3yj70BuHzTGc-XWSXS5Vy86udaBJbia1TOgMJCX4YdhLwPKUTp7xZ7Qj5zalAFstys-VoarNEHw8SM7mB00mYWqDcNmv9UiPjz7ITbRJS-JxAYqYKhSI7SRRqgKS-b31IoASS-cQFTBjXlV8o75Ekct227Y2P4-pyFpwIw3v6sAeAbu2ePn3pylut5SPpMEy7cXrkpsszDy-EE-FxuRp4StNs_kXtcxTOrEnw_u1m00 "tags")

Best regards
Helmut
