### ISSUE TITLE
File not found error for C4_*.puml in !include on local server

### ISSUE THREAD

**Issue by AjitDingankar** [plantuml-stdlib/C4-PlantUML#54]
I've opened an issue at the PlantUML-Server project: 
https://github.com/plantuml/plantuml-server/issues/143 

The summary is that the server can't find the puml files I copied from your repo to the root of the server repo and restarted the server, but I get the file not found error for "!include C4_Context.puml" for example. 

I need to know where to place those files so that I can use the local !include directives instead of the remote !includeurl paths. 

Thanks, 
Ajit

**Comment by AjitDingankar** [comment]
I'm using absolute paths as a work-around, but would like to find a clean solution.

**Comment by Potherca** [comment]
Closing as this issue lies in the upstream project PlantUML and can not be fixed in this repo.
