### ISSUE TITLE
System Boudary Add labels in corners 

### ISSUE THREAD

**Issue by DTHerrera** [plantuml-stdlib/C4-PlantUML#56]
Hello, good afternoon.

Is there an option to add text or labels in the corners of the System_Boundary at the same time?

as the following example:

System_Boundary(c1, "DeskTop PC", "Wintel","Windows 10","Browser\nChrome or IE"){
    
}
and get something like the following picture

![System_Boundary](https://user-images.githubusercontent.com/36610780/81235984-c84a6400-8fc1-11ea-97dd-2415843d76ce.png)

Thanks a lot
Domingo Tapia

**Comment by DTHerrera** [comment]
Hi, any comments about this help??

**Comment by kirchsth** [comment]
Instead of values in the 4 corners of a node we could add properties tables to the description, that (existings) systems could be documented like (style has to be updated)
![grafik](https://user-images.githubusercontent.com/21959385/104770760-60176900-5771-11eb-9b56-7e9236c42bf0.png)
