### ISSUE TITLE
Documentation on how to use Lay_D, Lay_U etc

### ISSUE THREAD

**Issue by ppoluha** [plantuml-stdlib/C4-PlantUML#74]
I often find it hard to get the layout I want and I see in your examples that you use "layout commands", such as Lay_D and Lay_U. Could you please add a few lines in the documentation on how to use these and how to think about how to order the elements (ie should I use Rel_R or Lay_R, for example).

**Comment by adrianvlupu** [comment]
`Rel_R` actually adds a relationship arrow between the elements and serves the same purpose of a normal `Rel` but tells plantUML that the arrow should be pointing right `-RIGHT->>`.

The `Lay_R` is mostly for rare circumstances when you want to arrange the Containers in a specific order but don't want to add an actual relationship between them (`$from -[hidden]R- $to`).

**Comment by kirchsth** [comment]
Rel_* is used if the elements has a relation, Lay_* is used if you want a specific layout of the elements:

In following sample a person uses different systems, and group of persons which have no relations

```csharp
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()

Person(a, "A")
Person(b, "B")
Person(c, "C")
Person(d, "D")
Person(e, "E")

Lay_U(a, b)
Lay_R(a, c)
Lay_D(a, d)
Lay_L(a, e)

Person(x, "X")
System(s1, "S1")
System(s2, "S2")
System(s3, "S3")
System(s4, "S4")

Rel_U(x, s1, "uses")
Rel_R(x, s2, "uses")
Rel_D(x, s3, "uses")
Rel_L(x, s4, "uses")
@enduml
```

![Relation versus Layout](http://www.plantuml.com/plantuml/png/LSt1QeD04CRnkq-HvgJGA55FFQLLeGLBHIEq9rbrQ8HrbTrPshnzPmn5Svl_3_RRaq6XqOxIUHXK9sqFkmlYR9w2G8iV_tl0Yssj0TrD2a6XtqrZC4kX-Ct1O2-7DaZYGy5Kl-V1A0o29ceIUY461TgVUV_rBSsQwfoLsSVvgyXSpt4Aq6PIhdZSxP_ttd-sb2zhTfJ9cZrbkYPGPfHEBgvDpLEjjzmbtztjJldkRtVEDwoV_zB09mrKLuCmkkP8NHqt43A46uWOeWt43361Ku9iQfvSPgm1GyfOBXZUOxfWT8_vWl6A9r2z7UKV "Relation versus Layout")

**Comment by kirchsth** [comment]
@adrianvlupu: I think it can be closed based on my merged sample
