### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by dazinator** [plantuml-stdlib/C4-PlantUML#76]
For a couple of my containers A and B, adding two relationships between them (one for each direction) caused the label text to overlap. This didn't happen when the same thing was done on some other containers within my diagram. I assume this is a graphviz thing... Is there a suggested remedy for this kind of thing?

**Comment by adrianvlupu** [comment]
You can try messing around with other relationship types like `Rel_Left`, `Rel_Up`, etc.
