### ISSUE TITLE
[Question] How to change color of link

### ISSUE THREAD

**Issue by Orybon** [plantuml-stdlib/C4-PlantUML#8]
Hi, 

Is it possible to change the color of a relationship ?

**Comment by adrianvlupu** [comment]
You could call the underlying Rel_ like this

```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN

Container(c1, "C1", "tech")
Container(c2, "C2", "tech")
Container(c3, "C3", "tech")
Container(c4, "C4", "tech")

Rel_(c1, c2, "label", "tech", "-[#cc44ff]->")
Rel_(c3, c4, "label", "-[#cc44ff]->")

@enduml
```

It gives you something like
![diagram](https://www.plantuml.com/plantuml/png/TO_12i8m38RlWxs3pek2Mr5xyY3AFAeJKKH4HjT5L-YwqQNu-hOJXWfU4iZt9JzPDiWqcbBwNbyeBaqEHijUWLWtSq8qUqOFWON9J0EQLmf1OSIhaXm4PpglTW9ga2IcuLuoXQVjXfIiGT1sbCRMPqA1ZkesmVSsgqjoEgR7P9-ka_FEZJffo2VZNX1F0biHU16Clk3KmUaVE7DmzWTI1-adzBq3oBGDREzAbe7i1Dl3wu1pIk_tMxXm2s_TfhJ7ElrNyxqbgDp--W80)

**Comment by Orybon** [comment]
Thank you for your answer.

What i did prior to your post is the following .

I defined a new RelO_ :  

`!define RelO_(e_alias1, e_alias2, e_label, e_color, e_direction="") e_alias1 e_direction e_alias2 #text:e_color : "===e_label"`

and for each type of Rel new entries, like this : 

```
!define RelO_D(e_from,e_to, e_label, e_color) Rel_(e_from,e_to, e_label, "-[e_color]DOWN->")
!define RelO_D(e_from,e_to, e_label, e_color, e_type) Rel_(e_from,e_to, e_label, "-[e_color,e_type]DOWN->")
```
I'am sure there is a better way to do this, but for now it's working for me.

**Comment by davidhenery1** [comment]
You can also use the following to change the line and font colour.
skinparam sequence {
    ArrowColor DarkTurquoise 
    ArrowFontColor DarkTurquoise 
}

**Comment by Potherca** [comment]
Closing this issue as the asked question has received a useable answer.
