### ISSUE TITLE
Future of C4-PlantUML

### ISSUE THREAD

**Issue by RicardoNiepel** [plantuml-stdlib/C4-PlantUML#81]
Hi community,

first of all, big thanks to all of you constantly pushing me.
For private and professional reasons I could not find enough love for this project in the last two years.
I apologize for this!

I propose the following changes / next steps:
- adding two additional contributors to the project
- choosing (and aligning with the owner - should in my view one of the contribs above) one fork and merging everything back
- add the usage of GitHub Actions for creating the samples and verifying the lib
- updating C4-PlantUML in the PlantUML Standard Library
- after that also applying the same to https://github.com/RicardoNiepel/Azure-PlantUML/

Anything I forgot?
And most important:
- Which is the most used / future ready fork and would love to be also a contributor?
- Who wants to be one of the additional contributors?
  (I would really love to have somone here who is using it every week and thus has an ongoing interest of it)

@adrianvlupu, @fineconstant, @IOrlandoni, @stawirej, @xmobe, @Potherca, @aheil

**Comment by IOrlandoni** [comment]
Hey,

I'm a constant user of both projects. It's what I use during calls/presentations to quickly illustrate what we talk about as a group with developers, executives, etc.

 I'd be happy to bring over the automation from [my repo](https://github.com/IOrlandoni/C4-PlantUML) (here and to Azure-PlantUML) and be a contributor in general to both projects.

I'd also suggest we do that first and quickly, so all other changes go through the automated tests and re-generation of diagrams.

Thanks!

**Comment by IOrlandoni** [comment]
My simple/basic suggested plan is:
- [ ] Transfer those repositories to my empty organization: SoftwareIsCool. 
This should take care of all redirects for existing uses of the project
We'll maintain the same list of contributors and start adding new ones as they come.
- [ ] I'll set up automation on the repo for testing, diagram generation, issue inactivity, etc.
- [ ] We'll start merging from forks, PRs, suggestions, and generate new official releases as we see fit.
- [ ] Move on as a community open source project.

**Comment by RicardoNiepel** [comment]
Taking a look into all forks, their activity and #80 - I would personally favor:
- taking @adrianvlupu fork as the new starting point
- adding for the same reason @adrianvlupu as contributor
- adding @IOrlandoni as contributor for the ideas of automation and verifiction
- adding @aheil as contributor for making sure that other PlantUML libs align and the idea and documentation is also aligned to newcomers and students

Please let me know what you all think about that and if you would accept it.

**Comment by stawirej** [comment]
Hi,

About "_...most used / future ready fork_": 
Changes from [my fork](https://github.com/stawirej/C4-PlantUML) are used daily by multiple developer teams in my work. 
The most significant change is rewriting @RicardoNiepel C4-PlantUML to [latest PlantUML preprocessor](https://github.com/stawirej/C4-PlantUML#use-current-plantuml-preprocessor).
Additional enhancements are results of my struggles and my coworkers feedback when we were visualising enterprise level commercial systems. They are:
- Person icon in personas box
- External container and component
- Live Templates for IntelliJ

Please put under consideration changes made on that fork as potentially small step for "future ready" solution.

**Comment by IOrlandoni** [comment]
@RicardoNiepel I suggest you should, as a first step, transfer ownership of the repo to an organization so the projects can out-grow the limitations of being a personal repository, as @Potherca suggested in #80, giving [bats-core](https://github.com/bats-core) as an example of that transition. From there we could work on establishing a way to communicate (slack?), choosing a fork, merging, and moving forward.

**Comment by RicardoNiepel** [comment]
I've already created https://github.com/C4-PlantUML

Any idea how you would like the main repo be named?

If @adrianvlupu would like to join - I could also imagine that https://github.com/adrianvlupu/C4-Builder will be part of the new organization.

Let's wait 3 days for feedback from all others coming in,

**Comment by adrianvlupu** [comment]
Hi, I would really like to join this, I strongly believe that this repo deserves a new live and I appreciate you including me 😊. I will come back to this tomorrow morning, I'm a bit broken tonight.

**Comment by Potherca** [comment]
First of all: No need to apologise @RicardoNiepel, we all know the struggles of open-source. Supercool to see some action on this!

Regarding chat/communication, if GitHub issues prove to be too troublesome for this, maybe [Github Team Discussions](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions) would be a good match for now? (At least until something more full-featured is needed).

Next, to avoid divise effort or conflicting interest, one of the things that will need to be decided is whether the GitHub organisation is more C4 or more PlantUML oriented.

The reason for saying this is that the mention of [RicardoNiepel/Azure-PlantUML](https://github.com/RicardoNiepel/Azure-PlantUML) would suggest making a PlantUML centric org but the mention of [adrianvlupu/C4-Builder](https://github.com/adrianvlupu/C4-Builder) would suggest a more C4 centric one.

As-is [C4-PlantUML/C4-PlantUML](https://github.com/C4-PlantUML/C4-PlantUML/) would make sense but [C4-PlantUML/Azure-PlantUML](https://github.com/C4-PlantUML/Azure-PlantUML) and [C4-PlantUML/C4-Builder](https://github.com/C4-PlantUML/C4-Builder) less so...

**Comment by aheil** [comment]
Thanks for adding me here. As @Potherca says, there is no need to apologize. Moving forward this project to a community project is a great step forward. 

I am happy if we can consolidate all the contributions in various forks into one project. That's by the way one of the major issues when someone starts with this lib, that they used different works. This happened even to my students even if I pointed the to this particular repo. Said that I introduce the C4 model and C4-PlantUML to three of my courses, which are in sum about 200-300 students each year. About every 6 months, we will have a huge batch of "new" users. And I am happing to upgrading my lectures and tutorials on a regular basis to the latest versions.

**Comment by adrianvlupu** [comment]
Hi again,

@Potherca 
> Next, to avoid divise effort or conflicting interest, one of the things that will need to be decided is whether the GitHub organisation is more C4 or more PlantUML oriented.

You are right. Regarding the naming, If @RicardoNiepel adds Azure-PlantUML I think the organization can be called PlantUML-Libraries or something like that. I don't insist on adding C4-Builder, it's a small tool that just relies on C4-PlantUML to be stable and work with different versions of PlantUML. 

Btw, regarding tags and releases, does it need to be v1.0.0, v1.0.1 etc, or can they be named by the PlantUML version they are compatible with (1.2020.19)?

@stawirej 
Check out my fork, it includes many of the changes in your repo that make it compatible with different versions of PlantUml. It's been stable for the last year. Not trying to fight for what fork is better, as long as there is a central repo, I'm happy. 
Maybe we can merge commits regarding IntelliJ templates and external components/containers if it's something people use. The reason why I didn't add more external entities was the metamodel of C4.

@IOrlandoni 
Cool thing with the visual testing, I've been living in a cave.

@aheil and @stawirej 
It's nice to see there are so many people using this, I'm sure we can come up with many improvements to the library.

**Comment by IOrlandoni** [comment]
Hey, guys.

The discussion now grew to the following topics.
- Organization focus
- Release/versioning strategy.
- Fork choices
- Communication channel

I have opinions on the matters but... does it really matter for now? We just have to get the project started and setup the right places for those discussions. We don't need to come up with the perfect solution to everything before we move forward.

The focus of each of the repos (C4-PlantUML and Azure-PlantUML) is clear. The focus of the organization will be decided as we move forward and we're free to move repos in and out of the organization as we please. 

I do have _some_ experience with open source projects and I think the most important thing is that we **move forward**. If we let the discussion grow, we'll never come up with a final/perfect decision on all the topics.

I suggest we keep the scope of the discussion to how do we **start** this. Not how we maintain it over the following weeks, months, years. I think that what we **must** agree on now is just:

- Everyone OK with transferring both repos to the organization? Any problem that you can think of that this will bring?
- Everyone OK with communicating through GH team discussions? Any better/easier suggestions?

Again, these are starting points, and just starting points. We'll setup the proper channels to have the following discussions, and start agreeing on other topics and continue moving forward.

**Comment by Potherca** [comment]
As @IOrlandoni stated

> If we let the discussion grow, we'll never come up with a final/perfect decision on all the topics.

It might be worth creating separate issues for follow-up actions, as not everyone needs to be involved with each item.

- - -

Regarding an org name, why not just use `plantuml-stdlib`? I've just created [plantuml-stdlib org](https://github.com/orgs/plantuml-stdlib) and added everyone from this thread as "owner", in case you like the name all you need to do is accept the invitation.

- - -

Regarding the other topics, paraphrasing from @RicardoNiepel's original post:

> 1. adding two additional contributors to the project

Resolved by "adding@adrianvlupu, @IOrlandoni, and @aheil as contributor"

> 2. choosing (and aligning with the owner - should in my view one of the contribs above) one fork and merging everything back

Might be worth having a separate discussion about somewhere other than in this ticket? As this will take some to-and-fro to get all the changes aligned.

> 3. add the usage of GitHub Actions for creating the samples and verifying the lib

Make a separate ticket?

> 4. updating C4-PlantUML in the PlantUML Standard Library

Out of scope for this repo, but I can add (and keep track of) a new ticket in [plantuml/plantuml-stdlib](https://github.com/plantuml/plantuml-stdlib)

> 5. after that also applying the same to https://github.com/RicardoNiepel/Azure-PlantUML/

Pick org name, move repo.

> 6. Which is the most used / future ready fork and would love to be also a contributor?

Same as item 2. 

> 7. Who wants to be one of the additional contributors?

Same as item 1. 

- - - 

@adrianvlupu Regarding tags and releases, either works fine. As long as _any_ versioning is used it'll work to automate things.

**Comment by aheil** [comment]
I kind of like the idea of the plantuml-stdlib org. I could also add my project (https://github.com/aheil/EIP-PlantUML) to this one.

**Comment by RicardoNiepel** [comment]
Same for me - love the idea of plantuml-stdlib org.

The only thing in my mind: as we cannot speak about what will be "stdlib" maybe "plantuml-libs"?

And do we have a GO from the PlantUML creator regarding the name collision?

I would transfer C4 and Azure PlantUML libs.

**Comment by Crashedmind** [comment]
Great to see this conversation happening! 

Earlier this year when I had some free time, based on discussions with Arnaud, I did some thinking/playing/writing about standardising Plantuml stdlib to elicit feedback i.e. https://crashedmind.github.io/PlantUMLHitchhikersGuide/Stdlib/stdlibRequirements.html which e.g. suggested the keyword arguments should be used in new libraries, what macro fields should be supported etc... Other sections of the guide on using/abusing the preprocessor :) 

Would this be part of the scope you're considering?


Either way, I'm interested in contributing.

P.S. I don't have access to plantuml-stdlib org.

**Comment by Potherca** [comment]
> P.S. I don't have access to plantuml-stdlib org.

@Crashedmind You do now 😏

**Comment by Potherca** [comment]
> And do we have a GO from the PlantUML creator regarding the name collision?

@RicardoNiepel  We have a ["yes"](https://github.com/plantuml/plantuml-stdlib/issues/31#issuecomment-728321815)

**Comment by RicardoNiepel** [comment]
I've now transfered both libs and give the @plantuml-stdlib owners write rights in both

I would suggest to not add more people to the core team at this current stage and start with working on it.

**Comment by Potherca** [comment]
> I would suggest to not add more people to the core team

@RicardoNiepel Thus far I've just added everyone to the org as "owner", feel free to change that to "member" if things feel too crowded in the ownersphere :+1:

**Comment by Berkmann18** [comment]
Pardon me if I'm going slightly off-topic.

I'm trying to see which repo/library to use (since I'm looking to use C4 in PlantUML), I've seen plenty of variations (some of which include icons like https://github.com/adrianvlupu/C4-PlantUML and https://github.com/IOrlandoni/C4-PlantUML) but none of the ones made by the new maintainers/core members seems to have been added to this one and **I was wondering if any consensus has been made as that what fork/repo ended up being the _new starting point_?** 

Also, I noticed https://github.com/C4-PlantUML still exists even tho it was abandoned in favour of https://github.com/plantuml-stdlib (not sure if it's normal or it was just forgotten).

**Comment by adrianvlupu** [comment]
Hi, I'm working on collecting useful additions to the library right now and will be merging it back in the official repository.
