### ISSUE TITLE
Change README to use plantuml-stdlib url

### ISSUE THREAD

**Issue by Riduidel** [plantuml-stdlib/C4-PlantUML#91]
Readme still uses old RicardoNiepe urls.
URL should be changed to official plantuml-stdlib ones

**Comment by Potherca** [comment]
Could you point out where you are seeing `RicardoNiepe`? 

Both [looking at the README](https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/README.md) and [searching this repo](https://github.com/plantuml-stdlib/C4-PlantUML/search?q=RicardoNiepe) I don't see it mentioned anywhere?

**Comment by Riduidel** [comment]
Daaaamn, it seems I confused that readme with another. Sorry.

**Comment by Potherca** [comment]
No problem! We still appreciate the effort you took to report this. This time we're just lucky we don't have to fix anything :grin:
