### ISSUE TITLE
The include section of all "percy" diagrams looks wrong

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#93]
all "percy" diagramms has a include section like 

```
!include ./../C4_Container.puml
!include ./../C4_Context.puml
!include ./../C4.puml
```

This looks wrong for me.

1. `C4_Container.puml` includes `C4_Context.puml` already, why is it repeated?
2. If this pattern is used with "first" `C4_Dynamic.puml` and "last" `C4.puml`, then the automatic indexing is overwritten.

I think "percy" should include only the "first" `*.puml` and skip all following includes

BR Helmut

**Comment by adrianvlupu** [comment]
They seem to be in the wrong order. I have no idea how percy does the includes, maybe @IOrlandoni has an opinion. I know that including diagrams locally is a bit different than including a URL.

**Comment by kirchsth** [comment]
@IOrlandoni, @adrianvlupu:   based on the "false failure" build error in #107 PR I rechecked the current used include pattern in the test files. Independent of the error the additional include files can change the generated output file.
Eg. if it is used with dynamic diagrams the automatic counting of the relations is lost

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml

LAYOUT_WITH_LEGEND()

ContainerDb(c4, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
Container(c1, "Single-Page Application", "JavaScript and Angular", "Provides all of the Internet banking functionality to customers via their web browser.")
Container_Boundary(b, "API Application") {
  Component(c3, "Security Component", "Spring Bean", "Provides functionality Related to signing in, changing passwords, etc.")
  Component(c2, "Sign In Controller", "Spring MVC Rest Controller", "Allows users to sign in to the Internet Banking System.")
}
Rel_R(c1, c2, "Submits credentials to", "JSON/HTTPS")
Rel(c2, c3, "Calls isAuthenticated() on")
Rel_R(c3, c4, "select * from users where username = ?", "JDBC")
@enduml
```
![orig with counting](http://www.plantuml.com/plantuml/png/jL9BRnD13BxdLvXUI52R2EW92T4yAbhKHzIa84wHTzRP7J6FbUrjY13_dPbDInhEz3RZyVVmvpaJHTRMkzuh6unhIu9QjP4Fen7ZPbXPhTkY5M8JWrBGeOb-r3WC6NCYMZfRZAQd9_DSkh--6daK9KwbrMmRq5ipR3BxQ_Zl_DE4G1k8NrI1VkfByUzuUrVZxxVtozMto-N5wkhyy_dDh3_ezVvEDolwvlGOZcQeMA3GKJhVaKErCQ23fp8iJ4qUy-j28vD0zWHCbHNbhXjiM4VstVaOQfIQIi1MQmfgpQx5C9NvYawE0OqX4N2nIXTICpmQx7trpTkiPKFbw6IE5S6uQTmZJxRn1HzmOTWs2XXA68UgTSZvPSxnmPOaWCv1N4Do09T1YGCf51X-959Ojy7iPhIw1OrWMj7eYGKUB6QCPTXG0GN7ZH0Vc5jDOXjAv6s_I7hZ-UM1kG7ywW5CeszYeA1zypvFGgRb9BMlTrasdCrC2CE1yqDttJwep2x5LY4ZR8hOr1YgV6bGP1EvtCTu8Fyk2oLS2W7o21oT8tucV_rrcZH4_taTEnStkqNBatOIJiV3I2UFaIwsekIp_EzUihowwtQuasyBRrMUxp_HT6jStDwCBfRB-IBX4ggpsoKsHPUwh8ptNuZA_W1oma_ygQ_xlKAEZC8RM7FqZuutDJ5rvu2Uu2DywlHcasd2dr4eM-_-0000)

with additional includes no counting anymore

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml

LAYOUT_WITH_LEGEND()

ContainerDb(c4, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
Container(c1, "Single-Page Application", "JavaScript and Angular", "Provides all of the Internet banking functionality to customers via their web browser.")
Container_Boundary(b, "API Application") {
  Component(c3, "Security Component", "Spring Bean", "Provides functionality Related to signing in, changing passwords, etc.")
  Component(c2, "Sign In Controller", "Spring MVC Rest Controller", "Allows users to sign in to the Internet Banking System.")
}
Rel_R(c1, c2, "Submits credentials to", "JSON/HTTPS")
Rel(c2, c3, "Calls isAuthenticated() on")
Rel_R(c3, c4, "select * from users where username = ?", "JDBC")
@enduml
```
![test file without counting](http://www.plantuml.com/plantuml/png/jL9BRnD13BxdLvYU4jGc0df2GZIFYXRr4JKfY5FadNLsHynZPNiR8iH_PsRJaePxRZCUVmz_dWjHP6szwxsnmRYs9AXL6_au6Z5kXfNLkYrQ8JOnA0KTckX7ZSEGCMUYfRF5Q7f-Di-bnzkRaKTHubHQpRO1lJN3vYZiquH06uYFo4-_z3ZiEzRUpVZ7_UDozVrwURMwkVnoUJVh3tgzVvFDYhuvFuMJ6IeMA7IIpW_aK6qCwE2b30jJayVykj38990z0LDbHRdh1XlMaNrtFeKQfQOIiDMQWbgpQp5CPRwYarD0OqW4NApIXTGCJmPxNttpBclPK3awcsD5C6uQzyoJRNp59rmOjeq2XXB6eMeTSdwPStoo9GcWSn3Na1p0TL3YG0e5Xf-95DPjCBiPhMv18vXMD7fYWIUB6MCPDbH0mN4Zn0VcLfFOXX9vso-ItdX-VM1k0Bzx0DFecnWeQDzyo9EGQJb9xUjTbWrdCnF2SE3yq5st3ogpIx5Lo0YR8ZOrXYfV6XJPH2xtCHx8lyz22PT2W3m2H-U8NydVVfic3T7_NiVEnSrkqVAYdOJJyJ3IoNEaYwqe-Ip_fvSihnww7Uxasy9RbTVxJpJT6XVtTwEhvNA-IBY4wknsYKtHfIuhu_qNeh8_W9pm2t_gwtwla2EZy1RM7FspuqrDJDqve2Vu19yxlTbacl0N5ChMkxy0)

Therefore I think it is a better approach to add a switch in the C4_* files which loads the included files via url or local. And via an additional command line defintion it can be switched to the local version (if it is not already part of the "master" puml itself). This approach could be used independent of the test context too

e.g. C4_Dynamic.puml
```
!if %variable_exists("RELATIVE_INCLUDE")
  !include %get_variable_value("RELATIVE_INCLUDE")/C4_Component.puml
!else
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!endif
...
```
e.g. "percy\C4_Dynamic Diagram Sample - bigbankplc.puml"
```
@startuml
!if %variable_exists("RELATIVE_INCLUDE")
!include ./../C4_Dynamic.puml
!else
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
!endif
```

**local versions can be activated via**
a) set variable in "master" puml (e.g. "percy\C4_Dynamic Diagram Sample - bigbankplc.puml")
```
@startuml
%set_variable_value("RELATIVE_INCLUDE", ".")
...
```
b) or via command line
```
java -jar plantuml.jar -DRELATIVE_INCLUDE="."  ...
```

**Comment by kirchsth** [comment]
the corresponding changes are part of PR #107 merged that workflow uses the correct local version during build that no "false failure" occurs anymore
#93: local file includes can be activated via command line argument -DRELATIVE_INCLUDE="."
Update github workflow that local files are used
