### ISSUE TITLE
Simpler custom numbering in dynamic diagram

### ISSUE THREAD

**Issue by kirchsth** [plantuml-stdlib/C4-PlantUML#96]
PlantUML fixed a [bug](https://forum.plantuml.net/12624/variable-increased-diagram-function-called-preprocessing?show=12624#q12624) that functions can be used as procedure argument. This fix could simplify the customized numbering in the dynamic diagrams.
The new implementation is compatible with the existing one (existing procedures starts lowercase, new functions starts uppercase like all others which can produce output). 
New
```
Rel_D(customer, app, "Updates his profile using", "HTTPS")
Rel(app, customer_service, "Updates customer information using", "JSON/HTTPS")
Rel_R(customer_service, customer_db, "Stores data in", "JDBC")

RelIndex_D(Index()-1, customer_service, message_bus, "Sends customer update events to", "async")
RelIndex_U(LastIndex()-2, customer_service, app, "Confirm update to", "async")

RelIndex_L(Index()-1, message_bus, reporting_service, "Sends customer update events to", "async")
RelIndex(Index()-1, reporting_service, reporting_db, "Stores data in")

RelIndex_R(SetIndex(5)-2, message_bus, audit_service, "Sends customer update events to", "async")
RelIndex(Index()-2, audit_service, audit_store, "Stores events in")
```
Existing
```
Rel_D(customer, app, "Updates his profile using", "HTTPS")
Rel(app, customer_service, "Updates customer information using", "JSON/HTTPS")
Rel_R(customer_service, customer_db, "Stores data in", "JDBC")

RelIndex_D($index-1, customer_service, message_bus, "Sends customer update events to", "async")
RelIndex_U($index-2, customer_service, app, "Confirm update to", "async")

increment()
RelIndex_L($index-1, message_bus, reporting_service, "Sends customer update events to", "async")
increment()
RelIndex($index-1, reporting_service, reporting_db, "Stores data in")

setIndex(5)
RelIndex_R($index-2, message_bus, audit_service, "Sends customer update events to", "async")
increment()
RelIndex($index-2, audit_service, audit_store, "Stores events in")
```
![grafik](https://user-images.githubusercontent.com/21959385/102139566-4dea9800-3e5e-11eb-9bd6-0f263e0dae52.png)

@adrianvlupu: Are the new function names OK, or should I change something? (the implementation is basically finished)

Best regards
Helmut

PS.: this new functions can be used in all other diagrams
```
customer -DOWN-> app : **Index(): Updates his profile using**
app -DOWN-> customer_service : **Index(): Updates customer information using**
customer_service -DOWN-> customer_db : **Index(): Stores data in**

customer_service --> message_bus : **Index()-1: Sends customer update events to**
customer_service --> app : **LastIndex()-2: Confirm update to**

message_bus --> audit_service : **SetIndex(17)-7: Sends customer update events to**
audit_service --> audit_store : **Index()-7: Stores events in**
```
![grafik](https://user-images.githubusercontent.com/21959385/102139507-37dcd780-3e5e-11eb-8f98-6ddd15cac822.png)

**Comment by adrianvlupu** [comment]
I checked your PR #98, it looks good

**Comment by kirchsth** [comment]
@adrianvlupu or @Potherca: can you merge my approved #98 that we can close it?
Thank you and best regards
Helmut

**Comment by Potherca** [comment]
@kirchsth Thank you for the reminder! I've merged the MR. :+1:

**Comment by ncasaux** [comment]
I have the feeling that these "dynamic" and "auto numbering" things should not be part of C4 Model diagrams...
It look like C4 Model diagrams are "transformed" into some sequence diagram, which are not their purpose.
